# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-25 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='checkbox_1',
            field=models.CharField(default='', help_text='label for the first checkbox option (may contain HTML)', max_length=1024),
        ),
        migrations.AddField(
            model_name='petition',
            name='checkbox_2',
            field=models.CharField(default='', help_text='label for the second checkbox option (may contain HTML)', max_length=1024),
        ),
        migrations.AddField(
            model_name='petition',
            name='checkbox_3',
            field=models.CharField(default='', help_text='label for the third checkbox option (may contain HTML)', max_length=1024),
        ),
        migrations.AddField(
            model_name='petition',
            name='checkbox_4',
            field=models.CharField(default='', help_text='label for the fourth checkbox option (may contain HTML)', max_length=1024),
        ),
        migrations.AddField(
            model_name='petition',
            name='google_forms_url',
            field=models.URLField(help_text='Google form to post petition data to', max_length=2048, null=True),
        ),
    ]
