# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-06 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='checkbox_1_form_field',
            field=models.CharField(blank=True, help_text='Google form field name for Checkbox 1', max_length=1024, verbose_name='First checkbox Google Form field'),
        ),
        migrations.AddField(
            model_name='petition',
            name='checkbox_2_form_field',
            field=models.CharField(blank=True, help_text='Google form field name for Checkbox 1', max_length=1024, verbose_name='Second checkbox Google Form field'),
        ),
        migrations.AddField(
            model_name='petition',
            name='email_form_field',
            field=models.CharField(default='entry.474888454', help_text='Google form field name for Email', max_length=1024, verbose_name='Email Google Form field'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petition',
            name='given_name_form_field',
            field=models.CharField(default='entry.1017670790', help_text='Google form field name for Given Name(s)', max_length=1024, verbose_name='Given Name(s) Google Form field'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petition',
            name='newsletter_signup_form_field',
            field=models.CharField(default='entry.645784103', help_text='Google form field name for Mozilla Newsletter checkbox', max_length=1024, verbose_name='Mozilla Newsletter signup checkbox Google Form field'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petition',
            name='surname_form_field',
            field=models.CharField(default='entry.623318390', help_text='Google form field name for Surname', max_length=1024, verbose_name='Surname Google Form field'),
            preserve_default=False,
        ),
    ]
