# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-25 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_auto_20180124_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petition',
            name='checkbox_3',
        ),
        migrations.RemoveField(
            model_name='petition',
            name='checkbox_4',
        ),
    ]
