# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-08 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('people', '0025_remove_person_homepage'),
        ('highlights', '0006_auto_20180208_2205'),
        ('news', '0011_auto_20171012_1326'),
        ('homepage', '0003_auto_20170919_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageRelatedHighlights',
            fields=[
                ('highlight_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='highlights.Highlight')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('highlights', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_highlights', to='highlights.Highlight')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=('highlights.highlight', models.Model),
        ),
        migrations.CreateModel(
            name='HomepageRelatedNews',
            fields=[
                ('news_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news.News')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_news', to='news.News')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=('news.news', models.Model),
        ),
        migrations.CreateModel(
            name='HomepageRelatedPeople',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='people.Person')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=('people.person', models.Model),
        ),
        migrations.CreateModel(
            name='WagtailHomepage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='homepagerelatedpeople',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_people', to='homepage.WagtailHomepage'),
        ),
        migrations.AddField(
            model_name='homepagerelatedpeople',
            name='people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_people', to='people.Person'),
        ),
        migrations.AddField(
            model_name='homepagerelatednews',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_news', to='homepage.WagtailHomepage'),
        ),
        migrations.AddField(
            model_name='homepagerelatedhighlights',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_highlights', to='homepage.WagtailHomepage'),
        ),
    ]
