# Generated by Django 4.2.29 on 2026-04-07 04:12

import modelcluster.contrib.taggit
import wagtail.fields
from django.db import migrations

import foundation_cms.legacy_apps.wagtailpages.validators
import foundation_cms.validators


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_remove_new_from_verbose_names"),
        ("gallery_hub", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallerypage",
            name="topics",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="Select one or more topics from the dropdown. If a topic is unavailable, please reach out to StratComms for help.",
                through="base.PageTopic",
                to="base.Topic",
                verbose_name="Page Topics",
            ),
        ),
        migrations.AlterField(
            model_name="projectpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("accordion_block", 5),
                    ("callout", 8),
                    ("custom_media", 14),
                    ("divider", 15),
                    ("featured_card_block", 32),
                    ("featured_container", 41),
                    ("fru_element_block", 44),
                    ("icon_info_grid", 54),
                    ("iframe_block", 59),
                    ("image", 62),
                    ("image_grid", 72),
                    ("impact_numbers", 78),
                    ("link_button_block", 79),
                    ("list_block", 84),
                    ("newsletter_signup", 86),
                    ("newsletter_unsubscribe", 88),
                    ("pillar_card_set", 93),
                    ("podcast_block", 96),
                    ("portrait_card_set_block", 102),
                    ("quote", 105),
                    ("rich_text", 106),
                    ("spacer_block", 107),
                    ("spotlight_card_set_block", 112),
                    ("tabbed_content", 123),
                    ("three_column_container_block", 142),
                    ("timely_activations_cards", 148),
                    ("title_block", 151),
                    ("two_column_container_block", 152),
                    ("video_block", 153),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Heading for the Accordion Item", "required": True},
                    ),
                    1: ("foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock", (), {}),
                    2: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 1)]],
                        {"required": False, "use_json_field": True},
                    ),
                    3: ("wagtail.blocks.StructBlock", [[("title", 0), ("content", 2)]], {}),
                    4: ("wagtail.blocks.ListBlock", (3,), {"min_num": 1}),
                    5: ("wagtail.blocks.StructBlock", [[("accordion_items", 4)]], {"group": "Text"}),
                    6: (
                        "foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock",
                        (),
                        {"features": ["h4", "h5", "h6"], "help_text": "Callout box title", "required": True},
                    ),
                    7: (
                        "foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock",
                        (),
                        {"help_text": "Callout box content", "required": True},
                    ),
                    8: ("wagtail.blocks.StructBlock", [[("heading", 6), ("description", 7)]], {"group": "Text"}),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title/caption for this media", "required": False},
                    ),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("image", "Image"), ("video", "Video")],
                            "help_text": "Select the type of media to display",
                        },
                    ),
                    11: ("wagtail.images.blocks.ImageBlock", [], {}),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Log into Vimeo using 1Password and upload the desired video. Then select the video and click "...", "Video File Links", and select "(mp4, 1920 x 1080)". Copy and paste the link here.',
                            "max_length": 500,
                            "required": False,
                        },
                    ),
                    13: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("portrait", "Portrait"),
                                ("landscape", "Landscape"),
                                ("square", "Square"),
                                ("widescreen", "Widescreen 16:9 (12 columns wide)"),
                            ],
                            "help_text": "Select the orientation of this media",
                        },
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 9), ("content", 10), ("image", 11), ("video_url", 12), ("orientation", 13)]],
                        {"group": "Media & Embeds"},
                    ),
                    15: ("wagtail.blocks.StructBlock", [[]], {"group": "Layout"}),
                    16: ("wagtail.blocks.CharBlock", (), {"label": "Heading", "max_length": 50, "required": True}),
                    17: (
                        "foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock",
                        (),
                        {"features": ["bold", "italic"], "label": "Description", "max_length": 500, "required": True},
                    ),
                    18: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Image for the card", "label": "Image"},
                    ),
                    19: ("wagtail.blocks.CharBlock", (), {}),
                    20: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("external_url", "External URL"),
                                ("relative_url", "Relative URL"),
                                ("email", "Email"),
                                ("anchor", "Anchor"),
                                ("file", "File"),
                                ("phone", "Phone"),
                            ],
                            "label": "Link to",
                        },
                    ),
                    21: ("wagtail.blocks.PageChooserBlock", (), {"label": "Page", "required": False}),
                    22: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Enter a full URL including http:// or https://",
                            "label": "External URL",
                            "max_length": 300,
                            "required": False,
                        },
                    ),
                    23: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'A path relative to this domain. For example, "/foo/bar" or "?foo=bar".',
                            "label": "Relative URL",
                            "max_length": 300,
                            "required": False,
                            "validators": [foundation_cms.legacy_apps.wagtailpages.validators.RelativeURLValidator()],
                        },
                    ),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'An id attribute of an element on the current page. For example, "#section-1"',
                            "label": "#",
                            "max_length": 300,
                            "required": False,
                            "validators": [foundation_cms.validators.AnchorLinkValidator()],
                        },
                    ),
                    25: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    26: ("wagtail.documents.blocks.DocumentChooserBlock", (), {"label": "File", "required": False}),
                    27: ("wagtail.blocks.CharBlock", (), {"label": "Phone", "max_length": 30, "required": False}),
                    28: ("wagtail.blocks.BooleanBlock", (), {"label": "Open in new window", "required": False}),
                    29: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("btn-primary", "Primary"), ("btn-secondary", "Secondary")]},
                    ),
                    30: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("link-button-block--left", "Left"), ("link-button-block--center", "Center")]},
                    ),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 19),
                                ("link_to", 20),
                                ("page", 21),
                                ("external_url", 22),
                                ("relative_url", 23),
                                ("anchor", 24),
                                ("email", 25),
                                ("file", 26),
                                ("phone", 27),
                                ("new_window", 28),
                                ("style", 29),
                                ("alignment", 30),
                            ]
                        ],
                        {"help_text": "Link button for the card.", "label": "Button", "required": False},
                    ),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 16), ("description", 17), ("image", 18), ("button", 31)]],
                        {"group": "Card Collections"},
                    ),
                    33: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("white", "White"),
                                ("neutral-100", "Grey 100"),
                                ("neutral-200", "Grey 200"),
                                ("neutral-300", "Grey 300"),
                                ("blue-100", "Blue 100"),
                                ("blue-200", "Blue 200"),
                                ("blue-300", "Blue 300"),
                                ("green-100", "Green 100"),
                                ("green-200", "Green 200"),
                                ("green-300", "Green 300"),
                                ("orange-100", "Orange 100"),
                                ("orange-200", "Orange 200"),
                                ("orange-300", "Orange 300"),
                                ("yellow-100", "Yellow 100"),
                                ("yellow-200", "Yellow 200"),
                                ("yellow-300", "Yellow 300"),
                            ]
                        },
                    ),
                    34: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("top", "Top"), ("middle", "Middle"), ("bottom", "Bottom")],
                            "help_text": "Vertical alignment of the columns content",
                        },
                    ),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 9), ("content", 10), ("image", 11), ("video_url", 12), ("orientation", 13)]],
                        {},
                    ),
                    36: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("small", "Small"),
                                ("medium", "Medium"),
                                ("large", "Large"),
                                ("xlarge", "Extra Large"),
                            ],
                            "help_text": "Select the size of the spacer",
                        },
                    ),
                    37: ("wagtail.blocks.StructBlock", [[("size", 36)]], {}),
                    38: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 1), ("media", 35), ("spacer", 37)]],
                        {"label": "Left Column", "required": False},
                    ),
                    39: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 1), ("media", 35), ("spacer", 37)]],
                        {"label": "Right Column", "required": False},
                    ),
                    40: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("none", "None"), ("left", "Left Column"), ("right", "Right Column")],
                            "help_text": "Make one column sticky on scroll",
                        },
                    ),
                    41: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 33),
                                ("vertical_alignment", 34),
                                ("left_column", 38),
                                ("right_column", 39),
                                ("sticky", 40),
                            ]
                        ],
                        {"group": "Layout"},
                    ),
                    42: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("donation-form", "Donation Form"),
                                ("donor-map", "Donor Map"),
                                ("top-locations", "Top Locations"),
                                ("donation-levels", "Donation Levels"),
                                ("donate-button", "Donate Button"),
                            ],
                            "help_text": "Select the type of Fundraise Up element.",
                        },
                    ),
                    43: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Copy the HTML code generated by the desired Fundraise Up element and paste it here.",
                            "required": True,
                        },
                    ),
                    44: (
                        "wagtail.blocks.StructBlock",
                        [[("fru_element_type", 42), ("fru_element_embed_code", 43)]],
                        {"group": "Engagement & Buttons"},
                    ),
                    45: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Section heading for this grid", "max_length": 100, "required": True},
                    ),
                    46: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("orange", "Orange"), ("black", "Black")],
                            "help_text": "Color applied to all icons in this grid",
                        },
                    ),
                    47: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("1", "1 column"), ("2", "2 columns"), ("3", "3 columns")],
                            "help_text": "Number of columns on desktop (automatically stacks on mobile)",
                            "label": "Number of columns for this grid",
                        },
                    ),
                    48: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("compact", "Compact (icons + titles only)"),
                                ("detailed", "Detailed (icons + titles + descriptions)"),
                            ],
                            "help_text": "Choose content density. Compact hides descriptions, Detailed shows them.",
                            "label": "Layout style",
                        },
                    ),
                    49: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("chat", "Chat icon"),
                                ("eye-open", "Eye Open icon"),
                                ("gear", "Gear icon"),
                                ("globe", "Globe icon"),
                                ("megaphone", "Megaphone icon"),
                                ("star", "Star icon"),
                            ],
                            "help_text": "Select an icon for this item",
                        },
                    ),
                    50: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title for this item", "max_length": 100, "required": True},
                    ),
                    51: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional description (max 126 characters)",
                            "max_length": 126,
                            "required": False,
                        },
                    ),
                    52: ("wagtail.blocks.StructBlock", [[("icon", 49), ("title", 50), ("description", 51)]], {}),
                    53: ("wagtail.blocks.ListBlock", (52,), {"help_text": "Add icon info items", "min_num": 1}),
                    54: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 45), ("icon_color", 46), ("columns", 47), ("layout_style", 48), ("items", 53)]],
                        {"group": "Card Collections"},
                    ),
                    55: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Please note that only URLs from allow-listed domains will work."},
                    ),
                    56: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Optional integer pixel value for custom iFrame height", "required": False},
                    ),
                    57: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("normal", "Normal"), ("full_width", "Full Width")]},
                    ),
                    58: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": 'Checking this will add "scrolling=no" to the iframe. Use this if your iframe is rendering an unnecessary scroll bar or whitespace below it.',
                            "required": False,
                        },
                    ),
                    59: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 55), ("height", 56), ("iframe_width", 57), ("disable_scroll", 58)]],
                        {"group": "Media & Embeds"},
                    ),
                    60: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title/caption for this image", "required": False},
                    ),
                    61: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("portrait", "Portrait"), ("landscape", "Landscape"), ("square", "Square")],
                            "help_text": "Select the orientation of this image",
                        },
                    ),
                    62: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 60), ("image", 11), ("orientation", 61)]],
                        {"group": "Media & Embeds"},
                    ),
                    63: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional heading for this section", "max_length": 100, "required": False},
                    ),
                    64: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("portrait", "Portrait (2:3)"),
                                ("landscape", "Landscape (3:2)"),
                                ("square", "Square (1:1)"),
                            ],
                            "help_text": "Orientation for all images in this section",
                            "label": "Image grid section orientation",
                        },
                    ),
                    65: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("4", "4 per row"), ("5", "5 per row"), ("6", "6 per row")],
                            "label": "Items per section row",
                        },
                    ),
                    66: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["h5", "h6", "large", "bold", "italic"],
                            "help_text": "Optional caption for this image",
                            "required": False,
                        },
                    ),
                    67: (
                        "foundation_cms.blocks.link_block.OptionalLinkBlock",
                        (),
                        {"help_text": "Optional link for both image and caption", "required": False},
                    ),
                    68: ("wagtail.blocks.StructBlock", [[("image", 11), ("caption", 66), ("link", 67)]], {}),
                    69: ("wagtail.blocks.ListBlock", (68,), {"min_num": 1}),
                    70: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 63), ("section_orientation", 64), ("items_per_row", 65), ("items", 69)]],
                        {},
                    ),
                    71: ("wagtail.blocks.ListBlock", (70,), {"label": "Image grid sections", "min_num": 1}),
                    72: ("wagtail.blocks.StructBlock", [[("sections", 71)]], {"group": "Card Collections"}),
                    73: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The full value to animate, including any symbols, commas, decimals, or suffixes (e.g., $5.2M).",
                            "max_length": 5,
                            "required": True,
                        },
                    ),
                    74: ("wagtail.blocks.CharBlock", (), {"help_text": "Heading of the stat", "required": True}),
                    75: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Short description of the stat", "required": False},
                    ),
                    76: (
                        "wagtail.blocks.StructBlock",
                        [[("stat_number", 73), ("stat_heading", 74), ("stat_description", 75)]],
                        {},
                    ),
                    77: (
                        "wagtail.blocks.ListBlock",
                        (76,),
                        {
                            "default": [
                                {"stat_description": "", "stat_heading": "", "stat_number": ""},
                                {"stat_description": "", "stat_heading": "", "stat_number": ""},
                                {"stat_description": "", "stat_heading": "", "stat_number": ""},
                            ],
                            "help_text": "Add exactly 3 stats to appear in the Impact Numbers section",
                            "label": "Impact Stats",
                            "max_num": 3,
                            "min_num": 3,
                        },
                    ),
                    78: ("wagtail.blocks.StructBlock", [[("stats", 77)]], {"group": "Data Display"}),
                    79: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 19),
                                ("link_to", 20),
                                ("page", 21),
                                ("external_url", 22),
                                ("relative_url", 23),
                                ("anchor", 24),
                                ("email", 25),
                                ("file", 26),
                                ("phone", 27),
                                ("new_window", 28),
                                ("style", 29),
                                ("alignment", 30),
                            ]
                        ],
                        {"group": "Engagement & Buttons"},
                    ),
                    80: ("wagtail.blocks.CharBlock", (), {"help_text": "Heading displayed above the list"}),
                    81: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Description displayed above the list", "required": False},
                    ),
                    82: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 19),
                                ("link_to", 20),
                                ("page", 21),
                                ("external_url", 22),
                                ("relative_url", 23),
                                ("anchor", 24),
                                ("email", 25),
                                ("file", 26),
                                ("phone", 27),
                                ("new_window", 28),
                            ]
                        ],
                        {},
                    ),
                    83: ("wagtail.blocks.ListBlock", (82,), {"max_num": 4, "min_num": 1}),
                    84: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 80), ("description", 81), ("items", 83)]],
                        {"group": "Data Display"},
                    ),
                    85: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("snippets.NewsletterSignup",),
                        {"max_num": 1},
                    ),
                    86: (
                        "wagtail.blocks.StructBlock",
                        [[("newsletter_signup", 85)]],
                        {"group": "Engagement & Buttons"},
                    ),
                    87: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("snippets.NewsletterUnsubscribe",),
                        {"max_num": 1},
                    ),
                    88: (
                        "wagtail.blocks.StructBlock",
                        [[("newsletter_unsubscribe", 87)]],
                        {"group": "Engagement & Buttons"},
                    ),
                    89: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Appears as the main heading.", "label": "Headline", "required": False},
                    ),
                    90: (
                        "foundation_cms.blocks.link_block.OptionalLinkBlock",
                        (),
                        {
                            "help_text": "Optional link for the card.",
                            "label": "Call to Action Link",
                            "required": False,
                        },
                    ),
                    91: ("wagtail.blocks.StructBlock", [[("headline", 89), ("cta_link", 90)]], {}),
                    92: (
                        "wagtail.blocks.ListBlock",
                        (91,),
                        {
                            "default": [
                                {"cta_link": [], "headline": ""},
                                {"cta_link": [], "headline": ""},
                                {"cta_link": [], "headline": ""},
                            ],
                            "help_text": "3 cards required.",
                            "label": "Pillar Cards",
                            "max_num": 3,
                            "min_num": 3,
                        },
                    ),
                    93: ("wagtail.blocks.StructBlock", [[("cards", 92)]], {"group": "Card Collections"}),
                    94: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Title of the podcast. <strong>Note:</strong> Does not render on "NothingPersonal" pages.'
                        },
                    ),
                    95: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": 'Optional short description of the podcast. <strong>Note:</strong> Does not render on "NothingPersonal" pages.',
                            "required": False,
                        },
                    ),
                    96: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 94), ("description", 95), ("simplecast_embed_code", 19)]],
                        {"group": "Media & Embeds"},
                    ),
                    97: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Appears above the headline.", "label": "Label", "required": False},
                    ),
                    98: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Optional Image for the card", "label": "Image"},
                    ),
                    99: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 19),
                                ("link_to", 20),
                                ("page", 21),
                                ("external_url", 22),
                                ("relative_url", 23),
                                ("anchor", 24),
                                ("email", 25),
                                ("file", 26),
                                ("phone", 27),
                                ("new_window", 28),
                            ]
                        ],
                        {"help_text": "Link for the card.", "label": "Call to Action Link", "required": True},
                    ),
                    100: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 97), ("headline", 89), ("image", 98), ("cta_link", 99)]],
                        {},
                    ),
                    101: (
                        "wagtail.blocks.ListBlock",
                        (100,),
                        {
                            "help_text": "Minimum of 3 cards required. More than 3 will turn element into a carousel.",
                            "label": "Portrait Cards",
                            "min_num": 3,
                        },
                    ),
                    102: ("wagtail.blocks.StructBlock", [[("cards", 101)]], {"group": "Card Collections"}),
                    103: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    104: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    105: ("wagtail.blocks.StructBlock", [[("quote", 103), ("attribution", 104)]], {"group": "Text"}),
                    106: ("foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock", (), {"group": "Text"}),
                    107: ("wagtail.blocks.StructBlock", [[("size", 36)]], {"group": "Layout"}),
                    108: ("wagtail.blocks.CharBlock", (), {"label": "Name", "max_length": 50, "required": True}),
                    109: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Image should follow a 1:1 aspect ratio.", "label": "Image"},
                    ),
                    110: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 103), ("name", 108), ("description", 17), ("image", 109)]],
                        {},
                    ),
                    111: (
                        "wagtail.blocks.ListBlock",
                        (110,),
                        {"help_text": "3 cards required.", "label": "Spotlight Cards", "max_num": 3, "min_num": 3},
                    ),
                    112: ("wagtail.blocks.StructBlock", [[("cards", 111)]], {"group": "Card Collections"}),
                    113: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title shown on the tab button", "required": True},
                    ),
                    114: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Subtitle shown under the title on the tab", "required": False},
                    ),
                    115: ("foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock", (), {"required": False}),
                    116: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 60), ("image", 11), ("orientation", 61)]],
                        {"required": False},
                    ),
                    117: ("foundation_cms.blocks.link_block.OptionalLinkBlock", (), {"required": False}),
                    118: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 104), ("subtitle", 104), ("text", 115), ("image", 116), ("link", 117)]],
                        {},
                    ),
                    119: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 19), ("image", 11), ("subtitle", 19), ("link", 117)]],
                        {},
                    ),
                    120: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 1), ("text_image", 118), ("tab_card_set", 119)]],
                        {"help_text": "Add one or more content blocks to the tab.", "min_num": 1, "required": True},
                    ),
                    121: ("wagtail.blocks.StructBlock", [[("title", 113), ("subtitle", 114), ("content", 120)]], {}),
                    122: ("wagtail.blocks.ListBlock", (121,), {"label": "Tabs", "max_num": 8, "min_num": 1}),
                    123: ("wagtail.blocks.StructBlock", [[("tabs", 122)]], {"group": "Card Collections"}),
                    124: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 94), ("description", 95), ("simplecast_embed_code", 19)]],
                        {},
                    ),
                    125: ("wagtail.blocks.StructBlock", [[("title", 60), ("image", 11), ("orientation", 61)]], {}),
                    126: ("wagtail.blocks.StructBlock", [[("newsletter_signup", 85)]], {}),
                    127: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Log into Vimeo, select your desired video, and click 'Copy Link'",
                            "label": "Vimeo Video URL",
                            "required": True,
                        },
                    ),
                    128: ("wagtail.blocks.CharBlock", (), {"help_text": "Optional Caption Text", "required": False}),
                    129: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_to", 20),
                                ("page", 21),
                                ("external_url", 22),
                                ("relative_url", 23),
                                ("anchor", 24),
                                ("email", 25),
                                ("file", 26),
                                ("phone", 27),
                                ("new_window", 28),
                            ]
                        ],
                        {},
                    ),
                    130: (
                        "wagtail.blocks.ListBlock",
                        (129,),
                        {
                            "default": [],
                            "help_text": "Optional URL that this caption should link out to.",
                            "max_num": 1,
                            "min_num": 0,
                        },
                    ),
                    131: (
                        "wagtail.blocks.StructBlock",
                        [[("video_url", 127), ("caption", 128), ("caption_url", 130)]],
                        {},
                    ),
                    132: ("wagtail.blocks.StructBlock", [[("title", 80), ("description", 81), ("items", 83)]], {}),
                    133: ("wagtail.blocks.StructBlock", [[("quote", 103), ("attribution", 104)]], {}),
                    134: ("wagtail.blocks.StructBlock", [[("title", 104), ("text", 115)]], {}),
                    135: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 19),
                                ("link_to", 20),
                                ("page", 21),
                                ("external_url", 22),
                                ("relative_url", 23),
                                ("anchor", 24),
                                ("email", 25),
                                ("file", 26),
                                ("phone", 27),
                                ("new_window", 28),
                                ("style", 29),
                                ("alignment", 30),
                            ]
                        ],
                        {},
                    ),
                    136: (
                        "wagtail.blocks.StructBlock",
                        [[("fru_element_type", 42), ("fru_element_embed_code", 43)]],
                        {},
                    ),
                    137: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Page", "page_type": ["gallery_hub.ProjectPage"], "required": True},
                    ),
                    138: ("wagtail.blocks.StructBlock", [[("page", 137)]], {}),
                    139: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 1),
                                ("podcast", 124),
                                ("image", 125),
                                ("newsletter_signup", 126),
                                ("video", 131),
                                ("list", 132),
                                ("spacer", 37),
                                ("quote", 133),
                                ("text_social", 134),
                                ("link_button", 135),
                                ("fru_element", 136),
                                ("gallery_card", 138),
                            ]
                        ],
                        {"label": "Left Column", "required": False},
                    ),
                    140: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 1),
                                ("podcast", 124),
                                ("image", 125),
                                ("newsletter_signup", 126),
                                ("video", 131),
                                ("list", 132),
                                ("spacer", 37),
                                ("quote", 133),
                                ("text_social", 134),
                                ("link_button", 135),
                                ("fru_element", 136),
                                ("gallery_card", 138),
                            ]
                        ],
                        {"label": "Center Column", "required": False},
                    ),
                    141: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 1),
                                ("podcast", 124),
                                ("image", 125),
                                ("newsletter_signup", 126),
                                ("video", 131),
                                ("list", 132),
                                ("spacer", 37),
                                ("quote", 133),
                                ("text_social", 134),
                                ("link_button", 135),
                                ("fru_element", 136),
                                ("gallery_card", 138),
                            ]
                        ],
                        {"label": "Right Column", "required": False},
                    ),
                    142: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 33),
                                ("vertical_alignment", 34),
                                ("left_column", 139),
                                ("center_column", 140),
                                ("right_column", 141),
                            ]
                        ],
                        {"group": "Layout"},
                    ),
                    143: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional category for the card", "required": False},
                    ),
                    144: ("wagtail.blocks.CharBlock", (), {"help_text": "Title for the card", "required": True}),
                    145: (
                        "foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock",
                        (),
                        {"help_text": "Optional description text", "required": False},
                    ),
                    146: (
                        "wagtail.blocks.StructBlock",
                        [[("category", 143), ("title", 144), ("text", 145), ("image", 11), ("link", 82)]],
                        {},
                    ),
                    147: (
                        "wagtail.blocks.StreamBlock",
                        [[("card", 146)]],
                        {"help_text": "Add between 1 and 3 cards.", "max_num": 3, "min_num": 1},
                    ),
                    148: ("wagtail.blocks.StructBlock", [[("cards", 147)]], {"group": "Card Collections"}),
                    149: ("wagtail.blocks.CharBlock", (), {"help_text": "Title for the block", "required": True}),
                    150: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("shape", "Shape"), ("loop-line", "Loop Line")],
                            "help_text": "Select the style of the title",
                        },
                    ),
                    151: ("wagtail.blocks.StructBlock", [[("title", 149), ("style", 150)]], {"group": "Text"}),
                    152: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 33),
                                ("vertical_alignment", 34),
                                ("left_column", 139),
                                ("right_column", 141),
                            ]
                        ],
                        {"group": "Layout"},
                    ),
                    153: (
                        "wagtail.blocks.StructBlock",
                        [[("video_url", 127), ("caption", 128), ("caption_url", 130)]],
                        {"group": "Media & Embeds"},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="projectpage",
            name="topics",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="Select one or more topics from the dropdown. If a topic is unavailable, please reach out to StratComms for help.",
                through="base.PageTopic",
                to="base.Topic",
                verbose_name="Page Topics",
            ),
        ),
    ]
