# Generated by Django 4.2.29 on 2026-03-30 13:57

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery_hub", "0003_programlabel"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectPageProgramLabel",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "content_object",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_label_items",
                        to="gallery_hub.projectpage",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tagged_projects",
                        to="gallery_hub.programlabel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="projectpage",
            name="program_label",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="Add one or more existing program labels. Start typing to search, then press “Down” arrow on your keyboard to select program label. If program label is unavailable check if it exists by going to the left side-nav to Snippet > Program Labels > Check if program label exists. If not, click “Add new program label”.",
                through="gallery_hub.ProjectPageProgramLabel",
                to="gallery_hub.ProgramLabel",
                verbose_name="Program Label",
            ),
        ),
    ]
