# Generated by Django 5.2.15 on 2026-10-08 18:29

import wagtail.fields
from django.db import migrations

import foundation_cms.legacy_apps.wagtailpages.validators
import foundation_cms.validators


class Migration(migrations.Migration):

    dependencies = [
        ("gallery_hub", "0012_gallerypage_notice_banner_projectpage_notice_banner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("accordion_block", 5),
                    ("callout", 8),
                    ("custom_media", 14),
                    ("divider", 15),
                    ("featured_card_block", 32),
                    ("featured_container", 41),
                    ("flywheel_banner", 44),
                    ("fru_element_block", 47),
                    ("icon_info_grid", 57),
                    ("iframe_block", 62),
                    ("image", 65),
                    ("image_grid", 75),
                    ("impact_numbers", 81),
                    ("link_button_block", 82),
                    ("list_block", 87),
                    ("newsletter_signup", 89),
                    ("newsletter_unsubscribe", 91),
                    ("pillar_card_set", 96),
                    ("podcast_block", 99),
                    ("portrait_card_set_block", 105),
                    ("quote", 108),
                    ("rich_text", 109),
                    ("spacer_block", 110),
                    ("spotlight_card_set_block", 115),
                    ("tabbed_content", 126),
                    ("three_column_container_block", 145),
                    ("timely_activations_cards", 151),
                    ("title_block", 154),
                    ("two_column_container_block", 158),
                    ("video_block", 159),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Heading for the Accordion Item", "required": True},
                    ),
                    1: ("foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock", (), {}),
                    2: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 1)]],
                        {"required": False, "use_json_field": True},
                    ),
                    3: ("wagtail.blocks.StructBlock", [[("title", 0), ("content", 2)]], {}),
                    4: ("wagtail.blocks.ListBlock", (3,), {"min_num": 1}),
                    5: ("wagtail.blocks.StructBlock", [[("accordion_items", 4)]], {"group": "Text"}),
                    6: (
                        "foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock",
                        (),
                        {"features": ["h4", "h5", "h6"], "help_text": "Callout box title", "required": True},
                    ),
                    7: (
                        "foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock",
                        (),
                        {"help_text": "Callout box content", "required": True},
                    ),
                    8: ("wagtail.blocks.StructBlock", [[("heading", 6), ("description", 7)]], {"group": "Text"}),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title/caption for this media", "required": False},
                    ),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("image", "Image"), ("video", "Video")],
                            "help_text": "Select the type of media to display",
                        },
                    ),
                    11: ("wagtail.images.blocks.ImageBlock", [], {}),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Log into Vimeo using 1Password and upload the desired video. Then select the video and click "...", "Video File Links", and select "(mp4, 1920 x 1080)". Copy and paste the link here.',
                            "max_length": 500,
                            "required": False,
                        },
                    ),
                    13: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("portrait", "Portrait"),
                                ("landscape", "Landscape"),
                                ("square", "Square"),
                                ("widescreen", "Widescreen 16:9 (12 columns wide)"),
                            ],
                            "help_text": "Select the orientation of this media",
                        },
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 9), ("content", 10), ("image", 11), ("video_url", 12), ("orientation", 13)]],
                        {"group": "Media & Embeds"},
                    ),
                    15: ("wagtail.blocks.StructBlock", [[]], {"group": "Layout"}),
                    16: ("wagtail.blocks.CharBlock", (), {"label": "Heading", "max_length": 50, "required": True}),
                    17: (
                        "foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock",
                        (),
                        {"features": ["bold", "italic"], "label": "Description", "max_length": 500, "required": True},
                    ),
                    18: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Image for the card", "label": "Image"},
                    ),
                    19: ("wagtail.blocks.CharBlock", (), {}),
                    20: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("external_url", "External URL"),
                                ("relative_url", "Relative URL"),
                                ("email", "Email"),
                                ("anchor", "Anchor"),
                                ("file", "File"),
                                ("phone", "Phone"),
                            ],
                            "label": "Link to",
                        },
                    ),
                    21: ("wagtail.blocks.PageChooserBlock", (), {"label": "Page", "required": False}),
                    22: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Enter a full URL including http:// or https://",
                            "label": "External URL",
                            "max_length": 300,
                            "required": False,
                        },
                    ),
                    23: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'A path relative to this domain. For example, "/foo/bar" or "?foo=bar".',
                            "label": "Relative URL",
                            "max_length": 300,
                            "required": False,
                            "validators": [foundation_cms.legacy_apps.wagtailpages.validators.RelativeURLValidator()],
                        },
                    ),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'An id attribute of an element on the current page. For example, "#section-1"',
                            "label": "#",
                            "max_length": 300,
                            "required": False,
                            "validators": [foundation_cms.validators.AnchorLinkValidator()],
                        },
                    ),
                    25: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    26: ("wagtail.documents.blocks.DocumentChooserBlock", (), {"label": "File", "required": False}),
                    27: ("wagtail.blocks.CharBlock", (), {"label": "Phone", "max_length": 30, "required": False}),
                    28: ("wagtail.blocks.BooleanBlock", (), {"label": "Open in new window", "required": False}),
                    29: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("btn-primary", "Primary"), ("btn-secondary", "Secondary")]},
                    ),
                    30: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("link-button-block--left", "Left"), ("link-button-block--center", "Center")]},
                    ),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 19),
                                ("link_to", 20),
                                ("page", 21),
                                ("external_url", 22),
                                ("relative_url", 23),
                                ("anchor", 24),
                                ("email", 25),
                                ("file", 26),
                                ("phone", 27),
                                ("new_window", 28),
                                ("style", 29),
                                ("alignment", 30),
                            ]
                        ],
                        {"help_text": "Link button for the card.", "label": "Button", "required": False},
                    ),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 16), ("description", 17), ("image", 18), ("button", 31)]],
                        {"group": "Card Collections"},
                    ),
                    33: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("white", "White"),
                                ("neutral-100", "Grey 100"),
                                ("neutral-200", "Grey 200"),
                                ("neutral-300", "Grey 300"),
                                ("blue-100", "Blue 100"),
                                ("blue-200", "Blue 200"),
                                ("blue-300", "Blue 300"),
                                ("green-100", "Green 100"),
                                ("green-200", "Green 200"),
                                ("green-300", "Green 300"),
                                ("orange-100", "Orange 100"),
                                ("orange-200", "Orange 200"),
                                ("orange-300", "Orange 300"),
                                ("yellow-100", "Yellow 100"),
                                ("yellow-200", "Yellow 200"),
                                ("yellow-300", "Yellow 300"),
                            ]
                        },
                    ),
                    34: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("top", "Top"), ("middle", "Middle"), ("bottom", "Bottom")],
                            "help_text": "Vertical alignment of the columns content",
                        },
                    ),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 9), ("content", 10), ("image", 11), ("video_url", 12), ("orientation", 13)]],
                        {},
                    ),
                    36: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("small", "Small"),
                                ("medium", "Medium"),
                                ("large", "Large"),
                                ("xlarge", "Extra Large"),
                            ],
                            "help_text": "Select the size of the spacer",
                        },
                    ),
                    37: ("wagtail.blocks.StructBlock", [[("size", 36)]], {}),
                    38: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 1), ("media", 35), ("spacer", 37)]],
                        {"label": "Left Column", "required": False},
                    ),
                    39: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 1), ("media", 35), ("spacer", 37)]],
                        {"label": "Right Column", "required": False},
                    ),
                    40: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("none", "None"), ("left", "Left Column"), ("right", "Right Column")],
                            "help_text": "Make one column sticky on scroll",
                        },
                    ),
                    41: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 33),
                                ("vertical_alignment", 34),
                                ("left_column", 38),
                                ("right_column", 39),
                                ("sticky", 40),
                            ]
                        ],
                        {"group": "Layout"},
                    ),
                    42: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("imagine", "Imagine"), ("co-create", "Co-create"), ("mobilize", "Mobilize")],
                            "help_text": "Select the mission that determines the banner artwork and colors.",
                        },
                    ),
                    43: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Imagine",
                            "help_text": "Defaults to the mission name, but can be customized and translated.",
                            "max_length": 50,
                        },
                    ),
                    44: ("wagtail.blocks.StructBlock", [[("mission", 42), ("heading", 43)]], {"group": "Banners"}),
                    45: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("donation-form", "Donation Form"),
                                ("donor-map", "Donor Map"),
                                ("top-locations", "Top Locations"),
                                ("donation-levels", "Donation Levels"),
                                ("donate-button", "Donate Button"),
                            ],
                            "help_text": "Select the type of Fundraise Up element.",
                        },
                    ),
                    46: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Copy the HTML code generated by the desired Fundraise Up element and paste it here.",
                            "required": True,
                        },
                    ),
                    47: (
                        "wagtail.blocks.StructBlock",
                        [[("fru_element_type", 45), ("fru_element_embed_code", 46)]],
                        {"group": "Engagement & Buttons"},
                    ),
                    48: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Section heading for this grid", "max_length": 100, "required": True},
                    ),
                    49: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("orange", "Orange"), ("black", "Black")],
                            "help_text": "Color applied to all icons in this grid",
                        },
                    ),
                    50: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("1", "1 column"), ("2", "2 columns"), ("3", "3 columns")],
                            "help_text": "Number of columns on desktop (automatically stacks on mobile)",
                            "label": "Number of columns for this grid",
                        },
                    ),
                    51: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("compact", "Compact (icons + titles only)"),
                                ("detailed", "Detailed (icons + titles + descriptions)"),
                            ],
                            "help_text": "Choose content density. Compact hides descriptions, Detailed shows them.",
                            "label": "Layout style",
                        },
                    ),
                    52: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("chat", "Chat icon"),
                                ("eye-open", "Eye Open icon"),
                                ("gear", "Gear icon"),
                                ("globe", "Globe icon"),
                                ("megaphone", "Megaphone icon"),
                                ("star", "Star icon"),
                            ],
                            "help_text": "Select an icon for this item",
                        },
                    ),
                    53: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title for this item", "max_length": 100, "required": True},
                    ),
                    54: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional description (max 126 characters)",
                            "max_length": 126,
                            "required": False,
                        },
                    ),
                    55: ("wagtail.blocks.StructBlock", [[("icon", 52), ("title", 53), ("description", 54)]], {}),
                    56: ("wagtail.blocks.ListBlock", (55,), {"help_text": "Add icon info items", "min_num": 1}),
                    57: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 48), ("icon_color", 49), ("columns", 50), ("layout_style", 51), ("items", 56)]],
                        {"group": "Card Collections"},
                    ),
                    58: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Please note that only URLs from allow-listed domains will work."},
                    ),
                    59: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Optional integer pixel value for custom iFrame height", "required": False},
                    ),
                    60: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("normal", "Normal"), ("full_width", "Full Width")]},
                    ),
                    61: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": 'Checking this will add "scrolling=no" to the iframe. Use this if your iframe is rendering an unnecessary scroll bar or whitespace below it.',
                            "required": False,
                        },
                    ),
                    62: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 58), ("height", 59), ("iframe_width", 60), ("disable_scroll", 61)]],
                        {"group": "Media & Embeds"},
                    ),
                    63: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title/caption for this image", "required": False},
                    ),
                    64: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("portrait", "Portrait"), ("landscape", "Landscape"), ("square", "Square")],
                            "help_text": "Select the orientation of this image",
                        },
                    ),
                    65: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 63), ("image", 11), ("orientation", 64)]],
                        {"group": "Media & Embeds"},
                    ),
                    66: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional heading for this section", "max_length": 100, "required": False},
                    ),
                    67: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("portrait", "Portrait (2:3)"),
                                ("landscape", "Landscape (3:2)"),
                                ("square", "Square (1:1)"),
                            ],
                            "help_text": "Orientation for all images in this section",
                            "label": "Image grid section orientation",
                        },
                    ),
                    68: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("4", "4 per row"), ("5", "5 per row"), ("6", "6 per row")],
                            "label": "Items per section row",
                        },
                    ),
                    69: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["h5", "h6", "large", "bold", "italic"],
                            "help_text": "Optional caption for this image",
                            "required": False,
                        },
                    ),
                    70: (
                        "foundation_cms.blocks.link_block.OptionalLinkBlock",
                        (),
                        {"help_text": "Optional link for both image and caption", "required": False},
                    ),
                    71: ("wagtail.blocks.StructBlock", [[("image", 11), ("caption", 69), ("link", 70)]], {}),
                    72: ("wagtail.blocks.ListBlock", (71,), {"min_num": 1}),
                    73: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 66), ("section_orientation", 67), ("items_per_row", 68), ("items", 72)]],
                        {},
                    ),
                    74: ("wagtail.blocks.ListBlock", (73,), {"label": "Image grid sections", "min_num": 1}),
                    75: ("wagtail.blocks.StructBlock", [[("sections", 74)]], {"group": "Card Collections"}),
                    76: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The full value to animate, including any symbols, commas, decimals, or suffixes (e.g., $5.2M).",
                            "max_length": 5,
                            "required": True,
                        },
                    ),
                    77: ("wagtail.blocks.CharBlock", (), {"help_text": "Heading of the stat", "required": True}),
                    78: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Short description of the stat", "required": False},
                    ),
                    79: (
                        "wagtail.blocks.StructBlock",
                        [[("stat_number", 76), ("stat_heading", 77), ("stat_description", 78)]],
                        {},
                    ),
                    80: (
                        "wagtail.blocks.ListBlock",
                        (79,),
                        {
                            "default": [
                                {"stat_description": "", "stat_heading": "", "stat_number": ""},
                                {"stat_description": "", "stat_heading": "", "stat_number": ""},
                                {"stat_description": "", "stat_heading": "", "stat_number": ""},
                            ],
                            "help_text": "Add exactly 3 stats to appear in the Impact Numbers section",
                            "label": "Impact Stats",
                            "max_num": 3,
                            "min_num": 3,
                        },
                    ),
                    81: ("wagtail.blocks.StructBlock", [[("stats", 80)]], {"group": "Data Display"}),
                    82: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 19),
                                ("link_to", 20),
                                ("page", 21),
                                ("external_url", 22),
                                ("relative_url", 23),
                                ("anchor", 24),
                                ("email", 25),
                                ("file", 26),
                                ("phone", 27),
                                ("new_window", 28),
                                ("style", 29),
                                ("alignment", 30),
                            ]
                        ],
                        {"group": "Engagement & Buttons"},
                    ),
                    83: ("wagtail.blocks.CharBlock", (), {"help_text": "Heading displayed above the list"}),
                    84: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Description displayed above the list", "required": False},
                    ),
                    85: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 19),
                                ("link_to", 20),
                                ("page", 21),
                                ("external_url", 22),
                                ("relative_url", 23),
                                ("anchor", 24),
                                ("email", 25),
                                ("file", 26),
                                ("phone", 27),
                                ("new_window", 28),
                            ]
                        ],
                        {},
                    ),
                    86: ("wagtail.blocks.ListBlock", (85,), {"max_num": 4, "min_num": 1}),
                    87: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 83), ("description", 84), ("items", 86)]],
                        {"group": "Data Display"},
                    ),
                    88: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("snippets.NewsletterSignup",),
                        {"max_num": 1},
                    ),
                    89: (
                        "wagtail.blocks.StructBlock",
                        [[("newsletter_signup", 88)]],
                        {"group": "Engagement & Buttons"},
                    ),
                    90: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("snippets.NewsletterUnsubscribe",),
                        {"max_num": 1},
                    ),
                    91: (
                        "wagtail.blocks.StructBlock",
                        [[("newsletter_unsubscribe", 90)]],
                        {"group": "Engagement & Buttons"},
                    ),
                    92: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Appears as the main heading.", "label": "Headline", "required": False},
                    ),
                    93: (
                        "foundation_cms.blocks.link_block.OptionalLinkBlock",
                        (),
                        {
                            "help_text": "Optional link for the card.",
                            "label": "Call to Action Link",
                            "required": False,
                        },
                    ),
                    94: ("wagtail.blocks.StructBlock", [[("headline", 92), ("cta_link", 93)]], {}),
                    95: (
                        "wagtail.blocks.ListBlock",
                        (94,),
                        {
                            "default": [
                                {"cta_link": [], "headline": ""},
                                {"cta_link": [], "headline": ""},
                                {"cta_link": [], "headline": ""},
                            ],
                            "help_text": "3 cards required.",
                            "label": "Pillar Cards",
                            "max_num": 3,
                            "min_num": 3,
                        },
                    ),
                    96: ("wagtail.blocks.StructBlock", [[("cards", 95)]], {"group": "Card Collections"}),
                    97: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Title of the podcast. <strong>Note:</strong> Does not render on "NothingPersonal" pages.'
                        },
                    ),
                    98: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": 'Optional short description of the podcast. <strong>Note:</strong> Does not render on "NothingPersonal" pages.',
                            "required": False,
                        },
                    ),
                    99: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 97), ("description", 98), ("simplecast_embed_code", 19)]],
                        {"group": "Media & Embeds"},
                    ),
                    100: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Appears above the headline.", "label": "Label", "required": False},
                    ),
                    101: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Optional Image for the card", "label": "Image"},
                    ),
                    102: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 19),
                                ("link_to", 20),
                                ("page", 21),
                                ("external_url", 22),
                                ("relative_url", 23),
                                ("anchor", 24),
                                ("email", 25),
                                ("file", 26),
                                ("phone", 27),
                                ("new_window", 28),
                            ]
                        ],
                        {"help_text": "Link for the card.", "label": "Call to Action Link", "required": True},
                    ),
                    103: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 100), ("headline", 92), ("image", 101), ("cta_link", 102)]],
                        {},
                    ),
                    104: (
                        "wagtail.blocks.ListBlock",
                        (103,),
                        {
                            "help_text": "Minimum of 3 cards required. More than 3 will turn element into a carousel.",
                            "label": "Portrait Cards",
                            "min_num": 3,
                        },
                    ),
                    105: ("wagtail.blocks.StructBlock", [[("cards", 104)]], {"group": "Card Collections"}),
                    106: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    107: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    108: ("wagtail.blocks.StructBlock", [[("quote", 106), ("attribution", 107)]], {"group": "Text"}),
                    109: ("foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock", (), {"group": "Text"}),
                    110: ("wagtail.blocks.StructBlock", [[("size", 36)]], {"group": "Layout"}),
                    111: ("wagtail.blocks.CharBlock", (), {"label": "Name", "max_length": 50, "required": True}),
                    112: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Image should follow a 1:1 aspect ratio.", "label": "Image"},
                    ),
                    113: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 106), ("name", 111), ("description", 17), ("image", 112)]],
                        {},
                    ),
                    114: (
                        "wagtail.blocks.ListBlock",
                        (113,),
                        {"help_text": "3 cards required.", "label": "Spotlight Cards", "max_num": 3, "min_num": 3},
                    ),
                    115: ("wagtail.blocks.StructBlock", [[("cards", 114)]], {"group": "Card Collections"}),
                    116: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title shown on the tab button", "required": True},
                    ),
                    117: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Subtitle shown under the title on the tab", "required": False},
                    ),
                    118: ("foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock", (), {"required": False}),
                    119: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 63), ("image", 11), ("orientation", 64)]],
                        {"required": False},
                    ),
                    120: ("foundation_cms.blocks.link_block.OptionalLinkBlock", (), {"required": False}),
                    121: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 107), ("subtitle", 107), ("text", 118), ("image", 119), ("link", 120)]],
                        {},
                    ),
                    122: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 19), ("image", 11), ("subtitle", 19), ("link", 120)]],
                        {},
                    ),
                    123: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 1), ("text_image", 121), ("tab_card_set", 122)]],
                        {"help_text": "Add one or more content blocks to the tab.", "min_num": 1, "required": True},
                    ),
                    124: ("wagtail.blocks.StructBlock", [[("title", 116), ("subtitle", 117), ("content", 123)]], {}),
                    125: ("wagtail.blocks.ListBlock", (124,), {"label": "Tabs", "max_num": 8, "min_num": 1}),
                    126: ("wagtail.blocks.StructBlock", [[("tabs", 125)]], {"group": "Card Collections"}),
                    127: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 97), ("description", 98), ("simplecast_embed_code", 19)]],
                        {},
                    ),
                    128: ("wagtail.blocks.StructBlock", [[("title", 63), ("image", 11), ("orientation", 64)]], {}),
                    129: ("wagtail.blocks.StructBlock", [[("newsletter_signup", 88)]], {}),
                    130: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Log into Vimeo, select your desired video, and click 'Copy Link'",
                            "label": "Vimeo Video URL",
                            "required": True,
                        },
                    ),
                    131: ("wagtail.blocks.CharBlock", (), {"help_text": "Optional Caption Text", "required": False}),
                    132: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_to", 20),
                                ("page", 21),
                                ("external_url", 22),
                                ("relative_url", 23),
                                ("anchor", 24),
                                ("email", 25),
                                ("file", 26),
                                ("phone", 27),
                                ("new_window", 28),
                            ]
                        ],
                        {},
                    ),
                    133: (
                        "wagtail.blocks.ListBlock",
                        (132,),
                        {
                            "default": [],
                            "help_text": "Optional URL that this caption should link out to.",
                            "max_num": 1,
                            "min_num": 0,
                        },
                    ),
                    134: (
                        "wagtail.blocks.StructBlock",
                        [[("video_url", 130), ("caption", 131), ("caption_url", 133)]],
                        {},
                    ),
                    135: ("wagtail.blocks.StructBlock", [[("title", 83), ("description", 84), ("items", 86)]], {}),
                    136: ("wagtail.blocks.StructBlock", [[("quote", 106), ("attribution", 107)]], {}),
                    137: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 19),
                                ("link_to", 20),
                                ("page", 21),
                                ("external_url", 22),
                                ("relative_url", 23),
                                ("anchor", 24),
                                ("email", 25),
                                ("file", 26),
                                ("phone", 27),
                                ("new_window", 28),
                                ("style", 29),
                                ("alignment", 30),
                            ]
                        ],
                        {},
                    ),
                    138: (
                        "wagtail.blocks.StructBlock",
                        [[("fru_element_type", 45), ("fru_element_embed_code", 46)]],
                        {},
                    ),
                    139: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Project", "page_type": ["gallery_hub.ProjectPage"], "required": True},
                    ),
                    140: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": True, "label": "Show description", "required": False},
                    ),
                    141: ("wagtail.blocks.StructBlock", [[("project", 139), ("show_description", 140)]], {}),
                    142: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 1),
                                ("podcast", 127),
                                ("image", 128),
                                ("newsletter_signup", 129),
                                ("video", 134),
                                ("list", 135),
                                ("spacer", 37),
                                ("quote", 136),
                                ("link_button", 137),
                                ("fru_element", 138),
                                ("project_block", 141),
                            ]
                        ],
                        {"label": "Left Column", "required": False},
                    ),
                    143: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 1),
                                ("podcast", 127),
                                ("image", 128),
                                ("newsletter_signup", 129),
                                ("video", 134),
                                ("list", 135),
                                ("spacer", 37),
                                ("quote", 136),
                                ("link_button", 137),
                                ("fru_element", 138),
                                ("project_block", 141),
                            ]
                        ],
                        {"label": "Center Column", "required": False},
                    ),
                    144: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 1),
                                ("podcast", 127),
                                ("image", 128),
                                ("newsletter_signup", 129),
                                ("video", 134),
                                ("list", 135),
                                ("spacer", 37),
                                ("quote", 136),
                                ("link_button", 137),
                                ("fru_element", 138),
                                ("project_block", 141),
                            ]
                        ],
                        {"label": "Right Column", "required": False},
                    ),
                    145: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 33),
                                ("vertical_alignment", 34),
                                ("left_column", 142),
                                ("center_column", 143),
                                ("right_column", 144),
                            ]
                        ],
                        {"group": "Layout"},
                    ),
                    146: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional category for the card.", "required": False},
                    ),
                    147: ("wagtail.blocks.CharBlock", (), {"help_text": "Title for the card.", "required": True}),
                    148: (
                        "foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock",
                        (),
                        {"help_text": "Optional description text.", "required": False},
                    ),
                    149: (
                        "wagtail.blocks.StructBlock",
                        [[("category", 146), ("title", 147), ("text", 148), ("image", 11), ("link", 85)]],
                        {},
                    ),
                    150: (
                        "wagtail.blocks.StreamBlock",
                        [[("card", 149)]],
                        {"help_text": "Add between 1 and 3 cards.", "max_num": 3, "min_num": 1},
                    ),
                    151: ("wagtail.blocks.StructBlock", [[("cards", 150)]], {"group": "Card Collections"}),
                    152: ("wagtail.blocks.CharBlock", (), {"help_text": "Title for the block", "required": True}),
                    153: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("shape", "Shape"), ("loop-line", "Loop Line")],
                            "help_text": "Select the style of the title",
                        },
                    ),
                    154: ("wagtail.blocks.StructBlock", [[("title", 152), ("style", 153)]], {"group": "Text"}),
                    155: ("wagtail.blocks.StructBlock", [[("title", 107), ("text", 118)]], {}),
                    156: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 1),
                                ("podcast", 127),
                                ("image", 128),
                                ("newsletter_signup", 129),
                                ("video", 134),
                                ("list", 135),
                                ("spacer", 37),
                                ("quote", 136),
                                ("text_social", 155),
                                ("link_button", 137),
                                ("fru_element", 138),
                                ("project_block", 141),
                            ]
                        ],
                        {"label": "Left Column", "required": False},
                    ),
                    157: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 1),
                                ("podcast", 127),
                                ("image", 128),
                                ("newsletter_signup", 129),
                                ("video", 134),
                                ("list", 135),
                                ("spacer", 37),
                                ("quote", 136),
                                ("text_social", 155),
                                ("link_button", 137),
                                ("fru_element", 138),
                                ("project_block", 141),
                            ]
                        ],
                        {"label": "Right Column", "required": False},
                    ),
                    158: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 33),
                                ("vertical_alignment", 34),
                                ("left_column", 156),
                                ("right_column", 157),
                            ]
                        ],
                        {"group": "Layout"},
                    ),
                    159: (
                        "wagtail.blocks.StructBlock",
                        [[("video_url", 130), ("caption", 131), ("caption_url", 133)]],
                        {"group": "Media & Embeds"},
                    ),
                },
            ),
        ),
    ]
