# Generated by Django 3.1.11 on 2021-05-31 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('news', '0004_remove_news_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='locale',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale'),
        ),
        migrations.AddField(
            model_name='news',
            name='translation_key',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
