# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import networkapi.news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20170406_1855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-date',), 'verbose_name': 'news article', 'verbose_name_plural': 'news'},
        ),
        migrations.AddField(
            model_name='news',
            name='is_video',
            field=models.BooleanField(default=False, help_text='Is this news piece a video?'),
        ),
        migrations.AddField(
            model_name='news',
            name='thumbnail',
            field=models.FileField(blank=True, help_text='Thumbnail image associated with the news piece. Unsure of what to use? Leave blank and ask a designer', max_length=2048, null=True, upload_to=networkapi.news.models.get_thumbnail_upload_path),
        ),
        migrations.AlterField(
            model_name='news',
            name='featured',
            field=models.BooleanField(default=False, help_text='Do you want to feature this news piece on the homepage?'),
        ),
        migrations.AlterField(
            model_name='news',
            name='glyph',
            field=models.FileField(blank=True, help_text='Image associated with the article source. Unsure of what to use? Leave blank and ask a designer', max_length=2048, null=True, upload_to=networkapi.news.models.get_news_glyph_upload_path),
        ),
    ]
