# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-23 08:53
from __future__ import unicode_literals

from django.db import migrations
import filebrowser_safe.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20170504_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='glyph',
            field=filebrowser_safe.fields.FileBrowseField(blank=True, help_text='Image associated with the article source. Unsure of what to use? Leave blank and ask a designer', max_length=2048, null=True),
        ),
    ]
