# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-22 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20170322_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-date',), 'verbose_name_plural': 'news'},
        ),
        migrations.RemoveField(
            model_name='news',
            name='topic',
        ),
        migrations.AddField(
            model_name='news',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='news.Topic'),
        ),
    ]
