version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 99
  labels:
    - "engineering"
    - "dependencies"  
    - "backend"
    - "pip"
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 99
  labels:
    - "engineering"
    - "dependencies"
    - "frontend"
    - "npm"
  ignore:
    - dependency-name: "tailwindcss"
      update-types: ["version-update:semver-major"]
    - dependency-name: "react"
      update-types: ["version-update:semver-major"]
    - dependency-name: "react-dom"
      update-types: ["version-update:semver-major"]
    - dependency-name: "locomotive-scroll"
      update-types: ["version-update:semver-major"]
