pull_request_rules:
  - name: Automatic merge for dependabot PRs
    conditions:
      - "#approved-reviews-by>=1"
      - author~=^dependabot(|-preview)\[bot\]$
      - "status-success=percy/foundation.mozilla.org"
      - "status-success=Continuous Integration / Node CI (pull_request)"
      - "status-success=Continuous Integration / Wagtail CI (pull_request)"
    actions:
      merge:
        method: squash
        strict_method: rebase
        strict: true
  - name: Automatic merge for PRs labelled "ready to merge"
    conditions:
      - "#approved-reviews-by>=1"
      - "status-success=percy/foundation.mozilla.org"
      - "status-success=Continuous Integration / Node CI (pull_request)"
      - "status-success=Continuous Integration / Wagtail CI (pull_request)"
      - "label=ready-to-merge"
    actions:
      merge:
        method: squash
        strict_method: rebase
        strict: true
