queue_rules:
  - name: dependabot
    conditions:
      - "status-success=percy/foundation.mozilla.org"
      - "status-success=Continuous Integration / Node CI (pull_request)"
      - "status-success=Continuous Integration / Wagtail CI (pull_request)"

  - name: ready-to-merge
    conditions:
      - "status-success=percy/foundation.mozilla.org"
      - "status-success=Continuous Integration / Node CI (pull_request)"
      - "status-success=Continuous Integration / Wagtail CI (pull_request)"

pull_request_rules:
  - name: Automatic merge for dependabot PRs
    conditions:
      - "#approved-reviews-by>=1"
      - author~=^dependabot(|-preview)\[bot\]$
      - "status-success=percy/foundation.mozilla.org"
      - "status-success=Continuous Integration / Node CI (pull_request)"
      - "status-success=Continuous Integration / Wagtail CI (pull_request)"
    actions:
      queue:
        method: squash
        name: dependabot

  - name: Automatic merge for PRs labelled "ready to merge"
    conditions:
      - "#approved-reviews-by>=1"
      - "status-success=percy/foundation.mozilla.org"
      - "status-success=Continuous Integration / Node CI (pull_request)"
      - "status-success=Continuous Integration / Wagtail CI (pull_request)"
      - "label=ready-to-merge"
    actions:
      queue:
        method: squash
        name: ready-to-merge
