[tool.black]
line-length = 119
target-version = ['py39']

[tool.djlint]
profile = "django"
use_gitignore = true
# H017: Ignored because opposite of W3C validator recommendation.
ignore="H017"


[tool.isort]
profile = "black"
extend_skip = ["network-api/media", "network-api/staticfiles"]
skip_gitignore = true
known_first_party = ["networkapi"]
