[tool.black]
line-length = 119
target-version = ['py39']

[tool.djlint]
blank_line_before_tag="load,extends,include,block"
blank_line_after_tag="load,extends,include,endblock"
format_attribute_template_tags = true
profile = "django"
use_gitignore = true

[tool.isort]
profile = "black"
extend_skip = ["network-api/media", "network-api/staticfiles"]
skip_gitignore = true
known_first_party = ["networkapi"]
