# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-23 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.migrations.operations.special
import django.db.models.deletion


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# networkapi.landingpage.migrations.0004_signup_title

class Migration(migrations.Migration):

    replaces = [
        ('landingpage', '0001_initial'),
        ('landingpage', '0002_remove_landingpage_name'),
        ('landingpage', '0003_delete_footerlink'),
        ('landingpage', '0004_signup_title'),
        ('landingpage', '0005_auto_20170428_2134'),
        ('landingpage', '0006_signup_newsletter'),
        ('landingpage', '0007_auto_20180125_1539'),
        ('landingpage', '0008_auto_20180626_1546')
    ]

    initial = True

    dependencies = [
    ]

    operations = [
    ]
