# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-25 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0006_signup_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='newsletter',
            field=models.CharField(default='mozilla-foundation', help_text='The (pre-existing) SalesForce newsletter to sign up for', max_length=100),
        ),
    ]
