# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 22:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20170411_0504'),
        ('landingpage', '0007_auto_20180125_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='signup',
        ),
        migrations.DeleteModel(
            name='LandingPage',
        ),
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
