from django.shortcuts import render

PALETTE = [
    "#FF6B6B",
    "#4ECDC4",
    "#45B7D1",
    "#96CEB4",
    "#FFEAA7",
    "#DDA0DD",
    "#98D8C8",
    "#F7DC6F",
]

FILLER_PROJECTS = [
    {
        "name": "Signal Garden",
        "expert": "Mara Osei",
        "image": None,
        "bg_color": PALETTE[0],
        "tags": ["Imagination"],
        "program": "TIAT Residency",
        "country": "Ghana",
        "year": 2025,
        "url": "/test-test",
        "filler": True,
    },
    {
        "name": "Open Frequencies",
        "expert": "Teo Vasquez",
        "image": None,
        "bg_color": PALETTE[1],
        "tags": ["Digital Inclusion", "Community"],
        "program": "Mozilla Fellow",
        "country": "Colombia",
        "year": 2024,
        "url": "/test-test",
        "filler": True,
    },
    {
        "name": "Mirror Protocol",
        "expert": "Yuki Ishida",
        "image": None,
        "bg_color": PALETTE[2],
        "tags": ["Artificial Intelligence"],
        "program": "TIAT Residency",
        "country": "Japan",
        "year": 2025,
        "url": "/test-test",
        "filler": True,
    },
    {
        "name": "Threshold",
        "expert": "Amara Diallo",
        "image": None,
        "bg_color": PALETTE[3],
        "tags": ["Community", "Imagination"],
        "program": "Mozilla Fellow",
        "country": "Senegal",
        "year": 2025,
        "url": "/test-test",
        "filler": True,
    },
    {
        "name": "The Listening Machine",
        "expert": "Finn Larsen",
        "image": None,
        "bg_color": PALETTE[4],
        "tags": ["Artificial Intelligence", "Digital Inclusion"],
        "program": "TIAT Residency",
        "country": "Denmark",
        "year": 2024,
        "url": "/test-test",
        "filler": True,
    },
    {
        "name": "Data Rituals",
        "expert": "Cleo Ferreira",
        "image": None,
        "bg_color": PALETTE[5],
        "tags": ["Community"],
        "program": "Mozilla Fellow",
        "country": "Brazil",
        "year": 2025,
        "url": "/test-test",
        "filler": True,
    },
    {
        "name": "Phantom Cartography",
        "expert": "Reza Ahmadi",
        "image": None,
        "bg_color": PALETTE[6],
        "tags": ["Imagination"],
        "program": "TIAT Residency",
        "country": "Iran",
        "year": 2024,
        "url": "/test-test",
        "filler": True,
    },
    {
        "name": "Consent Engine",
        "expert": "Nadia Owusu",
        "image": None,
        "bg_color": PALETTE[7],
        "tags": ["Digital Inclusion", "Community"],
        "program": "Mozilla Fellow",
        "country": "Kenya",
        "year": 2025,
        "url": "/test-test",
        "filler": True,
    },
    {
        "name": "Soft Infrastructure",
        "expert": "Luca Bianchi",
        "image": None,
        "bg_color": PALETTE[0],
        "tags": ["Artificial Intelligence"],
        "program": "TIAT Residency",
        "country": "Italy",
        "year": 2025,
        "url": "/test-test",
        "filler": True,
    },
    {
        "name": "Echo Chamber Studies",
        "expert": "Soo-Jin Park",
        "image": None,
        "bg_color": PALETTE[1],
        "tags": ["Community", "Imagination"],
        "program": "Mozilla Fellow",
        "country": "South Korea",
        "year": 2024,
        "url": "/test-test",
        "filler": True,
    },
    {
        "name": "Ground Truth",
        "expert": "Emeka Eze",
        "image": None,
        "bg_color": PALETTE[2],
        "tags": ["Digital Inclusion"],
        "program": "TIAT Residency",
        "country": "Nigeria",
        "year": 2025,
        "url": "/test-test",
        "filler": True,
    },
    {
        "name": "Tender Networks",
        "expert": "Ingrid Holst",
        "image": None,
        "bg_color": PALETTE[3],
        "tags": ["Community", "Artificial Intelligence"],
        "program": "Mozilla Fellow",
        "country": "Sweden",
        "year": 2025,
        "url": "/test-test",
        "filler": True,
    },
    {
        "name": "Latent Space",
        "expert": "Diego Reyes",
        "image": None,
        "bg_color": PALETTE[4],
        "tags": ["Imagination", "Artificial Intelligence"],
        "program": "TIAT Residency",
        "country": "Mexico",
        "year": 2024,
        "url": "/test-test",
        "filler": True,
    },
    {
        "name": "Civic Pulse",
        "expert": "Anika Sen",
        "image": None,
        "bg_color": PALETTE[5],
        "tags": ["Community", "Digital Inclusion"],
        "program": "Mozilla Fellow",
        "country": "India",
        "year": 2025,
        "url": "/test-test",
        "filler": True,
    },
    {
        "name": "The Quiet Algorithm",
        "expert": "Zara Mensah",
        "image": None,
        "bg_color": PALETTE[6],
        "tags": ["Artificial Intelligence", "Imagination"],
        "program": "TIAT Residency",
        "country": "Ghana",
        "year": 2025,
        "url": "/test-test",
        "filler": True,
    },
]

PROJECTS = [
    {
        "name": "Soft Trigger",
        "expert": "Althea Rao",
        "image": "foundation_cms/_images/prototype/gallery/soft-trigger.jpg",
        "bg_color": None,
        "tags": ["Artificial Intelligence"],
        "program": "TIAT Residency",
        "country": "USA",
        "year": 2025,
        "url": "/test-test",
    },
    {
        "name": "Stuck in the Middle",
        "expert": "Avital Meshi",
        "image": "foundation_cms/_images/prototype/gallery/stuck-in-the-middle.png",
        "bg_color": None,
        "tags": ["Artificial Intelligence"],
        "program": "TIAT Residency",
        "country": "USA",
        "year": 2025,
        "url": "/test-test",
    },
    {
        "name": "Archive the Memory",
        "expert": "Cheng Xu",
        "image": "foundation_cms/_images/prototype/gallery/archive-the-memory.jpg",
        "bg_color": None,
        "tags": ["Community", "Imagination", "Artificial Intelligence"],
        "program": "TIAT Residency",
        "country": "USA",
        "year": 2025,
        "url": "/test-test",
    },
    {
        "name": "Versus.exe",
        "expert": "Halim Madi",
        "image": "foundation_cms/_images/prototype/gallery/versus-exe.jpg",
        "bg_color": None,
        "tags": ["Digital Inclusion"],
        "program": "TIAT Residency",
        "country": "USA",
        "year": 2025,
        "url": "/test-test",
    },
    {
        "name": "The Beating Heart",
        "expert": "Héloïse Garry",
        "image": "foundation_cms/_images/prototype/gallery/the-beating-heart.jpg",
        "bg_color": None,
        "tags": ["Imagination"],
        "program": "TIAT Residency",
        "country": "USA",
        "year": 2025,
        "url": "/test-test",
    },
    {
        "name": "Prompt Fountain – Slop Generator",
        "expert": "Jordan Metz",
        "image": "foundation_cms/_images/prototype/gallery/prompt-fountain-slop-generator.jpg",
        "bg_color": None,
        "tags": ["Community", "Imagination", "Artificial Intelligence"],
        "program": "TIAT Residency",
        "country": "USA",
        "year": 2025,
        "url": "/test-test",
    },
    {
        "name": "Memory Well",
        "expert": "Nocellcoverage",
        "image": "foundation_cms/_images/prototype/gallery/memory-well.gif",
        "bg_color": None,
        "tags": ["Community", "Imagination", "Artificial Intelligence"],
        "program": "TIAT Residency",
        "country": "USA",
        "year": 2025,
        "url": "/test-test",
    },
    {
        "name": "SUPER ASHA",
        "expert": "Priya Goswami",
        "image": "foundation_cms/_images/prototype/gallery/super-asha.jpg",
        "bg_color": None,
        "tags": ["Community"],
        "program": "Mozilla Fellow",
        "country": "Hong Kong",
        "year": 2025,
        "url": "/test-test",
    },
    {
        "name": "Citizen Data Generation",
        "expert": "Thiane Neves Barros",
        "image": "foundation_cms/_images/prototype/gallery/citizen-data-generation.jpg",
        "bg_color": None,
        "tags": ["Community"],
        "program": "Mozilla Fellow",
        "country": "Brasil",
        "year": 2025,
        "url": "/test-test",
    },
]


def prototype_gallery(request):
    projects = PROJECTS + FILLER_PROJECTS
    return render(request, "patterns/pages/prototype/gallery.html", {"projects": projects})
