# Generated by Django 3.2.21 on 2023-10-13 01:11

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("donate", "0004_remove_donatehelppage_show_notice_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="donatehelppage",
            name="notice",
            field=wagtail.fields.StreamField(
                [
                    (
                        "notice",
                        wagtail.blocks.StructBlock(
                            [
                                ("image", wagtail.images.blocks.ImageChooserBlock(required=False)),
                                (
                                    "image_altText",
                                    wagtail.blocks.CharBlock(
                                        help_text="Image description (for screen readers).", required=False
                                    ),
                                ),
                                ("text", wagtail.blocks.RichTextBlock(features=["bold", "italic", "link"])),
                            ]
                        ),
                    )
                ],
                blank=True,
                help_text="Optional notice that will render at the top of the page.",
                use_json_field=True,
            ),
        ),
    ]
