# Generated by Django 4.2.11 on 2024-05-22 22:22

import uuid

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donate", "0010_make_link_to_required_in_link_block"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donatehelppage",
            name="notice",
        ),
        migrations.CreateModel(
            name="HelpPageNotice",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("translation_key", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("name", models.CharField(help_text="What will this notice be called in the CMS?", max_length=50)),
                ("text", wagtail.fields.RichTextField()),
                (
                    "notice_image_alt_text",
                    models.CharField(blank=True, help_text="Image description (for screen readers).", max_length=50),
                ),
                (
                    "locale",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="wagtailcore.locale",
                    ),
                ),
                (
                    "notice_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="wagtailimages.image",
                        verbose_name="Notice Image",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("translation_key", "locale")},
            },
        ),
        migrations.AddField(
            model_name="donatehelppage",
            name="notice",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional notice that will render at the top of the page.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="donate.helppagenotice",
            ),
        ),
    ]
