# Generated by Django 4.2.20 on 2025-03-26 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
        ("donate", "0028_alter_donatehelppage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donatehelppage",
            name="search_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Image must be high quality, include our logo mark and have the dimensions 1200 x 628 px. For more design guidelines see here: https://foundation.mozilla.org/en/docs/brand/brand-identity/social-media/#og-images",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.foundationcustomimage",
                verbose_name="Search image",
            ),
        ),
        migrations.AlterField(
            model_name="donatelandingpage",
            name="featured_image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="+", to="images.foundationcustomimage"
            ),
        ),
        migrations.AlterField(
            model_name="donatelandingpage",
            name="search_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Image must be high quality, include our logo mark and have the dimensions 1200 x 628 px. For more design guidelines see here: https://foundation.mozilla.org/en/docs/brand/brand-identity/social-media/#og-images",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.foundationcustomimage",
                verbose_name="Search image",
            ),
        ),
        migrations.AlterField(
            model_name="helppagenotice",
            name="notice_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="images.foundationcustomimage",
                verbose_name="Notice Image",
            ),
        ),
    ]
