# Generated by Django 5.1.4 on 2025-01-14 17:52

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="roles",
            field=wagtail.fields.StreamField(
                [("researcher", 2), ("blog_author", 5), ("grantee", 7)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Research area or expertise"},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Affiliated institution"},
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("research_area", 0), ("institution", 1)]],
                        {"label": "Researcher Role", "max_num": 1},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Primary blog topic or category"},
                    ),
                    4: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Short author bio"},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("blog_topic", 3), ("bio", 4)]],
                        {"label": "Blog Author Role", "max_num": 1},
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Primary project"},
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("project", 6)]],
                        {"label": "Grantee Role", "max_num": 1},
                    ),
                },
            ),
        ),
    ]
