# Generated by Django 5.2.15 on 2026-08-24 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0012_expertprofilepage_selected_article_and_project"),
        ("snippets", "0013_noticebanner"),
    ]

    operations = [
        migrations.AddField(
            model_name="expertdirectorypage",
            name="notice_banner",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional. Displays a notice at the top of this page, e.g. to announce that the content has moved or is no longer maintained.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="snippets.noticebanner",
            ),
        ),
        migrations.AddField(
            model_name="experthubpage",
            name="notice_banner",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional. Displays a notice at the top of this page, e.g. to announce that the content has moved or is no longer maintained.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="snippets.noticebanner",
            ),
        ),
        migrations.AddField(
            model_name="expertprofilepage",
            name="notice_banner",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional. Displays a notice at the top of this page, e.g. to announce that the content has moved or is no longer maintained.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="snippets.noticebanner",
            ),
        ),
    ]
