# Generated by Django 5.2.15 on 2026-10-08 18:29

import wagtail.fields
from django.db import migrations

import foundation_cms.legacy_apps.wagtailpages.validators
import foundation_cms.validators


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0015_alter_experthubpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expertdirectorypage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("accordion_block", 5),
                    ("divider", 6),
                    ("featured_card_block", 23),
                    ("flywheel_banner", 26),
                    ("fru_element_block", 29),
                    ("icon_info_grid", 39),
                    ("iframe_block", 44),
                    ("image", 48),
                    ("image_grid", 58),
                    ("impact_numbers", 64),
                    ("link_button_block", 65),
                    ("list_block", 70),
                    ("newsletter_signup", 72),
                    ("newsletter_unsubscribe", 74),
                    ("pillar_card_set", 79),
                    ("podcast_block", 82),
                    ("portrait_card_set_block", 88),
                    ("quote", 91),
                    ("rich_text", 92),
                    ("spacer_block", 94),
                    ("spotlight_card_set_block", 99),
                    ("tabbed_content", 110),
                    ("three_column_container_block", 132),
                    ("timely_activations_cards", 138),
                    ("title_block", 141),
                    ("two_column_container_block", 145),
                    ("video_block", 146),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Heading for the Accordion Item", "required": True},
                    ),
                    1: ("foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock", (), {}),
                    2: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 1)]],
                        {"required": False, "use_json_field": True},
                    ),
                    3: ("wagtail.blocks.StructBlock", [[("title", 0), ("content", 2)]], {}),
                    4: ("wagtail.blocks.ListBlock", (3,), {"min_num": 1}),
                    5: ("wagtail.blocks.StructBlock", [[("accordion_items", 4)]], {"group": "Text"}),
                    6: ("wagtail.blocks.StructBlock", [[]], {"group": "Layout"}),
                    7: ("wagtail.blocks.CharBlock", (), {"label": "Heading", "max_length": 50, "required": True}),
                    8: (
                        "foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock",
                        (),
                        {"features": ["bold", "italic"], "label": "Description", "max_length": 500, "required": True},
                    ),
                    9: ("wagtail.images.blocks.ImageBlock", [], {"help_text": "Image for the card", "label": "Image"}),
                    10: ("wagtail.blocks.CharBlock", (), {}),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("external_url", "External URL"),
                                ("relative_url", "Relative URL"),
                                ("email", "Email"),
                                ("anchor", "Anchor"),
                                ("file", "File"),
                                ("phone", "Phone"),
                            ],
                            "label": "Link to",
                        },
                    ),
                    12: ("wagtail.blocks.PageChooserBlock", (), {"label": "Page", "required": False}),
                    13: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Enter a full URL including http:// or https://",
                            "label": "External URL",
                            "max_length": 300,
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'A path relative to this domain. For example, "/foo/bar" or "?foo=bar".',
                            "label": "Relative URL",
                            "max_length": 300,
                            "required": False,
                            "validators": [foundation_cms.legacy_apps.wagtailpages.validators.RelativeURLValidator()],
                        },
                    ),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'An id attribute of an element on the current page. For example, "#section-1"',
                            "label": "#",
                            "max_length": 300,
                            "required": False,
                            "validators": [foundation_cms.validators.AnchorLinkValidator()],
                        },
                    ),
                    16: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    17: ("wagtail.documents.blocks.DocumentChooserBlock", (), {"label": "File", "required": False}),
                    18: ("wagtail.blocks.CharBlock", (), {"label": "Phone", "max_length": 30, "required": False}),
                    19: ("wagtail.blocks.BooleanBlock", (), {"label": "Open in new window", "required": False}),
                    20: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("btn-primary", "Primary"), ("btn-secondary", "Secondary")]},
                    ),
                    21: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("link-button-block--left", "Left"), ("link-button-block--center", "Center")]},
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 10),
                                ("link_to", 11),
                                ("page", 12),
                                ("external_url", 13),
                                ("relative_url", 14),
                                ("anchor", 15),
                                ("email", 16),
                                ("file", 17),
                                ("phone", 18),
                                ("new_window", 19),
                                ("style", 20),
                                ("alignment", 21),
                            ]
                        ],
                        {"help_text": "Link button for the card.", "label": "Button", "required": False},
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 7), ("description", 8), ("image", 9), ("button", 22)]],
                        {"group": "Card Collections"},
                    ),
                    24: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("imagine", "Imagine"), ("co-create", "Co-create"), ("mobilize", "Mobilize")],
                            "help_text": "Select the mission that determines the banner artwork and colors.",
                        },
                    ),
                    25: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Imagine",
                            "help_text": "Defaults to the mission name, but can be customized and translated.",
                            "max_length": 50,
                        },
                    ),
                    26: ("wagtail.blocks.StructBlock", [[("mission", 24), ("heading", 25)]], {"group": "Banners"}),
                    27: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("donation-form", "Donation Form"),
                                ("donor-map", "Donor Map"),
                                ("top-locations", "Top Locations"),
                                ("donation-levels", "Donation Levels"),
                                ("donate-button", "Donate Button"),
                            ],
                            "help_text": "Select the type of Fundraise Up element.",
                        },
                    ),
                    28: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Copy the HTML code generated by the desired Fundraise Up element and paste it here.",
                            "required": True,
                        },
                    ),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [[("fru_element_type", 27), ("fru_element_embed_code", 28)]],
                        {"group": "Engagement & Buttons"},
                    ),
                    30: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Section heading for this grid", "max_length": 100, "required": True},
                    ),
                    31: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("orange", "Orange"), ("black", "Black")],
                            "help_text": "Color applied to all icons in this grid",
                        },
                    ),
                    32: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("1", "1 column"), ("2", "2 columns"), ("3", "3 columns")],
                            "help_text": "Number of columns on desktop (automatically stacks on mobile)",
                            "label": "Number of columns for this grid",
                        },
                    ),
                    33: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("compact", "Compact (icons + titles only)"),
                                ("detailed", "Detailed (icons + titles + descriptions)"),
                            ],
                            "help_text": "Choose content density. Compact hides descriptions, Detailed shows them.",
                            "label": "Layout style",
                        },
                    ),
                    34: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("chat", "Chat icon"),
                                ("eye-open", "Eye Open icon"),
                                ("gear", "Gear icon"),
                                ("globe", "Globe icon"),
                                ("megaphone", "Megaphone icon"),
                                ("star", "Star icon"),
                            ],
                            "help_text": "Select an icon for this item",
                        },
                    ),
                    35: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title for this item", "max_length": 100, "required": True},
                    ),
                    36: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional description (max 126 characters)",
                            "max_length": 126,
                            "required": False,
                        },
                    ),
                    37: ("wagtail.blocks.StructBlock", [[("icon", 34), ("title", 35), ("description", 36)]], {}),
                    38: ("wagtail.blocks.ListBlock", (37,), {"help_text": "Add icon info items", "min_num": 1}),
                    39: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 30), ("icon_color", 31), ("columns", 32), ("layout_style", 33), ("items", 38)]],
                        {"group": "Card Collections"},
                    ),
                    40: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Please note that only URLs from allow-listed domains will work."},
                    ),
                    41: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Optional integer pixel value for custom iFrame height", "required": False},
                    ),
                    42: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("normal", "Normal"), ("full_width", "Full Width")]},
                    ),
                    43: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": 'Checking this will add "scrolling=no" to the iframe. Use this if your iframe is rendering an unnecessary scroll bar or whitespace below it.',
                            "required": False,
                        },
                    ),
                    44: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 40), ("height", 41), ("iframe_width", 42), ("disable_scroll", 43)]],
                        {"group": "Media & Embeds"},
                    ),
                    45: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title/caption for this image", "required": False},
                    ),
                    46: ("wagtail.images.blocks.ImageBlock", [], {}),
                    47: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("portrait", "Portrait"), ("landscape", "Landscape"), ("square", "Square")],
                            "help_text": "Select the orientation of this image",
                        },
                    ),
                    48: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 45), ("image", 46), ("orientation", 47)]],
                        {"group": "Media & Embeds"},
                    ),
                    49: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional heading for this section", "max_length": 100, "required": False},
                    ),
                    50: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("portrait", "Portrait (2:3)"),
                                ("landscape", "Landscape (3:2)"),
                                ("square", "Square (1:1)"),
                            ],
                            "help_text": "Orientation for all images in this section",
                            "label": "Image grid section orientation",
                        },
                    ),
                    51: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("4", "4 per row"), ("5", "5 per row"), ("6", "6 per row")],
                            "label": "Items per section row",
                        },
                    ),
                    52: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["h5", "h6", "large", "bold", "italic"],
                            "help_text": "Optional caption for this image",
                            "required": False,
                        },
                    ),
                    53: (
                        "foundation_cms.blocks.link_block.OptionalLinkBlock",
                        (),
                        {"help_text": "Optional link for both image and caption", "required": False},
                    ),
                    54: ("wagtail.blocks.StructBlock", [[("image", 46), ("caption", 52), ("link", 53)]], {}),
                    55: ("wagtail.blocks.ListBlock", (54,), {"min_num": 1}),
                    56: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 49), ("section_orientation", 50), ("items_per_row", 51), ("items", 55)]],
                        {},
                    ),
                    57: ("wagtail.blocks.ListBlock", (56,), {"label": "Image grid sections", "min_num": 1}),
                    58: ("wagtail.blocks.StructBlock", [[("sections", 57)]], {"group": "Card Collections"}),
                    59: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The full value to animate, including any symbols, commas, decimals, or suffixes (e.g., $5.2M).",
                            "max_length": 5,
                            "required": True,
                        },
                    ),
                    60: ("wagtail.blocks.CharBlock", (), {"help_text": "Heading of the stat", "required": True}),
                    61: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Short description of the stat", "required": False},
                    ),
                    62: (
                        "wagtail.blocks.StructBlock",
                        [[("stat_number", 59), ("stat_heading", 60), ("stat_description", 61)]],
                        {},
                    ),
                    63: (
                        "wagtail.blocks.ListBlock",
                        (62,),
                        {
                            "default": [
                                {"stat_description": "", "stat_heading": "", "stat_number": ""},
                                {"stat_description": "", "stat_heading": "", "stat_number": ""},
                                {"stat_description": "", "stat_heading": "", "stat_number": ""},
                            ],
                            "help_text": "Add exactly 3 stats to appear in the Impact Numbers section",
                            "label": "Impact Stats",
                            "max_num": 3,
                            "min_num": 3,
                        },
                    ),
                    64: ("wagtail.blocks.StructBlock", [[("stats", 63)]], {"group": "Data Display"}),
                    65: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 10),
                                ("link_to", 11),
                                ("page", 12),
                                ("external_url", 13),
                                ("relative_url", 14),
                                ("anchor", 15),
                                ("email", 16),
                                ("file", 17),
                                ("phone", 18),
                                ("new_window", 19),
                                ("style", 20),
                                ("alignment", 21),
                            ]
                        ],
                        {"group": "Engagement & Buttons"},
                    ),
                    66: ("wagtail.blocks.CharBlock", (), {"help_text": "Heading displayed above the list"}),
                    67: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Description displayed above the list", "required": False},
                    ),
                    68: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 10),
                                ("link_to", 11),
                                ("page", 12),
                                ("external_url", 13),
                                ("relative_url", 14),
                                ("anchor", 15),
                                ("email", 16),
                                ("file", 17),
                                ("phone", 18),
                                ("new_window", 19),
                            ]
                        ],
                        {},
                    ),
                    69: ("wagtail.blocks.ListBlock", (68,), {"max_num": 4, "min_num": 1}),
                    70: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 66), ("description", 67), ("items", 69)]],
                        {"group": "Data Display"},
                    ),
                    71: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("snippets.NewsletterSignup",),
                        {"max_num": 1},
                    ),
                    72: (
                        "wagtail.blocks.StructBlock",
                        [[("newsletter_signup", 71)]],
                        {"group": "Engagement & Buttons"},
                    ),
                    73: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("snippets.NewsletterUnsubscribe",),
                        {"max_num": 1},
                    ),
                    74: (
                        "wagtail.blocks.StructBlock",
                        [[("newsletter_unsubscribe", 73)]],
                        {"group": "Engagement & Buttons"},
                    ),
                    75: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Appears as the main heading.", "label": "Headline", "required": False},
                    ),
                    76: (
                        "foundation_cms.blocks.link_block.OptionalLinkBlock",
                        (),
                        {
                            "help_text": "Optional link for the card.",
                            "label": "Call to Action Link",
                            "required": False,
                        },
                    ),
                    77: ("wagtail.blocks.StructBlock", [[("headline", 75), ("cta_link", 76)]], {}),
                    78: (
                        "wagtail.blocks.ListBlock",
                        (77,),
                        {
                            "default": [
                                {"cta_link": [], "headline": ""},
                                {"cta_link": [], "headline": ""},
                                {"cta_link": [], "headline": ""},
                            ],
                            "help_text": "3 cards required.",
                            "label": "Pillar Cards",
                            "max_num": 3,
                            "min_num": 3,
                        },
                    ),
                    79: ("wagtail.blocks.StructBlock", [[("cards", 78)]], {"group": "Card Collections"}),
                    80: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Title of the podcast. <strong>Note:</strong> Does not render on "NothingPersonal" pages.'
                        },
                    ),
                    81: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": 'Optional short description of the podcast. <strong>Note:</strong> Does not render on "NothingPersonal" pages.',
                            "required": False,
                        },
                    ),
                    82: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 80), ("description", 81), ("simplecast_embed_code", 10)]],
                        {"group": "Media & Embeds"},
                    ),
                    83: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Appears above the headline.", "label": "Label", "required": False},
                    ),
                    84: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Optional Image for the card", "label": "Image"},
                    ),
                    85: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 10),
                                ("link_to", 11),
                                ("page", 12),
                                ("external_url", 13),
                                ("relative_url", 14),
                                ("anchor", 15),
                                ("email", 16),
                                ("file", 17),
                                ("phone", 18),
                                ("new_window", 19),
                            ]
                        ],
                        {"help_text": "Link for the card.", "label": "Call to Action Link", "required": True},
                    ),
                    86: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 83), ("headline", 75), ("image", 84), ("cta_link", 85)]],
                        {},
                    ),
                    87: (
                        "wagtail.blocks.ListBlock",
                        (86,),
                        {
                            "help_text": "Minimum of 3 cards required. More than 3 will turn element into a carousel.",
                            "label": "Portrait Cards",
                            "min_num": 3,
                        },
                    ),
                    88: ("wagtail.blocks.StructBlock", [[("cards", 87)]], {"group": "Card Collections"}),
                    89: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    90: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    91: ("wagtail.blocks.StructBlock", [[("quote", 89), ("attribution", 90)]], {"group": "Text"}),
                    92: ("foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock", (), {"group": "Text"}),
                    93: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("small", "Small"),
                                ("medium", "Medium"),
                                ("large", "Large"),
                                ("xlarge", "Extra Large"),
                            ],
                            "help_text": "Select the size of the spacer",
                        },
                    ),
                    94: ("wagtail.blocks.StructBlock", [[("size", 93)]], {"group": "Layout"}),
                    95: ("wagtail.blocks.CharBlock", (), {"label": "Name", "max_length": 50, "required": True}),
                    96: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Image should follow a 1:1 aspect ratio.", "label": "Image"},
                    ),
                    97: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 89), ("name", 95), ("description", 8), ("image", 96)]],
                        {},
                    ),
                    98: (
                        "wagtail.blocks.ListBlock",
                        (97,),
                        {"help_text": "3 cards required.", "label": "Spotlight Cards", "max_num": 3, "min_num": 3},
                    ),
                    99: ("wagtail.blocks.StructBlock", [[("cards", 98)]], {"group": "Card Collections"}),
                    100: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title shown on the tab button", "required": True},
                    ),
                    101: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Subtitle shown under the title on the tab", "required": False},
                    ),
                    102: ("foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock", (), {"required": False}),
                    103: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 45), ("image", 46), ("orientation", 47)]],
                        {"required": False},
                    ),
                    104: ("foundation_cms.blocks.link_block.OptionalLinkBlock", (), {"required": False}),
                    105: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 90), ("subtitle", 90), ("text", 102), ("image", 103), ("link", 104)]],
                        {},
                    ),
                    106: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 10), ("image", 46), ("subtitle", 10), ("link", 104)]],
                        {},
                    ),
                    107: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 1), ("text_image", 105), ("tab_card_set", 106)]],
                        {"help_text": "Add one or more content blocks to the tab.", "min_num": 1, "required": True},
                    ),
                    108: ("wagtail.blocks.StructBlock", [[("title", 100), ("subtitle", 101), ("content", 107)]], {}),
                    109: ("wagtail.blocks.ListBlock", (108,), {"label": "Tabs", "max_num": 8, "min_num": 1}),
                    110: ("wagtail.blocks.StructBlock", [[("tabs", 109)]], {"group": "Card Collections"}),
                    111: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("white", "White"),
                                ("neutral-100", "Grey 100"),
                                ("neutral-200", "Grey 200"),
                                ("neutral-300", "Grey 300"),
                                ("blue-100", "Blue 100"),
                                ("blue-200", "Blue 200"),
                                ("blue-300", "Blue 300"),
                                ("green-100", "Green 100"),
                                ("green-200", "Green 200"),
                                ("green-300", "Green 300"),
                                ("orange-100", "Orange 100"),
                                ("orange-200", "Orange 200"),
                                ("orange-300", "Orange 300"),
                                ("yellow-100", "Yellow 100"),
                                ("yellow-200", "Yellow 200"),
                                ("yellow-300", "Yellow 300"),
                            ]
                        },
                    ),
                    112: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("top", "Top"), ("middle", "Middle"), ("bottom", "Bottom")],
                            "help_text": "Vertical alignment of the columns content",
                        },
                    ),
                    113: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 80), ("description", 81), ("simplecast_embed_code", 10)]],
                        {},
                    ),
                    114: ("wagtail.blocks.StructBlock", [[("title", 45), ("image", 46), ("orientation", 47)]], {}),
                    115: ("wagtail.blocks.StructBlock", [[("newsletter_signup", 71)]], {}),
                    116: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Log into Vimeo, select your desired video, and click 'Copy Link'",
                            "label": "Vimeo Video URL",
                            "required": True,
                        },
                    ),
                    117: ("wagtail.blocks.CharBlock", (), {"help_text": "Optional Caption Text", "required": False}),
                    118: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_to", 11),
                                ("page", 12),
                                ("external_url", 13),
                                ("relative_url", 14),
                                ("anchor", 15),
                                ("email", 16),
                                ("file", 17),
                                ("phone", 18),
                                ("new_window", 19),
                            ]
                        ],
                        {},
                    ),
                    119: (
                        "wagtail.blocks.ListBlock",
                        (118,),
                        {
                            "default": [],
                            "help_text": "Optional URL that this caption should link out to.",
                            "max_num": 1,
                            "min_num": 0,
                        },
                    ),
                    120: (
                        "wagtail.blocks.StructBlock",
                        [[("video_url", 116), ("caption", 117), ("caption_url", 119)]],
                        {},
                    ),
                    121: ("wagtail.blocks.StructBlock", [[("title", 66), ("description", 67), ("items", 69)]], {}),
                    122: ("wagtail.blocks.StructBlock", [[("size", 93)]], {}),
                    123: ("wagtail.blocks.StructBlock", [[("quote", 89), ("attribution", 90)]], {}),
                    124: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 10),
                                ("link_to", 11),
                                ("page", 12),
                                ("external_url", 13),
                                ("relative_url", 14),
                                ("anchor", 15),
                                ("email", 16),
                                ("file", 17),
                                ("phone", 18),
                                ("new_window", 19),
                                ("style", 20),
                                ("alignment", 21),
                            ]
                        ],
                        {},
                    ),
                    125: (
                        "wagtail.blocks.StructBlock",
                        [[("fru_element_type", 27), ("fru_element_embed_code", 28)]],
                        {},
                    ),
                    126: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Project", "page_type": ["gallery_hub.ProjectPage"], "required": True},
                    ),
                    127: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": True, "label": "Show description", "required": False},
                    ),
                    128: ("wagtail.blocks.StructBlock", [[("project", 126), ("show_description", 127)]], {}),
                    129: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 1),
                                ("podcast", 113),
                                ("image", 114),
                                ("newsletter_signup", 115),
                                ("video", 120),
                                ("list", 121),
                                ("spacer", 122),
                                ("quote", 123),
                                ("link_button", 124),
                                ("fru_element", 125),
                                ("project_block", 128),
                            ]
                        ],
                        {"label": "Left Column", "required": False},
                    ),
                    130: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 1),
                                ("podcast", 113),
                                ("image", 114),
                                ("newsletter_signup", 115),
                                ("video", 120),
                                ("list", 121),
                                ("spacer", 122),
                                ("quote", 123),
                                ("link_button", 124),
                                ("fru_element", 125),
                                ("project_block", 128),
                            ]
                        ],
                        {"label": "Center Column", "required": False},
                    ),
                    131: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 1),
                                ("podcast", 113),
                                ("image", 114),
                                ("newsletter_signup", 115),
                                ("video", 120),
                                ("list", 121),
                                ("spacer", 122),
                                ("quote", 123),
                                ("link_button", 124),
                                ("fru_element", 125),
                                ("project_block", 128),
                            ]
                        ],
                        {"label": "Right Column", "required": False},
                    ),
                    132: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 111),
                                ("vertical_alignment", 112),
                                ("left_column", 129),
                                ("center_column", 130),
                                ("right_column", 131),
                            ]
                        ],
                        {"group": "Layout"},
                    ),
                    133: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional category for the card.", "required": False},
                    ),
                    134: ("wagtail.blocks.CharBlock", (), {"help_text": "Title for the card.", "required": True}),
                    135: (
                        "foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock",
                        (),
                        {"help_text": "Optional description text.", "required": False},
                    ),
                    136: (
                        "wagtail.blocks.StructBlock",
                        [[("category", 133), ("title", 134), ("text", 135), ("image", 46), ("link", 68)]],
                        {},
                    ),
                    137: (
                        "wagtail.blocks.StreamBlock",
                        [[("card", 136)]],
                        {"help_text": "Add between 1 and 3 cards.", "max_num": 3, "min_num": 1},
                    ),
                    138: ("wagtail.blocks.StructBlock", [[("cards", 137)]], {"group": "Card Collections"}),
                    139: ("wagtail.blocks.CharBlock", (), {"help_text": "Title for the block", "required": True}),
                    140: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("shape", "Shape"), ("loop-line", "Loop Line")],
                            "help_text": "Select the style of the title",
                        },
                    ),
                    141: ("wagtail.blocks.StructBlock", [[("title", 139), ("style", 140)]], {"group": "Text"}),
                    142: ("wagtail.blocks.StructBlock", [[("title", 90), ("text", 102)]], {}),
                    143: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 1),
                                ("podcast", 113),
                                ("image", 114),
                                ("newsletter_signup", 115),
                                ("video", 120),
                                ("list", 121),
                                ("spacer", 122),
                                ("quote", 123),
                                ("text_social", 142),
                                ("link_button", 124),
                                ("fru_element", 125),
                                ("project_block", 128),
                            ]
                        ],
                        {"label": "Left Column", "required": False},
                    ),
                    144: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 1),
                                ("podcast", 113),
                                ("image", 114),
                                ("newsletter_signup", 115),
                                ("video", 120),
                                ("list", 121),
                                ("spacer", 122),
                                ("quote", 123),
                                ("text_social", 142),
                                ("link_button", 124),
                                ("fru_element", 125),
                                ("project_block", 128),
                            ]
                        ],
                        {"label": "Right Column", "required": False},
                    ),
                    145: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 111),
                                ("vertical_alignment", 112),
                                ("left_column", 143),
                                ("right_column", 144),
                            ]
                        ],
                        {"group": "Layout"},
                    ),
                    146: (
                        "wagtail.blocks.StructBlock",
                        [[("video_url", 116), ("caption", 117), ("caption_url", 119)]],
                        {"group": "Media & Embeds"},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="experthubpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("accordion_block", 5),
                    ("call_to_action", 19),
                    ("divider", 20),
                    ("featured_card_block", 27),
                    ("flywheel_banner", 30),
                    ("fru_element_block", 33),
                    ("icon_info_grid", 43),
                    ("iframe_block", 48),
                    ("image", 52),
                    ("image_grid", 62),
                    ("impact_numbers", 68),
                    ("link_button_block", 69),
                    ("list_block", 73),
                    ("newsletter_signup", 75),
                    ("newsletter_unsubscribe", 77),
                    ("pillar_card_set", 82),
                    ("podcast_block", 85),
                    ("portrait_card_set_block", 91),
                    ("quote", 94),
                    ("rich_text", 95),
                    ("spacer_block", 97),
                    ("spotlight_card_set_block", 102),
                    ("tabbed_content", 113),
                    ("three_column_container_block", 135),
                    ("timely_activations_cards", 141),
                    ("title_block", 144),
                    ("two_column_container_block", 148),
                    ("video_block", 149),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Heading for the Accordion Item", "required": True},
                    ),
                    1: ("foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock", (), {}),
                    2: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 1)]],
                        {"required": False, "use_json_field": True},
                    ),
                    3: ("wagtail.blocks.StructBlock", [[("title", 0), ("content", 2)]], {}),
                    4: ("wagtail.blocks.ListBlock", (3,), {"min_num": 1}),
                    5: ("wagtail.blocks.StructBlock", [[("accordion_items", 4)]], {"group": "Text"}),
                    6: ("wagtail.blocks.CharBlock", (), {"max_length": 100}),
                    7: ("wagtail.blocks.TextBlock", (), {"max_length": 250, "required": False}),
                    8: ("wagtail.blocks.CharBlock", (), {}),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("external_url", "External URL"),
                                ("relative_url", "Relative URL"),
                                ("email", "Email"),
                                ("anchor", "Anchor"),
                                ("file", "File"),
                                ("phone", "Phone"),
                            ],
                            "label": "Link to",
                        },
                    ),
                    10: ("wagtail.blocks.PageChooserBlock", (), {"label": "Page", "required": False}),
                    11: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Enter a full URL including http:// or https://",
                            "label": "External URL",
                            "max_length": 300,
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'A path relative to this domain. For example, "/foo/bar" or "?foo=bar".',
                            "label": "Relative URL",
                            "max_length": 300,
                            "required": False,
                            "validators": [foundation_cms.legacy_apps.wagtailpages.validators.RelativeURLValidator()],
                        },
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'An id attribute of an element on the current page. For example, "#section-1"',
                            "label": "#",
                            "max_length": 300,
                            "required": False,
                            "validators": [foundation_cms.validators.AnchorLinkValidator()],
                        },
                    ),
                    14: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    15: ("wagtail.documents.blocks.DocumentChooserBlock", (), {"label": "File", "required": False}),
                    16: ("wagtail.blocks.CharBlock", (), {"label": "Phone", "max_length": 30, "required": False}),
                    17: ("wagtail.blocks.BooleanBlock", (), {"label": "Open in new window", "required": False}),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 8),
                                ("link_to", 9),
                                ("page", 10),
                                ("external_url", 11),
                                ("relative_url", 12),
                                ("anchor", 13),
                                ("email", 14),
                                ("file", 15),
                                ("phone", 16),
                                ("new_window", 17),
                            ]
                        ],
                        {},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 6), ("body", 7), ("button", 18)]],
                        {"group": "Engagement & Buttons"},
                    ),
                    20: ("wagtail.blocks.StructBlock", [[]], {"group": "Layout"}),
                    21: ("wagtail.blocks.CharBlock", (), {"label": "Heading", "max_length": 50, "required": True}),
                    22: (
                        "foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock",
                        (),
                        {"features": ["bold", "italic"], "label": "Description", "max_length": 500, "required": True},
                    ),
                    23: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Image for the card", "label": "Image"},
                    ),
                    24: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("btn-primary", "Primary"), ("btn-secondary", "Secondary")]},
                    ),
                    25: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("link-button-block--left", "Left"), ("link-button-block--center", "Center")]},
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 8),
                                ("link_to", 9),
                                ("page", 10),
                                ("external_url", 11),
                                ("relative_url", 12),
                                ("anchor", 13),
                                ("email", 14),
                                ("file", 15),
                                ("phone", 16),
                                ("new_window", 17),
                                ("style", 24),
                                ("alignment", 25),
                            ]
                        ],
                        {"help_text": "Link button for the card.", "label": "Button", "required": False},
                    ),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 21), ("description", 22), ("image", 23), ("button", 26)]],
                        {"group": "Card Collections"},
                    ),
                    28: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("imagine", "Imagine"), ("co-create", "Co-create"), ("mobilize", "Mobilize")],
                            "help_text": "Select the mission that determines the banner artwork and colors.",
                        },
                    ),
                    29: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Imagine",
                            "help_text": "Defaults to the mission name, but can be customized and translated.",
                            "max_length": 50,
                        },
                    ),
                    30: ("wagtail.blocks.StructBlock", [[("mission", 28), ("heading", 29)]], {"group": "Banners"}),
                    31: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("donation-form", "Donation Form"),
                                ("donor-map", "Donor Map"),
                                ("top-locations", "Top Locations"),
                                ("donation-levels", "Donation Levels"),
                                ("donate-button", "Donate Button"),
                            ],
                            "help_text": "Select the type of Fundraise Up element.",
                        },
                    ),
                    32: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Copy the HTML code generated by the desired Fundraise Up element and paste it here.",
                            "required": True,
                        },
                    ),
                    33: (
                        "wagtail.blocks.StructBlock",
                        [[("fru_element_type", 31), ("fru_element_embed_code", 32)]],
                        {"group": "Engagement & Buttons"},
                    ),
                    34: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Section heading for this grid", "max_length": 100, "required": True},
                    ),
                    35: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("orange", "Orange"), ("black", "Black")],
                            "help_text": "Color applied to all icons in this grid",
                        },
                    ),
                    36: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("1", "1 column"), ("2", "2 columns"), ("3", "3 columns")],
                            "help_text": "Number of columns on desktop (automatically stacks on mobile)",
                            "label": "Number of columns for this grid",
                        },
                    ),
                    37: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("compact", "Compact (icons + titles only)"),
                                ("detailed", "Detailed (icons + titles + descriptions)"),
                            ],
                            "help_text": "Choose content density. Compact hides descriptions, Detailed shows them.",
                            "label": "Layout style",
                        },
                    ),
                    38: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("chat", "Chat icon"),
                                ("eye-open", "Eye Open icon"),
                                ("gear", "Gear icon"),
                                ("globe", "Globe icon"),
                                ("megaphone", "Megaphone icon"),
                                ("star", "Star icon"),
                            ],
                            "help_text": "Select an icon for this item",
                        },
                    ),
                    39: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title for this item", "max_length": 100, "required": True},
                    ),
                    40: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional description (max 126 characters)",
                            "max_length": 126,
                            "required": False,
                        },
                    ),
                    41: ("wagtail.blocks.StructBlock", [[("icon", 38), ("title", 39), ("description", 40)]], {}),
                    42: ("wagtail.blocks.ListBlock", (41,), {"help_text": "Add icon info items", "min_num": 1}),
                    43: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 34), ("icon_color", 35), ("columns", 36), ("layout_style", 37), ("items", 42)]],
                        {"group": "Card Collections"},
                    ),
                    44: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Please note that only URLs from allow-listed domains will work."},
                    ),
                    45: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Optional integer pixel value for custom iFrame height", "required": False},
                    ),
                    46: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("normal", "Normal"), ("full_width", "Full Width")]},
                    ),
                    47: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": 'Checking this will add "scrolling=no" to the iframe. Use this if your iframe is rendering an unnecessary scroll bar or whitespace below it.',
                            "required": False,
                        },
                    ),
                    48: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 44), ("height", 45), ("iframe_width", 46), ("disable_scroll", 47)]],
                        {"group": "Media & Embeds"},
                    ),
                    49: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title/caption for this image", "required": False},
                    ),
                    50: ("wagtail.images.blocks.ImageBlock", [], {}),
                    51: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("portrait", "Portrait"), ("landscape", "Landscape"), ("square", "Square")],
                            "help_text": "Select the orientation of this image",
                        },
                    ),
                    52: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 49), ("image", 50), ("orientation", 51)]],
                        {"group": "Media & Embeds"},
                    ),
                    53: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional heading for this section", "max_length": 100, "required": False},
                    ),
                    54: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("portrait", "Portrait (2:3)"),
                                ("landscape", "Landscape (3:2)"),
                                ("square", "Square (1:1)"),
                            ],
                            "help_text": "Orientation for all images in this section",
                            "label": "Image grid section orientation",
                        },
                    ),
                    55: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("4", "4 per row"), ("5", "5 per row"), ("6", "6 per row")],
                            "label": "Items per section row",
                        },
                    ),
                    56: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["h5", "h6", "large", "bold", "italic"],
                            "help_text": "Optional caption for this image",
                            "required": False,
                        },
                    ),
                    57: (
                        "foundation_cms.blocks.link_block.OptionalLinkBlock",
                        (),
                        {"help_text": "Optional link for both image and caption", "required": False},
                    ),
                    58: ("wagtail.blocks.StructBlock", [[("image", 50), ("caption", 56), ("link", 57)]], {}),
                    59: ("wagtail.blocks.ListBlock", (58,), {"min_num": 1}),
                    60: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 53), ("section_orientation", 54), ("items_per_row", 55), ("items", 59)]],
                        {},
                    ),
                    61: ("wagtail.blocks.ListBlock", (60,), {"label": "Image grid sections", "min_num": 1}),
                    62: ("wagtail.blocks.StructBlock", [[("sections", 61)]], {"group": "Card Collections"}),
                    63: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The full value to animate, including any symbols, commas, decimals, or suffixes (e.g., $5.2M).",
                            "max_length": 5,
                            "required": True,
                        },
                    ),
                    64: ("wagtail.blocks.CharBlock", (), {"help_text": "Heading of the stat", "required": True}),
                    65: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Short description of the stat", "required": False},
                    ),
                    66: (
                        "wagtail.blocks.StructBlock",
                        [[("stat_number", 63), ("stat_heading", 64), ("stat_description", 65)]],
                        {},
                    ),
                    67: (
                        "wagtail.blocks.ListBlock",
                        (66,),
                        {
                            "default": [
                                {"stat_description": "", "stat_heading": "", "stat_number": ""},
                                {"stat_description": "", "stat_heading": "", "stat_number": ""},
                                {"stat_description": "", "stat_heading": "", "stat_number": ""},
                            ],
                            "help_text": "Add exactly 3 stats to appear in the Impact Numbers section",
                            "label": "Impact Stats",
                            "max_num": 3,
                            "min_num": 3,
                        },
                    ),
                    68: ("wagtail.blocks.StructBlock", [[("stats", 67)]], {"group": "Data Display"}),
                    69: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 8),
                                ("link_to", 9),
                                ("page", 10),
                                ("external_url", 11),
                                ("relative_url", 12),
                                ("anchor", 13),
                                ("email", 14),
                                ("file", 15),
                                ("phone", 16),
                                ("new_window", 17),
                                ("style", 24),
                                ("alignment", 25),
                            ]
                        ],
                        {"group": "Engagement & Buttons"},
                    ),
                    70: ("wagtail.blocks.CharBlock", (), {"help_text": "Heading displayed above the list"}),
                    71: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Description displayed above the list", "required": False},
                    ),
                    72: ("wagtail.blocks.ListBlock", (18,), {"max_num": 4, "min_num": 1}),
                    73: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 70), ("description", 71), ("items", 72)]],
                        {"group": "Data Display"},
                    ),
                    74: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("snippets.NewsletterSignup",),
                        {"max_num": 1},
                    ),
                    75: (
                        "wagtail.blocks.StructBlock",
                        [[("newsletter_signup", 74)]],
                        {"group": "Engagement & Buttons"},
                    ),
                    76: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("snippets.NewsletterUnsubscribe",),
                        {"max_num": 1},
                    ),
                    77: (
                        "wagtail.blocks.StructBlock",
                        [[("newsletter_unsubscribe", 76)]],
                        {"group": "Engagement & Buttons"},
                    ),
                    78: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Appears as the main heading.", "label": "Headline", "required": False},
                    ),
                    79: (
                        "foundation_cms.blocks.link_block.OptionalLinkBlock",
                        (),
                        {
                            "help_text": "Optional link for the card.",
                            "label": "Call to Action Link",
                            "required": False,
                        },
                    ),
                    80: ("wagtail.blocks.StructBlock", [[("headline", 78), ("cta_link", 79)]], {}),
                    81: (
                        "wagtail.blocks.ListBlock",
                        (80,),
                        {
                            "default": [
                                {"cta_link": [], "headline": ""},
                                {"cta_link": [], "headline": ""},
                                {"cta_link": [], "headline": ""},
                            ],
                            "help_text": "3 cards required.",
                            "label": "Pillar Cards",
                            "max_num": 3,
                            "min_num": 3,
                        },
                    ),
                    82: ("wagtail.blocks.StructBlock", [[("cards", 81)]], {"group": "Card Collections"}),
                    83: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Title of the podcast. <strong>Note:</strong> Does not render on "NothingPersonal" pages.'
                        },
                    ),
                    84: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": 'Optional short description of the podcast. <strong>Note:</strong> Does not render on "NothingPersonal" pages.',
                            "required": False,
                        },
                    ),
                    85: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 83), ("description", 84), ("simplecast_embed_code", 8)]],
                        {"group": "Media & Embeds"},
                    ),
                    86: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Appears above the headline.", "label": "Label", "required": False},
                    ),
                    87: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Optional Image for the card", "label": "Image"},
                    ),
                    88: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 8),
                                ("link_to", 9),
                                ("page", 10),
                                ("external_url", 11),
                                ("relative_url", 12),
                                ("anchor", 13),
                                ("email", 14),
                                ("file", 15),
                                ("phone", 16),
                                ("new_window", 17),
                            ]
                        ],
                        {"help_text": "Link for the card.", "label": "Call to Action Link", "required": True},
                    ),
                    89: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 86), ("headline", 78), ("image", 87), ("cta_link", 88)]],
                        {},
                    ),
                    90: (
                        "wagtail.blocks.ListBlock",
                        (89,),
                        {
                            "help_text": "Minimum of 3 cards required. More than 3 will turn element into a carousel.",
                            "label": "Portrait Cards",
                            "min_num": 3,
                        },
                    ),
                    91: ("wagtail.blocks.StructBlock", [[("cards", 90)]], {"group": "Card Collections"}),
                    92: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    93: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    94: ("wagtail.blocks.StructBlock", [[("quote", 92), ("attribution", 93)]], {"group": "Text"}),
                    95: ("foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock", (), {"group": "Text"}),
                    96: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("small", "Small"),
                                ("medium", "Medium"),
                                ("large", "Large"),
                                ("xlarge", "Extra Large"),
                            ],
                            "help_text": "Select the size of the spacer",
                        },
                    ),
                    97: ("wagtail.blocks.StructBlock", [[("size", 96)]], {"group": "Layout"}),
                    98: ("wagtail.blocks.CharBlock", (), {"label": "Name", "max_length": 50, "required": True}),
                    99: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Image should follow a 1:1 aspect ratio.", "label": "Image"},
                    ),
                    100: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 92), ("name", 98), ("description", 22), ("image", 99)]],
                        {},
                    ),
                    101: (
                        "wagtail.blocks.ListBlock",
                        (100,),
                        {"help_text": "3 cards required.", "label": "Spotlight Cards", "max_num": 3, "min_num": 3},
                    ),
                    102: ("wagtail.blocks.StructBlock", [[("cards", 101)]], {"group": "Card Collections"}),
                    103: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title shown on the tab button", "required": True},
                    ),
                    104: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Subtitle shown under the title on the tab", "required": False},
                    ),
                    105: ("foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock", (), {"required": False}),
                    106: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 49), ("image", 50), ("orientation", 51)]],
                        {"required": False},
                    ),
                    107: ("foundation_cms.blocks.link_block.OptionalLinkBlock", (), {"required": False}),
                    108: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 93), ("subtitle", 93), ("text", 105), ("image", 106), ("link", 107)]],
                        {},
                    ),
                    109: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 8), ("image", 50), ("subtitle", 8), ("link", 107)]],
                        {},
                    ),
                    110: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 1), ("text_image", 108), ("tab_card_set", 109)]],
                        {"help_text": "Add one or more content blocks to the tab.", "min_num": 1, "required": True},
                    ),
                    111: ("wagtail.blocks.StructBlock", [[("title", 103), ("subtitle", 104), ("content", 110)]], {}),
                    112: ("wagtail.blocks.ListBlock", (111,), {"label": "Tabs", "max_num": 8, "min_num": 1}),
                    113: ("wagtail.blocks.StructBlock", [[("tabs", 112)]], {"group": "Card Collections"}),
                    114: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("white", "White"),
                                ("neutral-100", "Grey 100"),
                                ("neutral-200", "Grey 200"),
                                ("neutral-300", "Grey 300"),
                                ("blue-100", "Blue 100"),
                                ("blue-200", "Blue 200"),
                                ("blue-300", "Blue 300"),
                                ("green-100", "Green 100"),
                                ("green-200", "Green 200"),
                                ("green-300", "Green 300"),
                                ("orange-100", "Orange 100"),
                                ("orange-200", "Orange 200"),
                                ("orange-300", "Orange 300"),
                                ("yellow-100", "Yellow 100"),
                                ("yellow-200", "Yellow 200"),
                                ("yellow-300", "Yellow 300"),
                            ]
                        },
                    ),
                    115: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("top", "Top"), ("middle", "Middle"), ("bottom", "Bottom")],
                            "help_text": "Vertical alignment of the columns content",
                        },
                    ),
                    116: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 83), ("description", 84), ("simplecast_embed_code", 8)]],
                        {},
                    ),
                    117: ("wagtail.blocks.StructBlock", [[("title", 49), ("image", 50), ("orientation", 51)]], {}),
                    118: ("wagtail.blocks.StructBlock", [[("newsletter_signup", 74)]], {}),
                    119: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Log into Vimeo, select your desired video, and click 'Copy Link'",
                            "label": "Vimeo Video URL",
                            "required": True,
                        },
                    ),
                    120: ("wagtail.blocks.CharBlock", (), {"help_text": "Optional Caption Text", "required": False}),
                    121: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_to", 9),
                                ("page", 10),
                                ("external_url", 11),
                                ("relative_url", 12),
                                ("anchor", 13),
                                ("email", 14),
                                ("file", 15),
                                ("phone", 16),
                                ("new_window", 17),
                            ]
                        ],
                        {},
                    ),
                    122: (
                        "wagtail.blocks.ListBlock",
                        (121,),
                        {
                            "default": [],
                            "help_text": "Optional URL that this caption should link out to.",
                            "max_num": 1,
                            "min_num": 0,
                        },
                    ),
                    123: (
                        "wagtail.blocks.StructBlock",
                        [[("video_url", 119), ("caption", 120), ("caption_url", 122)]],
                        {},
                    ),
                    124: ("wagtail.blocks.StructBlock", [[("title", 70), ("description", 71), ("items", 72)]], {}),
                    125: ("wagtail.blocks.StructBlock", [[("size", 96)]], {}),
                    126: ("wagtail.blocks.StructBlock", [[("quote", 92), ("attribution", 93)]], {}),
                    127: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 8),
                                ("link_to", 9),
                                ("page", 10),
                                ("external_url", 11),
                                ("relative_url", 12),
                                ("anchor", 13),
                                ("email", 14),
                                ("file", 15),
                                ("phone", 16),
                                ("new_window", 17),
                                ("style", 24),
                                ("alignment", 25),
                            ]
                        ],
                        {},
                    ),
                    128: (
                        "wagtail.blocks.StructBlock",
                        [[("fru_element_type", 31), ("fru_element_embed_code", 32)]],
                        {},
                    ),
                    129: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Project", "page_type": ["gallery_hub.ProjectPage"], "required": True},
                    ),
                    130: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": True, "label": "Show description", "required": False},
                    ),
                    131: ("wagtail.blocks.StructBlock", [[("project", 129), ("show_description", 130)]], {}),
                    132: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 1),
                                ("podcast", 116),
                                ("image", 117),
                                ("newsletter_signup", 118),
                                ("video", 123),
                                ("list", 124),
                                ("spacer", 125),
                                ("quote", 126),
                                ("link_button", 127),
                                ("fru_element", 128),
                                ("project_block", 131),
                            ]
                        ],
                        {"label": "Left Column", "required": False},
                    ),
                    133: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 1),
                                ("podcast", 116),
                                ("image", 117),
                                ("newsletter_signup", 118),
                                ("video", 123),
                                ("list", 124),
                                ("spacer", 125),
                                ("quote", 126),
                                ("link_button", 127),
                                ("fru_element", 128),
                                ("project_block", 131),
                            ]
                        ],
                        {"label": "Center Column", "required": False},
                    ),
                    134: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 1),
                                ("podcast", 116),
                                ("image", 117),
                                ("newsletter_signup", 118),
                                ("video", 123),
                                ("list", 124),
                                ("spacer", 125),
                                ("quote", 126),
                                ("link_button", 127),
                                ("fru_element", 128),
                                ("project_block", 131),
                            ]
                        ],
                        {"label": "Right Column", "required": False},
                    ),
                    135: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 114),
                                ("vertical_alignment", 115),
                                ("left_column", 132),
                                ("center_column", 133),
                                ("right_column", 134),
                            ]
                        ],
                        {"group": "Layout"},
                    ),
                    136: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional category for the card.", "required": False},
                    ),
                    137: ("wagtail.blocks.CharBlock", (), {"help_text": "Title for the card.", "required": True}),
                    138: (
                        "foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock",
                        (),
                        {"help_text": "Optional description text.", "required": False},
                    ),
                    139: (
                        "wagtail.blocks.StructBlock",
                        [[("category", 136), ("title", 137), ("text", 138), ("image", 50), ("link", 18)]],
                        {},
                    ),
                    140: (
                        "wagtail.blocks.StreamBlock",
                        [[("card", 139)]],
                        {"help_text": "Add between 1 and 3 cards.", "max_num": 3, "min_num": 1},
                    ),
                    141: ("wagtail.blocks.StructBlock", [[("cards", 140)]], {"group": "Card Collections"}),
                    142: ("wagtail.blocks.CharBlock", (), {"help_text": "Title for the block", "required": True}),
                    143: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("shape", "Shape"), ("loop-line", "Loop Line")],
                            "help_text": "Select the style of the title",
                        },
                    ),
                    144: ("wagtail.blocks.StructBlock", [[("title", 142), ("style", 143)]], {"group": "Text"}),
                    145: ("wagtail.blocks.StructBlock", [[("title", 93), ("text", 105)]], {}),
                    146: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 1),
                                ("podcast", 116),
                                ("image", 117),
                                ("newsletter_signup", 118),
                                ("video", 123),
                                ("list", 124),
                                ("spacer", 125),
                                ("quote", 126),
                                ("text_social", 145),
                                ("link_button", 127),
                                ("fru_element", 128),
                                ("project_block", 131),
                            ]
                        ],
                        {"label": "Left Column", "required": False},
                    ),
                    147: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 1),
                                ("podcast", 116),
                                ("image", 117),
                                ("newsletter_signup", 118),
                                ("video", 123),
                                ("list", 124),
                                ("spacer", 125),
                                ("quote", 126),
                                ("text_social", 145),
                                ("link_button", 127),
                                ("fru_element", 128),
                                ("project_block", 131),
                            ]
                        ],
                        {"label": "Right Column", "required": False},
                    ),
                    148: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 114),
                                ("vertical_alignment", 115),
                                ("left_column", 146),
                                ("right_column", 147),
                            ]
                        ],
                        {"group": "Layout"},
                    ),
                    149: (
                        "wagtail.blocks.StructBlock",
                        [[("video_url", 119), ("caption", 120), ("caption_url", 122)]],
                        {"group": "Media & Embeds"},
                    ),
                },
            ),
        ),
    ]
