from factory import Faker, SubFactory, django
import wagtail_factories


class CollectionFactory(wagtail_factories.CollectionFactory):
    '''
    Custom collection factory with random names

    The collection factory in Wagtail Factories uses a static name for all
    collections. This factory generates a random name for each collection.

    '''
    name = Faker('text', max_nb_chars=60)


class DocumentFactory(wagtail_factories.DocumentFactory):
    '''
    Custom document factory with random titles

    The document factory in Wagtail Factories uses a static title for all
    documents. This factory generates a random title for each document.

    Also, this factory adds the documents to collections generated by
    the custom collection factory.

    '''
    collection = SubFactory(CollectionFactory, parent=None)
    title = Faker('text', max_nb_chars=250)
    file = django.FileField(filename='test.pdf')
