# Generated by Django 4.2.27 on 2026-02-20 17:31

from django.db import migrations, models
import django.db.models.deletion
import foundation_cms.legacy_apps.wagtailpages.validators
import uuid
import wagtail.fields
import wagtail.models.preview


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="NavigationMenu",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("translation_key", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("live", models.BooleanField(default=True, editable=False, verbose_name="live")),
                (
                    "has_unpublished_changes",
                    models.BooleanField(default=False, editable=False, verbose_name="has unpublished changes"),
                ),
                (
                    "first_published_at",
                    models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="first published at"),
                ),
                (
                    "last_published_at",
                    models.DateTimeField(editable=False, null=True, verbose_name="last published at"),
                ),
                ("go_live_at", models.DateTimeField(blank=True, null=True, verbose_name="go live date/time")),
                ("expire_at", models.DateTimeField(blank=True, null=True, verbose_name="expiry date/time")),
                ("expired", models.BooleanField(default=False, editable=False, verbose_name="expired")),
                ("title", models.CharField(help_text="For internal identification only", max_length=100)),
                (
                    "dropdowns",
                    wagtail.fields.StreamField(
                        [("dropdown", 8)],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {}),
                            1: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("page", "Page"),
                                        ("external_url", "External URL"),
                                        ("relative_url", "Relative URL"),
                                    ],
                                    "label": "Link to",
                                },
                            ),
                            2: ("wagtail.blocks.PageChooserBlock", (), {"label": "Page", "required": False}),
                            3: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {
                                    "help_text": "Enter a full URL including http:// or https://",
                                    "label": "External URL",
                                    "max_length": 300,
                                    "required": False,
                                },
                            ),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": 'A path relative to this domain. For example, "/foo/bar" or "?foo=bar".',
                                    "label": "Relative URL",
                                    "max_length": 300,
                                    "required": False,
                                    "validators": [
                                        foundation_cms.legacy_apps.wagtailpages.validators.RelativeURLValidator()
                                    ],
                                },
                            ),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("label", 0),
                                        ("link_to", 1),
                                        ("page", 2),
                                        ("external_url", 3),
                                        ("relative_url", 4),
                                    ]
                                ],
                                {
                                    "help_text": "This label is shown in the nav bar and links to the dropdown landing page.",
                                    "label": "Dropdown Link",
                                    "required": True,
                                },
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("label", 0),
                                        ("link_to", 1),
                                        ("page", 2),
                                        ("external_url", 3),
                                        ("relative_url", 4),
                                    ]
                                ],
                                {},
                            ),
                            7: (
                                "wagtail.blocks.ListBlock",
                                (6,),
                                {
                                    "help_text": "Up to 5 links shown in the dropdown panel.",
                                    "label": "Dropdown Items",
                                    "max_num": 5,
                                },
                            ),
                            8: ("wagtail.blocks.StructBlock", [[("header", 5), ("items", 7)]], {"label": "Dropdown"}),
                        },
                        help_text="Add up to 5 dropdown menus",
                    ),
                ),
                (
                    "latest_revision",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.revision",
                        verbose_name="latest revision",
                    ),
                ),
                (
                    "live_revision",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.revision",
                        verbose_name="live revision",
                    ),
                ),
                (
                    "locale",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="wagtailcore.locale",
                        verbose_name="locale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Navigation Menu",
                "verbose_name_plural": "Navigation Menus",
                "abstract": False,
                "unique_together": {("translation_key", "locale")},
            },
            bases=(wagtail.models.preview.PreviewableMixin, models.Model),
        ),
        migrations.CreateModel(
            name="SiteNavigationMenu",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "active_navigation_menu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="site_navigation_menu",
                        to="navigation.navigationmenu",
                        verbose_name="Active Navigation Menu",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False, on_delete=django.db.models.deletion.CASCADE, to="wagtailcore.site"
                    ),
                ),
            ],
            options={
                "verbose_name": "Navigation Menu",
                "verbose_name_plural": "Navigation Menus",
            },
        ),
    ]
