# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-15 19:50
from __future__ import unicode_literals

from django.db import migrations
import networkapi.minisites.models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('minisites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modularpage',
            name='body',
            field=wagtail.core.fields.StreamField((('heading', wagtail.core.blocks.CharBlock()), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image_text', wagtail.core.blocks.StructBlock((('text', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('ordering', wagtail.core.blocks.ChoiceBlock(choices=[('left', 'Image on the left'), ('right', 'Image on the right')]))))), ('image', wagtail.images.blocks.ImageChooserBlock()), ('bio', wagtail.core.blocks.StructBlock((('text', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('ordering', wagtail.core.blocks.ChoiceBlock(choices=[('left', 'Image on the left'), ('right', 'Image on the right')])), ('name', wagtail.core.blocks.CharBlock())))), ('video', networkapi.minisites.models.VideoBlock()), ('linkbutton', wagtail.core.blocks.StructBlock((('label', wagtail.core.blocks.CharBlock()), ('URL', wagtail.core.blocks.CharBlock())))), ('spacer', wagtail.core.blocks.StructBlock((('rem', wagtail.core.blocks.IntegerBlock()),))))),
        ),
    ]
