# Generated by Django 4.2.20 on 2025-06-10 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterSignup",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "cta_text",
                    models.CharField(default="Stay updated with our latest news and updates.", max_length=255),
                ),
                (
                    "button_text",
                    models.CharField(
                        default="Sign Up", help_text="Text to display on the signup button.", max_length=50
                    ),
                ),
                (
                    "newsletter",
                    models.CharField(
                        default="mozilla-foundation",
                        help_text="The (pre-existing) newsletter to sign up for",
                        max_length=100,
                    ),
                ),
                (
                    "layout",
                    models.CharField(
                        choices=[("expanded", "Expanded"), ("expand_on_focus", "Expand On Focus")],
                        default="expanded",
                        help_text="Controls how the form is displayed",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FooterNewsletterSignup",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "newsletter_signup",
                    models.ForeignKey(
                        blank=True,
                        help_text="Select a newsletter signup to appear in the footer.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="snippets.newslettersignup",
                        verbose_name="Footer Newsletter Signup",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False, on_delete=django.db.models.deletion.CASCADE, to="wagtailcore.site"
                    ),
                ),
            ],
            options={
                "verbose_name": "Footer Newsletter Signup (New)",
                "verbose_name_plural": "Footer Newsletter Signups (New)",
            },
        ),
    ]
