# Generated by Django 4.2.20 on 2025-09-03 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0002_donatebanner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="newslettersignup",
            old_name="cta_text",
            new_name="cta_header",
        ),
        migrations.AddField(
            model_name="newslettersignup",
            name="cta_description",
            field=models.CharField(
                blank=True, help_text="Additional description text below the header.", max_length=255
            ),
        ),
    ]
