# Generated by Django 4.2.20 on 2025-10-09 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0004_donatebanner_banner_style"),
    ]

    operations = [
        migrations.AddField(
            model_name="donatebanner",
            name="fru_stat_counter_caption",
            field=models.CharField(
                blank=True, help_text="Text used to describe the FRU Stat Counter Number (e.g. 'donors so far')."
            ),
        ),
        migrations.AddField(
            model_name="donatebanner",
            name="fru_stat_counter_embed_code",
            field=models.CharField(
                blank=True,
                help_text="Copy the HTML code generated by the desired FRU Stat Counter element and paste it here.",
            ),
        ),
        migrations.AddField(
            model_name="donatebanner",
            name="fru_thermometer_embed_code",
            field=models.CharField(
                blank=True,
                help_text="Copy the HTML code generated by the desired FRU Thermometer element and paste it here.",
            ),
        ),
    ]
