# Generated by Django 4.2.20 on 2025-10-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0005_make_newslettersignup_translatable"),
    ]

    operations = [
        migrations.AddField(
            model_name="donatebanner",
            name="banner_style",
            field=models.CharField(
                choices=[("legacy", "Legacy"), ("pushdown", "Pushdown")],
                default="legacy",
                help_text="Style of the banner to display",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="donatebanner",
            name="fru_stat_counter_caption",
            field=models.CharField(
                blank=True, help_text="Text used to describe the FRU Stat Counter Number (e.g. 'donors so far')."
            ),
        ),
        migrations.AddField(
            model_name="donatebanner",
            name="fru_stat_counter_embed_code",
            field=models.CharField(
                blank=True,
                help_text="Copy the HTML code generated by the desired FRU Stat Counter element and paste it here.",
            ),
        ),
        migrations.AddField(
            model_name="donatebanner",
            name="fru_thermometer_embed_code",
            field=models.CharField(
                blank=True,
                help_text="Copy the HTML code generated by the desired FRU Thermometer element and paste it here.",
            ),
        ),
        migrations.AlterField(
            model_name="donatebanner",
            name="background_color",
            field=models.CharField(
                blank=True,
                choices=[("red", "Red"), ("blue", "Blue"), ("green", "Green"), ("white", "White"), ("black", "Black")],
                default="blue",
                help_text="Background color for the banner",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="donatebanner",
            name="button_color",
            field=models.CharField(
                choices=[("blue", "Blue"), ("green", "Green")],
                default="blue",
                help_text="Button color for the banner",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="donatebanner",
            name="text_color",
            field=models.CharField(
                choices=[("white", "White"), ("black", "Black")],
                default="white",
                help_text="Text color for the banner",
                max_length=20,
            ),
        ),
    ]
