# Generated by Django 4.2.27 on 2026-01-22 17:30

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("snippets", "0008_remove_donatebanner_background_color_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PdfDownloadSignup",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("translation_key", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("name", models.CharField(default="", help_text="The name of this signup form.", max_length=100)),
                (
                    "cta_header",
                    models.CharField(default="Stay updated with our latest news and updates.", max_length=255),
                ),
                (
                    "cta_description",
                    models.CharField(
                        blank=True, help_text="Additional description text below the header.", max_length=255
                    ),
                ),
                (
                    "button_text",
                    models.CharField(default="Sign Up", help_text="Text to display on the button.", max_length=50),
                ),
                (
                    "layout",
                    models.CharField(
                        choices=[("expanded", "Expanded"), ("expand_on_focus", "Expand On Focus")],
                        default="expanded",
                        help_text="Controls how the form is displayed.",
                        max_length=20,
                    ),
                ),
                (
                    "smart_email_id",
                    models.CharField(
                        default="2d306f6b-1998-49dd-8ebe-fd4b85cf73f6",
                        help_text="The (pre-existing) CaMo template ID for the PDF download signup.",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name": "PDF Download Signup",
                "verbose_name_plural": "PDF Download Signups",
            },
        ),
        migrations.AlterModelOptions(
            name="newslettersignup",
            options={"verbose_name": "Newsletter Signup", "verbose_name_plural": "Newsletter Signups"},
        ),
        migrations.AlterUniqueTogether(
            name="newslettersignup",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="newslettersignup",
            name="button_text",
            field=models.CharField(default="Sign Up", help_text="Text to display on the button.", max_length=50),
        ),
        migrations.AlterField(
            model_name="newslettersignup",
            name="name",
            field=models.CharField(default="", help_text="The name of this signup form.", max_length=100),
        ),
        migrations.AddConstraint(
            model_name="newslettersignup",
            constraint=models.UniqueConstraint(
                fields=("translation_key", "locale"), name="unique_translation_key_locale_snippets_newslettersignup"
            ),
        ),
        migrations.AddField(
            model_name="pdfdownloadsignup",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AddConstraint(
            model_name="pdfdownloadsignup",
            constraint=models.UniqueConstraint(
                fields=("translation_key", "locale"), name="unique_translation_key_locale_snippets_pdfdownloadsignup"
            ),
        ),
    ]
