# Generated by Django 4.2.20 on 2025-05-07 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
        ("donate_banner", "0007_alter_donatebanner_locale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donatebanner",
            name="background_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="images.foundationcustomimage",
            ),
        ),
        migrations.AlterField(
            model_name="donatebanner",
            name="foreground_image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="+", to="images.foundationcustomimage"
            ),
        ),
    ]
