# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-22 21:56
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0002_auto_20180220_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modularpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('bio', wagtail.wagtailcore.blocks.StructBlock((('name', wagtail.wagtailcore.blocks.CharBlock()), ('bio', wagtail.wagtailcore.blocks.TextBlock()), ('picture', wagtail.wagtailimages.blocks.ImageChooserBlock())))), ('video', wagtail.wagtailembeds.blocks.EmbedBlock()))),
        ),
    ]
