# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-22 22:52
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0003_auto_20180222_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='modularpage',
            name='header',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='modularpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.CharBlock()), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image+text', wagtail.wagtailcore.blocks.StructBlock((('text', wagtail.wagtailcore.blocks.CharBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock())), icon='doc-full')), ('text+image', wagtail.wagtailcore.blocks.StructBlock((('picture', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('text', wagtail.wagtailcore.blocks.CharBlock())), icon='doc-full')), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('bio', wagtail.wagtailcore.blocks.StructBlock((('name', wagtail.wagtailcore.blocks.CharBlock()), ('bio', wagtail.wagtailcore.blocks.TextBlock()), ('picture', wagtail.wagtailimages.blocks.ImageChooserBlock())))), ('video', wagtail.wagtailembeds.blocks.EmbedBlock()), ('linkbutton', wagtail.wagtailcore.blocks.StructBlock((('label', wagtail.wagtailcore.blocks.CharBlock()), ('URL', wagtail.wagtailcore.blocks.URLBlock())))))),
        ),
    ]
