# Generated by Django 4.2.20 on 2025-09-10 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
        ("base", "0004_delete_pagetag_delete_taggedpage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="author_image",
                to="images.foundationcustomimage",
            ),
        ),
    ]
