# Generated by Django 4.2.27 on 2026-01-14 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("donate", "0029_alter_donatehelppage_search_image_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="donatehelppage",
            options={"verbose_name": "Donate Help Page (Legacy)", "verbose_name_plural": "Donate Help Pages (Legacy)"},
        ),
        migrations.AlterModelOptions(
            name="donatelandingpage",
            options={
                "verbose_name": "Donate Landing Page (Legacy)",
                "verbose_name_plural": "Donate Landing Pages (Legacy)",
            },
        ),
        migrations.AlterModelOptions(
            name="helppagenotice",
            options={
                "verbose_name": "Donate Help Page Notice (Legacy)",
                "verbose_name_plural": "Donate Help Page Notices (Legacy)",
            },
        ),
    ]
