# Generated by Django 3.2.16 on 2022-12-14 00:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailpages", "0070_adds_url_field_for_listing_card"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buyersguidepage",
            name="dark_theme",
        ),
        migrations.RemoveField(
            model_name="buyersguidepage",
            name="header",
        ),
        migrations.RemoveField(
            model_name="buyersguidepage",
            name="hero_image",
        ),
    ]
