# Generated by Django 3.2.23 on 2024-01-11 17:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailpages", "0117_alter_buyersguidepageherosupportingpagerelation_supporting_page"),
        ("wagtailpages", "0117_merge_20240110_1121"),
    ]

    operations = []
