# Generated by Django 4.2.25 on 2025-11-14 15:41

import uuid

import django.db.models.deletion
import modelcluster.fields
import wagtail.blocks.migrations.migrate_operation
import wagtail.fields
from django.db import migrations, models

class Migration(migrations.Migration):

    replaces = [
        ("wagtailpages", "0130_fix_urls_on_translation_context_model"),
        ("wagtailpages", "0131_set_relative_url_on_linkblock"),
        ("wagtailpages", "0132_make_link_to_required_in_link_block"),
        ("wagtailpages", "0133_appinstallpage"),
        ("wagtailpages", "0134_update_rccauthorrelation_meta"),
        ("wagtailpages", "0135_featuredcampaignpagerelation"),
        ("wagtailpages", "0136_alter_donationmodal_body_richtext"),
        ("wagtailpages", "0137_blogsignup_privacy_notice_cta_privacy_notice"),
        ("wagtailpages", "0138_remove_modularpage_zen_nav_and_more"),
        ("wagtailpages", "0139_update_annotatedimageblock_with_linkblock"),
        ("wagtailpages", "0140_update_iframeblock_with_linkblock"),
        ("wagtailpages", "0141_update_imagetextblock_with_linkblock"),
        ("wagtailpages", "0142_alter_blogindexpage_callout_box"),
        ("wagtailpages", "0143_delete_youtuberegretsreporterextensionpage"),
        ("wagtailpages", "0144_alter_appinstallpage_hero_heading_and_more"),
        ("wagtailpages", "0145_update_videoblock_with_linkblock"),
        ("wagtailpages", "0146_update_imageteaserblock_with_linkblock"),
        ("wagtailpages", "0147_update_grouplistingblock_with_linkblock"),
        ("wagtailpages", "0148_update_imagegridblock_with_linkblock"),
        ("wagtailpages", "0149_update_listingblock_with_linkblock"),
        ("wagtailpages", "0150_update_textonlyteaserblock_with_linkblock"),
        ("wagtailpages", "0151_update_dearinternetpage_cta_with_linkblock"),
        ("wagtailpages", "0152_format_linkblock_empty_values"),
        ("wagtailpages", "0153_update_baselinkblock_relative_link_validation"),
        ("wagtailpages", "0154_update_cardgridblock_with_linkblock"),
        ("wagtailpages", "0155_homepagetakeactioncards_cta"),
        ("wagtailpages", "0156_homepage_show_hero_button_and_more"),
        ("wagtailpages", "0157_homepage_show_cause_statement"),
        ("wagtailpages", "0158_alter_blogpage_body_and_more"),
        ("wagtailpages", "0159_update_bgcta_with_linkblock"),
        ("wagtailpages", "0160_homepageideasposts_and_more"),
        ("wagtailpages", "0161_alter_homepage_ideas_headline_and_more"),
        ("wagtailpages", "0162_alter_articlepage_body"),
        ("wagtailpages", "0163_remove_focusarea_page"),
        ("wagtailpages", "0164_homepage_hero_intro_body_homepage_hero_intro_heading_and_more"),
        ("wagtailpages", "0165_alter_articlepage_body_alter_blogpage_body_and_more"),
        ("wagtailpages", "0166_homepagehighlights_replace_homepagenewsyoucanuse"),
        ("wagtailpages", "0167_alter_blogauthors_locale_alter_blogpagetopic_locale_and_more"),
        ("wagtailpages", "0168_alter_blogpage_body_and_more"),
        ("wagtailpages", "0169_alter_blogpage_body_and_more"),
    ]

    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("wagtailpages", "0129_allow_spacer_on_articlepage_body"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
    ]

    operations = [
        migrations.RunPython(
            code=migrations.RunPython.noop,
            reverse_code=migrations.RunPython.noop,
            elidable=True,
        ),
        migrations.AlterField(
            model_name="articlepage",
            name="body",
            field=wagtail.fields.StreamField([]),
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="body",
            field=wagtail.fields.StreamField([]),
        ),
        migrations.AlterField(
            model_name="rcclandingpage",
            name="aside_cta",
            field=wagtail.fields.StreamField([], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="researchlandingpage",
            name="aside_cta",
            field=wagtail.fields.StreamField([], blank=True, null=True),
        ),
        migrations.CreateModel(
            name="AppInstallPage",
            fields=[
                (
                    "campaignpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailpages.campaignpage",
                    ),
                ),
                ("hero_heading", models.CharField(help_text="Hero story headline", max_length=80)),
                ("hero_subheading", models.CharField(blank=True, help_text="Hero story subheadline", max_length=80)),
                (
                    "hero_video",
                    models.URLField(
                        blank=True,
                        help_text="To find embed link: go to your YouTube video and click “Share,” then “Embed,” and then copy and paste the provided URL only. EX: https://www.youtube.com/embed/3FIVXBawyQ",
                        null=True,
                    ),
                ),
                ("download_buttons", wagtail.fields.StreamField([], blank=True)),
                (
                    "hero_background",
                    models.ForeignKey(
                        help_text="Background image for the hero section",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailpages.campaignpage",),
        ),
        migrations.AlterModelOptions(
            name="rccauthorrelation",
            options={"ordering": ["sort_order"]},
        ),
        migrations.CreateModel(
            name="FeaturedCampaignPageRelation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("translation_key", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                (
                    "featured_page",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="wagtailcore.page"
                    ),
                ),
                (
                    "index_page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="featured_campaign_pages",
                        to="wagtailpages.campaignindexpage",
                    ),
                ),
                (
                    "locale",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="wagtailcore.locale",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
                "unique_together": {("translation_key", "locale")},
            },
        ),
        migrations.AlterField(
            model_name="donationmodal",
            name="body",
            field=wagtail.fields.RichTextField(
                default="Mozilla is a nonprofit organization fighting for a healthy internet, where privacy is included by design and you have more control over your personal information. We depend on contributions from people like you to carry out this work. Can you donate today?",
                help_text="Donation text",
            ),
        ),
        migrations.AddField(
            model_name="blogsignup",
            name="privacy_notice",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="This optional privacy notice field will overwrite the default privacy notice text. If this field is left blank, the default privacy notice text is used.",
            ),
        ),
        migrations.AddField(
            model_name="cta",
            name="privacy_notice",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="This optional privacy notice field will overwrite the default privacy notice text. If this field is left blank, the default privacy notice text is used.",
            ),
        ),
        migrations.RemoveField(
            model_name="modularpage",
            name="zen_nav",
        ),
        migrations.RemoveField(
            model_name="primarypage",
            name="zen_nav",
        ),
        migrations.AlterField(
            model_name="blogindexpage",
            name="callout_box",
            field=wagtail.fields.StreamField(
                [], blank=True, help_text="Callout box that appears after the featured posts section"
            ),
        ),
        migrations.DeleteModel(
            name="YoutubeRegretsReporterExtensionPage",
        ),
        migrations.AlterField(
            model_name="appinstallpage",
            name="hero_heading",
            field=models.CharField(help_text="Hero story headline", max_length=250),
        ),
        migrations.AlterField(
            model_name="appinstallpage",
            name="hero_subheading",
            field=models.CharField(blank=True, help_text="Hero story subheadline", max_length=250),
        ),
        migrations.AddField(
            model_name="dearinternetpage",
            name="cta_button",
            field=wagtail.fields.StreamField([], blank=True),
        ),
        migrations.RemoveField(
            model_name="dearinternetpage",
            name="cta_button_link",
        ),
        migrations.RemoveField(
            model_name="dearinternetpage",
            name="cta_button_text",
        ),
        migrations.AlterField(
            model_name="appinstallpage",
            name="download_buttons",
            field=wagtail.fields.StreamField([], blank=True),
        ),
        migrations.AlterField(
            model_name="dearinternetpage",
            name="cta_button",
            field=wagtail.fields.StreamField([], blank=True),
        ),
        migrations.AlterField(
            model_name="rcclandingpage",
            name="aside_cta",
            field=wagtail.fields.StreamField([], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="researchlandingpage",
            name="aside_cta",
            field=wagtail.fields.StreamField([], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="buyersguidearticlepage",
            name="body",
            field=wagtail.fields.StreamField([], null=True),
        ),
        migrations.AlterField(
            model_name="buyersguidecampaignpage",
            name="body",
            field=wagtail.fields.StreamField([]),
        ),
        migrations.AlterField(
            model_name="modularpage",
            name="body",
            field=wagtail.fields.StreamField([]),
        ),
        migrations.AlterField(
            model_name="primarypage",
            name="body",
            field=wagtail.fields.StreamField([]),
        ),
        migrations.AddField(
            model_name="homepagetakeactioncards",
            name="cta",
            field=models.CharField(default="Learn more", max_length=50),
        ),
        migrations.AddField(
            model_name="homepage",
            name="show_hero_button",
            field=models.BooleanField(default=True, help_text="Display hero button"),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero_headline",
            field=models.CharField(blank=True, help_text="Hero story headline", max_length=120),
        ),
        migrations.AddField(
            model_name="homepage",
            name="show_cause_statement",
            field=models.BooleanField(default=False, help_text="Display cause statement"),
        ),
        migrations.AddField(
            model_name="buyersguidecalltoaction",
            name="link",
            field=wagtail.fields.StreamField([], blank=True),
        ),
        migrations.RemoveField(
            model_name="buyersguidecalltoaction",
            name="link_label",
        ),
        migrations.RemoveField(
            model_name="buyersguidecalltoaction",
            name="link_target_page",
        ),
        migrations.RemoveField(
            model_name="buyersguidecalltoaction",
            name="link_target_url",
        ),
        migrations.RenameModel(
            old_name="HomepageSpotlightPosts",
            new_name="HomepageIdeasPosts",
        ),
        migrations.RenameField(
            model_name="homepage",
            old_name="spotlight_headline",
            new_name="ideas_headline",
        ),
        migrations.RenameField(
            model_name="homepage",
            old_name="spotlight_image",
            new_name="ideas_image",
        ),
        migrations.AddField(
            model_name="homepageideasposts",
            name="cta",
            field=models.CharField(default="Read more", max_length=50),
        ),
        migrations.AlterField(
            model_name="homepageideasposts",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="ideas_posts", to="wagtailpages.homepage"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="ideas_headline",
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="ideas_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ideas_image",
                to="wagtailimages.image",
            ),
        ),
        migrations.RemoveField(
            model_name="focusarea",
            name="page",
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_intro_body",
            field=models.TextField(
                blank=True,
                default="Mozilla empowers consumers to demand better online privacy, trustworthy AI, and safe online experiences from Big Tech and governments. We work across borders, disciplines, and technologies to uphold principles like privacy, inclusion and decentralization online.",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_intro_heading",
            field=models.CharField(
                blank=True,
                default="A healthy internet is one in which privacy, openness, and inclusion are the norms.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_intro_link",
            field=wagtail.fields.StreamField([], blank=True),
        ),
        migrations.RenameModel(
            old_name="HomepageNewsYouCanUse",
            new_name="HomepageHighlights",
        ),
        migrations.AddField(
            model_name="homepage",
            name="ideas_title",
            field=models.CharField(default="Ideas", max_length=50),
        ),
        migrations.AddField(
            model_name="homepage",
            name="highlights_title",
            field=models.CharField(default="The Highlights", max_length=50),
        ),
        migrations.AlterField(
            model_name="homepagehighlights",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="highlights", to="wagtailpages.homepage"
            ),
        ),
        migrations.AlterField(
            model_name="blogauthors",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="blogpagetopic",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="blogsignup",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="buyersguidearticlepageauthorprofilerelation",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="buyersguidearticlepagecontentcategoryrelation",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="buyersguidecalltoaction",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="buyersguidecampaignpagedonationmodalrelation",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="buyersguidecontentcategory",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="buyersguideeditorialcontentindexpagearticlepagerelation",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="buyersguidepagefeaturedarticlerelation",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="buyersguidepagefeaturedupdaterelation",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="buyersguidepageherosupportingpagerelation",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="buyersguideproductcategory",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="buyersguideproductcategoryarticlepagerelation",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="buyersguideproductpagearticlepagerelation",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="callpower",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="cta4",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="donationmodal",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="donationmodals",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="excludedcategories",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="featuredcampaignpagerelation",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="focusarea",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="homepagefocusareas",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="homepagehighlights",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="homepageideasposts",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="homepagetakeactioncards",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="initiativesection",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="initiativeshighlights",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="participatehighlights",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="participatehighlights2",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="partnerlogos",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="petition",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="productpagecategory",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="productpageprivacypolicylink",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="productupdates",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="rccauthorrelation",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="rcccontenttype",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="rcccurriculararea",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="rccdetaillink",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="rccdetailpagercccontenttyperelation",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="rccdetailpagercccurriculararearelation",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="rccdetailpagercctopicrelation",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="rcclandingpagefeaturedauthorsrelation",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="rcclandingpagefeaturedrcccontenttyperelation",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="rcctopic",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="relatedproducts",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="researchauthorrelation",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="researchdetaillink",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="researchdetailpageresearchregionrelation",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="researchdetailpageresearchtopicrelation",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="researchlandingpagefeaturedauthorsrelation",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="researchlandingpagefeaturedresearchtopicrelation",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="researchregion",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="researchtopic",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="signup",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
    ]
