# Generated by Django 4.2.11 on 2024-07-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailpages", "0154_update_cardgridblock_with_linkblock"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepagetakeactioncards",
            name="cta",
            field=models.CharField(default="Learn more", max_length=50),
        ),
    ]
