# Generated by Django 4.2.20 on 2025-11-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailpages", "0171_merge_20250627_1531"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogsignup",
            name="newsletter",
            field=models.CharField(
                default="mozillafoundationorg",
                help_text="The (pre-existing) newsletter to sign up for",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="cta",
            name="newsletter",
            field=models.CharField(
                default="mozillafoundationorg",
                help_text="The (pre-existing) newsletter to sign up for",
                max_length=100,
            ),
        ),
    ]
