# Generated by Django 4.2.27 on 2026-01-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailpages", "0172_alter_blogsignup_newsletter_alter_cta_newsletter"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appinstallpage",
            options={"verbose_name": "App Install Page (Legacy)", "verbose_name_plural": "App Install Pages (Legacy)"},
        ),
        migrations.AlterModelOptions(
            name="articlepage",
            options={"verbose_name": "Article Page (Legacy)", "verbose_name_plural": "Article Pages (Legacy)"},
        ),
        migrations.AlterModelOptions(
            name="banneredcampaignpage",
            options={"verbose_name": "Banner Page (Legacy)", "verbose_name_plural": "Banner pages (Legacy)"},
        ),
        migrations.AlterModelOptions(
            name="blogindexpage",
            options={"verbose_name": "Blog Index Page (Legacy)", "verbose_name_plural": "Blog Index Pages (Legacy)"},
        ),
        migrations.AlterModelOptions(
            name="blogpage",
            options={"verbose_name": "Blog Page (Legacy)", "verbose_name_plural": "Blog Pages (Legacy)"},
        ),
        migrations.AlterModelOptions(
            name="blogpagetopic",
            options={
                "ordering": ["name"],
                "verbose_name": "Blog Page Topic (Legacy)",
                "verbose_name_plural": "Blog Page Topics (Legacy)",
            },
        ),
        migrations.AlterModelOptions(
            name="blogsignup",
            options={
                "ordering": ["name"],
                "verbose_name": "Blog Signup (Legacy)",
                "verbose_name_plural": "Blog Signups (Legacy)",
            },
        ),
        migrations.AlterModelOptions(
            name="buyersguidearticlepage",
            options={
                "verbose_name": "Buyers Guide Article Page (Legacy)",
                "verbose_name_plural": "Buyers Guide Article Pages (Legacy)",
            },
        ),
        migrations.AlterModelOptions(
            name="buyersguidecalltoaction",
            options={
                "ordering": ["title"],
                "verbose_name": "Buyers Guide Call To Action (Legacy)",
                "verbose_name_plural": "Buyers Guide Call To Actions (Legacy)",
            },
        ),
        migrations.AlterModelOptions(
            name="buyersguidecampaignpage",
            options={
                "verbose_name": "Buyers Guide Campaign Page (Legacy)",
                "verbose_name_plural": "Buyers Guide Campaign Pages (Legacy)",
            },
        ),
        migrations.AlterModelOptions(
            name="buyersguidecategorynav",
            options={
                "verbose_name": "*PNI categories navbar (Legacy)",
                "verbose_name_plural": "*PNI categories navbar (Legacy)",
            },
        ),
        migrations.AlterModelOptions(
            name="buyersguidecategorynavrelation",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "Category Navigation Relation (Legacy)",
                "verbose_name_plural": "Category Navigation Relations (Legacy)",
            },
        ),
        migrations.AlterModelOptions(
            name="buyersguidecontentcategory",
            options={
                "ordering": ["title"],
                "verbose_name": "Buyers Guide Content Category (Legacy)",
                "verbose_name_plural": "Buyers Guide Content Categories (Legacy)",
            },
        ),
        migrations.AlterModelOptions(
            name="buyersguideeditorialcontentindexpage",
            options={
                "verbose_name": "Buyers Guide Editorial Content Index Page (Legacy)",
                "verbose_name_plural": "Buyers Guide Editorial Content Index Pages (Legacy)",
            },
        ),
        migrations.AlterModelOptions(
            name="buyersguidepage",
            options={
                "verbose_name": "Buyers Guide Page (Legacy)",
                "verbose_name_plural": "Buyers Guide Pages (Legacy)",
            },
        ),
        migrations.AlterModelOptions(
            name="buyersguideproductcategory",
            options={
                "ordering": [models.OrderBy(models.F("parent__name"), nulls_first=True), "name"],
                "verbose_name": "Buyers Guide Product Category (Legacy)",
                "verbose_name_plural": "Buyers Guide Product Categories (Legacy)",
            },
        ),
        migrations.AlterModelOptions(
            name="callpower",
            options={
                "ordering": ["name"],
                "verbose_name": "Callpower (Legacy)",
                "verbose_name_plural": "Callpowers (Legacy)",
            },
        ),
        migrations.AlterModelOptions(
            name="campaignindexpage",
            options={
                "verbose_name": "Campaign Index Page (Legacy)",
                "verbose_name_plural": "Campaign Index Pages (Legacy)",
            },
        ),
        migrations.AlterModelOptions(
            name="campaignpage",
            options={"verbose_name": "Campaign Page (Legacy)", "verbose_name_plural": "Campaign Pages (Legacy)"},
        ),
        migrations.AlterModelOptions(
            name="consumercreepometerpage",
            options={
                "verbose_name": "Consumer Creepometer Page (Legacy)",
                "verbose_name_plural": "Consumer Creepometer Pages (Legacy)",
            },
        ),
        migrations.AlterModelOptions(
            name="cta",
            options={"ordering": ["-id"], "verbose_name": "CTA (Legacy)", "verbose_name_plural": "CTAs (Legacy)"},
        ),
        migrations.AlterModelOptions(
            name="dearinternetpage",
            options={
                "verbose_name": "Dear Internet Page (Legacy)",
                "verbose_name_plural": "Dear Internet Pages (Legacy)",
            },
        ),
        migrations.AlterModelOptions(
            name="donationmodal",
            options={
                "ordering": ["name"],
                "verbose_name": "Donation CTA (Legacy)",
                "verbose_name_plural": "Donation CTAs (Legacy)",
            },
        ),
        migrations.AlterModelOptions(
            name="donationmodals",
            options={"verbose_name": "Donation Modals (Legacy)", "verbose_name_plural": "Donation Modals (Legacy)"},
        ),
        migrations.AlterModelOptions(
            name="focusarea",
            options={
                "ordering": ["name"],
                "verbose_name": "Area of focus (Legacy)",
                "verbose_name_plural": "Areas of focus (Legacy)",
            },
        ),
        migrations.AlterModelOptions(
            name="generalproductpage",
            options={
                "verbose_name": "General Product Page (Legacy)",
                "verbose_name_plural": "General Product Pages (Legacy)",
            },
        ),
        migrations.AlterModelOptions(
            name="homepage",
            options={"verbose_name": "Homepage (Legacy)", "verbose_name_plural": "Homepages (Legacy)"},
        ),
        migrations.AlterModelOptions(
            name="indexpage",
            options={"verbose_name": "Index Page (Legacy)", "verbose_name_plural": "Index Pages (Legacy)"},
        ),
        migrations.AlterModelOptions(
            name="initiativespage",
            options={"verbose_name": "Initiatives Page (Legacy)", "verbose_name_plural": "Initiatives Pages (Legacy)"},
        ),
        migrations.AlterModelOptions(
            name="minisitenamespace",
            options={
                "verbose_name": "Mini Site Namespace (Legacy)",
                "verbose_name_plural": "Mini Site Namespaces (Legacy)",
            },
        ),
        migrations.AlterModelOptions(
            name="opportunitypage",
            options={"verbose_name": "Default Page (Legacy)", "verbose_name_plural": "Default pages (Legacy)"},
        ),
        migrations.AlterModelOptions(
            name="participatepage2",
            options={
                "verbose_name": "Participate Page 2 (Legacy)",
                "verbose_name_plural": "Participate Pages 2 (Legacy)",
            },
        ),
        migrations.AlterModelOptions(
            name="petition",
            options={
                "ordering": ["-id"],
                "verbose_name": "Petition (Legacy)",
                "verbose_name_plural": "Petitions (Legacy)",
            },
        ),
        migrations.AlterModelOptions(
            name="primarypage",
            options={"verbose_name": "Primary Page (Legacy)", "verbose_name_plural": "Primary Pages (Legacy)"},
        ),
        migrations.AlterModelOptions(
            name="productpage",
            options={"verbose_name": "Product Page (Legacy)", "verbose_name_plural": "Product Pages (Legacy)"},
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={
                "ordering": ["name"],
                "verbose_name": "Profile (Legacy)",
                "verbose_name_plural": "Profiles (Legacy)",
            },
        ),
        migrations.AlterModelOptions(
            name="publicationpage",
            options={"verbose_name": "Publication Page (Legacy)", "verbose_name_plural": "Publication Pages (Legacy)"},
        ),
        migrations.AlterModelOptions(
            name="pulsefilter",
            options={
                "ordering": ["name"],
                "verbose_name": "Pulse Filter (Legacy)",
                "verbose_name_plural": "Pulse Filters (Legacy)",
            },
        ),
        migrations.AlterModelOptions(
            name="rccauthorsindexpage",
            options={
                "verbose_name": "RCC authors index page (Legacy)",
                "verbose_name_plural": "RCC authors index pages (Legacy)",
            },
        ),
        migrations.AlterModelOptions(
            name="rcccontenttype",
            options={
                "ordering": ["name"],
                "verbose_name": "RCC Content Type (Legacy)",
                "verbose_name_plural": "RCC Content Types (Legacy)",
            },
        ),
        migrations.AlterModelOptions(
            name="rcccurriculararea",
            options={
                "ordering": ["name"],
                "verbose_name": "RCC Curricular Area (Legacy)",
                "verbose_name_plural": "RCC Curricular Areas (Legacy)",
            },
        ),
        migrations.AlterModelOptions(
            name="rccdetailpage",
            options={"verbose_name": "RCC detail page (Legacy)", "verbose_name_plural": "RCC detail pages (Legacy)"},
        ),
        migrations.AlterModelOptions(
            name="rcclandingpage",
            options={"verbose_name": "RCC landing page (Legacy)", "verbose_name_plural": "RCC landing pages (Legacy)"},
        ),
        migrations.AlterModelOptions(
            name="rcclibrarypage",
            options={"verbose_name": "RCC library page (Legacy)", "verbose_name_plural": "RCC library pages (Legacy)"},
        ),
        migrations.AlterModelOptions(
            name="rcctopic",
            options={
                "ordering": ["name"],
                "verbose_name": "RCC Topic (Legacy)",
                "verbose_name_plural": "RCC Topics (Legacy)",
            },
        ),
        migrations.AlterModelOptions(
            name="relatedblogposts",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "Related blog posts (Legacy)",
                "verbose_name_plural": "Related blog posts (Legacy)",
            },
        ),
        migrations.AlterModelOptions(
            name="researchauthorsindexpage",
            options={
                "verbose_name": "Research Authors index page (Legacy)",
                "verbose_name_plural": "Research Authors index pages (Legacy)",
            },
        ),
        migrations.AlterModelOptions(
            name="researchdetailpage",
            options={
                "verbose_name": "Research Detail Page (Legacy)",
                "verbose_name_plural": "Research Detail Pages (Legacy)",
            },
        ),
        migrations.AlterModelOptions(
            name="researchlandingpage",
            options={
                "verbose_name": "Research Landing Page (Legacy)",
                "verbose_name_plural": "Research Landing Pages (Legacy)",
            },
        ),
        migrations.AlterModelOptions(
            name="researchlibrarypage",
            options={
                "verbose_name": "Research Library Page (Legacy)",
                "verbose_name_plural": "Research Library Pages (Legacy)",
            },
        ),
        migrations.AlterModelOptions(
            name="researchregion",
            options={
                "ordering": ["name"],
                "verbose_name": "Research Region (Legacy)",
                "verbose_name_plural": "Research Regions (Legacy)",
            },
        ),
        migrations.AlterModelOptions(
            name="researchtopic",
            options={
                "ordering": ["name"],
                "verbose_name": "Research Topic (Legacy)",
                "verbose_name_plural": "Research Topics (Legacy)",
            },
        ),
        migrations.AlterModelOptions(
            name="signup",
            options={
                "ordering": ["name"],
                "verbose_name": "Signup (Legacy)",
                "verbose_name_plural": "Signups (Legacy)",
            },
        ),
        migrations.AlterModelOptions(
            name="styleguide",
            options={"verbose_name": "Styleguide (Legacy)"},
        ),
        migrations.AlterModelOptions(
            name="update",
            options={
                "ordering": ["title"],
                "verbose_name": "Buyers Guide Product Update (Legacy)",
                "verbose_name_plural": "Buyers Guide Product Updates (Legacy)",
            },
        ),
        migrations.AlterModelOptions(
            name="youtuberegrets2021page",
            options={
                "verbose_name": "YouTube Regrets 2021 Page (Legacy)",
                "verbose_name_plural": "YouTube Regrets 2021 Pages (Legacy)",
            },
        ),
        migrations.AlterModelOptions(
            name="youtuberegrets2022page",
            options={
                "verbose_name": "YouTube Regrets 2022 Page (Legacy)",
                "verbose_name_plural": "YouTube Regrets 2022 Pages (Legacy)",
            },
        ),
        migrations.AlterModelOptions(
            name="youtuberegretspage",
            options={
                "verbose_name": "YouTube Regrets Page (Legacy)",
                "verbose_name_plural": "YouTube Regrets Pages (Legacy)",
            },
        ),
        migrations.AlterModelOptions(
            name="youtuberegretsreporterpage",
            options={
                "verbose_name": "YouTube Regrets Reporter Page (Legacy)",
                "verbose_name_plural": "YouTube Regrets Reporter Pages (Legacy)",
            },
        ),
    ]
