# Generated by Django 5.2.15 on 2026-09-09 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailpages", "0177_articlepage_notice_banner_blogpage_notice_banner_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articlepage",
            name="show_side_share_buttons",
        ),
    ]
