# Generated by Django 4.2.20 on 2025-08-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nothing_personal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nothingpersonalarticlecollectionpage",
            name="theme",
            field=models.CharField(
                blank=True,
                choices=[("default", "Default"), ("nothing_personal", "Nothing Personal")],
                help_text="Optional. If unset, theme will be inherited from section root.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="nothingpersonalarticlepage",
            name="theme",
            field=models.CharField(
                blank=True,
                choices=[("default", "Default"), ("nothing_personal", "Nothing Personal")],
                help_text="Optional. If unset, theme will be inherited from section root.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="nothingpersonalproductreviewpage",
            name="theme",
            field=models.CharField(
                blank=True,
                choices=[("default", "Default"), ("nothing_personal", "Nothing Personal")],
                help_text="Optional. If unset, theme will be inherited from section root.",
                max_length=50,
                null=True,
            ),
        ),
    ]
