# Generated by Django 4.2.20 on 2025-09-04 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
        ("nothing_personal", "0004_alter_nothingpersonalarticlecollectionpage_theme_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nothingpersonalarticlepage",
            name="hero_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Image for page hero section.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="images.foundationcustomimage",
                verbose_name="Hero Image",
            ),
        ),
        migrations.AddField(
            model_name="nothingpersonalarticlepage",
            name="hero_image_alt_text",
            field=models.CharField(
                blank=True,
                help_text="Descriptive text for screen readers. Leave blank to use the image's default title.",
                max_length=255,
                verbose_name="Alt Text",
            ),
        ),
    ]
