# Generated by Django 4.2.20 on 2025-09-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nothing_personal", "0007_alter_nothingpersonalarticlecollectionpage_body_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nothingpersonalhomepage",
            name="who_we_are_description",
            field=models.TextField(blank=True, help_text="Description text for the Who We Are section"),
        ),
    ]
