# Generated by Django 4.2.20 on 2025-09-12 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
        ("nothing_personal", "0008_productmentioned"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nothingpersonalproductreviewpage",
            name="body",
        ),
        migrations.AddField(
            model_name="nothingpersonalproductreviewpage",
            name="hero_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Image for page hero section.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="images.foundationcustomimage",
                verbose_name="Hero Image",
            ),
        ),
        migrations.AddField(
            model_name="nothingpersonalproductreviewpage",
            name="hero_image_alt_text",
            field=models.CharField(
                blank=True,
                help_text="Descriptive text for screen readers. Leave blank to use the image's default title.",
                max_length=255,
                verbose_name="Alt Text",
            ),
        ),
        migrations.AddField(
            model_name="nothingpersonalproductreviewpage",
            name="research",
            field=models.CharField(
                blank=True, help_text="Amount of time spent on research.", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="nothingpersonalproductreviewpage",
            name="reviewed",
            field=models.DateField(blank=True, help_text="Date of the product review.", null=True),
        ),
        migrations.AddField(
            model_name="nothingpersonalproductreviewpage",
            name="updated",
            field=models.DateField(blank=True, help_text="When the review was last updated.", null=True),
        ),
    ]
