# Generated by Django 4.2.20 on 2025-09-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nothing_personal", "0011_remove_nothingpersonalhomepage_who_we_are_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nothingpersonalproductreviewpage",
            name="show_reduce_your_risks_section",
            field=models.BooleanField(default=False, verbose_name="Show 'Reduce Your Risks' Section"),
        ),
        migrations.AddField(
            model_name="nothingpersonalproductreviewpage",
            name="show_the_bottom_line_section",
            field=models.BooleanField(default=False, verbose_name="Show 'The Bottom Line' Section"),
        ),
        migrations.AddField(
            model_name="nothingpersonalproductreviewpage",
            name="show_the_good_and_the_bad_section",
            field=models.BooleanField(default=False, verbose_name="Show 'The Good and The Bad' Section"),
        ),
        migrations.AddField(
            model_name="nothingpersonalproductreviewpage",
            name="show_what_you_should_know_section",
            field=models.BooleanField(default=False, verbose_name="Show 'What You Should Know' Section"),
        ),
    ]
