# Generated by Django 4.2.20 on 2025-09-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nothing_personal", "0011_remove_nothingpersonalhomepage_who_we_are_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nothingpersonalarticlepage",
            name="displayed_hero_content",
            field=models.CharField(
                choices=[("image", "Image"), ("video", "Video")],
                default="image",
                max_length=25,
                verbose_name="Select media type from dropdown",
            ),
        ),
        migrations.AddField(
            model_name="nothingpersonalarticlepage",
            name="hero_video_url",
            field=models.CharField(
                blank=True,
                help_text='Log into Vimeo using 1Password and upload the desired video. Then select the video and click "...", "Video File Links", and select "(mp4, 1920 x 1080)". Copy and paste the link here.',
                max_length=500,
            ),
        ),
    ]
