# Generated by Django 4.2.20 on 2025-09-18 17:20

import wagtail.fields
from django.db import migrations

import foundation_cms.legacy_apps.wagtailpages.validators
import foundation_cms.validators


class Migration(migrations.Migration):

    dependencies = [
        ("nothing_personal", "0014_nothingpersonalpodcastpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nothingpersonalhomepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("two_column_container_block", 40),
                    ("narrow_text_image_block", 43),
                    ("product_review_carousel_block", 51),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("top", "Top"), ("middle", "Middle"), ("bottom", "Bottom")],
                            "help_text": "Vertical alignment of the columns content",
                        },
                    ),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Optional image to display at the top of the block."},
                    ),
                    3: ("wagtail.blocks.CharBlock", (), {}),
                    4: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Short description of the audio", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 2), ("title", 3), ("description", 4), ("simplecast_embed_code", 3)]],
                        {},
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title/caption for this image", "required": False},
                    ),
                    7: ("wagtail.images.blocks.ImageBlock", [], {}),
                    8: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("portrait", "Portrait"), ("landscape", "Landscape"), ("square", "Square")],
                            "help_text": "Select the orientation of this image",
                        },
                    ),
                    9: ("wagtail.blocks.StructBlock", [[("title", 6), ("image", 7), ("orientation", 8)]], {}),
                    10: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("snippets.NewsletterSignup",),
                        {"max_num": 1},
                    ),
                    11: ("wagtail.blocks.StructBlock", [[("newsletter_signup", 10)]], {}),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Log into Vimeo, select your desired video, and click 'Copy Link'",
                            "label": "Vimeo Video URL",
                            "required": True,
                        },
                    ),
                    13: ("wagtail.blocks.CharBlock", (), {"help_text": "Optional Caption Text", "required": False}),
                    14: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("external_url", "External URL"),
                                ("relative_url", "Relative URL"),
                                ("email", "Email"),
                                ("anchor", "Anchor"),
                                ("file", "File"),
                                ("phone", "Phone"),
                            ],
                            "label": "Link to",
                        },
                    ),
                    15: ("wagtail.blocks.PageChooserBlock", (), {"label": "Page", "required": False}),
                    16: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Enter a full URL including http:// or https://",
                            "label": "External URL",
                            "max_length": 300,
                            "required": False,
                        },
                    ),
                    17: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'A path relative to this domain. For example, "/foo/bar" or "?foo=bar".',
                            "label": "Relative URL",
                            "max_length": 300,
                            "required": False,
                            "validators": [foundation_cms.legacy_apps.wagtailpages.validators.RelativeURLValidator()],
                        },
                    ),
                    18: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'An id attribute of an element on the current page. For example, "#section-1"',
                            "label": "#",
                            "max_length": 300,
                            "required": False,
                            "validators": [foundation_cms.validators.AnchorLinkValidator()],
                        },
                    ),
                    19: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    20: ("wagtail.documents.blocks.DocumentChooserBlock", (), {"label": "File", "required": False}),
                    21: ("wagtail.blocks.CharBlock", (), {"label": "Phone", "max_length": 30, "required": False}),
                    22: ("wagtail.blocks.BooleanBlock", (), {"label": "Open in new window", "required": False}),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_to", 14),
                                ("page", 15),
                                ("external_url", 16),
                                ("relative_url", 17),
                                ("anchor", 18),
                                ("email", 19),
                                ("file", 20),
                                ("phone", 21),
                                ("new_window", 22),
                            ]
                        ],
                        {},
                    ),
                    24: (
                        "wagtail.blocks.ListBlock",
                        (23,),
                        {
                            "default": [],
                            "help_text": "Optional URL that this caption should link out to.",
                            "max_num": 1,
                            "min_num": 0,
                        },
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [[("video_url", 12), ("caption", 13), ("caption_url", 24)]],
                        {},
                    ),
                    26: ("wagtail.blocks.CharBlock", (), {"help_text": "Heading displayed above the list"}),
                    27: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Description displayed above the list", "required": False},
                    ),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 3),
                                ("link_to", 14),
                                ("page", 15),
                                ("external_url", 16),
                                ("relative_url", 17),
                                ("anchor", 18),
                                ("email", 19),
                                ("file", 20),
                                ("phone", 21),
                                ("new_window", 22),
                            ]
                        ],
                        {},
                    ),
                    29: ("wagtail.blocks.ListBlock", (28,), {"max_num": 4, "min_num": 1}),
                    30: ("wagtail.blocks.StructBlock", [[("title", 26), ("description", 27), ("items", 29)]], {}),
                    31: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("small", "Small"),
                                ("medium", "Medium"),
                                ("large", "Large"),
                                ("xlarge", "Extra Large"),
                            ],
                            "help_text": "Select the size of the spacer",
                        },
                    ),
                    32: ("wagtail.blocks.StructBlock", [[("size", 31)]], {}),
                    33: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    34: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    35: ("wagtail.blocks.StructBlock", [[("quote", 33), ("attribution", 34)]], {}),
                    36: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    37: ("wagtail.blocks.StructBlock", [[("title", 34), ("text", 36)]], {}),
                    38: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 1),
                                ("audio", 5),
                                ("image", 9),
                                ("newsletter_signup", 11),
                                ("video", 25),
                                ("list", 30),
                                ("spacer", 32),
                                ("quote", 35),
                                ("text_social", 37),
                            ]
                        ],
                        {"label": "Left Column", "required": False},
                    ),
                    39: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 1),
                                ("audio", 5),
                                ("image", 9),
                                ("newsletter_signup", 11),
                                ("video", 25),
                                ("list", 30),
                                ("spacer", 32),
                                ("quote", 35),
                                ("text_social", 37),
                            ]
                        ],
                        {"label": "Right Column", "required": False},
                    ),
                    40: (
                        "wagtail.blocks.StructBlock",
                        [[("vertical_alignment", 0), ("left_column", 38), ("right_column", 39)]],
                        {},
                    ),
                    41: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 6), ("image", 7), ("orientation", 8)]],
                        {"required": False},
                    ),
                    42: ("foundation_cms.blocks.link_block.OptionalLinkBlock", (), {"required": False}),
                    43: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 34), ("subtitle", 34), ("text", 36), ("image", 41), ("link", 42)]],
                        {},
                    ),
                    44: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional subtitle for the contianer", "required": False},
                    ),
                    45: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional title for the container", "required": False},
                    ),
                    46: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Optional description text for the container", "required": False},
                    ),
                    47: (
                        "foundation_cms.blocks.link_block.OptionalLinkBlock",
                        (),
                        {"help_text": "Optional link for the container.", "label": "Link", "required": False},
                    ),
                    48: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "help_text": "Select a Product Review",
                            "label": "Product review selector",
                            "page_type": ["nothing_personal.NothingPersonalProductReviewPage"],
                        },
                    ),
                    49: ("wagtail.blocks.StructBlock", [[("product_review", 48)]], {}),
                    50: (
                        "wagtail.blocks.StreamBlock",
                        [[("product_review_card", 49)]],
                        {"help_text": "Maximum of 10 per carousel.", "max_num": 10},
                    ),
                    51: (
                        "wagtail.blocks.StructBlock",
                        [[("subtitle", 44), ("title", 45), ("text", 46), ("cta_link", 47), ("cards", 50)]],
                        {},
                    ),
                },
            ),
        ),
    ]
