# Generated by Django 4.2.20 on 2025-09-22 17:59

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("nothing_personal", "0015_alter_nothingpersonalhomepage_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nothingpersonalhomepage",
            name="hero_image",
        ),
        migrations.RemoveField(
            model_name="nothingpersonalhomepage",
            name="hero_image_alt_text",
        ),
        migrations.RemoveField(
            model_name="nothingpersonalhomepage",
            name="hero_title",
        ),
        migrations.AddField(
            model_name="nothingpersonalhomepage",
            name="featured_item",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                help_text="Select a page to feature in the hero section.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="featured_post",
                to="wagtailcore.page",
            ),
        ),
    ]
