# Generated by Django 4.2.20 on 2025-09-19 21:49

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nothing_personal", "0015_alter_nothingpersonalhomepage_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nothingpersonalproductreviewpage",
            name="show_reduce_your_risks_section",
        ),
        migrations.RemoveField(
            model_name="nothingpersonalproductreviewpage",
            name="show_the_bottom_line_section",
        ),
        migrations.RemoveField(
            model_name="nothingpersonalproductreviewpage",
            name="show_the_good_and_the_bad_section",
        ),
        migrations.RemoveField(
            model_name="nothingpersonalproductreviewpage",
            name="show_what_you_should_know_section",
        ),
        migrations.AddField(
            model_name="nothingpersonalproductreviewpage",
            name="review_sections",
            field=wagtail.fields.StreamField(
                [
                    ("what_you_should_know", 6),
                    ("newsletter_signup", 8),
                    ("reduce_your_risks", 10),
                    ("good_and_bad", 13),
                    ("bottom_line", 15),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("yes", "Yes"), ("no", "No")],
                            "help_text": "Should I trust their default settings?",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("yes", "Yes"), ("no", "No")],
                            "help_text": "Should I give them my data by default?",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("yes", "Yes"), ("no", "No")],
                            "help_text": "Can I use this product/service offline?",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("yes", "Yes"), ("no", "No")],
                            "help_text": "Should I reconsider buying this product because of this company's track record + data practices?",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Optional explanation for this answer", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("yes", "Yes"), ("no", "No")],
                            "help_text": "Does this product/service sell or giveaway user data?",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("trust_default_settings", 0),
                                ("give_data_by_default", 1),
                                ("use_offline", 2),
                                ("reconsider_buying", 3),
                                ("reconsider_buying_explanation", 4),
                                ("sells_user_data", 5),
                                ("sells_user_data_explanation", 4),
                            ]
                        ],
                        {},
                    ),
                    7: ("wagtail.snippets.blocks.SnippetChooserBlock", ("snippets.NewsletterSignup",), {"max_num": 1}),
                    8: ("wagtail.blocks.StructBlock", [[("newsletter_signup", 7)]], {}),
                    9: ("wagtail.blocks.RichTextBlock", (), {"help_text": "Advice on how to reduce privacy risks"}),
                    10: ("wagtail.blocks.StructBlock", [[("content", 9)]], {}),
                    11: ("wagtail.blocks.RichTextBlock", (), {"help_text": "Positive aspects of this product"}),
                    12: ("wagtail.blocks.RichTextBlock", (), {"help_text": "Negative aspects of this product"}),
                    13: ("wagtail.blocks.StructBlock", [[("the_good", 11), ("the_bad", 12)]], {}),
                    14: ("wagtail.blocks.RichTextBlock", (), {"help_text": "Final verdict and recommendation"}),
                    15: ("wagtail.blocks.StructBlock", [[("content", 14)]], {}),
                },
            ),
        ),
    ]
