# Generated by Django 4.2.20 on 2025-10-02 21:11

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nothing_personal", "0022_add_verbose_name_to_product_mentioned"),
    ]

    operations = [
        migrations.AddField(
            model_name="nothingpersonalhomepage",
            name="tagline",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Tagline displayed above the featured articles (max ~150 chars)."
            ),
        ),
    ]
