# Generated by Django 4.2.20 on 2025-10-03 19:01

import wagtail.fields
from django.db import migrations

import foundation_cms.legacy_apps.wagtailpages.validators
import foundation_cms.validators


class Migration(migrations.Migration):

    dependencies = [
        ("nothing_personal", "0023_nothingpersonalhomepage_tagline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nothingpersonalarticlecollectionpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("rich_text", 0),
                    ("media", 6),
                    ("podcast_block", 9),
                    ("tabbed_content", 22),
                    ("two_column_container_block", 52),
                    ("link_button_block", 54),
                    ("portrait_card_set_block", 61),
                    ("spotlight_card_set_block", 67),
                    ("spacer_block", 46),
                    ("iframe_block", 72),
                    ("impact_numbers", 78),
                    ("newsletter_signup", 25),
                    ("timely_activations_cards", 84),
                    ("quote", 48),
                    ("list_block", 44),
                    ("video_block", 39),
                    ("pillar_card_set", 88),
                    ("featured_card_block", 92),
                    ("divider", 93),
                    ("title_block", 96),
                    ("callout", 99),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"template": "patterns/blocks/themes/default/rich_text_block.html"},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title/caption for this media", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("image", "Image"), ("video", "Video")],
                            "help_text": "Select the type of media to display",
                        },
                    ),
                    3: ("wagtail.images.blocks.ImageBlock", [], {}),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Log into Vimeo using 1Password and upload the desired video. Then select the video and click "...", "Video File Links", and select "(mp4, 1920 x 1080)". Copy and paste the link here.',
                            "max_length": 500,
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("portrait", "Portrait"), ("landscape", "Landscape"), ("square", "Square")],
                            "help_text": "Select the orientation of this media",
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("content", 2), ("image", 3), ("video_url", 4), ("orientation", 5)]],
                        {},
                    ),
                    7: ("wagtail.blocks.CharBlock", (), {}),
                    8: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Optional short description of the podcast", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 7), ("description", 8), ("simplecast_embed_code", 7)]],
                        {},
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title shown on the tab button", "required": True},
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Subtitle shown under the title on the tab", "required": False},
                    ),
                    12: ("wagtail.blocks.RichTextBlock", (), {}),
                    13: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    14: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("content", 2), ("image", 3), ("video_url", 4), ("orientation", 5)]],
                        {"required": False},
                    ),
                    16: ("foundation_cms.blocks.link_block.OptionalLinkBlock", (), {"required": False}),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 13), ("subtitle", 13), ("text", 14), ("media", 15), ("link", 16)]],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 7), ("image", 3), ("subtitle", 7), ("link", 16)]],
                        {},
                    ),
                    19: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 12), ("text_media", 17), ("tab_card_set", 18)]],
                        {"help_text": "Add one or more content blocks to the tab.", "min_num": 1, "required": True},
                    ),
                    20: ("wagtail.blocks.StructBlock", [[("title", 10), ("subtitle", 11), ("content", 19)]], {}),
                    21: ("wagtail.blocks.ListBlock", (20,), {"label": "Tabs", "max_num": 8, "min_num": 1}),
                    22: ("wagtail.blocks.StructBlock", [[("tabs", 21)]], {}),
                    23: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("top", "Top"), ("middle", "Middle"), ("bottom", "Bottom")],
                            "help_text": "Vertical alignment of the columns content",
                        },
                    ),
                    24: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("snippets.NewsletterSignup",),
                        {"max_num": 1},
                    ),
                    25: ("wagtail.blocks.StructBlock", [[("newsletter_signup", 24)]], {}),
                    26: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Log into Vimeo, select your desired video, and click 'Copy Link'",
                            "label": "Vimeo Video URL",
                            "required": True,
                        },
                    ),
                    27: ("wagtail.blocks.CharBlock", (), {"help_text": "Optional Caption Text", "required": False}),
                    28: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("external_url", "External URL"),
                                ("relative_url", "Relative URL"),
                                ("email", "Email"),
                                ("anchor", "Anchor"),
                                ("file", "File"),
                                ("phone", "Phone"),
                            ],
                            "label": "Link to",
                        },
                    ),
                    29: ("wagtail.blocks.PageChooserBlock", (), {"label": "Page", "required": False}),
                    30: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Enter a full URL including http:// or https://",
                            "label": "External URL",
                            "max_length": 300,
                            "required": False,
                        },
                    ),
                    31: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'A path relative to this domain. For example, "/foo/bar" or "?foo=bar".',
                            "label": "Relative URL",
                            "max_length": 300,
                            "required": False,
                            "validators": [foundation_cms.legacy_apps.wagtailpages.validators.RelativeURLValidator()],
                        },
                    ),
                    32: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'An id attribute of an element on the current page. For example, "#section-1"',
                            "label": "#",
                            "max_length": 300,
                            "required": False,
                            "validators": [foundation_cms.validators.AnchorLinkValidator()],
                        },
                    ),
                    33: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    34: ("wagtail.documents.blocks.DocumentChooserBlock", (), {"label": "File", "required": False}),
                    35: ("wagtail.blocks.CharBlock", (), {"label": "Phone", "max_length": 30, "required": False}),
                    36: ("wagtail.blocks.BooleanBlock", (), {"label": "Open in new window", "required": False}),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_to", 28),
                                ("page", 29),
                                ("external_url", 30),
                                ("relative_url", 31),
                                ("anchor", 32),
                                ("email", 33),
                                ("file", 34),
                                ("phone", 35),
                                ("new_window", 36),
                            ]
                        ],
                        {},
                    ),
                    38: (
                        "wagtail.blocks.ListBlock",
                        (37,),
                        {
                            "default": [],
                            "help_text": "Optional URL that this caption should link out to.",
                            "max_num": 1,
                            "min_num": 0,
                        },
                    ),
                    39: (
                        "wagtail.blocks.StructBlock",
                        [[("video_url", 26), ("caption", 27), ("caption_url", 38)]],
                        {},
                    ),
                    40: ("wagtail.blocks.CharBlock", (), {"help_text": "Heading displayed above the list"}),
                    41: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Description displayed above the list", "required": False},
                    ),
                    42: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 7),
                                ("link_to", 28),
                                ("page", 29),
                                ("external_url", 30),
                                ("relative_url", 31),
                                ("anchor", 32),
                                ("email", 33),
                                ("file", 34),
                                ("phone", 35),
                                ("new_window", 36),
                            ]
                        ],
                        {},
                    ),
                    43: ("wagtail.blocks.ListBlock", (42,), {"max_num": 4, "min_num": 1}),
                    44: ("wagtail.blocks.StructBlock", [[("title", 40), ("description", 41), ("items", 43)]], {}),
                    45: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("small", "Small"),
                                ("medium", "Medium"),
                                ("large", "Large"),
                                ("xlarge", "Extra Large"),
                            ],
                            "help_text": "Select the size of the spacer",
                        },
                    ),
                    46: ("wagtail.blocks.StructBlock", [[("size", 45)]], {}),
                    47: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    48: ("wagtail.blocks.StructBlock", [[("quote", 47), ("attribution", 13)]], {}),
                    49: ("wagtail.blocks.StructBlock", [[("title", 13), ("text", 14)]], {}),
                    50: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 12),
                                ("podcast", 9),
                                ("media", 6),
                                ("newsletter_signup", 25),
                                ("video", 39),
                                ("list", 44),
                                ("spacer", 46),
                                ("quote", 48),
                                ("text_social", 49),
                            ]
                        ],
                        {"label": "Left Column", "required": False},
                    ),
                    51: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 12),
                                ("podcast", 9),
                                ("media", 6),
                                ("newsletter_signup", 25),
                                ("video", 39),
                                ("list", 44),
                                ("spacer", 46),
                                ("quote", 48),
                                ("text_social", 49),
                            ]
                        ],
                        {"label": "Right Column", "required": False},
                    ),
                    52: (
                        "wagtail.blocks.StructBlock",
                        [[("vertical_alignment", 23), ("left_column", 50), ("right_column", 51)]],
                        {},
                    ),
                    53: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("btn-primary", "Primary"), ("btn-secondary", "Secondary")]},
                    ),
                    54: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 7),
                                ("link_to", 28),
                                ("page", 29),
                                ("external_url", 30),
                                ("relative_url", 31),
                                ("anchor", 32),
                                ("email", 33),
                                ("file", 34),
                                ("phone", 35),
                                ("new_window", 36),
                                ("style", 53),
                            ]
                        ],
                        {},
                    ),
                    55: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Appears above the headline.", "label": "Label", "required": False},
                    ),
                    56: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Appears as the main heading.", "label": "Headline", "required": False},
                    ),
                    57: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Optional Image for the card", "label": "Image"},
                    ),
                    58: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 7),
                                ("link_to", 28),
                                ("page", 29),
                                ("external_url", 30),
                                ("relative_url", 31),
                                ("anchor", 32),
                                ("email", 33),
                                ("file", 34),
                                ("phone", 35),
                                ("new_window", 36),
                            ]
                        ],
                        {"help_text": "Link for the card.", "label": "Call to Action Link", "required": True},
                    ),
                    59: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 55), ("headline", 56), ("image", 57), ("cta_link", 58)]],
                        {},
                    ),
                    60: (
                        "wagtail.blocks.ListBlock",
                        (59,),
                        {
                            "help_text": "Minimum of 3 cards required. More than 3 will turn element into a carousel.",
                            "label": "Portrait Cards",
                            "min_num": 3,
                        },
                    ),
                    61: ("wagtail.blocks.StructBlock", [[("cards", 60)]], {}),
                    62: ("wagtail.blocks.CharBlock", (), {"label": "Name", "max_length": 50, "required": True}),
                    63: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic"], "label": "Description", "max_length": 500, "required": True},
                    ),
                    64: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Image should follow a 1:1 aspect ratio.", "label": "Image"},
                    ),
                    65: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 47), ("name", 62), ("description", 63), ("image", 64)]],
                        {},
                    ),
                    66: (
                        "wagtail.blocks.ListBlock",
                        (65,),
                        {"help_text": "3 cards required.", "label": "Spotlight Cards", "max_num": 3, "min_num": 3},
                    ),
                    67: ("wagtail.blocks.StructBlock", [[("cards", 66)]], {}),
                    68: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Please note that only URLs from allow-listed domains will work."},
                    ),
                    69: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Optional integer pixel value for custom iFrame height", "required": False},
                    ),
                    70: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("normal", "Normal"), ("full_width", "Full Width")]},
                    ),
                    71: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": 'Checking this will add "scrolling=no" to the iframe. Use this if your iframe is rendering an unnecessary scroll bar or whitespace below it.',
                            "required": False,
                        },
                    ),
                    72: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 68), ("height", 69), ("iframe_width", 70), ("disable_scroll", 71)]],
                        {},
                    ),
                    73: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The full value to animate, including any symbols, commas, decimals, or suffixes (e.g., $5.2M).",
                            "max_length": 5,
                            "required": True,
                        },
                    ),
                    74: ("wagtail.blocks.CharBlock", (), {"help_text": "Heading of the stat", "required": True}),
                    75: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Short description of the stat", "required": False},
                    ),
                    76: (
                        "wagtail.blocks.StructBlock",
                        [[("stat_number", 73), ("stat_heading", 74), ("stat_description", 75)]],
                        {},
                    ),
                    77: (
                        "wagtail.blocks.ListBlock",
                        (76,),
                        {
                            "default": [
                                {"stat_description": "", "stat_heading": "", "stat_number": ""},
                                {"stat_description": "", "stat_heading": "", "stat_number": ""},
                                {"stat_description": "", "stat_heading": "", "stat_number": ""},
                            ],
                            "help_text": "Add exactly 3 stats to appear in the Impact Numbers section",
                            "label": "Impact Stats",
                            "max_num": 3,
                            "min_num": 3,
                        },
                    ),
                    78: ("wagtail.blocks.StructBlock", [[("stats", 77)]], {}),
                    79: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional category for the card", "required": False},
                    ),
                    80: ("wagtail.blocks.CharBlock", (), {"help_text": "Title for the card", "required": True}),
                    81: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Optional description text", "required": False},
                    ),
                    82: (
                        "wagtail.blocks.StructBlock",
                        [[("category", 79), ("title", 80), ("text", 81), ("image", 3), ("link", 42)]],
                        {},
                    ),
                    83: (
                        "wagtail.blocks.StreamBlock",
                        [[("card", 82)]],
                        {"help_text": "Add between 1 and 3 cards.", "max_num": 3, "min_num": 1},
                    ),
                    84: ("wagtail.blocks.StructBlock", [[("cards", 83)]], {}),
                    85: (
                        "foundation_cms.blocks.link_block.OptionalLinkBlock",
                        (),
                        {
                            "help_text": "Optional link for the card.",
                            "label": "Call to Action Link",
                            "required": False,
                        },
                    ),
                    86: ("wagtail.blocks.StructBlock", [[("headline", 56), ("cta_link", 85)]], {}),
                    87: (
                        "wagtail.blocks.ListBlock",
                        (86,),
                        {
                            "default": [
                                {"cta_link": [], "headline": ""},
                                {"cta_link": [], "headline": ""},
                                {"cta_link": [], "headline": ""},
                            ],
                            "help_text": "3 cards required.",
                            "label": "Pillar Cards",
                            "max_num": 3,
                            "min_num": 3,
                        },
                    ),
                    88: ("wagtail.blocks.StructBlock", [[("cards", 87)]], {}),
                    89: ("wagtail.blocks.CharBlock", (), {"label": "Heading", "max_length": 50, "required": True}),
                    90: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Image for the card", "label": "Image"},
                    ),
                    91: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 7),
                                ("link_to", 28),
                                ("page", 29),
                                ("external_url", 30),
                                ("relative_url", 31),
                                ("anchor", 32),
                                ("email", 33),
                                ("file", 34),
                                ("phone", 35),
                                ("new_window", 36),
                                ("style", 53),
                            ]
                        ],
                        {"help_text": "Link button for the card.", "label": "Button", "required": False},
                    ),
                    92: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 89), ("description", 63), ("image", 90), ("button", 91)]],
                        {},
                    ),
                    93: ("wagtail.blocks.StructBlock", [[]], {}),
                    94: ("wagtail.blocks.CharBlock", (), {"help_text": "Title for the block", "required": True}),
                    95: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("shape", "Shape"), ("loop-line", "Loop Line")],
                            "help_text": "Select the style of the title",
                        },
                    ),
                    96: ("wagtail.blocks.StructBlock", [[("title", 94), ("style", 95)]], {}),
                    97: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["h4", "h5", "h6"], "help_text": "Callout box title", "required": True},
                    ),
                    98: ("wagtail.blocks.RichTextBlock", (), {"help_text": "Callout box content", "required": True}),
                    99: ("wagtail.blocks.StructBlock", [[("heading", 97), ("description", 98)]], {}),
                },
            ),
        ),
        migrations.AlterField(
            model_name="nothingpersonalarticlepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("rich_text", 0),
                    ("media", 6),
                    ("podcast_block", 9),
                    ("tabbed_content", 22),
                    ("two_column_container_block", 52),
                    ("link_button_block", 54),
                    ("portrait_card_set_block", 61),
                    ("spotlight_card_set_block", 67),
                    ("spacer_block", 46),
                    ("iframe_block", 72),
                    ("impact_numbers", 78),
                    ("newsletter_signup", 25),
                    ("timely_activations_cards", 84),
                    ("quote", 48),
                    ("list_block", 44),
                    ("video_block", 39),
                    ("pillar_card_set", 88),
                    ("featured_card_block", 92),
                    ("divider", 93),
                    ("title_block", 96),
                    ("callout", 99),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"template": "patterns/blocks/themes/default/rich_text_block.html"},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title/caption for this media", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("image", "Image"), ("video", "Video")],
                            "help_text": "Select the type of media to display",
                        },
                    ),
                    3: ("wagtail.images.blocks.ImageBlock", [], {}),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Log into Vimeo using 1Password and upload the desired video. Then select the video and click "...", "Video File Links", and select "(mp4, 1920 x 1080)". Copy and paste the link here.',
                            "max_length": 500,
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("portrait", "Portrait"), ("landscape", "Landscape"), ("square", "Square")],
                            "help_text": "Select the orientation of this media",
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("content", 2), ("image", 3), ("video_url", 4), ("orientation", 5)]],
                        {},
                    ),
                    7: ("wagtail.blocks.CharBlock", (), {}),
                    8: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Optional short description of the podcast", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 7), ("description", 8), ("simplecast_embed_code", 7)]],
                        {},
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title shown on the tab button", "required": True},
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Subtitle shown under the title on the tab", "required": False},
                    ),
                    12: ("wagtail.blocks.RichTextBlock", (), {}),
                    13: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    14: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("content", 2), ("image", 3), ("video_url", 4), ("orientation", 5)]],
                        {"required": False},
                    ),
                    16: ("foundation_cms.blocks.link_block.OptionalLinkBlock", (), {"required": False}),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 13), ("subtitle", 13), ("text", 14), ("media", 15), ("link", 16)]],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 7), ("image", 3), ("subtitle", 7), ("link", 16)]],
                        {},
                    ),
                    19: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 12), ("text_media", 17), ("tab_card_set", 18)]],
                        {"help_text": "Add one or more content blocks to the tab.", "min_num": 1, "required": True},
                    ),
                    20: ("wagtail.blocks.StructBlock", [[("title", 10), ("subtitle", 11), ("content", 19)]], {}),
                    21: ("wagtail.blocks.ListBlock", (20,), {"label": "Tabs", "max_num": 8, "min_num": 1}),
                    22: ("wagtail.blocks.StructBlock", [[("tabs", 21)]], {}),
                    23: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("top", "Top"), ("middle", "Middle"), ("bottom", "Bottom")],
                            "help_text": "Vertical alignment of the columns content",
                        },
                    ),
                    24: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("snippets.NewsletterSignup",),
                        {"max_num": 1},
                    ),
                    25: ("wagtail.blocks.StructBlock", [[("newsletter_signup", 24)]], {}),
                    26: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Log into Vimeo, select your desired video, and click 'Copy Link'",
                            "label": "Vimeo Video URL",
                            "required": True,
                        },
                    ),
                    27: ("wagtail.blocks.CharBlock", (), {"help_text": "Optional Caption Text", "required": False}),
                    28: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("external_url", "External URL"),
                                ("relative_url", "Relative URL"),
                                ("email", "Email"),
                                ("anchor", "Anchor"),
                                ("file", "File"),
                                ("phone", "Phone"),
                            ],
                            "label": "Link to",
                        },
                    ),
                    29: ("wagtail.blocks.PageChooserBlock", (), {"label": "Page", "required": False}),
                    30: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Enter a full URL including http:// or https://",
                            "label": "External URL",
                            "max_length": 300,
                            "required": False,
                        },
                    ),
                    31: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'A path relative to this domain. For example, "/foo/bar" or "?foo=bar".',
                            "label": "Relative URL",
                            "max_length": 300,
                            "required": False,
                            "validators": [foundation_cms.legacy_apps.wagtailpages.validators.RelativeURLValidator()],
                        },
                    ),
                    32: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'An id attribute of an element on the current page. For example, "#section-1"',
                            "label": "#",
                            "max_length": 300,
                            "required": False,
                            "validators": [foundation_cms.validators.AnchorLinkValidator()],
                        },
                    ),
                    33: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    34: ("wagtail.documents.blocks.DocumentChooserBlock", (), {"label": "File", "required": False}),
                    35: ("wagtail.blocks.CharBlock", (), {"label": "Phone", "max_length": 30, "required": False}),
                    36: ("wagtail.blocks.BooleanBlock", (), {"label": "Open in new window", "required": False}),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_to", 28),
                                ("page", 29),
                                ("external_url", 30),
                                ("relative_url", 31),
                                ("anchor", 32),
                                ("email", 33),
                                ("file", 34),
                                ("phone", 35),
                                ("new_window", 36),
                            ]
                        ],
                        {},
                    ),
                    38: (
                        "wagtail.blocks.ListBlock",
                        (37,),
                        {
                            "default": [],
                            "help_text": "Optional URL that this caption should link out to.",
                            "max_num": 1,
                            "min_num": 0,
                        },
                    ),
                    39: (
                        "wagtail.blocks.StructBlock",
                        [[("video_url", 26), ("caption", 27), ("caption_url", 38)]],
                        {},
                    ),
                    40: ("wagtail.blocks.CharBlock", (), {"help_text": "Heading displayed above the list"}),
                    41: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Description displayed above the list", "required": False},
                    ),
                    42: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 7),
                                ("link_to", 28),
                                ("page", 29),
                                ("external_url", 30),
                                ("relative_url", 31),
                                ("anchor", 32),
                                ("email", 33),
                                ("file", 34),
                                ("phone", 35),
                                ("new_window", 36),
                            ]
                        ],
                        {},
                    ),
                    43: ("wagtail.blocks.ListBlock", (42,), {"max_num": 4, "min_num": 1}),
                    44: ("wagtail.blocks.StructBlock", [[("title", 40), ("description", 41), ("items", 43)]], {}),
                    45: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("small", "Small"),
                                ("medium", "Medium"),
                                ("large", "Large"),
                                ("xlarge", "Extra Large"),
                            ],
                            "help_text": "Select the size of the spacer",
                        },
                    ),
                    46: ("wagtail.blocks.StructBlock", [[("size", 45)]], {}),
                    47: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    48: ("wagtail.blocks.StructBlock", [[("quote", 47), ("attribution", 13)]], {}),
                    49: ("wagtail.blocks.StructBlock", [[("title", 13), ("text", 14)]], {}),
                    50: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 12),
                                ("podcast", 9),
                                ("media", 6),
                                ("newsletter_signup", 25),
                                ("video", 39),
                                ("list", 44),
                                ("spacer", 46),
                                ("quote", 48),
                                ("text_social", 49),
                            ]
                        ],
                        {"label": "Left Column", "required": False},
                    ),
                    51: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 12),
                                ("podcast", 9),
                                ("media", 6),
                                ("newsletter_signup", 25),
                                ("video", 39),
                                ("list", 44),
                                ("spacer", 46),
                                ("quote", 48),
                                ("text_social", 49),
                            ]
                        ],
                        {"label": "Right Column", "required": False},
                    ),
                    52: (
                        "wagtail.blocks.StructBlock",
                        [[("vertical_alignment", 23), ("left_column", 50), ("right_column", 51)]],
                        {},
                    ),
                    53: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("btn-primary", "Primary"), ("btn-secondary", "Secondary")]},
                    ),
                    54: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 7),
                                ("link_to", 28),
                                ("page", 29),
                                ("external_url", 30),
                                ("relative_url", 31),
                                ("anchor", 32),
                                ("email", 33),
                                ("file", 34),
                                ("phone", 35),
                                ("new_window", 36),
                                ("style", 53),
                            ]
                        ],
                        {},
                    ),
                    55: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Appears above the headline.", "label": "Label", "required": False},
                    ),
                    56: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Appears as the main heading.", "label": "Headline", "required": False},
                    ),
                    57: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Optional Image for the card", "label": "Image"},
                    ),
                    58: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 7),
                                ("link_to", 28),
                                ("page", 29),
                                ("external_url", 30),
                                ("relative_url", 31),
                                ("anchor", 32),
                                ("email", 33),
                                ("file", 34),
                                ("phone", 35),
                                ("new_window", 36),
                            ]
                        ],
                        {"help_text": "Link for the card.", "label": "Call to Action Link", "required": True},
                    ),
                    59: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 55), ("headline", 56), ("image", 57), ("cta_link", 58)]],
                        {},
                    ),
                    60: (
                        "wagtail.blocks.ListBlock",
                        (59,),
                        {
                            "help_text": "Minimum of 3 cards required. More than 3 will turn element into a carousel.",
                            "label": "Portrait Cards",
                            "min_num": 3,
                        },
                    ),
                    61: ("wagtail.blocks.StructBlock", [[("cards", 60)]], {}),
                    62: ("wagtail.blocks.CharBlock", (), {"label": "Name", "max_length": 50, "required": True}),
                    63: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic"], "label": "Description", "max_length": 500, "required": True},
                    ),
                    64: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Image should follow a 1:1 aspect ratio.", "label": "Image"},
                    ),
                    65: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 47), ("name", 62), ("description", 63), ("image", 64)]],
                        {},
                    ),
                    66: (
                        "wagtail.blocks.ListBlock",
                        (65,),
                        {"help_text": "3 cards required.", "label": "Spotlight Cards", "max_num": 3, "min_num": 3},
                    ),
                    67: ("wagtail.blocks.StructBlock", [[("cards", 66)]], {}),
                    68: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Please note that only URLs from allow-listed domains will work."},
                    ),
                    69: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Optional integer pixel value for custom iFrame height", "required": False},
                    ),
                    70: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("normal", "Normal"), ("full_width", "Full Width")]},
                    ),
                    71: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": 'Checking this will add "scrolling=no" to the iframe. Use this if your iframe is rendering an unnecessary scroll bar or whitespace below it.',
                            "required": False,
                        },
                    ),
                    72: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 68), ("height", 69), ("iframe_width", 70), ("disable_scroll", 71)]],
                        {},
                    ),
                    73: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The full value to animate, including any symbols, commas, decimals, or suffixes (e.g., $5.2M).",
                            "max_length": 5,
                            "required": True,
                        },
                    ),
                    74: ("wagtail.blocks.CharBlock", (), {"help_text": "Heading of the stat", "required": True}),
                    75: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Short description of the stat", "required": False},
                    ),
                    76: (
                        "wagtail.blocks.StructBlock",
                        [[("stat_number", 73), ("stat_heading", 74), ("stat_description", 75)]],
                        {},
                    ),
                    77: (
                        "wagtail.blocks.ListBlock",
                        (76,),
                        {
                            "default": [
                                {"stat_description": "", "stat_heading": "", "stat_number": ""},
                                {"stat_description": "", "stat_heading": "", "stat_number": ""},
                                {"stat_description": "", "stat_heading": "", "stat_number": ""},
                            ],
                            "help_text": "Add exactly 3 stats to appear in the Impact Numbers section",
                            "label": "Impact Stats",
                            "max_num": 3,
                            "min_num": 3,
                        },
                    ),
                    78: ("wagtail.blocks.StructBlock", [[("stats", 77)]], {}),
                    79: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional category for the card", "required": False},
                    ),
                    80: ("wagtail.blocks.CharBlock", (), {"help_text": "Title for the card", "required": True}),
                    81: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Optional description text", "required": False},
                    ),
                    82: (
                        "wagtail.blocks.StructBlock",
                        [[("category", 79), ("title", 80), ("text", 81), ("image", 3), ("link", 42)]],
                        {},
                    ),
                    83: (
                        "wagtail.blocks.StreamBlock",
                        [[("card", 82)]],
                        {"help_text": "Add between 1 and 3 cards.", "max_num": 3, "min_num": 1},
                    ),
                    84: ("wagtail.blocks.StructBlock", [[("cards", 83)]], {}),
                    85: (
                        "foundation_cms.blocks.link_block.OptionalLinkBlock",
                        (),
                        {
                            "help_text": "Optional link for the card.",
                            "label": "Call to Action Link",
                            "required": False,
                        },
                    ),
                    86: ("wagtail.blocks.StructBlock", [[("headline", 56), ("cta_link", 85)]], {}),
                    87: (
                        "wagtail.blocks.ListBlock",
                        (86,),
                        {
                            "default": [
                                {"cta_link": [], "headline": ""},
                                {"cta_link": [], "headline": ""},
                                {"cta_link": [], "headline": ""},
                            ],
                            "help_text": "3 cards required.",
                            "label": "Pillar Cards",
                            "max_num": 3,
                            "min_num": 3,
                        },
                    ),
                    88: ("wagtail.blocks.StructBlock", [[("cards", 87)]], {}),
                    89: ("wagtail.blocks.CharBlock", (), {"label": "Heading", "max_length": 50, "required": True}),
                    90: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Image for the card", "label": "Image"},
                    ),
                    91: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 7),
                                ("link_to", 28),
                                ("page", 29),
                                ("external_url", 30),
                                ("relative_url", 31),
                                ("anchor", 32),
                                ("email", 33),
                                ("file", 34),
                                ("phone", 35),
                                ("new_window", 36),
                                ("style", 53),
                            ]
                        ],
                        {"help_text": "Link button for the card.", "label": "Button", "required": False},
                    ),
                    92: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 89), ("description", 63), ("image", 90), ("button", 91)]],
                        {},
                    ),
                    93: ("wagtail.blocks.StructBlock", [[]], {}),
                    94: ("wagtail.blocks.CharBlock", (), {"help_text": "Title for the block", "required": True}),
                    95: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("shape", "Shape"), ("loop-line", "Loop Line")],
                            "help_text": "Select the style of the title",
                        },
                    ),
                    96: ("wagtail.blocks.StructBlock", [[("title", 94), ("style", 95)]], {}),
                    97: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["h4", "h5", "h6"], "help_text": "Callout box title", "required": True},
                    ),
                    98: ("wagtail.blocks.RichTextBlock", (), {"help_text": "Callout box content", "required": True}),
                    99: ("wagtail.blocks.StructBlock", [[("heading", 97), ("description", 98)]], {}),
                },
            ),
        ),
        migrations.AlterField(
            model_name="nothingpersonalhomepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("two_column_container_block", 41),
                    ("narrow_text_media_block", 44),
                    ("product_review_carousel_block", 52),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("top", "Top"), ("middle", "Middle"), ("bottom", "Bottom")],
                            "help_text": "Vertical alignment of the columns content",
                        },
                    ),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: ("wagtail.blocks.CharBlock", (), {}),
                    3: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Optional short description of the podcast", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 2), ("description", 3), ("simplecast_embed_code", 2)]],
                        {},
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title/caption for this media", "required": False},
                    ),
                    6: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("image", "Image"), ("video", "Video")],
                            "help_text": "Select the type of media to display",
                        },
                    ),
                    7: ("wagtail.images.blocks.ImageBlock", [], {}),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Log into Vimeo using 1Password and upload the desired video. Then select the video and click "...", "Video File Links", and select "(mp4, 1920 x 1080)". Copy and paste the link here.',
                            "max_length": 500,
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("portrait", "Portrait"), ("landscape", "Landscape"), ("square", "Square")],
                            "help_text": "Select the orientation of this media",
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 5), ("content", 6), ("image", 7), ("video_url", 8), ("orientation", 9)]],
                        {},
                    ),
                    11: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("snippets.NewsletterSignup",),
                        {"max_num": 1},
                    ),
                    12: ("wagtail.blocks.StructBlock", [[("newsletter_signup", 11)]], {}),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Log into Vimeo, select your desired video, and click 'Copy Link'",
                            "label": "Vimeo Video URL",
                            "required": True,
                        },
                    ),
                    14: ("wagtail.blocks.CharBlock", (), {"help_text": "Optional Caption Text", "required": False}),
                    15: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("external_url", "External URL"),
                                ("relative_url", "Relative URL"),
                                ("email", "Email"),
                                ("anchor", "Anchor"),
                                ("file", "File"),
                                ("phone", "Phone"),
                            ],
                            "label": "Link to",
                        },
                    ),
                    16: ("wagtail.blocks.PageChooserBlock", (), {"label": "Page", "required": False}),
                    17: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Enter a full URL including http:// or https://",
                            "label": "External URL",
                            "max_length": 300,
                            "required": False,
                        },
                    ),
                    18: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'A path relative to this domain. For example, "/foo/bar" or "?foo=bar".',
                            "label": "Relative URL",
                            "max_length": 300,
                            "required": False,
                            "validators": [foundation_cms.legacy_apps.wagtailpages.validators.RelativeURLValidator()],
                        },
                    ),
                    19: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'An id attribute of an element on the current page. For example, "#section-1"',
                            "label": "#",
                            "max_length": 300,
                            "required": False,
                            "validators": [foundation_cms.validators.AnchorLinkValidator()],
                        },
                    ),
                    20: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    21: ("wagtail.documents.blocks.DocumentChooserBlock", (), {"label": "File", "required": False}),
                    22: ("wagtail.blocks.CharBlock", (), {"label": "Phone", "max_length": 30, "required": False}),
                    23: ("wagtail.blocks.BooleanBlock", (), {"label": "Open in new window", "required": False}),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_to", 15),
                                ("page", 16),
                                ("external_url", 17),
                                ("relative_url", 18),
                                ("anchor", 19),
                                ("email", 20),
                                ("file", 21),
                                ("phone", 22),
                                ("new_window", 23),
                            ]
                        ],
                        {},
                    ),
                    25: (
                        "wagtail.blocks.ListBlock",
                        (24,),
                        {
                            "default": [],
                            "help_text": "Optional URL that this caption should link out to.",
                            "max_num": 1,
                            "min_num": 0,
                        },
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [[("video_url", 13), ("caption", 14), ("caption_url", 25)]],
                        {},
                    ),
                    27: ("wagtail.blocks.CharBlock", (), {"help_text": "Heading displayed above the list"}),
                    28: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Description displayed above the list", "required": False},
                    ),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 2),
                                ("link_to", 15),
                                ("page", 16),
                                ("external_url", 17),
                                ("relative_url", 18),
                                ("anchor", 19),
                                ("email", 20),
                                ("file", 21),
                                ("phone", 22),
                                ("new_window", 23),
                            ]
                        ],
                        {},
                    ),
                    30: ("wagtail.blocks.ListBlock", (29,), {"max_num": 4, "min_num": 1}),
                    31: ("wagtail.blocks.StructBlock", [[("title", 27), ("description", 28), ("items", 30)]], {}),
                    32: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("small", "Small"),
                                ("medium", "Medium"),
                                ("large", "Large"),
                                ("xlarge", "Extra Large"),
                            ],
                            "help_text": "Select the size of the spacer",
                        },
                    ),
                    33: ("wagtail.blocks.StructBlock", [[("size", 32)]], {}),
                    34: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    35: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    36: ("wagtail.blocks.StructBlock", [[("quote", 34), ("attribution", 35)]], {}),
                    37: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    38: ("wagtail.blocks.StructBlock", [[("title", 35), ("text", 37)]], {}),
                    39: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 1),
                                ("podcast", 4),
                                ("media", 10),
                                ("newsletter_signup", 12),
                                ("video", 26),
                                ("list", 31),
                                ("spacer", 33),
                                ("quote", 36),
                                ("text_social", 38),
                            ]
                        ],
                        {"label": "Left Column", "required": False},
                    ),
                    40: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 1),
                                ("podcast", 4),
                                ("media", 10),
                                ("newsletter_signup", 12),
                                ("video", 26),
                                ("list", 31),
                                ("spacer", 33),
                                ("quote", 36),
                                ("text_social", 38),
                            ]
                        ],
                        {"label": "Right Column", "required": False},
                    ),
                    41: (
                        "wagtail.blocks.StructBlock",
                        [[("vertical_alignment", 0), ("left_column", 39), ("right_column", 40)]],
                        {},
                    ),
                    42: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 5), ("content", 6), ("image", 7), ("video_url", 8), ("orientation", 9)]],
                        {"required": False},
                    ),
                    43: ("foundation_cms.blocks.link_block.OptionalLinkBlock", (), {"required": False}),
                    44: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 35), ("subtitle", 35), ("text", 37), ("media", 42), ("link", 43)]],
                        {},
                    ),
                    45: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional subtitle for the contianer", "required": False},
                    ),
                    46: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional title for the container", "required": False},
                    ),
                    47: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Optional description text for the container", "required": False},
                    ),
                    48: (
                        "foundation_cms.blocks.link_block.OptionalLinkBlock",
                        (),
                        {"help_text": "Optional link for the container.", "label": "Link", "required": False},
                    ),
                    49: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "help_text": "Select a Product Review",
                            "label": "Product review selector",
                            "page_type": ["nothing_personal.NothingPersonalProductReviewPage"],
                        },
                    ),
                    50: ("wagtail.blocks.StructBlock", [[("product_review", 49)]], {}),
                    51: (
                        "wagtail.blocks.StreamBlock",
                        [[("product_review_card", 50)]],
                        {"help_text": "Maximum of 10 per carousel.", "max_num": 10},
                    ),
                    52: (
                        "wagtail.blocks.StructBlock",
                        [[("subtitle", 45), ("title", 46), ("text", 47), ("cta_link", 48), ("cards", 51)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="nothingpersonalpodcastpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("rich_text", 0),
                    ("media", 6),
                    ("podcast_block", 9),
                    ("tabbed_content", 22),
                    ("two_column_container_block", 52),
                    ("link_button_block", 54),
                    ("portrait_card_set_block", 61),
                    ("spotlight_card_set_block", 67),
                    ("spacer_block", 46),
                    ("iframe_block", 72),
                    ("impact_numbers", 78),
                    ("newsletter_signup", 25),
                    ("timely_activations_cards", 84),
                    ("quote", 48),
                    ("list_block", 44),
                    ("video_block", 39),
                    ("pillar_card_set", 88),
                    ("featured_card_block", 92),
                    ("divider", 93),
                    ("title_block", 96),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"template": "patterns/blocks/themes/default/rich_text_block.html"},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title/caption for this media", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("image", "Image"), ("video", "Video")],
                            "help_text": "Select the type of media to display",
                        },
                    ),
                    3: ("wagtail.images.blocks.ImageBlock", [], {}),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Log into Vimeo using 1Password and upload the desired video. Then select the video and click "...", "Video File Links", and select "(mp4, 1920 x 1080)". Copy and paste the link here.',
                            "max_length": 500,
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("portrait", "Portrait"), ("landscape", "Landscape"), ("square", "Square")],
                            "help_text": "Select the orientation of this media",
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("content", 2), ("image", 3), ("video_url", 4), ("orientation", 5)]],
                        {},
                    ),
                    7: ("wagtail.blocks.CharBlock", (), {}),
                    8: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Optional short description of the podcast", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 7), ("description", 8), ("simplecast_embed_code", 7)]],
                        {},
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title shown on the tab button", "required": True},
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Subtitle shown under the title on the tab", "required": False},
                    ),
                    12: ("wagtail.blocks.RichTextBlock", (), {}),
                    13: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    14: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("content", 2), ("image", 3), ("video_url", 4), ("orientation", 5)]],
                        {"required": False},
                    ),
                    16: ("foundation_cms.blocks.link_block.OptionalLinkBlock", (), {"required": False}),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 13), ("subtitle", 13), ("text", 14), ("media", 15), ("link", 16)]],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 7), ("image", 3), ("subtitle", 7), ("link", 16)]],
                        {},
                    ),
                    19: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 12), ("text_media", 17), ("tab_card_set", 18)]],
                        {"help_text": "Add one or more content blocks to the tab.", "min_num": 1, "required": True},
                    ),
                    20: ("wagtail.blocks.StructBlock", [[("title", 10), ("subtitle", 11), ("content", 19)]], {}),
                    21: ("wagtail.blocks.ListBlock", (20,), {"label": "Tabs", "max_num": 8, "min_num": 1}),
                    22: ("wagtail.blocks.StructBlock", [[("tabs", 21)]], {}),
                    23: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("top", "Top"), ("middle", "Middle"), ("bottom", "Bottom")],
                            "help_text": "Vertical alignment of the columns content",
                        },
                    ),
                    24: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("snippets.NewsletterSignup",),
                        {"max_num": 1},
                    ),
                    25: ("wagtail.blocks.StructBlock", [[("newsletter_signup", 24)]], {}),
                    26: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Log into Vimeo, select your desired video, and click 'Copy Link'",
                            "label": "Vimeo Video URL",
                            "required": True,
                        },
                    ),
                    27: ("wagtail.blocks.CharBlock", (), {"help_text": "Optional Caption Text", "required": False}),
                    28: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("external_url", "External URL"),
                                ("relative_url", "Relative URL"),
                                ("email", "Email"),
                                ("anchor", "Anchor"),
                                ("file", "File"),
                                ("phone", "Phone"),
                            ],
                            "label": "Link to",
                        },
                    ),
                    29: ("wagtail.blocks.PageChooserBlock", (), {"label": "Page", "required": False}),
                    30: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Enter a full URL including http:// or https://",
                            "label": "External URL",
                            "max_length": 300,
                            "required": False,
                        },
                    ),
                    31: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'A path relative to this domain. For example, "/foo/bar" or "?foo=bar".',
                            "label": "Relative URL",
                            "max_length": 300,
                            "required": False,
                            "validators": [foundation_cms.legacy_apps.wagtailpages.validators.RelativeURLValidator()],
                        },
                    ),
                    32: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'An id attribute of an element on the current page. For example, "#section-1"',
                            "label": "#",
                            "max_length": 300,
                            "required": False,
                            "validators": [foundation_cms.validators.AnchorLinkValidator()],
                        },
                    ),
                    33: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    34: ("wagtail.documents.blocks.DocumentChooserBlock", (), {"label": "File", "required": False}),
                    35: ("wagtail.blocks.CharBlock", (), {"label": "Phone", "max_length": 30, "required": False}),
                    36: ("wagtail.blocks.BooleanBlock", (), {"label": "Open in new window", "required": False}),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_to", 28),
                                ("page", 29),
                                ("external_url", 30),
                                ("relative_url", 31),
                                ("anchor", 32),
                                ("email", 33),
                                ("file", 34),
                                ("phone", 35),
                                ("new_window", 36),
                            ]
                        ],
                        {},
                    ),
                    38: (
                        "wagtail.blocks.ListBlock",
                        (37,),
                        {
                            "default": [],
                            "help_text": "Optional URL that this caption should link out to.",
                            "max_num": 1,
                            "min_num": 0,
                        },
                    ),
                    39: (
                        "wagtail.blocks.StructBlock",
                        [[("video_url", 26), ("caption", 27), ("caption_url", 38)]],
                        {},
                    ),
                    40: ("wagtail.blocks.CharBlock", (), {"help_text": "Heading displayed above the list"}),
                    41: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Description displayed above the list", "required": False},
                    ),
                    42: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 7),
                                ("link_to", 28),
                                ("page", 29),
                                ("external_url", 30),
                                ("relative_url", 31),
                                ("anchor", 32),
                                ("email", 33),
                                ("file", 34),
                                ("phone", 35),
                                ("new_window", 36),
                            ]
                        ],
                        {},
                    ),
                    43: ("wagtail.blocks.ListBlock", (42,), {"max_num": 4, "min_num": 1}),
                    44: ("wagtail.blocks.StructBlock", [[("title", 40), ("description", 41), ("items", 43)]], {}),
                    45: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("small", "Small"),
                                ("medium", "Medium"),
                                ("large", "Large"),
                                ("xlarge", "Extra Large"),
                            ],
                            "help_text": "Select the size of the spacer",
                        },
                    ),
                    46: ("wagtail.blocks.StructBlock", [[("size", 45)]], {}),
                    47: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    48: ("wagtail.blocks.StructBlock", [[("quote", 47), ("attribution", 13)]], {}),
                    49: ("wagtail.blocks.StructBlock", [[("title", 13), ("text", 14)]], {}),
                    50: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 12),
                                ("podcast", 9),
                                ("media", 6),
                                ("newsletter_signup", 25),
                                ("video", 39),
                                ("list", 44),
                                ("spacer", 46),
                                ("quote", 48),
                                ("text_social", 49),
                            ]
                        ],
                        {"label": "Left Column", "required": False},
                    ),
                    51: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 12),
                                ("podcast", 9),
                                ("media", 6),
                                ("newsletter_signup", 25),
                                ("video", 39),
                                ("list", 44),
                                ("spacer", 46),
                                ("quote", 48),
                                ("text_social", 49),
                            ]
                        ],
                        {"label": "Right Column", "required": False},
                    ),
                    52: (
                        "wagtail.blocks.StructBlock",
                        [[("vertical_alignment", 23), ("left_column", 50), ("right_column", 51)]],
                        {},
                    ),
                    53: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("btn-primary", "Primary"), ("btn-secondary", "Secondary")]},
                    ),
                    54: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 7),
                                ("link_to", 28),
                                ("page", 29),
                                ("external_url", 30),
                                ("relative_url", 31),
                                ("anchor", 32),
                                ("email", 33),
                                ("file", 34),
                                ("phone", 35),
                                ("new_window", 36),
                                ("style", 53),
                            ]
                        ],
                        {},
                    ),
                    55: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Appears above the headline.", "label": "Label", "required": False},
                    ),
                    56: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Appears as the main heading.", "label": "Headline", "required": False},
                    ),
                    57: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Optional Image for the card", "label": "Image"},
                    ),
                    58: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 7),
                                ("link_to", 28),
                                ("page", 29),
                                ("external_url", 30),
                                ("relative_url", 31),
                                ("anchor", 32),
                                ("email", 33),
                                ("file", 34),
                                ("phone", 35),
                                ("new_window", 36),
                            ]
                        ],
                        {"help_text": "Link for the card.", "label": "Call to Action Link", "required": True},
                    ),
                    59: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 55), ("headline", 56), ("image", 57), ("cta_link", 58)]],
                        {},
                    ),
                    60: (
                        "wagtail.blocks.ListBlock",
                        (59,),
                        {
                            "help_text": "Minimum of 3 cards required. More than 3 will turn element into a carousel.",
                            "label": "Portrait Cards",
                            "min_num": 3,
                        },
                    ),
                    61: ("wagtail.blocks.StructBlock", [[("cards", 60)]], {}),
                    62: ("wagtail.blocks.CharBlock", (), {"label": "Name", "max_length": 50, "required": True}),
                    63: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic"], "label": "Description", "max_length": 500, "required": True},
                    ),
                    64: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Image should follow a 1:1 aspect ratio.", "label": "Image"},
                    ),
                    65: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 47), ("name", 62), ("description", 63), ("image", 64)]],
                        {},
                    ),
                    66: (
                        "wagtail.blocks.ListBlock",
                        (65,),
                        {"help_text": "3 cards required.", "label": "Spotlight Cards", "max_num": 3, "min_num": 3},
                    ),
                    67: ("wagtail.blocks.StructBlock", [[("cards", 66)]], {}),
                    68: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Please note that only URLs from allow-listed domains will work."},
                    ),
                    69: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Optional integer pixel value for custom iFrame height", "required": False},
                    ),
                    70: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("normal", "Normal"), ("full_width", "Full Width")]},
                    ),
                    71: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": 'Checking this will add "scrolling=no" to the iframe. Use this if your iframe is rendering an unnecessary scroll bar or whitespace below it.',
                            "required": False,
                        },
                    ),
                    72: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 68), ("height", 69), ("iframe_width", 70), ("disable_scroll", 71)]],
                        {},
                    ),
                    73: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The full value to animate, including any symbols, commas, decimals, or suffixes (e.g., $5.2M).",
                            "max_length": 5,
                            "required": True,
                        },
                    ),
                    74: ("wagtail.blocks.CharBlock", (), {"help_text": "Heading of the stat", "required": True}),
                    75: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Short description of the stat", "required": False},
                    ),
                    76: (
                        "wagtail.blocks.StructBlock",
                        [[("stat_number", 73), ("stat_heading", 74), ("stat_description", 75)]],
                        {},
                    ),
                    77: (
                        "wagtail.blocks.ListBlock",
                        (76,),
                        {
                            "default": [
                                {"stat_description": "", "stat_heading": "", "stat_number": ""},
                                {"stat_description": "", "stat_heading": "", "stat_number": ""},
                                {"stat_description": "", "stat_heading": "", "stat_number": ""},
                            ],
                            "help_text": "Add exactly 3 stats to appear in the Impact Numbers section",
                            "label": "Impact Stats",
                            "max_num": 3,
                            "min_num": 3,
                        },
                    ),
                    78: ("wagtail.blocks.StructBlock", [[("stats", 77)]], {}),
                    79: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional category for the card", "required": False},
                    ),
                    80: ("wagtail.blocks.CharBlock", (), {"help_text": "Title for the card", "required": True}),
                    81: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Optional description text", "required": False},
                    ),
                    82: (
                        "wagtail.blocks.StructBlock",
                        [[("category", 79), ("title", 80), ("text", 81), ("image", 3), ("link", 42)]],
                        {},
                    ),
                    83: (
                        "wagtail.blocks.StreamBlock",
                        [[("card", 82)]],
                        {"help_text": "Add between 1 and 3 cards.", "max_num": 3, "min_num": 1},
                    ),
                    84: ("wagtail.blocks.StructBlock", [[("cards", 83)]], {}),
                    85: (
                        "foundation_cms.blocks.link_block.OptionalLinkBlock",
                        (),
                        {
                            "help_text": "Optional link for the card.",
                            "label": "Call to Action Link",
                            "required": False,
                        },
                    ),
                    86: ("wagtail.blocks.StructBlock", [[("headline", 56), ("cta_link", 85)]], {}),
                    87: (
                        "wagtail.blocks.ListBlock",
                        (86,),
                        {
                            "default": [
                                {"cta_link": [], "headline": ""},
                                {"cta_link": [], "headline": ""},
                                {"cta_link": [], "headline": ""},
                            ],
                            "help_text": "3 cards required.",
                            "label": "Pillar Cards",
                            "max_num": 3,
                            "min_num": 3,
                        },
                    ),
                    88: ("wagtail.blocks.StructBlock", [[("cards", 87)]], {}),
                    89: ("wagtail.blocks.CharBlock", (), {"label": "Heading", "max_length": 50, "required": True}),
                    90: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Image for the card", "label": "Image"},
                    ),
                    91: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 7),
                                ("link_to", 28),
                                ("page", 29),
                                ("external_url", 30),
                                ("relative_url", 31),
                                ("anchor", 32),
                                ("email", 33),
                                ("file", 34),
                                ("phone", 35),
                                ("new_window", 36),
                                ("style", 53),
                            ]
                        ],
                        {"help_text": "Link button for the card.", "label": "Button", "required": False},
                    ),
                    92: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 89), ("description", 63), ("image", 90), ("button", 91)]],
                        {},
                    ),
                    93: ("wagtail.blocks.StructBlock", [[]], {}),
                    94: ("wagtail.blocks.CharBlock", (), {"help_text": "Title for the block", "required": True}),
                    95: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("shape", "Shape"), ("loop-line", "Loop Line")],
                            "help_text": "Select the style of the title",
                        },
                    ),
                    96: ("wagtail.blocks.StructBlock", [[("title", 94), ("style", 95)]], {}),
                },
            ),
        ),
    ]
