# Generated by Django 4.2.20 on 2025-10-08 18:46

import wagtail.fields
from django.db import migrations

import foundation_cms.legacy_apps.wagtailpages.validators
import foundation_cms.validators


class Migration(migrations.Migration):

    dependencies = [
        ("nothing_personal", "0024_alter_nothingpersonalhomepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nothingpersonalhomepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("two_column_container_block", 39), ("text_media_block", 46), ("product_review_carousel_block", 55)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("top", "Top"), ("middle", "Middle"), ("bottom", "Bottom")],
                            "help_text": "Vertical alignment of the columns content",
                        },
                    ),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: ("wagtail.blocks.CharBlock", (), {}),
                    3: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Optional short description of the podcast", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 2), ("description", 3), ("simplecast_embed_code", 2)]],
                        {},
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title/caption for this image", "required": False},
                    ),
                    6: ("wagtail.images.blocks.ImageBlock", [], {}),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("portrait", "Portrait"), ("landscape", "Landscape"), ("square", "Square")],
                            "help_text": "Select the orientation of this image",
                        },
                    ),
                    8: ("wagtail.blocks.StructBlock", [[("title", 5), ("image", 6), ("orientation", 7)]], {}),
                    9: ("wagtail.snippets.blocks.SnippetChooserBlock", ("snippets.NewsletterSignup",), {"max_num": 1}),
                    10: ("wagtail.blocks.StructBlock", [[("newsletter_signup", 9)]], {}),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Log into Vimeo, select your desired video, and click 'Copy Link'",
                            "label": "Vimeo Video URL",
                            "required": True,
                        },
                    ),
                    12: ("wagtail.blocks.CharBlock", (), {"help_text": "Optional Caption Text", "required": False}),
                    13: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("external_url", "External URL"),
                                ("relative_url", "Relative URL"),
                                ("email", "Email"),
                                ("anchor", "Anchor"),
                                ("file", "File"),
                                ("phone", "Phone"),
                            ],
                            "label": "Link to",
                        },
                    ),
                    14: ("wagtail.blocks.PageChooserBlock", (), {"label": "Page", "required": False}),
                    15: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Enter a full URL including http:// or https://",
                            "label": "External URL",
                            "max_length": 300,
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'A path relative to this domain. For example, "/foo/bar" or "?foo=bar".',
                            "label": "Relative URL",
                            "max_length": 300,
                            "required": False,
                            "validators": [foundation_cms.legacy_apps.wagtailpages.validators.RelativeURLValidator()],
                        },
                    ),
                    17: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'An id attribute of an element on the current page. For example, "#section-1"',
                            "label": "#",
                            "max_length": 300,
                            "required": False,
                            "validators": [foundation_cms.validators.AnchorLinkValidator()],
                        },
                    ),
                    18: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    19: ("wagtail.documents.blocks.DocumentChooserBlock", (), {"label": "File", "required": False}),
                    20: ("wagtail.blocks.CharBlock", (), {"label": "Phone", "max_length": 30, "required": False}),
                    21: ("wagtail.blocks.BooleanBlock", (), {"label": "Open in new window", "required": False}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_to", 13),
                                ("page", 14),
                                ("external_url", 15),
                                ("relative_url", 16),
                                ("anchor", 17),
                                ("email", 18),
                                ("file", 19),
                                ("phone", 20),
                                ("new_window", 21),
                            ]
                        ],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.ListBlock",
                        (22,),
                        {
                            "default": [],
                            "help_text": "Optional URL that this caption should link out to.",
                            "max_num": 1,
                            "min_num": 0,
                        },
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [[("video_url", 11), ("caption", 12), ("caption_url", 23)]],
                        {},
                    ),
                    25: ("wagtail.blocks.CharBlock", (), {"help_text": "Heading displayed above the list"}),
                    26: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Description displayed above the list", "required": False},
                    ),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 2),
                                ("link_to", 13),
                                ("page", 14),
                                ("external_url", 15),
                                ("relative_url", 16),
                                ("anchor", 17),
                                ("email", 18),
                                ("file", 19),
                                ("phone", 20),
                                ("new_window", 21),
                            ]
                        ],
                        {},
                    ),
                    28: ("wagtail.blocks.ListBlock", (27,), {"max_num": 4, "min_num": 1}),
                    29: ("wagtail.blocks.StructBlock", [[("title", 25), ("description", 26), ("items", 28)]], {}),
                    30: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("small", "Small"),
                                ("medium", "Medium"),
                                ("large", "Large"),
                                ("xlarge", "Extra Large"),
                            ],
                            "help_text": "Select the size of the spacer",
                        },
                    ),
                    31: ("wagtail.blocks.StructBlock", [[("size", 30)]], {}),
                    32: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    33: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    34: ("wagtail.blocks.StructBlock", [[("quote", 32), ("attribution", 33)]], {}),
                    35: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    36: ("wagtail.blocks.StructBlock", [[("title", 33), ("text", 35)]], {}),
                    37: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 1),
                                ("podcast", 4),
                                ("image", 8),
                                ("newsletter_signup", 10),
                                ("video", 24),
                                ("list", 29),
                                ("spacer", 31),
                                ("quote", 34),
                                ("text_social", 36),
                            ]
                        ],
                        {"label": "Left Column", "required": False},
                    ),
                    38: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 1),
                                ("podcast", 4),
                                ("image", 8),
                                ("newsletter_signup", 10),
                                ("video", 24),
                                ("list", 29),
                                ("spacer", 31),
                                ("quote", 34),
                                ("text_social", 36),
                            ]
                        ],
                        {"label": "Right Column", "required": False},
                    ),
                    39: (
                        "wagtail.blocks.StructBlock",
                        [[("vertical_alignment", 0), ("left_column", 37), ("right_column", 38)]],
                        {},
                    ),
                    40: ("foundation_cms.blocks.link_block.OptionalLinkBlock", (), {"required": False}),
                    41: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title/caption for this media", "required": False},
                    ),
                    42: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("image", "Image"), ("video", "Video")],
                            "help_text": "Select the type of media to display",
                        },
                    ),
                    43: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Log into Vimeo using 1Password and upload the desired video. Then select the video and click "...", "Video File Links", and select "(mp4, 1920 x 1080)". Copy and paste the link here.',
                            "max_length": 500,
                            "required": False,
                        },
                    ),
                    44: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("portrait", "Portrait"), ("landscape", "Landscape"), ("square", "Square")],
                            "help_text": "Select the orientation of this media",
                        },
                    ),
                    45: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 41), ("content", 42), ("image", 6), ("video_url", 43), ("orientation", 44)]],
                        {"required": False},
                    ),
                    46: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 33), ("subtitle", 33), ("text", 35), ("link", 40), ("media", 45)]],
                        {},
                    ),
                    47: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional subtitle for the contianer", "required": False},
                    ),
                    48: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional title for the container", "required": False},
                    ),
                    49: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Optional description text for the container", "required": False},
                    ),
                    50: (
                        "foundation_cms.blocks.link_block.OptionalLinkBlock",
                        (),
                        {"help_text": "Optional link for the container.", "label": "Link", "required": False},
                    ),
                    51: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "help_text": "Select a Product Review",
                            "label": "Product review selector",
                            "page_type": ["nothing_personal.NothingPersonalProductReviewPage"],
                        },
                    ),
                    52: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("square", "Square"), ("portrait", "Portrait")],
                            "help_text": "Select the orientation for the product review card.",
                            "label": "Card Orientation",
                        },
                    ),
                    53: ("wagtail.blocks.StructBlock", [[("product_review", 51), ("orientation", 52)]], {}),
                    54: (
                        "wagtail.blocks.StreamBlock",
                        [[("product_review_card", 53)]],
                        {"help_text": "Maximum of 10 per carousel.", "max_num": 10},
                    ),
                    55: (
                        "wagtail.blocks.StructBlock",
                        [[("subtitle", 47), ("title", 48), ("text", 49), ("cta_link", 50), ("cards", 54)]],
                        {},
                    ),
                },
            ),
        ),
    ]
