# Generated by Django 4.2.20 on 2025-10-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nothing_personal", "0025_alter_nothingpersonalhomepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nothingpersonalpodcastpage",
            name="hero_description",
            field=models.CharField(
                blank=True, help_text="Brief description of the hero (max 120 characters)", max_length=120
            ),
        ),
    ]
