# Generated by Django 4.2.20 on 2025-10-09 17:55

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nothing_personal", "0026_alter_nothingpersonalpodcastpage_hero_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nothingpersonalproductreviewpage",
            name="research",
        ),
        migrations.AddField(
            model_name="nothingpersonalproductreviewpage",
            name="byline",
            field=models.CharField(blank=True, help_text="Byline", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="nothingpersonalproductreviewpage",
            name="hours_tested",
            field=models.CharField(
                blank=True, help_text="Number of hours tested (e.g. '20')", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="nothingpersonalproductreviewpage",
            name="type_of_testing",
            field=models.CharField(blank=True, help_text="Type of testing", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="nothingpersonalproductreviewpage",
            name="who_am_i",
            field=wagtail.fields.RichTextField(blank=True, help_text="Who am I? (rich text)"),
        ),
        migrations.AlterField(
            model_name="nothingpersonalproductreviewpage",
            name="what_you_should_know_section",
            field=wagtail.fields.StreamField(
                [("content", 4)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "large",
                                "ol",
                                "ul",
                                "hr",
                                "embed",
                                "link",
                                "document-link",
                                "image",
                            ],
                            "help_text": "Should I trust their default settings?",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "large",
                                "ol",
                                "ul",
                                "hr",
                                "embed",
                                "link",
                                "document-link",
                                "image",
                            ],
                            "help_text": "What personal data do they have?",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "large",
                                "ol",
                                "ul",
                                "hr",
                                "embed",
                                "link",
                                "document-link",
                                "image",
                            ],
                            "help_text": "Track record",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "large",
                                "ol",
                                "ul",
                                "hr",
                                "embed",
                                "link",
                                "document-link",
                                "image",
                            ],
                            "help_text": "Does this product sell or share user data?",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("trust_default_settings", 0),
                                ("what_personal_data_they_have", 1),
                                ("track_record", 2),
                                ("sells_or_shares_user_data", 3),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
    ]
