# Generated by Django 4.2.25 on 2025-12-04 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("nothing_personal", "0038_alter_nothingpersonalarticlecollectionpage_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nothingpersonalfeatureditem",
            name="page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nothing_personal_featured_items",
                to="wagtailcore.page",
            ),
        ),
    ]
