# Generated by Django 4.2.27 on 2026-01-29 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nothing_personal", "0044_alter_nothingpersonalarticlecollectionpage_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nothingpersonalarticlecollectionpage",
            name="theme",
            field=models.CharField(
                blank=True,
                choices=[
                    ("default", "Default"),
                    ("nothing_personal", "Nothing Personal"),
                    ("mozilla_festival", "Mozilla Festival"),
                ],
                help_text="Optional. If unset, theme will be inherited from section root.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="nothingpersonalarticlepage",
            name="theme",
            field=models.CharField(
                blank=True,
                choices=[
                    ("default", "Default"),
                    ("nothing_personal", "Nothing Personal"),
                    ("mozilla_festival", "Mozilla Festival"),
                ],
                help_text="Optional. If unset, theme will be inherited from section root.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="nothingpersonalhomepage",
            name="theme",
            field=models.CharField(
                blank=True,
                choices=[
                    ("default", "Default"),
                    ("nothing_personal", "Nothing Personal"),
                    ("mozilla_festival", "Mozilla Festival"),
                ],
                help_text="Optional. If unset, theme will be inherited from section root.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="nothingpersonalpodcastpage",
            name="theme",
            field=models.CharField(
                blank=True,
                choices=[
                    ("default", "Default"),
                    ("nothing_personal", "Nothing Personal"),
                    ("mozilla_festival", "Mozilla Festival"),
                ],
                help_text="Optional. If unset, theme will be inherited from section root.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="nothingpersonalproductcollectionpage",
            name="theme",
            field=models.CharField(
                blank=True,
                choices=[
                    ("default", "Default"),
                    ("nothing_personal", "Nothing Personal"),
                    ("mozilla_festival", "Mozilla Festival"),
                ],
                help_text="Optional. If unset, theme will be inherited from section root.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="nothingpersonalproductreviewpage",
            name="theme",
            field=models.CharField(
                blank=True,
                choices=[
                    ("default", "Default"),
                    ("nothing_personal", "Nothing Personal"),
                    ("mozilla_festival", "Mozilla Festival"),
                ],
                help_text="Optional. If unset, theme will be inherited from section root.",
                max_length=50,
                null=True,
            ),
        ),
    ]
