# Generated by Django 5.2.13 on 2026-05-13 19:49

from django.db import migrations, models

import foundation_cms.validators


class Migration(migrations.Migration):

    dependencies = [
        ("nothing_personal", "0055_alter_nothingpersonalarticlecollectionpage_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nothingpersonalarticlepage",
            name="hero_video_url",
            field=models.CharField(
                blank=True,
                help_text="Log into Vimeo using 1Password and upload the desired video. Then select the video and click '...', 'Video File Links', and select '(mp4, 1920 x 1080)'. Copy and paste the link here.",
                max_length=500,
                validators=[foundation_cms.validators.validate_vimeo_mp4_url],
            ),
        ),
    ]
