# Generated by Django 5.2.13 on 2026-05-21 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nothing_personal", "0057_add_sosha_to_nothing_personal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nothingpersonalarticlepage",
            name="displayed_hero_content",
            field=models.CharField(
                blank=True,
                choices=[("", "No media"), ("image", "Image"), ("video", "Video")],
                default="",
                max_length=25,
                verbose_name="Select media type from dropdown",
            ),
        ),
    ]
