# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-07 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20170306_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
