# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0022_merge_20170405_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='interview_url',
            field=models.URLField(blank=True, help_text='Link to interview for featured people', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='Link to LinkedIn account', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Link to twitter account', max_length=2048, null=True),
        ),
    ]
