FROM python:3.7-slim

RUN apt-get update && apt-get install -y \
      gettext \
    --no-install-recommends && rm -rf /var/lib/apt/lists/*

# We want output
ENV PYTHONUNBUFFERED 1
# We don't want *.pyc
ENV PYTHONDONTWRITEBYTECODE 1

WORKDIR /app/

# Install pipenv
RUN pip install pipenv

# Copy Pipfiles in the container
COPY Pipfile.*  ./

# Install app deps
RUN pipenv install -d
