FROM python:3.7-slim

# We want output
ENV PYTHONUNBUFFERED 1
# We don't want *.pyc
ENV PYTHONDONTWRITEBYTECODE 1

ENV SHELL /bin/bash

RUN apt-get update && apt-get install -y git

WORKDIR /app/

# Install pipenv
RUN pip install pipenv invoke

# Copy Pipfiles in the container
COPY Pipfile Pipfile.lock ./

# Install app deps
RUN pipenv install -d
