# Generated by Django 4.2.27 on 2026-01-14 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogindexpage",
            options={"verbose_name": "Blog Index Page"},
        ),
        migrations.AlterModelOptions(
            name="blogpage",
            options={"verbose_name": "Blog Page"},
        ),
    ]
