# Generated by Django 3.2.18 on 2023-05-18 02:40

from django.db import migrations, models
import django.db.models.deletion
import networkapi.wagtailpages.pagemodels.mixin.foundation_navigation
import wagtailmetadata.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('wagtailimages', '0024_index_image_file_hash'),
    ]

    operations = [

        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='ResearchLandingPage',
                    fields=[
                        ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                        ('intro', models.CharField(blank=True, max_length=250)),
                        ('banner_image', models.ForeignKey(blank=True, help_text='Image that will render at the top of the page.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image')),
                        ('search_image', models.ForeignKey(blank=True, help_text='Image must be high quality, include our logo mark and have the dimensions 1200 x 628 px. For more design guidelines see here: https://foundation.mozilla.org/en/docs/brand/brand-identity/social-media/#og-images', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Search image')),
                    ],
                    bases=(wagtailmetadata.models.WagtailImageMetadataMixin, networkapi.wagtailpages.pagemodels.mixin.foundation_navigation.FoundationNavigationPageMixin, 'wagtailcore.page', models.Model),
                ),
            ],
            # Table already exists. See wagtailpages/migrations/0083_copy_researchlandingpage_table.py
            database_operations=[],
         ),
    ]

