# Generated by Django 4.2.27 on 2026-01-14 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nav", "0009_alter_navmenufeaturedblogtopicrelationship_icon"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="navmenu",
            options={"verbose_name": "Navigation Menu (Legacy)", "verbose_name_plural": "Navigation Menus (Legacy)"},
        ),
        migrations.AlterModelOptions(
            name="navmenufeaturedblogtopicrelationship",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "Featured Blog Topic (Legacy)",
                "verbose_name_plural": "Featured Blog Topics (Legacy)",
            },
        ),
        migrations.AlterModelOptions(
            name="sitenavmenu",
            options={"verbose_name": "Navigation Menu (Legacy)", "verbose_name_plural": "Navigation Menus (Legacy)"},
        ),
    ]
