# Generated by Django 3.1.11 on 2021-12-01 23:20

from django.db import migrations

def print_progress(apps, schema_editor):
    print('Applying wagtailpages 0060')

class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0059_auto_20211129_1931'),
    ]

    operations = [
        migrations.RunPython(
            code=print_progress,
        ),
        migrations.AlterModelOptions(
            name='cta',
            options={'ordering': ['-id'], 'verbose_name_plural': 'CTA'},
        ),
        migrations.AlterModelOptions(
            name='petition',
            options={'ordering': ['-id'], 'verbose_name': 'petition snippet'},
        ),
    ]
