# Generated by Django 5.2.13 on 2026-05-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SearchEvent",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("query_string", models.CharField(db_index=True, max_length=255)),
                ("language_code", models.CharField(db_index=True, max_length=10)),
                ("results_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["created_at"], name="search_sear_created_a297d4_idx"),
                    models.Index(fields=["query_string", "created_at"], name="search_sear_query_s_c17460_idx"),
                    models.Index(fields=["language_code", "created_at"], name="search_sear_languag_3a42bf_idx"),
                ],
            },
        ),
    ]
