# Generated by Django 4.2.25 on 2025-12-05 21:48

import uuid

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("campaigns", "0004_add_donatebutton_to_frublock"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignPageKeepContributingRelation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("translation_key", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                (
                    "keep_contributing_page",
                    models.ForeignKey(
                        help_text="Select a page to feature as a keep-contributing link.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "locale",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="wagtailcore.locale",
                        verbose_name="locale",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keep_contributing_pages",
                        to="campaigns.campaignpage",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("translation_key", "locale")},
            },
        ),
    ]
