# Generated by Django 4.2.27 on 2026-01-21 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0009_remove_new_from_verbose_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="petition",
            name="share_twitter",
        ),
    ]
