# Generated by Django 4.2.27 on 2026-01-23 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0010_alter_campaignpage_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="petition",
            name="share_twitter",
        ),
    ]
