# Generated by Django 4.2.29 on 2026-04-16 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0020_alter_campaignpage_topics"),
    ]

    operations = [
        migrations.AddField(
            model_name="petition",
            name="sosha_toolkit_embed_code",
            field=models.TextField(
                blank=True,
                help_text="Paste the embed code generated from the Sosha social sharing toolkit.",
                null=True,
            ),
        ),
    ]
