# Generated by Django 5.2.13 on 2026-05-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0025_add_sosha_toolkit_embed_code_to_petition"),
    ]

    operations = [
        migrations.AddField(
            model_name="petition",
            name="campaign_name",
            field=models.CharField(help_text="Campaign Name to target audience segments.", max_length=255, null=True),
        ),
    ]
