# Generated by Django 5.2.17 on 2026-09-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0027_campaignpage_notice_banner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignpage",
            name="theme",
            field=models.CharField(
                blank=True,
                choices=[("default", "Default"), ("nothing_personal", "Nothing Personal"), ("solstice", "Solstice")],
                help_text="Optional. If unset, theme will be inherited from section root.",
                max_length=50,
                null=True,
            ),
        ),
    ]
