# Generated by Django 2.2.17 on 2021-04-07 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpage',
            name='cloudinary_image',
        ),
    ]
