# Generated by Django 2.2.17 on 2021-04-07 15:33

from django.db import migrations

def print_progress(apps, schema_editor):
    print('Applying wagtailpages 0002')

class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            code=print_progress,
        ),
        migrations.RemoveField(
            model_name='productpage',
            name='cloudinary_image',
        ),
    ]
