# Generated by Django 2.2.13 on 2020-06-11 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0002_delete_participatepage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomepageFeaturedNews',
        ),
    ]
