# Generated by Django 2.2.13 on 2020-07-08 23:01

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailpages', '0003_delete_homepagefeaturednews'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='partner_background_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='partner_external_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='partner_heading',
            field=models.CharField(default='Partner with us', max_length=75),
        ),
        migrations.AddField(
            model_name='homepage',
            name='partner_internal_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parnter_internal_link', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='partner_intro_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='partner_link_text',
            field=models.CharField(default="Let's work together", max_length=35),
        ),
        migrations.CreateModel(
            name='PartnerLogos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('logo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_logos', to='wagtailpages.Homepage')),
            ],
            options={
                'verbose_name': 'Partner Logo',
            },
        ),
    ]
