# Generated by Django 3.2.12 on 2022-03-08 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailpages', '0004_delete_newspage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContentAuthor',
            new_name='Profile',
        ),
    ]
