# Generated by Django 2.2.13 on 2020-08-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0006_homepage_take_action_cards'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areaoffocus',
            options={'verbose_name': 'Area of focus', 'verbose_name_plural': 'Areas of focus'},
        ),
        migrations.RemoveField(
            model_name='homepagetakeactioncards',
            name='external_link',
        ),
        migrations.AddField(
            model_name='partnerlogos',
            name='width',
            field=models.PositiveSmallIntegerField(default=200, help_text='The width of the image. Height will automatically be applied.'),
            preserve_default=False,
        ),
    ]
