# Generated by Django 2.2.14 on 2020-08-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0007_auto_20200805_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_headline',
            field=models.CharField(blank=True, help_text='Hero story headline', max_length=80),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_headline_de',
            field=models.CharField(blank=True, help_text='Hero story headline', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_headline_en',
            field=models.CharField(blank=True, help_text='Hero story headline', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_headline_es',
            field=models.CharField(blank=True, help_text='Hero story headline', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_headline_fr',
            field=models.CharField(blank=True, help_text='Hero story headline', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_headline_fy_NL',
            field=models.CharField(blank=True, help_text='Hero story headline', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_headline_nl',
            field=models.CharField(blank=True, help_text='Hero story headline', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_headline_pl',
            field=models.CharField(blank=True, help_text='Hero story headline', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_headline_pt',
            field=models.CharField(blank=True, help_text='Hero story headline', max_length=80, null=True),
        ),
    ]
