# Generated by Django 2.2.14 on 2020-08-10 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailpages', '0008_auto_20200811_1646'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AreaOfFocus',
            new_name='HomepageFocusAreas',
        ),
        migrations.RemoveField(
            model_name='focusarea',
            name='external_link',
        ),
        migrations.RemoveField(
            model_name='focusarea',
            name='internal_link',
        ),
        migrations.AddField(
            model_name='focusarea',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
