# Generated by Django 3.0.14 on 2021-06-03 10:34

import django.core.validators
from django.db import migrations, models
import networkapi.wagtailpages.pagemodels.customblocks.articles
import wagtail.contrib.table_block.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0008_auto_20210519_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='body_de',
            field=wagtail.core.fields.StreamField([('airtable', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.URLBlock(help_text="Copied from the Airtable embed code. The word 'embed' will be in the url")), ('height', wagtail.core.blocks.IntegerBlock(default=533, help_text='The pixel height on desktop view, usually copied from the Airtable embed code'))])), ('callout', wagtail.core.blocks.BlockQuoteBlock(template='wagtailpages/blocks/article_blockquote_block.html')), ('content', networkapi.wagtailpages.pagemodels.customblocks.articles.ArticleRichText(features=['bold', 'italic', 'h2', 'h3', 'h4', 'h5', 'link', 'large', 'ol', 'ul', 'image', 'hr', 'footnotes'])), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.RichTextBlock(features=['italic', 'bold', 'link'], label='Image caption', required=False)), ('alt_text', wagtail.core.blocks.CharBlock(required=False)), ('wide_image', wagtail.core.blocks.BooleanBlock(default=False, help_text='Checking this will use a wider version of this image, but not full width. For an edge-to-edge image, use the "Wide Image" block.', required=False))])), ('double_image', wagtail.core.blocks.StructBlock([('image_1', wagtail.images.blocks.ImageChooserBlock()), ('image_1_caption', wagtail.core.blocks.RichTextBlock(features=['italic', 'bold', 'link'], label='Image caption', required=False)), ('image_2', wagtail.images.blocks.ImageChooserBlock()), ('image_2_caption', wagtail.core.blocks.RichTextBlock(features=['italic', 'bold', 'link'], label='Image caption', required=False))])), ('full_width_image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('image_height', wagtail.core.blocks.IntegerBlock(default=410, help_text='A custom height for this image. The image will be 1400px wide by this height. Note: This may cause images to look pixelated. If the browser is wider than 1400px the height will scale vertically while the width scales horizontally')), ('caption', wagtail.core.blocks.RichTextBlock(features=['italic', 'bold', 'link'], label='Image caption', required=False))])), ('iframe', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.CharBlock(help_text='Please note that only URLs from white-listed domains will work.')), ('height', wagtail.core.blocks.IntegerBlock(help_text='Optional integer pixel value for custom iFrame height', required=False)), ('caption', wagtail.core.blocks.CharBlock(required=False)), ('captionURL', wagtail.core.blocks.CharBlock(help_text='Optional URL that this caption should link out to.', required=False)), ('wide_iframe', wagtail.core.blocks.BooleanBlock(help_text='Check this box for a wider iframe', required=False))])), ('table', wagtail.contrib.table_block.blocks.TableBlock(template='wagtailpages/blocks/article_table_block.html')), ('video', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.CharBlock(help_text='For YouTube: go to your YouTube video and click “Share,” then “Embed,” and then copy and paste the provided URL only. For example: https://www.youtube.com/embed/3FIVXBawyQw For Vimeo: follow similar steps to grab the embed URL. For example: https://player.vimeo.com/video/9004979')), ('caption', wagtail.core.blocks.CharBlock(required=False)), ('captionURL', wagtail.core.blocks.CharBlock(help_text='Optional URL for caption to link to.', required=False))])), ('advanced_table', wagtail.core.blocks.StructBlock([('header', wagtail.core.blocks.BooleanBlock(help_text='Display the first row as a header.', required=False)), ('column', wagtail.core.blocks.BooleanBlock(help_text='Display the first column as a header.', required=False)), ('caption', wagtail.core.blocks.CharBlock(help_text='A heading that identifies the overall topic of the table, and is useful for screen reader users', required=False)), ('table', wagtail.core.blocks.StreamBlock([('row', wagtail.core.blocks.StreamBlock([('cell', wagtail.core.blocks.StructBlock([('centered_text', wagtail.core.blocks.BooleanBlock(required=False)), ('column_width', wagtail.core.blocks.IntegerBlock(default=1, help_text='Enter the number of extra cell columns you want to merge together. Merging a cell column will expand a cell to the right. To merge two cells together, set the column width to 2. For 3, set 3. Default is 1. Min 1. Max 20.', validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)])), ('content', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'ul', 'ol']))]))]))]))]))], null=True),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='body_en',
            field=wagtail.core.fields.StreamField([('airtable', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.URLBlock(help_text="Copied from the Airtable embed code. The word 'embed' will be in the url")), ('height', wagtail.core.blocks.IntegerBlock(default=533, help_text='The pixel height on desktop view, usually copied from the Airtable embed code'))])), ('callout', wagtail.core.blocks.BlockQuoteBlock(template='wagtailpages/blocks/article_blockquote_block.html')), ('content', networkapi.wagtailpages.pagemodels.customblocks.articles.ArticleRichText(features=['bold', 'italic', 'h2', 'h3', 'h4', 'h5', 'link', 'large', 'ol', 'ul', 'image', 'hr', 'footnotes'])), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.RichTextBlock(features=['italic', 'bold', 'link'], label='Image caption', required=False)), ('alt_text', wagtail.core.blocks.CharBlock(required=False)), ('wide_image', wagtail.core.blocks.BooleanBlock(default=False, help_text='Checking this will use a wider version of this image, but not full width. For an edge-to-edge image, use the "Wide Image" block.', required=False))])), ('double_image', wagtail.core.blocks.StructBlock([('image_1', wagtail.images.blocks.ImageChooserBlock()), ('image_1_caption', wagtail.core.blocks.RichTextBlock(features=['italic', 'bold', 'link'], label='Image caption', required=False)), ('image_2', wagtail.images.blocks.ImageChooserBlock()), ('image_2_caption', wagtail.core.blocks.RichTextBlock(features=['italic', 'bold', 'link'], label='Image caption', required=False))])), ('full_width_image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('image_height', wagtail.core.blocks.IntegerBlock(default=410, help_text='A custom height for this image. The image will be 1400px wide by this height. Note: This may cause images to look pixelated. If the browser is wider than 1400px the height will scale vertically while the width scales horizontally')), ('caption', wagtail.core.blocks.RichTextBlock(features=['italic', 'bold', 'link'], label='Image caption', required=False))])), ('iframe', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.CharBlock(help_text='Please note that only URLs from white-listed domains will work.')), ('height', wagtail.core.blocks.IntegerBlock(help_text='Optional integer pixel value for custom iFrame height', required=False)), ('caption', wagtail.core.blocks.CharBlock(required=False)), ('captionURL', wagtail.core.blocks.CharBlock(help_text='Optional URL that this caption should link out to.', required=False)), ('wide_iframe', wagtail.core.blocks.BooleanBlock(help_text='Check this box for a wider iframe', required=False))])), ('table', wagtail.contrib.table_block.blocks.TableBlock(template='wagtailpages/blocks/article_table_block.html')), ('video', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.CharBlock(help_text='For YouTube: go to your YouTube video and click “Share,” then “Embed,” and then copy and paste the provided URL only. For example: https://www.youtube.com/embed/3FIVXBawyQw For Vimeo: follow similar steps to grab the embed URL. For example: https://player.vimeo.com/video/9004979')), ('caption', wagtail.core.blocks.CharBlock(required=False)), ('captionURL', wagtail.core.blocks.CharBlock(help_text='Optional URL for caption to link to.', required=False))])), ('advanced_table', wagtail.core.blocks.StructBlock([('header', wagtail.core.blocks.BooleanBlock(help_text='Display the first row as a header.', required=False)), ('column', wagtail.core.blocks.BooleanBlock(help_text='Display the first column as a header.', required=False)), ('caption', wagtail.core.blocks.CharBlock(help_text='A heading that identifies the overall topic of the table, and is useful for screen reader users', required=False)), ('table', wagtail.core.blocks.StreamBlock([('row', wagtail.core.blocks.StreamBlock([('cell', wagtail.core.blocks.StructBlock([('centered_text', wagtail.core.blocks.BooleanBlock(required=False)), ('column_width', wagtail.core.blocks.IntegerBlock(default=1, help_text='Enter the number of extra cell columns you want to merge together. Merging a cell column will expand a cell to the right. To merge two cells together, set the column width to 2. For 3, set 3. Default is 1. Min 1. Max 20.', validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)])), ('content', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'ul', 'ol']))]))]))]))]))], null=True),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='body_es',
            field=wagtail.core.fields.StreamField([('airtable', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.URLBlock(help_text="Copied from the Airtable embed code. The word 'embed' will be in the url")), ('height', wagtail.core.blocks.IntegerBlock(default=533, help_text='The pixel height on desktop view, usually copied from the Airtable embed code'))])), ('callout', wagtail.core.blocks.BlockQuoteBlock(template='wagtailpages/blocks/article_blockquote_block.html')), ('content', networkapi.wagtailpages.pagemodels.customblocks.articles.ArticleRichText(features=['bold', 'italic', 'h2', 'h3', 'h4', 'h5', 'link', 'large', 'ol', 'ul', 'image', 'hr', 'footnotes'])), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.RichTextBlock(features=['italic', 'bold', 'link'], label='Image caption', required=False)), ('alt_text', wagtail.core.blocks.CharBlock(required=False)), ('wide_image', wagtail.core.blocks.BooleanBlock(default=False, help_text='Checking this will use a wider version of this image, but not full width. For an edge-to-edge image, use the "Wide Image" block.', required=False))])), ('double_image', wagtail.core.blocks.StructBlock([('image_1', wagtail.images.blocks.ImageChooserBlock()), ('image_1_caption', wagtail.core.blocks.RichTextBlock(features=['italic', 'bold', 'link'], label='Image caption', required=False)), ('image_2', wagtail.images.blocks.ImageChooserBlock()), ('image_2_caption', wagtail.core.blocks.RichTextBlock(features=['italic', 'bold', 'link'], label='Image caption', required=False))])), ('full_width_image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('image_height', wagtail.core.blocks.IntegerBlock(default=410, help_text='A custom height for this image. The image will be 1400px wide by this height. Note: This may cause images to look pixelated. If the browser is wider than 1400px the height will scale vertically while the width scales horizontally')), ('caption', wagtail.core.blocks.RichTextBlock(features=['italic', 'bold', 'link'], label='Image caption', required=False))])), ('iframe', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.CharBlock(help_text='Please note that only URLs from white-listed domains will work.')), ('height', wagtail.core.blocks.IntegerBlock(help_text='Optional integer pixel value for custom iFrame height', required=False)), ('caption', wagtail.core.blocks.CharBlock(required=False)), ('captionURL', wagtail.core.blocks.CharBlock(help_text='Optional URL that this caption should link out to.', required=False)), ('wide_iframe', wagtail.core.blocks.BooleanBlock(help_text='Check this box for a wider iframe', required=False))])), ('table', wagtail.contrib.table_block.blocks.TableBlock(template='wagtailpages/blocks/article_table_block.html')), ('video', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.CharBlock(help_text='For YouTube: go to your YouTube video and click “Share,” then “Embed,” and then copy and paste the provided URL only. For example: https://www.youtube.com/embed/3FIVXBawyQw For Vimeo: follow similar steps to grab the embed URL. For example: https://player.vimeo.com/video/9004979')), ('caption', wagtail.core.blocks.CharBlock(required=False)), ('captionURL', wagtail.core.blocks.CharBlock(help_text='Optional URL for caption to link to.', required=False))])), ('advanced_table', wagtail.core.blocks.StructBlock([('header', wagtail.core.blocks.BooleanBlock(help_text='Display the first row as a header.', required=False)), ('column', wagtail.core.blocks.BooleanBlock(help_text='Display the first column as a header.', required=False)), ('caption', wagtail.core.blocks.CharBlock(help_text='A heading that identifies the overall topic of the table, and is useful for screen reader users', required=False)), ('table', wagtail.core.blocks.StreamBlock([('row', wagtail.core.blocks.StreamBlock([('cell', wagtail.core.blocks.StructBlock([('centered_text', wagtail.core.blocks.BooleanBlock(required=False)), ('column_width', wagtail.core.blocks.IntegerBlock(default=1, help_text='Enter the number of extra cell columns you want to merge together. Merging a cell column will expand a cell to the right. To merge two cells together, set the column width to 2. For 3, set 3. Default is 1. Min 1. Max 20.', validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)])), ('content', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'ul', 'ol']))]))]))]))]))], null=True),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='body_fr',
            field=wagtail.core.fields.StreamField([('airtable', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.URLBlock(help_text="Copied from the Airtable embed code. The word 'embed' will be in the url")), ('height', wagtail.core.blocks.IntegerBlock(default=533, help_text='The pixel height on desktop view, usually copied from the Airtable embed code'))])), ('callout', wagtail.core.blocks.BlockQuoteBlock(template='wagtailpages/blocks/article_blockquote_block.html')), ('content', networkapi.wagtailpages.pagemodels.customblocks.articles.ArticleRichText(features=['bold', 'italic', 'h2', 'h3', 'h4', 'h5', 'link', 'large', 'ol', 'ul', 'image', 'hr', 'footnotes'])), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.RichTextBlock(features=['italic', 'bold', 'link'], label='Image caption', required=False)), ('alt_text', wagtail.core.blocks.CharBlock(required=False)), ('wide_image', wagtail.core.blocks.BooleanBlock(default=False, help_text='Checking this will use a wider version of this image, but not full width. For an edge-to-edge image, use the "Wide Image" block.', required=False))])), ('double_image', wagtail.core.blocks.StructBlock([('image_1', wagtail.images.blocks.ImageChooserBlock()), ('image_1_caption', wagtail.core.blocks.RichTextBlock(features=['italic', 'bold', 'link'], label='Image caption', required=False)), ('image_2', wagtail.images.blocks.ImageChooserBlock()), ('image_2_caption', wagtail.core.blocks.RichTextBlock(features=['italic', 'bold', 'link'], label='Image caption', required=False))])), ('full_width_image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('image_height', wagtail.core.blocks.IntegerBlock(default=410, help_text='A custom height for this image. The image will be 1400px wide by this height. Note: This may cause images to look pixelated. If the browser is wider than 1400px the height will scale vertically while the width scales horizontally')), ('caption', wagtail.core.blocks.RichTextBlock(features=['italic', 'bold', 'link'], label='Image caption', required=False))])), ('iframe', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.CharBlock(help_text='Please note that only URLs from white-listed domains will work.')), ('height', wagtail.core.blocks.IntegerBlock(help_text='Optional integer pixel value for custom iFrame height', required=False)), ('caption', wagtail.core.blocks.CharBlock(required=False)), ('captionURL', wagtail.core.blocks.CharBlock(help_text='Optional URL that this caption should link out to.', required=False)), ('wide_iframe', wagtail.core.blocks.BooleanBlock(help_text='Check this box for a wider iframe', required=False))])), ('table', wagtail.contrib.table_block.blocks.TableBlock(template='wagtailpages/blocks/article_table_block.html')), ('video', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.CharBlock(help_text='For YouTube: go to your YouTube video and click “Share,” then “Embed,” and then copy and paste the provided URL only. For example: https://www.youtube.com/embed/3FIVXBawyQw For Vimeo: follow similar steps to grab the embed URL. For example: https://player.vimeo.com/video/9004979')), ('caption', wagtail.core.blocks.CharBlock(required=False)), ('captionURL', wagtail.core.blocks.CharBlock(help_text='Optional URL for caption to link to.', required=False))])), ('advanced_table', wagtail.core.blocks.StructBlock([('header', wagtail.core.blocks.BooleanBlock(help_text='Display the first row as a header.', required=False)), ('column', wagtail.core.blocks.BooleanBlock(help_text='Display the first column as a header.', required=False)), ('caption', wagtail.core.blocks.CharBlock(help_text='A heading that identifies the overall topic of the table, and is useful for screen reader users', required=False)), ('table', wagtail.core.blocks.StreamBlock([('row', wagtail.core.blocks.StreamBlock([('cell', wagtail.core.blocks.StructBlock([('centered_text', wagtail.core.blocks.BooleanBlock(required=False)), ('column_width', wagtail.core.blocks.IntegerBlock(default=1, help_text='Enter the number of extra cell columns you want to merge together. Merging a cell column will expand a cell to the right. To merge two cells together, set the column width to 2. For 3, set 3. Default is 1. Min 1. Max 20.', validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)])), ('content', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'ul', 'ol']))]))]))]))]))], null=True),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='body_fy_NL',
            field=wagtail.core.fields.StreamField([('airtable', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.URLBlock(help_text="Copied from the Airtable embed code. The word 'embed' will be in the url")), ('height', wagtail.core.blocks.IntegerBlock(default=533, help_text='The pixel height on desktop view, usually copied from the Airtable embed code'))])), ('callout', wagtail.core.blocks.BlockQuoteBlock(template='wagtailpages/blocks/article_blockquote_block.html')), ('content', networkapi.wagtailpages.pagemodels.customblocks.articles.ArticleRichText(features=['bold', 'italic', 'h2', 'h3', 'h4', 'h5', 'link', 'large', 'ol', 'ul', 'image', 'hr', 'footnotes'])), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.RichTextBlock(features=['italic', 'bold', 'link'], label='Image caption', required=False)), ('alt_text', wagtail.core.blocks.CharBlock(required=False)), ('wide_image', wagtail.core.blocks.BooleanBlock(default=False, help_text='Checking this will use a wider version of this image, but not full width. For an edge-to-edge image, use the "Wide Image" block.', required=False))])), ('double_image', wagtail.core.blocks.StructBlock([('image_1', wagtail.images.blocks.ImageChooserBlock()), ('image_1_caption', wagtail.core.blocks.RichTextBlock(features=['italic', 'bold', 'link'], label='Image caption', required=False)), ('image_2', wagtail.images.blocks.ImageChooserBlock()), ('image_2_caption', wagtail.core.blocks.RichTextBlock(features=['italic', 'bold', 'link'], label='Image caption', required=False))])), ('full_width_image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('image_height', wagtail.core.blocks.IntegerBlock(default=410, help_text='A custom height for this image. The image will be 1400px wide by this height. Note: This may cause images to look pixelated. If the browser is wider than 1400px the height will scale vertically while the width scales horizontally')), ('caption', wagtail.core.blocks.RichTextBlock(features=['italic', 'bold', 'link'], label='Image caption', required=False))])), ('iframe', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.CharBlock(help_text='Please note that only URLs from white-listed domains will work.')), ('height', wagtail.core.blocks.IntegerBlock(help_text='Optional integer pixel value for custom iFrame height', required=False)), ('caption', wagtail.core.blocks.CharBlock(required=False)), ('captionURL', wagtail.core.blocks.CharBlock(help_text='Optional URL that this caption should link out to.', required=False)), ('wide_iframe', wagtail.core.blocks.BooleanBlock(help_text='Check this box for a wider iframe', required=False))])), ('table', wagtail.contrib.table_block.blocks.TableBlock(template='wagtailpages/blocks/article_table_block.html')), ('video', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.CharBlock(help_text='For YouTube: go to your YouTube video and click “Share,” then “Embed,” and then copy and paste the provided URL only. For example: https://www.youtube.com/embed/3FIVXBawyQw For Vimeo: follow similar steps to grab the embed URL. For example: https://player.vimeo.com/video/9004979')), ('caption', wagtail.core.blocks.CharBlock(required=False)), ('captionURL', wagtail.core.blocks.CharBlock(help_text='Optional URL for caption to link to.', required=False))])), ('advanced_table', wagtail.core.blocks.StructBlock([('header', wagtail.core.blocks.BooleanBlock(help_text='Display the first row as a header.', required=False)), ('column', wagtail.core.blocks.BooleanBlock(help_text='Display the first column as a header.', required=False)), ('caption', wagtail.core.blocks.CharBlock(help_text='A heading that identifies the overall topic of the table, and is useful for screen reader users', required=False)), ('table', wagtail.core.blocks.StreamBlock([('row', wagtail.core.blocks.StreamBlock([('cell', wagtail.core.blocks.StructBlock([('centered_text', wagtail.core.blocks.BooleanBlock(required=False)), ('column_width', wagtail.core.blocks.IntegerBlock(default=1, help_text='Enter the number of extra cell columns you want to merge together. Merging a cell column will expand a cell to the right. To merge two cells together, set the column width to 2. For 3, set 3. Default is 1. Min 1. Max 20.', validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)])), ('content', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'ul', 'ol']))]))]))]))]))], null=True),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='body_nl',
            field=wagtail.core.fields.StreamField([('airtable', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.URLBlock(help_text="Copied from the Airtable embed code. The word 'embed' will be in the url")), ('height', wagtail.core.blocks.IntegerBlock(default=533, help_text='The pixel height on desktop view, usually copied from the Airtable embed code'))])), ('callout', wagtail.core.blocks.BlockQuoteBlock(template='wagtailpages/blocks/article_blockquote_block.html')), ('content', networkapi.wagtailpages.pagemodels.customblocks.articles.ArticleRichText(features=['bold', 'italic', 'h2', 'h3', 'h4', 'h5', 'link', 'large', 'ol', 'ul', 'image', 'hr', 'footnotes'])), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.RichTextBlock(features=['italic', 'bold', 'link'], label='Image caption', required=False)), ('alt_text', wagtail.core.blocks.CharBlock(required=False)), ('wide_image', wagtail.core.blocks.BooleanBlock(default=False, help_text='Checking this will use a wider version of this image, but not full width. For an edge-to-edge image, use the "Wide Image" block.', required=False))])), ('double_image', wagtail.core.blocks.StructBlock([('image_1', wagtail.images.blocks.ImageChooserBlock()), ('image_1_caption', wagtail.core.blocks.RichTextBlock(features=['italic', 'bold', 'link'], label='Image caption', required=False)), ('image_2', wagtail.images.blocks.ImageChooserBlock()), ('image_2_caption', wagtail.core.blocks.RichTextBlock(features=['italic', 'bold', 'link'], label='Image caption', required=False))])), ('full_width_image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('image_height', wagtail.core.blocks.IntegerBlock(default=410, help_text='A custom height for this image. The image will be 1400px wide by this height. Note: This may cause images to look pixelated. If the browser is wider than 1400px the height will scale vertically while the width scales horizontally')), ('caption', wagtail.core.blocks.RichTextBlock(features=['italic', 'bold', 'link'], label='Image caption', required=False))])), ('iframe', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.CharBlock(help_text='Please note that only URLs from white-listed domains will work.')), ('height', wagtail.core.blocks.IntegerBlock(help_text='Optional integer pixel value for custom iFrame height', required=False)), ('caption', wagtail.core.blocks.CharBlock(required=False)), ('captionURL', wagtail.core.blocks.CharBlock(help_text='Optional URL that this caption should link out to.', required=False)), ('wide_iframe', wagtail.core.blocks.BooleanBlock(help_text='Check this box for a wider iframe', required=False))])), ('table', wagtail.contrib.table_block.blocks.TableBlock(template='wagtailpages/blocks/article_table_block.html')), ('video', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.CharBlock(help_text='For YouTube: go to your YouTube video and click “Share,” then “Embed,” and then copy and paste the provided URL only. For example: https://www.youtube.com/embed/3FIVXBawyQw For Vimeo: follow similar steps to grab the embed URL. For example: https://player.vimeo.com/video/9004979')), ('caption', wagtail.core.blocks.CharBlock(required=False)), ('captionURL', wagtail.core.blocks.CharBlock(help_text='Optional URL for caption to link to.', required=False))])), ('advanced_table', wagtail.core.blocks.StructBlock([('header', wagtail.core.blocks.BooleanBlock(help_text='Display the first row as a header.', required=False)), ('column', wagtail.core.blocks.BooleanBlock(help_text='Display the first column as a header.', required=False)), ('caption', wagtail.core.blocks.CharBlock(help_text='A heading that identifies the overall topic of the table, and is useful for screen reader users', required=False)), ('table', wagtail.core.blocks.StreamBlock([('row', wagtail.core.blocks.StreamBlock([('cell', wagtail.core.blocks.StructBlock([('centered_text', wagtail.core.blocks.BooleanBlock(required=False)), ('column_width', wagtail.core.blocks.IntegerBlock(default=1, help_text='Enter the number of extra cell columns you want to merge together. Merging a cell column will expand a cell to the right. To merge two cells together, set the column width to 2. For 3, set 3. Default is 1. Min 1. Max 20.', validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)])), ('content', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'ul', 'ol']))]))]))]))]))], null=True),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='body_pl',
            field=wagtail.core.fields.StreamField([('airtable', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.URLBlock(help_text="Copied from the Airtable embed code. The word 'embed' will be in the url")), ('height', wagtail.core.blocks.IntegerBlock(default=533, help_text='The pixel height on desktop view, usually copied from the Airtable embed code'))])), ('callout', wagtail.core.blocks.BlockQuoteBlock(template='wagtailpages/blocks/article_blockquote_block.html')), ('content', networkapi.wagtailpages.pagemodels.customblocks.articles.ArticleRichText(features=['bold', 'italic', 'h2', 'h3', 'h4', 'h5', 'link', 'large', 'ol', 'ul', 'image', 'hr', 'footnotes'])), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.RichTextBlock(features=['italic', 'bold', 'link'], label='Image caption', required=False)), ('alt_text', wagtail.core.blocks.CharBlock(required=False)), ('wide_image', wagtail.core.blocks.BooleanBlock(default=False, help_text='Checking this will use a wider version of this image, but not full width. For an edge-to-edge image, use the "Wide Image" block.', required=False))])), ('double_image', wagtail.core.blocks.StructBlock([('image_1', wagtail.images.blocks.ImageChooserBlock()), ('image_1_caption', wagtail.core.blocks.RichTextBlock(features=['italic', 'bold', 'link'], label='Image caption', required=False)), ('image_2', wagtail.images.blocks.ImageChooserBlock()), ('image_2_caption', wagtail.core.blocks.RichTextBlock(features=['italic', 'bold', 'link'], label='Image caption', required=False))])), ('full_width_image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('image_height', wagtail.core.blocks.IntegerBlock(default=410, help_text='A custom height for this image. The image will be 1400px wide by this height. Note: This may cause images to look pixelated. If the browser is wider than 1400px the height will scale vertically while the width scales horizontally')), ('caption', wagtail.core.blocks.RichTextBlock(features=['italic', 'bold', 'link'], label='Image caption', required=False))])), ('iframe', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.CharBlock(help_text='Please note that only URLs from white-listed domains will work.')), ('height', wagtail.core.blocks.IntegerBlock(help_text='Optional integer pixel value for custom iFrame height', required=False)), ('caption', wagtail.core.blocks.CharBlock(required=False)), ('captionURL', wagtail.core.blocks.CharBlock(help_text='Optional URL that this caption should link out to.', required=False)), ('wide_iframe', wagtail.core.blocks.BooleanBlock(help_text='Check this box for a wider iframe', required=False))])), ('table', wagtail.contrib.table_block.blocks.TableBlock(template='wagtailpages/blocks/article_table_block.html')), ('video', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.CharBlock(help_text='For YouTube: go to your YouTube video and click “Share,” then “Embed,” and then copy and paste the provided URL only. For example: https://www.youtube.com/embed/3FIVXBawyQw For Vimeo: follow similar steps to grab the embed URL. For example: https://player.vimeo.com/video/9004979')), ('caption', wagtail.core.blocks.CharBlock(required=False)), ('captionURL', wagtail.core.blocks.CharBlock(help_text='Optional URL for caption to link to.', required=False))])), ('advanced_table', wagtail.core.blocks.StructBlock([('header', wagtail.core.blocks.BooleanBlock(help_text='Display the first row as a header.', required=False)), ('column', wagtail.core.blocks.BooleanBlock(help_text='Display the first column as a header.', required=False)), ('caption', wagtail.core.blocks.CharBlock(help_text='A heading that identifies the overall topic of the table, and is useful for screen reader users', required=False)), ('table', wagtail.core.blocks.StreamBlock([('row', wagtail.core.blocks.StreamBlock([('cell', wagtail.core.blocks.StructBlock([('centered_text', wagtail.core.blocks.BooleanBlock(required=False)), ('column_width', wagtail.core.blocks.IntegerBlock(default=1, help_text='Enter the number of extra cell columns you want to merge together. Merging a cell column will expand a cell to the right. To merge two cells together, set the column width to 2. For 3, set 3. Default is 1. Min 1. Max 20.', validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)])), ('content', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'ul', 'ol']))]))]))]))]))], null=True),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='body_pt',
            field=wagtail.core.fields.StreamField([('airtable', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.URLBlock(help_text="Copied from the Airtable embed code. The word 'embed' will be in the url")), ('height', wagtail.core.blocks.IntegerBlock(default=533, help_text='The pixel height on desktop view, usually copied from the Airtable embed code'))])), ('callout', wagtail.core.blocks.BlockQuoteBlock(template='wagtailpages/blocks/article_blockquote_block.html')), ('content', networkapi.wagtailpages.pagemodels.customblocks.articles.ArticleRichText(features=['bold', 'italic', 'h2', 'h3', 'h4', 'h5', 'link', 'large', 'ol', 'ul', 'image', 'hr', 'footnotes'])), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.RichTextBlock(features=['italic', 'bold', 'link'], label='Image caption', required=False)), ('alt_text', wagtail.core.blocks.CharBlock(required=False)), ('wide_image', wagtail.core.blocks.BooleanBlock(default=False, help_text='Checking this will use a wider version of this image, but not full width. For an edge-to-edge image, use the "Wide Image" block.', required=False))])), ('double_image', wagtail.core.blocks.StructBlock([('image_1', wagtail.images.blocks.ImageChooserBlock()), ('image_1_caption', wagtail.core.blocks.RichTextBlock(features=['italic', 'bold', 'link'], label='Image caption', required=False)), ('image_2', wagtail.images.blocks.ImageChooserBlock()), ('image_2_caption', wagtail.core.blocks.RichTextBlock(features=['italic', 'bold', 'link'], label='Image caption', required=False))])), ('full_width_image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('image_height', wagtail.core.blocks.IntegerBlock(default=410, help_text='A custom height for this image. The image will be 1400px wide by this height. Note: This may cause images to look pixelated. If the browser is wider than 1400px the height will scale vertically while the width scales horizontally')), ('caption', wagtail.core.blocks.RichTextBlock(features=['italic', 'bold', 'link'], label='Image caption', required=False))])), ('iframe', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.CharBlock(help_text='Please note that only URLs from white-listed domains will work.')), ('height', wagtail.core.blocks.IntegerBlock(help_text='Optional integer pixel value for custom iFrame height', required=False)), ('caption', wagtail.core.blocks.CharBlock(required=False)), ('captionURL', wagtail.core.blocks.CharBlock(help_text='Optional URL that this caption should link out to.', required=False)), ('wide_iframe', wagtail.core.blocks.BooleanBlock(help_text='Check this box for a wider iframe', required=False))])), ('table', wagtail.contrib.table_block.blocks.TableBlock(template='wagtailpages/blocks/article_table_block.html')), ('video', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.CharBlock(help_text='For YouTube: go to your YouTube video and click “Share,” then “Embed,” and then copy and paste the provided URL only. For example: https://www.youtube.com/embed/3FIVXBawyQw For Vimeo: follow similar steps to grab the embed URL. For example: https://player.vimeo.com/video/9004979')), ('caption', wagtail.core.blocks.CharBlock(required=False)), ('captionURL', wagtail.core.blocks.CharBlock(help_text='Optional URL for caption to link to.', required=False))])), ('advanced_table', wagtail.core.blocks.StructBlock([('header', wagtail.core.blocks.BooleanBlock(help_text='Display the first row as a header.', required=False)), ('column', wagtail.core.blocks.BooleanBlock(help_text='Display the first column as a header.', required=False)), ('caption', wagtail.core.blocks.CharBlock(help_text='A heading that identifies the overall topic of the table, and is useful for screen reader users', required=False)), ('table', wagtail.core.blocks.StreamBlock([('row', wagtail.core.blocks.StreamBlock([('cell', wagtail.core.blocks.StructBlock([('centered_text', wagtail.core.blocks.BooleanBlock(required=False)), ('column_width', wagtail.core.blocks.IntegerBlock(default=1, help_text='Enter the number of extra cell columns you want to merge together. Merging a cell column will expand a cell to the right. To merge two cells together, set the column width to 2. For 3, set 3. Default is 1. Min 1. Max 20.', validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)])), ('content', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'ul', 'ol']))]))]))]))]))], null=True),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='secondary_subtitle_de',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='secondary_subtitle_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='secondary_subtitle_es',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='secondary_subtitle_fr',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='secondary_subtitle_fy_NL',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='secondary_subtitle_nl',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='secondary_subtitle_pl',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='secondary_subtitle_pt',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='subtitle_de',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='subtitle_es',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='subtitle_fr',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='subtitle_fy_NL',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='subtitle_nl',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='subtitle_pl',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='subtitle_pt',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='additional_author_copy_de',
            field=models.CharField(blank=True, help_text='Example: with contributing authors', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='additional_author_copy_en',
            field=models.CharField(blank=True, help_text='Example: with contributing authors', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='additional_author_copy_es',
            field=models.CharField(blank=True, help_text='Example: with contributing authors', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='additional_author_copy_fr',
            field=models.CharField(blank=True, help_text='Example: with contributing authors', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='additional_author_copy_fy_NL',
            field=models.CharField(blank=True, help_text='Example: with contributing authors', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='additional_author_copy_nl',
            field=models.CharField(blank=True, help_text='Example: with contributing authors', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='additional_author_copy_pl',
            field=models.CharField(blank=True, help_text='Example: with contributing authors', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='additional_author_copy_pt',
            field=models.CharField(blank=True, help_text='Example: with contributing authors', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='contents_title_de',
            field=models.CharField(blank=True, default='Table of Contents', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='contents_title_en',
            field=models.CharField(blank=True, default='Table of Contents', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='contents_title_es',
            field=models.CharField(blank=True, default='Table of Contents', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='contents_title_fr',
            field=models.CharField(blank=True, default='Table of Contents', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='contents_title_fy_NL',
            field=models.CharField(blank=True, default='Table of Contents', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='contents_title_nl',
            field=models.CharField(blank=True, default='Table of Contents', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='contents_title_pl',
            field=models.CharField(blank=True, default='Table of Contents', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='contents_title_pt',
            field=models.CharField(blank=True, default='Table of Contents', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='intro_notes_de',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='intro_notes_en',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='intro_notes_es',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='intro_notes_fr',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='intro_notes_fy_NL',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='intro_notes_nl',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='intro_notes_pl',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='intro_notes_pt',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='notes_de',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='notes_en',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='notes_es',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='notes_fr',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='notes_fy_NL',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='notes_nl',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='notes_pl',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='notes_pt',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='secondary_subtitle_de',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='secondary_subtitle_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='secondary_subtitle_es',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='secondary_subtitle_fr',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='secondary_subtitle_fy_NL',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='secondary_subtitle_nl',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='secondary_subtitle_pl',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='secondary_subtitle_pt',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='subtitle_de',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='subtitle_es',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='subtitle_fr',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='subtitle_fy_NL',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='subtitle_nl',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='subtitle_pl',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='subtitle_pt',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
