# Generated by Django 3.2.12 on 2022-03-10 19:27

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0009_researchregion_researchtopic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchAuthorRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('author_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_research', to='wagtailpages.profile')),
                ('research_detail_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_authors', to='wagtailpages.researchdetailpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
