# Generated by Django 2.2.14 on 2020-08-12 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0010_focus_area_prepopulation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepagetakeactioncards',
            options={'verbose_name': 'Take Action Card'},
        ),
        migrations.AlterModelOptions(
            name='partnerlogos',
            options={'verbose_name': 'Partner Logo'},
        ),
    ]
