# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-06 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('wagtailpages', '0010_primarypage'),
    ]

    operations = [
        migrations.AddField(
            model_name='modularpage',
            name='search_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
