# Generated by Django 3.2.12 on 2022-03-11 21:11

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('wagtailpages', '0010_researchdetailpageresearchtopicrelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchDetailLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(max_length=50)),
                ('url', models.URLField(blank=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wagtaildocs.document')),
                ('research_detail_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_links', to='wagtailpages.researchdetailpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
