# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('wagtailpages', '0011_auto_20180411_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='primarypage',
            name='search_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
