# Generated by Django 2.2.14 on 2020-08-18 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0012_auto_20200812_2133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepagefocusareas',
            options={'verbose_name': 'Area of focus', 'verbose_name_plural': 'Areas of focus'},
        ),
    ]
