# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-13 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0012_auto_20180413_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='modularpage',
            name='narrowed_page_content',
            field=models.BooleanField(default=False, help_text='For text-heavy pages, turn this on to reduce the overall width of the content on the page.'),
        ),
        migrations.AddField(
            model_name='primarypage',
            name='narrowed_page_content',
            field=models.BooleanField(default=False, help_text='For text-heavy pages, turn this on to reduce the overall width of the content on the page.'),
        ),
    ]
