# Generated by Django 2.2.14 on 2020-08-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0012_auto_20200812_2133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepagefocusareas',
            options={'verbose_name': 'Area of focus', 'verbose_name_plural': 'Areas of focus'},
        ),
        migrations.AlterModelOptions(
            name='homepagetakeactioncards',
            options={'ordering': ['sort_order'], 'verbose_name': 'Take Action Card'},
        ),
        migrations.AlterModelOptions(
            name='partnerlogos',
            options={'ordering': ['sort_order'], 'verbose_name': 'Partner Logo'},
        ),
        migrations.AddField(
            model_name='partnerlogos',
            name='width',
            field=models.PositiveSmallIntegerField(default=100, help_text='The width of the image. Height will automatically be applied.'),
            preserve_default=False,
        ),
    ]
