# Generated by Django 3.2.13 on 2022-04-18 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0013_article_hero_custom_coloring'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchlandingpage',
            name='intro',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
