# Generated by Django 3.1.11 on 2021-06-04 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('wagtailpages', '0013_localize_migration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepagefocusareas',
            options={'verbose_name': 'Homepage Focus Area'},
        ),
        migrations.AddField(
            model_name='homepagefocusareas',
            name='locale',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale'),
        ),
        migrations.AddField(
            model_name='homepagefocusareas',
            name='translation_key',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='homepagetakeactioncards',
            name='locale',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale'),
        ),
        migrations.AddField(
            model_name='homepagetakeactioncards',
            name='translation_key',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='partnerlogos',
            name='locale',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale'),
        ),
        migrations.AddField(
            model_name='partnerlogos',
            name='translation_key',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
