# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-19 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0014_auto_20180417_1123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepagefeaturedhighlights',
            options={'ordering': ['sort_order'], 'verbose_name': 'highlight', 'verbose_name_plural': 'highlights'},
        ),
        migrations.AlterModelOptions(
            name='homepagefeaturednews',
            options={'ordering': ['sort_order'], 'verbose_name': 'news', 'verbose_name_plural': 'news'},
        ),
    ]
