# Generated by Django 3.1.11 on 2021-06-10 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0014_translation_mixin_migration'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cta',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='cta',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='cta',
            name='translation_key',
        ),
    ]
