# Generated by Django 3.1.11 on 2021-06-04 16:02

from django.db import migrations
from wagtail.core.models import BootstrapTranslatableModel

class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0014_bootstrap_models'),
    ]

    operations = [
        BootstrapTranslatableModel('wagtailpages.PartnerLogos'),
        BootstrapTranslatableModel('wagtailpages.HomepageTakeActionCards'),
        BootstrapTranslatableModel('wagtailpages.HomepageFocusAreas'),
    ]
