# Generated by Django 2.2.16 on 2020-11-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0016_dearinternetpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='campaign_id',
            field=models.CharField(blank=True, help_text='Which campaign identifier should this petition be tied to?', max_length=20, null=True),
        ),
    ]
