# Generated by Django 3.1.11 on 2021-06-04 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('wagtailpages', '0016_translation_mixin_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationmodals',
            name='locale',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale'),
        ),
        migrations.AddField(
            model_name='donationmodals',
            name='translation_key',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
