# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0016_auto_20180419_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='modularpage',
            name='zen_nav',
            field=models.BooleanField(default=False, help_text='For secondary nav pages, use this to collapse the primary nav under a toggle hamburger.'),
        ),
        migrations.AddField(
            model_name='primarypage',
            name='zen_nav',
            field=models.BooleanField(default=False, help_text='For secondary nav pages, use this to collapse the primary nav under a toggle hamburger.'),
        ),
    ]
