# Generated by Django 2.2.16 on 2020-11-16 20:28

import django.core.validators
import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0015_auto_20201110_1957'),
        ('wagtailpages', '0016_merge_20201117_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='current_vote_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ProductPageVotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='productpagevotes',
            name='vote_bin',
            field=models.CharField(default='0,0,0,0,0', max_length=50, validators=[django.core.validators.int_list_validator]),
        ),
        migrations.AddField(
            model_name='productpage',
            name='votes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votes', to='wagtailpages.ProductPageVotes'),
        ),
    ]
