# Generated by Django 2.2.16 on 2020-11-26 01:47

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0019_auto_20201126_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dearinternetpage',
            name='letters',
            field=wagtail.core.fields.StreamField([('letter', wagtail.core.blocks.StructBlock([('author_name', wagtail.core.blocks.CharBlock()), ('author', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link'], help_text='Author description')), ('author_photo', wagtail.images.blocks.ImageChooserBlock(required=False)), ('letter', wagtail.core.blocks.RichTextBlock(features=['bold', 'link', 'ol', 'ul'], help_text='Main letter content')), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('video_url', wagtail.core.blocks.URLBlock(help_text='Video url to link out to', required=False))]))]),
        ),
        migrations.AlterField(
            model_name='dearinternetpage',
            name='letters_de',
            field=wagtail.core.fields.StreamField([('letter', wagtail.core.blocks.StructBlock([('author_name', wagtail.core.blocks.CharBlock()), ('author', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link'], help_text='Author description')), ('author_photo', wagtail.images.blocks.ImageChooserBlock(required=False)), ('letter', wagtail.core.blocks.RichTextBlock(features=['bold', 'link', 'ol', 'ul'], help_text='Main letter content')), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('video_url', wagtail.core.blocks.URLBlock(help_text='Video url to link out to', required=False))]))], null=True),
        ),
        migrations.AlterField(
            model_name='dearinternetpage',
            name='letters_en',
            field=wagtail.core.fields.StreamField([('letter', wagtail.core.blocks.StructBlock([('author_name', wagtail.core.blocks.CharBlock()), ('author', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link'], help_text='Author description')), ('author_photo', wagtail.images.blocks.ImageChooserBlock(required=False)), ('letter', wagtail.core.blocks.RichTextBlock(features=['bold', 'link', 'ol', 'ul'], help_text='Main letter content')), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('video_url', wagtail.core.blocks.URLBlock(help_text='Video url to link out to', required=False))]))], null=True),
        ),
        migrations.AlterField(
            model_name='dearinternetpage',
            name='letters_es',
            field=wagtail.core.fields.StreamField([('letter', wagtail.core.blocks.StructBlock([('author_name', wagtail.core.blocks.CharBlock()), ('author', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link'], help_text='Author description')), ('author_photo', wagtail.images.blocks.ImageChooserBlock(required=False)), ('letter', wagtail.core.blocks.RichTextBlock(features=['bold', 'link', 'ol', 'ul'], help_text='Main letter content')), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('video_url', wagtail.core.blocks.URLBlock(help_text='Video url to link out to', required=False))]))], null=True),
        ),
        migrations.AlterField(
            model_name='dearinternetpage',
            name='letters_fr',
            field=wagtail.core.fields.StreamField([('letter', wagtail.core.blocks.StructBlock([('author_name', wagtail.core.blocks.CharBlock()), ('author', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link'], help_text='Author description')), ('author_photo', wagtail.images.blocks.ImageChooserBlock(required=False)), ('letter', wagtail.core.blocks.RichTextBlock(features=['bold', 'link', 'ol', 'ul'], help_text='Main letter content')), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('video_url', wagtail.core.blocks.URLBlock(help_text='Video url to link out to', required=False))]))], null=True),
        ),
        migrations.AlterField(
            model_name='dearinternetpage',
            name='letters_fy_NL',
            field=wagtail.core.fields.StreamField([('letter', wagtail.core.blocks.StructBlock([('author_name', wagtail.core.blocks.CharBlock()), ('author', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link'], help_text='Author description')), ('author_photo', wagtail.images.blocks.ImageChooserBlock(required=False)), ('letter', wagtail.core.blocks.RichTextBlock(features=['bold', 'link', 'ol', 'ul'], help_text='Main letter content')), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('video_url', wagtail.core.blocks.URLBlock(help_text='Video url to link out to', required=False))]))], null=True),
        ),
        migrations.AlterField(
            model_name='dearinternetpage',
            name='letters_nl',
            field=wagtail.core.fields.StreamField([('letter', wagtail.core.blocks.StructBlock([('author_name', wagtail.core.blocks.CharBlock()), ('author', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link'], help_text='Author description')), ('author_photo', wagtail.images.blocks.ImageChooserBlock(required=False)), ('letter', wagtail.core.blocks.RichTextBlock(features=['bold', 'link', 'ol', 'ul'], help_text='Main letter content')), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('video_url', wagtail.core.blocks.URLBlock(help_text='Video url to link out to', required=False))]))], null=True),
        ),
        migrations.AlterField(
            model_name='dearinternetpage',
            name='letters_pl',
            field=wagtail.core.fields.StreamField([('letter', wagtail.core.blocks.StructBlock([('author_name', wagtail.core.blocks.CharBlock()), ('author', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link'], help_text='Author description')), ('author_photo', wagtail.images.blocks.ImageChooserBlock(required=False)), ('letter', wagtail.core.blocks.RichTextBlock(features=['bold', 'link', 'ol', 'ul'], help_text='Main letter content')), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('video_url', wagtail.core.blocks.URLBlock(help_text='Video url to link out to', required=False))]))], null=True),
        ),
        migrations.AlterField(
            model_name='dearinternetpage',
            name='letters_pt',
            field=wagtail.core.fields.StreamField([('letter', wagtail.core.blocks.StructBlock([('author_name', wagtail.core.blocks.CharBlock()), ('author', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link'], help_text='Author description')), ('author_photo', wagtail.images.blocks.ImageChooserBlock(required=False)), ('letter', wagtail.core.blocks.RichTextBlock(features=['bold', 'link', 'ol', 'ul'], help_text='Main letter content')), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('video_url', wagtail.core.blocks.URLBlock(help_text='Video url to link out to', required=False))]))], null=True),
        ),
    ]
