# Generated by Django 3.2.13 on 2022-05-05 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('wagtailpages', '0019_researchlibrarypage_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchlandingpage',
            name='banner_image',
            field=models.ForeignKey(blank=True, help_text='Image that will render at the top of the page.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image'),
        ),
    ]
