# Generated by Django 2.2.16 on 2020-12-09 20:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0022_product_voting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpage',
            name='price_de',
        ),
        migrations.RemoveField(
            model_name='productpage',
            name='price_en',
        ),
        migrations.RemoveField(
            model_name='productpage',
            name='price_es',
        ),
        migrations.RemoveField(
            model_name='productpage',
            name='price_fr',
        ),
        migrations.RemoveField(
            model_name='productpage',
            name='price_fy_NL',
        ),
        migrations.RemoveField(
            model_name='productpage',
            name='price_nl',
        ),
        migrations.RemoveField(
            model_name='productpage',
            name='price_pl',
        ),
        migrations.RemoveField(
            model_name='productpage',
            name='price_pt',
        ),
        migrations.AddField(
            model_name='generalproductpage',
            name='ai_helptext_de',
            field=models.TextField(blank=True, help_text='Helpful text around AI to show on the product page', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproductpage',
            name='ai_helptext_en',
            field=models.TextField(blank=True, help_text='Helpful text around AI to show on the product page', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproductpage',
            name='ai_helptext_es',
            field=models.TextField(blank=True, help_text='Helpful text around AI to show on the product page', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproductpage',
            name='ai_helptext_fr',
            field=models.TextField(blank=True, help_text='Helpful text around AI to show on the product page', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproductpage',
            name='ai_helptext_fy_NL',
            field=models.TextField(blank=True, help_text='Helpful text around AI to show on the product page', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproductpage',
            name='ai_helptext_nl',
            field=models.TextField(blank=True, help_text='Helpful text around AI to show on the product page', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproductpage',
            name='ai_helptext_pl',
            field=models.TextField(blank=True, help_text='Helpful text around AI to show on the product page', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproductpage',
            name='ai_helptext_pt',
            field=models.TextField(blank=True, help_text='Helpful text around AI to show on the product page', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproductpage',
            name='biometric_data_collected_de',
            field=models.TextField(blank=True, help_text='What kind of biometric data does this product collect?', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproductpage',
            name='biometric_data_collected_en',
            field=models.TextField(blank=True, help_text='What kind of biometric data does this product collect?', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproductpage',
            name='biometric_data_collected_es',
            field=models.TextField(blank=True, help_text='What kind of biometric data does this product collect?', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproductpage',
            name='biometric_data_collected_fr',
            field=models.TextField(blank=True, help_text='What kind of biometric data does this product collect?', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproductpage',
            name='biometric_data_collected_fy_NL',
            field=models.TextField(blank=True, help_text='What kind of biometric data does this product collect?', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproductpage',
            name='biometric_data_collected_nl',
            field=models.TextField(blank=True, help_text='What kind of biometric data does this product collect?', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproductpage',
            name='biometric_data_collected_pl',
            field=models.TextField(blank=True, help_text='What kind of biometric data does this product collect?', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproductpage',
            name='biometric_data_collected_pt',
            field=models.TextField(blank=True, help_text='What kind of biometric data does this product collect?', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproductpage',
            name='how_can_you_control_your_data_de',
            field=models.TextField(blank=True, help_text='How does this product let you control your data?', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproductpage',
            name='how_can_you_control_your_data_en',
            field=models.TextField(blank=True, help_text='How does this product let you control your data?', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproductpage',
            name='how_can_you_control_your_data_es',
            field=models.TextField(blank=True, help_text='How does this product let you control your data?', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproductpage',
            name='how_can_you_control_your_data_fr',
            field=models.TextField(blank=True, help_text='How does this product let you control your data?', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproductpage',
            name='how_can_you_control_your_data_fy_NL',
            field=models.TextField(blank=True, help_text='How does this product let you control your data?', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproductpage',
            name='how_can_you_control_your_data_nl',
            field=models.TextField(blank=True, help_text='How does this product let you control your data?', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproductpage',
            name='how_can_you_control_your_data_pl',
            field=models.TextField(blank=True, help_text='How does this product let you control your data?', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproductpage',
            name='how_can_you_control_your_data_pt',
            field=models.TextField(blank=True, help_text='How does this product let you control your data?', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproductpage',
            name='personal_data_collected_de',
            field=models.TextField(blank=True, help_text='What kind of personal data does this product collect?', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproductpage',
            name='personal_data_collected_en',
            field=models.TextField(blank=True, help_text='What kind of personal data does this product collect?', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproductpage',
            name='personal_data_collected_es',
            field=models.TextField(blank=True, help_text='What kind of personal data does this product collect?', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproductpage',
            name='personal_data_collected_fr',
            field=models.TextField(blank=True, help_text='What kind of personal data does this product collect?', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproductpage',
            name='personal_data_collected_fy_NL',
            field=models.TextField(blank=True, help_text='What kind of personal data does this product collect?', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproductpage',
            name='personal_data_collected_nl',
            field=models.TextField(blank=True, help_text='What kind of personal data does this product collect?', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproductpage',
            name='personal_data_collected_pl',
            field=models.TextField(blank=True, help_text='What kind of personal data does this product collect?', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproductpage',
            name='personal_data_collected_pt',
            field=models.TextField(blank=True, help_text='What kind of personal data does this product collect?', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproductpage',
            name='track_record_details_de',
            field=models.TextField(blank=True, help_text='Describe the track record of this company here.', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproductpage',
            name='track_record_details_en',
            field=models.TextField(blank=True, help_text='Describe the track record of this company here.', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproductpage',
            name='track_record_details_es',
            field=models.TextField(blank=True, help_text='Describe the track record of this company here.', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproductpage',
            name='track_record_details_fr',
            field=models.TextField(blank=True, help_text='Describe the track record of this company here.', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproductpage',
            name='track_record_details_fy_NL',
            field=models.TextField(blank=True, help_text='Describe the track record of this company here.', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproductpage',
            name='track_record_details_nl',
            field=models.TextField(blank=True, help_text='Describe the track record of this company here.', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproductpage',
            name='track_record_details_pl',
            field=models.TextField(blank=True, help_text='Describe the track record of this company here.', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproductpage',
            name='track_record_details_pt',
            field=models.TextField(blank=True, help_text='Describe the track record of this company here.', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='blurb_de',
            field=models.TextField(blank=True, help_text='Description of the product', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='blurb_en',
            field=models.TextField(blank=True, help_text='Description of the product', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='blurb_es',
            field=models.TextField(blank=True, help_text='Description of the product', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='blurb_fr',
            field=models.TextField(blank=True, help_text='Description of the product', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='blurb_fy_NL',
            field=models.TextField(blank=True, help_text='Description of the product', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='blurb_nl',
            field=models.TextField(blank=True, help_text='Description of the product', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='blurb_pl',
            field=models.TextField(blank=True, help_text='Description of the product', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='blurb_pt',
            field=models.TextField(blank=True, help_text='Description of the product', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='how_does_it_use_data_collected_de',
            field=models.TextField(blank=True, help_text='How does this product use the data collected?', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='how_does_it_use_data_collected_en',
            field=models.TextField(blank=True, help_text='How does this product use the data collected?', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='how_does_it_use_data_collected_es',
            field=models.TextField(blank=True, help_text='How does this product use the data collected?', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='how_does_it_use_data_collected_fr',
            field=models.TextField(blank=True, help_text='How does this product use the data collected?', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='how_does_it_use_data_collected_fy_NL',
            field=models.TextField(blank=True, help_text='How does this product use the data collected?', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='how_does_it_use_data_collected_nl',
            field=models.TextField(blank=True, help_text='How does this product use the data collected?', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='how_does_it_use_data_collected_pl',
            field=models.TextField(blank=True, help_text='How does this product use the data collected?', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='how_does_it_use_data_collected_pt',
            field=models.TextField(blank=True, help_text='How does this product use the data collected?', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='manage_vulnerabilities_helptext_de',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='manage_vulnerabilities_helptext_en',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='manage_vulnerabilities_helptext_es',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='manage_vulnerabilities_helptext_fr',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='manage_vulnerabilities_helptext_fy_NL',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='manage_vulnerabilities_helptext_nl',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='manage_vulnerabilities_helptext_pl',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='manage_vulnerabilities_helptext_pt',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='privacy_policy_helptext_de',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='privacy_policy_helptext_en',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='privacy_policy_helptext_es',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='privacy_policy_helptext_fr',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='privacy_policy_helptext_fy_NL',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='privacy_policy_helptext_nl',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='privacy_policy_helptext_pl',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='privacy_policy_helptext_pt',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='security_updates_helptext_de',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='security_updates_helptext_en',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='security_updates_helptext_es',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='security_updates_helptext_fr',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='security_updates_helptext_fy_NL',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='security_updates_helptext_nl',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='security_updates_helptext_pl',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='security_updates_helptext_pt',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='signup_requirement_explanation_de',
            field=models.TextField(blank=True, help_text='Describe the particulars around sign-up requirements here.', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='signup_requirement_explanation_en',
            field=models.TextField(blank=True, help_text='Describe the particulars around sign-up requirements here.', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='signup_requirement_explanation_es',
            field=models.TextField(blank=True, help_text='Describe the particulars around sign-up requirements here.', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='signup_requirement_explanation_fr',
            field=models.TextField(blank=True, help_text='Describe the particulars around sign-up requirements here.', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='signup_requirement_explanation_fy_NL',
            field=models.TextField(blank=True, help_text='Describe the particulars around sign-up requirements here.', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='signup_requirement_explanation_nl',
            field=models.TextField(blank=True, help_text='Describe the particulars around sign-up requirements here.', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='signup_requirement_explanation_pl',
            field=models.TextField(blank=True, help_text='Describe the particulars around sign-up requirements here.', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='signup_requirement_explanation_pt',
            field=models.TextField(blank=True, help_text='Describe the particulars around sign-up requirements here.', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='strong_password_helptext_de',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='strong_password_helptext_en',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='strong_password_helptext_es',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='strong_password_helptext_fr',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='strong_password_helptext_fy_NL',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='strong_password_helptext_nl',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='strong_password_helptext_pl',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='strong_password_helptext_pt',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='uses_encryption_helptext_de',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='uses_encryption_helptext_en',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='uses_encryption_helptext_es',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='uses_encryption_helptext_fr',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='uses_encryption_helptext_fy_NL',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='uses_encryption_helptext_nl',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='uses_encryption_helptext_pl',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='uses_encryption_helptext_pt',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='worst_case_de',
            field=models.CharField(blank=True, help_text="What's the worst thing that could happen by using this product?", max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='worst_case_en',
            field=models.CharField(blank=True, help_text="What's the worst thing that could happen by using this product?", max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='worst_case_es',
            field=models.CharField(blank=True, help_text="What's the worst thing that could happen by using this product?", max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='worst_case_fr',
            field=models.CharField(blank=True, help_text="What's the worst thing that could happen by using this product?", max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='worst_case_fy_NL',
            field=models.CharField(blank=True, help_text="What's the worst thing that could happen by using this product?", max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='worst_case_nl',
            field=models.CharField(blank=True, help_text="What's the worst thing that could happen by using this product?", max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='worst_case_pl',
            field=models.CharField(blank=True, help_text="What's the worst thing that could happen by using this product?", max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='worst_case_pt',
            field=models.CharField(blank=True, help_text="What's the worst thing that could happen by using this product?", max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='review_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Review date of this product'),
        ),
    ]
