# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-15 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0022_auto_20180511_1729'),
        ('wagtailpages', '0022_auto_20180511_2056'),
    ]

    operations = [
    ]
