# Generated by Django 3.2.13 on 2022-05-30 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('wagtailpages', '0025_publication_hero_customization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchdetailpage',
            name='cover_image',
            field=models.ForeignKey(help_text='Select a cover image for this research. The cover image is displayed on the detail page and all research listings.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='researchdetailpage',
            name='introduction',
            field=models.CharField(blank=True, help_text='Provide a short blurb about the research that will be displayed on listing pages and search results.', max_length=300),
        ),
        migrations.AlterField(
            model_name='researchdetailpage',
            name='original_publication_date',
            field=models.DateField(blank=True, help_text='When was the research (not this page) originally published?', null=True),
        ),
    ]
