# Generated by Django 3.2.13 on 2022-05-25 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0025_update_blogpagetopic_help_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpage',
            old_name='category',
            new_name='topics',
        ),
    ]
