# Generated by Django 2.2.17 on 2021-01-13 21:12

from django.db import migrations, models


def set_pni_homepage_textfields(apps, schema_editor):
    BuyersGuidePage = apps.get_model("wagtailpages", "BuyersGuidePage")
    for page in BuyersGuidePage.objects.filter(header=''):
        page.header_en = 'Be Smart. Shop Safe.'
        page.intro_text_en = (
            'How creepy is that smart speaker, that fitness tracker'
            ', those wireless headphones? We created this guide to help you shop for safe'
            ', secure connected products.'
        )
        page.save()


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0026_buyersguidepage_hero_image copy'),
    ]

    operations = [
        migrations.RunPython(set_pni_homepage_textfields),
    ]
