# Generated by Django 2.2.17 on 2021-01-25 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('wagtailpages', '0029_productpage_airtable_record_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='toc_thumbnail_image',
            field=models.ForeignKey(blank=True, help_text='Thumbnail image to show on table of content. Use square image of 320×320 pixels or larger.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Table of Content Thumbnail'),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='toc_thumbnail_image',
            field=models.ForeignKey(blank=True, help_text='Thumbnail image to show on table of content. Use square image of 320×320 pixels or larger.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='toc_thumbnail_image', to='wagtailimages.Image', verbose_name='Table of Content Thumbnail'),
        ),
    ]
