# Generated by Django 3.2.13 on 2022-06-27 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0029_featuredvideopost'),
        ('wagtailpages', '0030_populate_profile_slug'),
    ]

    operations = [
    ]
