# # Generated by Django 3.0.14 on 2021-08-10 18:19

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.blocks.static_block
import wagtail.core.fields
import wagtail.images.blocks
import wagtailmedia.blocks


from networkapi.wagtailpages.pagemodels.blog.blog import BlogPage
from networkapi.wagtailpages.pagemodels.modular import ModularPage
from networkapi.wagtailpages.pagemodels.primary import PrimaryPage


def update_annotated_image_blocks(qs):
    # Loop through all pages
    for page in qs:
        # If this page doesn't have a Image that needs update, don't save it.
        # This will speed up how fast this task can run
        needs_saving = False
        # Only loop through streamfield data if there's a `body` field on the page
        if page.body:
            # Checking if page.body has raw_data, and looping through it.
            if hasattr(page.body, 'raw_data'):
                for block in page.body.raw_data:
                    # If the block type is an image,
                    # check if the image has the wide setting on.
                    if 'type' in block and block['type'] == "image":
                        # If so, set the new image_width value to wide.
                        if 'wide_image' in block['value'] and block['value']['wide_image'] == True:
                            block['value']['image_width'] = "wide"
                            needs_saving = True

            # If page is published already, continue to publish it.
            # Otherwise just save a revision for draft history.
            if needs_saving:
                revision = page.save_revision()
                if page.live:
                    revision.publish()

def loop_through_pages_with_image_blocks(apps, schema):
    # Only look through pages that use the Annotated Image Block streamfield.

    pages_with_image_blocks = [
        BlogPage.objects.all(),
        PrimaryPage.objects.all(),
        ModularPage.objects.all(),
    ]

    for page_qs in pages_with_image_blocks:
        if page_qs.count() != 0:
            update_annotated_image_blocks(page_qs)

class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0031_auto_20210818_0231'),
    ]

    operations = [
        migrations.RunPython(loop_through_pages_with_image_blocks)
    ]
