# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-16 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0032_auto_20180712_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiativespage',
            name='testField',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
