# Generated by Django 2.2.17 on 2021-02-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0033_auto_20210202_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyersguidepage',
            name='dark_theme',
            field=models.BooleanField(default=False, help_text='Does the intro need to be white text (for dark backgrounds)?'),
        ),
    ]
