# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-23 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailinventory', '0001_initial'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailpages', '0036_auto_20180823_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cta4',
            name='hero',
        ),
        migrations.RemoveField(
            model_name='cta4',
            name='page',
        ),
        migrations.RemoveField(
            model_name='participatehighlights',
            name='highlight',
        ),
        migrations.RemoveField(
            model_name='participatehighlights',
            name='page',
        ),
        migrations.RemoveField(
            model_name='participatehighlights2',
            name='highlight',
        ),
        migrations.RemoveField(
            model_name='participatehighlights2',
            name='page',
        ),
        migrations.RemoveField(
            model_name='participatepage2',
            name='ctaHero',
        ),
        migrations.RemoveField(
            model_name='participatepage2',
            name='ctaHero2',
        ),
        migrations.RemoveField(
            model_name='participatepage2',
            name='ctaHero3',
        ),
        migrations.RemoveField(
            model_name='participatepage2',
            name='primarypage_ptr',
        ),
        migrations.AddField(
            model_name='petition',
            name='comment_requirements',
            field=models.CharField(choices=[('none', 'No comments'), ('optional', 'Optional comments'), ('required', 'Required comments')], default='none', help_text='What is the comments policy for this petition?', max_length=8),
        ),
        migrations.DeleteModel(
            name='CTA4',
        ),
        migrations.DeleteModel(
            name='ParticipateHighlights',
        ),
        migrations.DeleteModel(
            name='ParticipateHighlights2',
        ),
        migrations.DeleteModel(
            name='ParticipatePage2',
        ),
    ]
