# Generated by Django 3.1.11 on 2021-09-26 21:56

from django.db import migrations, models
import networkapi.wagtailpages.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0038_auto_20210924_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalproductpage',
            name='ai_can_user_control',
            field=networkapi.wagtailpages.fields.ExtendedYesNoField(help_text='Does the user have control over the AI features?'),
        ),
        migrations.AddField(
            model_name='generalproductpage',
            name='ai_can_user_control_helptext',
            field=models.TextField(blank=True, help_text='Helptext that will appear in the can user control section.', max_length=5000),
        ),
        migrations.AddField(
            model_name='generalproductpage',
            name='ai_is_transparent_helptext',
            field=models.TextField(blank=True, help_text='Helptext that will appear in the AI is transparent section.', max_length=5000),
        ),
        migrations.AddField(
            model_name='generalproductpage',
            name='ai_is_untrustworthy_helptext',
            field=models.TextField(blank=True, help_text='Helptext that will appear in the AI is untrustworthy section.', max_length=5000),
        ),
    ]
