# Generated by Django 3.1.11 on 2021-09-27 21:40

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0038_auto_20210924_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='tips_to_protect_yourself',
            field=wagtail.core.fields.StreamField([('tip', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link']))], blank=True),
        ),
    ]
