# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-18 01:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailimages', '0020_add-verbose-name'),
        ('wagtailinventory', '0001_initial'),
        ('wagtailpages', '0039_auto_20181009_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participatepage2',
            name='ctaHero',
        ),
        migrations.RemoveField(
            model_name='participatepage2',
            name='ctaHero2',
        ),
        migrations.RemoveField(
            model_name='participatepage2',
            name='ctaHero3',
        ),
        migrations.RemoveField(
            model_name='participatepage2',
            name='primarypage_ptr',
        ),
        migrations.AddField(
            model_name='participatepage',
            name='ctaButtonTitle',
            field=models.CharField(blank=True, max_length=250, verbose_name='Button Text'),
        ),
        migrations.AddField(
            model_name='participatepage',
            name='ctaButtonTitle2',
            field=models.CharField(blank=True, max_length=250, verbose_name='Button Text'),
        ),
        migrations.AddField(
            model_name='participatepage',
            name='ctaButtonURL',
            field=models.TextField(blank=True, verbose_name='Button URL'),
        ),
        migrations.AddField(
            model_name='participatepage',
            name='ctaButtonURL2',
            field=models.TextField(blank=True, verbose_name='Button URL'),
        ),
        migrations.AddField(
            model_name='participatepage',
            name='ctaCommitment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='participatepage',
            name='ctaCommitment2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='participatepage',
            name='ctaCommitment3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='participatepage',
            name='ctaEmailShareBody3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='participatepage',
            name='ctaEmailShareSubject3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='participatepage',
            name='ctaFacebook3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='participatepage',
            name='ctaHero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_hero_participate', to='wagtailimages.Image', verbose_name='Primary Hero Image'),
        ),
        migrations.AddField(
            model_name='participatepage',
            name='ctaHero2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_hero_participate2', to='wagtailimages.Image', verbose_name='Primary Hero Image'),
        ),
        migrations.AddField(
            model_name='participatepage',
            name='ctaHero3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_hero_participate3', to='wagtailimages.Image', verbose_name='Primary Hero Image'),
        ),
        migrations.AddField(
            model_name='participatepage',
            name='ctaHeroHeader',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='participatepage',
            name='ctaHeroHeader2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='participatepage',
            name='ctaHeroHeader3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='participatepage',
            name='ctaHeroSubhead',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='participatepage',
            name='ctaHeroSubhead2',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='participatepage',
            name='ctaHeroSubhead3',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='participatepage',
            name='ctaTwitter3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='participatepage',
            name='h2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='participatepage',
            name='h2Subheader',
            field=models.TextField(blank=True, verbose_name='H2 Subheader'),
        ),
        migrations.AlterField(
            model_name='cta4',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='cta4', to='wagtailpages.ParticipatePage'),
        ),
        migrations.AlterField(
            model_name='participatehighlights',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_highlights', to='wagtailpages.ParticipatePage'),
        ),
        migrations.AlterField(
            model_name='participatehighlights2',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_highlights2', to='wagtailpages.ParticipatePage'),
        ),
        migrations.DeleteModel(
            name='ParticipatePage2',
        ),
    ]
