# Generated by Django 3.2.13 on 2022-07-29 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0039_buyersguidearticlepage_buyersguideeditorialcontentindexpage'),
        ('wagtailpages', '0039_research_detail_link_sort_order'),
    ]

    operations = [
    ]
