# Generated by Django 3.2.13 on 2022-07-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0040_buyersguidecontentcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyersguidecontentcategory',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
