# Generated by Django 3.2.13 on 2022-08-03 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0040_buyersguidecontentcategory'),
        ('wagtailpages', '0040_research_detail_link_sort_order'),
    ]

    operations = [
    ]
