# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-07 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0020_add-verbose-name'),
        ('wagtailpages', '0040_participatehighlights_commitment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipatePage2',
            fields=[
                ('primarypage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailpages.PrimaryPage')),
                ('heroHeader', models.TextField(blank=True)),
                ('heroSubhead', wagtail.core.fields.RichTextField(blank=True)),
                ('commitment', models.TextField(blank=True)),
                ('ctaButtonTitle', models.CharField(blank=True, max_length=250, verbose_name='Button Text')),
                ('ctaButtonURL', models.TextField(blank=True, verbose_name='Button URL')),
                ('h2', models.TextField(blank=True)),
                ('h2Subheader', models.TextField(blank=True)),
                ('primaryHero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_hero_participate', to='wagtailimages.Image', verbose_name='Primary Hero Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailpages.primarypage',),
        ),
        migrations.RemoveField(
            model_name='participatepage',
            name='commitment',
        ),
        migrations.RemoveField(
            model_name='participatepage',
            name='ctaButtonTitle',
        ),
        migrations.RemoveField(
            model_name='participatepage',
            name='ctaButtonURL',
        ),
        migrations.RemoveField(
            model_name='participatepage',
            name='h2',
        ),
        migrations.RemoveField(
            model_name='participatepage',
            name='h2Subheader',
        ),
        migrations.RemoveField(
            model_name='participatepage',
            name='heroHeader',
        ),
        migrations.RemoveField(
            model_name='participatepage',
            name='heroSubhead',
        ),
        migrations.RemoveField(
            model_name='participatepage',
            name='primaryHero',
        ),
        migrations.AlterField(
            model_name='participatehighlights',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_highlights', to='wagtailpages.ParticipatePage2'),
        ),
    ]
