# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-20 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('wagtailpages', '0040_auto_20180720_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiativespage',
            name='primaryHero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_hero', to='wagtailimages.Image', verbose_name='Primary Hero Image'),
        ),
    ]
