# Generated by Django 2.2.17 on 2021-03-16 19:12

from django.db import migrations
from wagtail.core.models import BootstrapTranslatableModel


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0041_auto_20210316_1912'),
    ]

    operations = [
        BootstrapTranslatableModel('wagtailpages.ProductPagePrivacyPolicyLink'),
    ]
