# Generated by Django 3.1.11 on 2021-10-19 21:33

from django.db import migrations, models
import django.db.models.deletion
import uuid
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('wagtailpages', '0041_cta_refactor_4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banneredcampaignpage',
            name='cta',
            field=models.ForeignKey(blank=True, help_text='Choose one of our call-to-action snippets, or create a new one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_page_for_cta', to='wagtailpages.cta'),
        ),
        migrations.AlterField(
            model_name='campaignpage',
            name='cta',
            field=models.ForeignKey(blank=True, help_text='Choose one of our call-to-action snippets, or create a new one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_page_for_cta', to='wagtailpages.cta'),
        ),
        migrations.CreateModel(
            name='Callpower',
            fields=[
                ('cta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailpages.cta')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('campaign_id', models.CharField(help_text='Which Callpower campaign identifier should this CTA be tied to?', max_length=20)),
                ('call_button_label', models.CharField(default='Make the call', help_text='The call button label (defaults to "Make the call")', max_length=20)),
                ('success_heading', models.CharField(default='Thank you for calling', help_text='The heading users will see after clicking the call button (defaults to "Thank you for calling")', max_length=50)),
                ('success_text', wagtail.core.fields.RichTextField(blank=True, help_text='The text users will see after clicking the call button')),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale')),
            ],
            options={
                'verbose_name': 'callpower snippet',
                'abstract': False,
                'unique_together': {('translation_key', 'locale')},
            },
            bases=('wagtailpages.cta', models.Model),
        ),
    ]
