# Generated by Django 3.2.13 on 2022-07-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0043_auto_20220727_2230'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='buyersguidecontentcategory',
            name='unique_slug',
        ),
        migrations.AlterField(
            model_name='buyersguidecontentcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
