# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-08 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0043_auto_20180808_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foo', models.CharField(blank=True, max_length=128)),
                ('bar', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Examples',
            },
        ),
        migrations.AddField(
            model_name='participatepage2',
            name='example',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailpages.Example'),
        ),
    ]
