# Generated by Django 3.1.11 on 2021-09-21 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0043_auto_20210917_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='mozilla_says',
            field=models.BooleanField(blank=True, help_text='Whether or not Mozilla would recommend this product. Will appear as a thumbs up/down/middle.', null=True),
        ),
    ]
