# Generated by Django 3.1.11 on 2021-10-25 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0043_auto_20211020_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalproductpage',
            name='ai_uses_personal_data',
        ),
    ]
