# Generated by Django 2.2.17 on 2021-03-11 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('wagtailpages', '0045_buyersguideproductcategory_2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogAuthor',
            new_name='ContentAuthor',
        ),
    ]
