# Generated by Django 3.2.13 on 2022-08-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0045_buyersguidepageherosupportingarticlerelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyersguidepage',
            name='hero_supporting_articles_heading',
            field=models.CharField(default='Related articles', help_text='Heading for the articles rendered next to the hero featured article. Common choices are "Related articles", "Popular articles", etc.', max_length=50),
        ),
    ]
