# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-09 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0046_auto_20180808_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participatepage2',
            name='foo',
        ),
        migrations.AddField(
            model_name='foo',
            name='bar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='foo',
            name='page',
            field=modelcluster.fields.ParentalKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='foos', to='wagtailpages.ParticipatePage2'),
            preserve_default=False,
        ),
    ]
