# Generated by Django 2.2.17 on 2021-03-16 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('wagtailpages', '0049_advanced_table_block'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogAuthor',
            new_name='ContentAuthor',
        ),
    ]
