# Generated by Django 3.1.11 on 2021-11-04 17:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('wagtailpages', '0049_auto_20211101_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='cta',
            name='locale',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cta',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='callpower',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='cta',
            unique_together={('translation_key', 'locale')},
        ),
        migrations.AlterUniqueTogether(
            name='petition',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='signup',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='callpower',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='callpower',
            name='translation_key',
        ),
        migrations.RemoveField(
            model_name='petition',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='petition',
            name='translation_key',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='translation_key',
        ),
    ]
