# Generated by Django 3.2.16 on 2022-10-27 17:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailpages", "0049_adds_image_teaser_block"),
        ("wagtailpages", "0051_adds_group_listing_block"),
        ("wagtailpages", "0051_adds_image_teaser_block"),
    ]

    operations = []
