# Generated by Django 3.2.13 on 2022-08-29 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0052_bg_article_index_related_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyersguideeditorialcontentindexpage',
            name='related_articles_heading',
        ),
    ]
