# Generated by Django 2.2.17 on 2021-03-19 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0052_auto_20210317_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='publication_date',
            field=models.DateField(blank=True, null=True, verbose_name='Publication date'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='secondary_subtitle',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
