# Generated by Django 2.2.17 on 2021-03-25 17:57

from django.db import migrations
import networkapi.wagtailpages.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0053_auto_20210319_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalproductpage',
            name='ai_is_transparent',
            field=networkapi.wagtailpages.fields.ExtendedYesNoField(help_text='Does the company allow users to see how the AI works?'),
        ),
        migrations.AlterField(
            model_name='generalproductpage',
            name='ai_uses_personal_data',
            field=networkapi.wagtailpages.fields.ExtendedYesNoField(help_text='Does the AI use your personal data to make decisions about you?'),
        ),
        migrations.AlterField(
            model_name='generalproductpage',
            name='camera_app',
            field=networkapi.wagtailpages.fields.ExtendedYesNoField(help_text='Does the app have or access a camera?'),
        ),
        migrations.AlterField(
            model_name='generalproductpage',
            name='camera_device',
            field=networkapi.wagtailpages.fields.ExtendedYesNoField(help_text='Does this device have or access a camera?'),
        ),
        migrations.AlterField(
            model_name='generalproductpage',
            name='location_app',
            field=networkapi.wagtailpages.fields.ExtendedYesNoField(help_text='Does this app access your location?'),
        ),
        migrations.AlterField(
            model_name='generalproductpage',
            name='location_device',
            field=networkapi.wagtailpages.fields.ExtendedYesNoField(help_text='Does this product access your location?'),
        ),
        migrations.AlterField(
            model_name='generalproductpage',
            name='microphone_app',
            field=networkapi.wagtailpages.fields.ExtendedYesNoField(help_text='Does this app have or access a microphone?'),
        ),
        migrations.AlterField(
            model_name='generalproductpage',
            name='microphone_device',
            field=networkapi.wagtailpages.fields.ExtendedYesNoField(help_text='Does this Device have or access a microphone?'),
        ),
        migrations.AlterField(
            model_name='generalproductpage',
            name='offline_capable',
            field=networkapi.wagtailpages.fields.ExtendedYesNoField(help_text='Can this product be used offline?'),
        ),
        migrations.AlterField(
            model_name='generalproductpage',
            name='uses_ai',
            field=networkapi.wagtailpages.fields.ExtendedYesNoField(help_text='Does the product use AI?'),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='manage_vulnerabilities',
            field=networkapi.wagtailpages.fields.ExtendedYesNoField(help_text='Manages security vulnerabilities?'),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='privacy_policy',
            field=networkapi.wagtailpages.fields.ExtendedYesNoField(help_text='Does this product have a privacy policy?'),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='security_updates',
            field=networkapi.wagtailpages.fields.ExtendedYesNoField(help_text='Security updates?'),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='signup_requires_email',
            field=networkapi.wagtailpages.fields.ExtendedYesNoField(help_text='Does this product requires providing an email address in order to sign up?'),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='signup_requires_phone',
            field=networkapi.wagtailpages.fields.ExtendedYesNoField(help_text='Does this product requires providing a phone number in order to sign up?'),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='signup_requires_third_party_account',
            field=networkapi.wagtailpages.fields.ExtendedYesNoField(help_text='Does this product require a third party account in order to sign up?'),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='strong_password',
            field=networkapi.wagtailpages.fields.ExtendedYesNoField(),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='user_friendly_privacy_policy',
            field=networkapi.wagtailpages.fields.ExtendedYesNoField(help_text='Does this product have a user-friendly privacy policy?'),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='uses_encryption',
            field=networkapi.wagtailpages.fields.ExtendedYesNoField(help_text='Does the product use encryption?'),
        ),
        migrations.AlterField(
            model_name='softwareproductpage',
            name='recording_alert',
            field=networkapi.wagtailpages.fields.ExtendedYesNoField(help_text='Alerts when calls are being recorded?', null=True),
        ),
    ]
