# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-16 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0053_participatehighlights2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipateCTA3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foo', models.TextField(blank=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='cta3', to='wagtailpages.ParticipatePage2')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
