# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-16 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0020_add-verbose-name'),
        ('wagtailpages', '0054_participatecta3'),
    ]

    operations = [
        migrations.AddField(
            model_name='participatecta3',
            name='NEWctaHero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='NEWprimary_hero_participate', to='wagtailimages.Image', verbose_name='Primary Hero Image'),
        ),
    ]
