# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-16 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0055_participatecta3_newctahero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participatecta3',
            name='NEWctaHero',
        ),
        migrations.RemoveField(
            model_name='participatecta3',
            name='page',
        ),
        migrations.DeleteModel(
            name='ParticipateCTA3',
        ),
    ]
