# Generated by Django 3.1.11 on 2021-11-29 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0058_featureflags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petition',
            options={'ordering': ['-id'], 'verbose_name': 'petition snippet'},
        ),
    ]
