# Generated by Django 3.1.11 on 2021-11-29 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0059_auto_20211129_1931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petition',
            options={'ordering': ['-id'], 'verbose_name': 'petition snippet'},
        ),
    ]
