# Generated by Django 3.1.11 on 2021-12-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0061_auto_20211210_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyersguideproductcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
