# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-20 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0061_auto_20180816_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='participatepage2',
            name='ctaFacebook3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='participatepage2',
            name='ctaGenericShare3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='participatepage2',
            name='ctaTwitter3',
            field=models.TextField(blank=True),
        ),
    ]
