# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-27 23:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0062_merge_20190325_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='banneredcampaignpage',
            name='signup',
            field=models.ForeignKey(blank=True, help_text='Choose an existing, or create a new, sign-up form', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bcpage', to='wagtailpages.Signup'),
        ),
        migrations.AlterField(
            model_name='banneredcampaignpage',
            name='cta',
            field=models.ForeignKey(blank=True, help_text='Choose an existing, or create a new, pettition form', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bcpage', to='wagtailpages.Petition'),
        ),
    ]
