# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-20 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0063_auto_20180820_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participatepage2',
            old_name='ctaEmailShareBody',
            new_name='ctaEmailShareBody3',
        ),
        migrations.RenameField(
            model_name='participatepage2',
            old_name='ctaEmailShareSubject',
            new_name='ctaEmailShareSubject3',
        ),
    ]
