# Generated by Django 3.1.11 on 2022-01-26 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0067_auto_20220125_2235'),
        ('wagtailpages', '0067_related_blog_posts_sort_order'),
    ]

    operations = [
    ]
