# Generated by Django 2.2.1 on 2019-05-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0068_auto_20190509_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='ask_name',
            field=models.BooleanField(default=False, help_text='Check this box to show (optional) name fields'),
        ),
    ]
