# Generated by Django 2.2.3 on 2019-07-23 16:43

from django.db import migrations, models
import django.db.models.deletion
import wagtailmetadata.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailpages', '0070_auto_20190716_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('header', models.CharField(blank=True, max_length=250)),
                ('header_en', models.CharField(blank=True, max_length=250, null=True)),
                ('header_de', models.CharField(blank=True, max_length=250, null=True)),
                ('header_pt', models.CharField(blank=True, max_length=250, null=True)),
                ('header_es', models.CharField(blank=True, max_length=250, null=True)),
                ('header_fr', models.CharField(blank=True, max_length=250, null=True)),
                ('header_pl', models.CharField(blank=True, max_length=250, null=True)),
                ('intro', models.CharField(blank=True, help_text='Intro paragraph to show in hero cutout box', max_length=250)),
                ('intro_en', models.CharField(blank=True, help_text='Intro paragraph to show in hero cutout box', max_length=250, null=True)),
                ('intro_de', models.CharField(blank=True, help_text='Intro paragraph to show in hero cutout box', max_length=250, null=True)),
                ('intro_pt', models.CharField(blank=True, help_text='Intro paragraph to show in hero cutout box', max_length=250, null=True)),
                ('intro_es', models.CharField(blank=True, help_text='Intro paragraph to show in hero cutout box', max_length=250, null=True)),
                ('intro_fr', models.CharField(blank=True, help_text='Intro paragraph to show in hero cutout box', max_length=250, null=True)),
                ('intro_pl', models.CharField(blank=True, help_text='Intro paragraph to show in hero cutout box', max_length=250, null=True)),
                ('search_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Search image')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtailmetadata.models.MetadataMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='BlogListingPage',
            fields=[
                ('listingpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailpages.ListingPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailpages.listingpage',),
        ),
    ]
