# Generated by Django 2.2.3 on 2019-08-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0071_indexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpage',
            name='page_size',
            field=models.IntegerField(choices=[(4, '4'), (8, '8'), (12, '12'), (24, '24')], default=12, help_text='The number of entries to show by default, and per incremental load'),
        ),
    ]
