# Generated by Django 3.1.11 on 2022-02-10 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0073_auto_20220210_0020'),
    ]

    operations = [
    ]
