# Generated by Django 2.2.4 on 2019-08-22 17:30

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0074_specialtemplatepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialtemplatepage',
            name='textfields_de',
            field=wagtail.core.fields.StreamField([('textblock', wagtail.core.blocks.StructBlock([('key', wagtail.core.blocks.CharBlock(help_text='the identifier to use in templates for fetching the text in this text block.', required=True)), ('textblock', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'h2', 'h3', 'h4', 'h5', 'h6', 'ol', 'ul', 'link'], help_text='The page text that will be rendered into the page, using the associated key.'))]))], null=True),
        ),
        migrations.AddField(
            model_name='specialtemplatepage',
            name='textfields_en',
            field=wagtail.core.fields.StreamField([('textblock', wagtail.core.blocks.StructBlock([('key', wagtail.core.blocks.CharBlock(help_text='the identifier to use in templates for fetching the text in this text block.', required=True)), ('textblock', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'h2', 'h3', 'h4', 'h5', 'h6', 'ol', 'ul', 'link'], help_text='The page text that will be rendered into the page, using the associated key.'))]))], null=True),
        ),
        migrations.AddField(
            model_name='specialtemplatepage',
            name='textfields_es',
            field=wagtail.core.fields.StreamField([('textblock', wagtail.core.blocks.StructBlock([('key', wagtail.core.blocks.CharBlock(help_text='the identifier to use in templates for fetching the text in this text block.', required=True)), ('textblock', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'h2', 'h3', 'h4', 'h5', 'h6', 'ol', 'ul', 'link'], help_text='The page text that will be rendered into the page, using the associated key.'))]))], null=True),
        ),
        migrations.AddField(
            model_name='specialtemplatepage',
            name='textfields_fr',
            field=wagtail.core.fields.StreamField([('textblock', wagtail.core.blocks.StructBlock([('key', wagtail.core.blocks.CharBlock(help_text='the identifier to use in templates for fetching the text in this text block.', required=True)), ('textblock', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'h2', 'h3', 'h4', 'h5', 'h6', 'ol', 'ul', 'link'], help_text='The page text that will be rendered into the page, using the associated key.'))]))], null=True),
        ),
        migrations.AddField(
            model_name='specialtemplatepage',
            name='textfields_pl',
            field=wagtail.core.fields.StreamField([('textblock', wagtail.core.blocks.StructBlock([('key', wagtail.core.blocks.CharBlock(help_text='the identifier to use in templates for fetching the text in this text block.', required=True)), ('textblock', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'h2', 'h3', 'h4', 'h5', 'h6', 'ol', 'ul', 'link'], help_text='The page text that will be rendered into the page, using the associated key.'))]))], null=True),
        ),
        migrations.AddField(
            model_name='specialtemplatepage',
            name='textfields_pt',
            field=wagtail.core.fields.StreamField([('textblock', wagtail.core.blocks.StructBlock([('key', wagtail.core.blocks.CharBlock(help_text='the identifier to use in templates for fetching the text in this text block.', required=True)), ('textblock', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'h2', 'h3', 'h4', 'h5', 'h6', 'ol', 'ul', 'link'], help_text='The page text that will be rendered into the page, using the associated key.'))]))], null=True),
        ),
    ]
