# Generated by Django 2.2.4 on 2019-08-30 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0074_auto_20190827_2235'),
        ('wagtailpages', '0075_auto_20190829_2317'),
    ]

    operations = [
    ]
