# Generated by Django 2.2.4 on 2019-09-17 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtailpages', '0082_homepagefeaturedblogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiativesection',
            name='sectionButtonTitle2_de',
            field=models.CharField(blank='True', max_length=250, null=True, verbose_name='Button 2 Text'),
        ),
        migrations.AddField(
            model_name='initiativesection',
            name='sectionButtonTitle2_en',
            field=models.CharField(blank='True', max_length=250, null=True, verbose_name='Button 2 Text'),
        ),
        migrations.AddField(
            model_name='initiativesection',
            name='sectionButtonTitle2_es',
            field=models.CharField(blank='True', max_length=250, null=True, verbose_name='Button 2 Text'),
        ),
        migrations.AddField(
            model_name='initiativesection',
            name='sectionButtonTitle2_fr',
            field=models.CharField(blank='True', max_length=250, null=True, verbose_name='Button 2 Text'),
        ),
        migrations.AddField(
            model_name='initiativesection',
            name='sectionButtonTitle2_pl',
            field=models.CharField(blank='True', max_length=250, null=True, verbose_name='Button 2 Text'),
        ),
        migrations.AddField(
            model_name='initiativesection',
            name='sectionButtonTitle2_pt',
            field=models.CharField(blank='True', max_length=250, null=True, verbose_name='Button 2 Text'),
        ),
        migrations.AddField(
            model_name='initiativesection',
            name='sectionButtonTitle_de',
            field=models.CharField(max_length=250, null=True, verbose_name='Button Text'),
        ),
        migrations.AddField(
            model_name='initiativesection',
            name='sectionButtonTitle_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Button Text'),
        ),
        migrations.AddField(
            model_name='initiativesection',
            name='sectionButtonTitle_es',
            field=models.CharField(max_length=250, null=True, verbose_name='Button Text'),
        ),
        migrations.AddField(
            model_name='initiativesection',
            name='sectionButtonTitle_fr',
            field=models.CharField(max_length=250, null=True, verbose_name='Button Text'),
        ),
        migrations.AddField(
            model_name='initiativesection',
            name='sectionButtonTitle_pl',
            field=models.CharField(max_length=250, null=True, verbose_name='Button Text'),
        ),
        migrations.AddField(
            model_name='initiativesection',
            name='sectionButtonTitle_pt',
            field=models.CharField(max_length=250, null=True, verbose_name='Button Text'),
        ),
        migrations.AddField(
            model_name='initiativesection',
            name='sectionCopy_de',
            field=models.TextField(null=True, verbose_name='Subheader'),
        ),
        migrations.AddField(
            model_name='initiativesection',
            name='sectionCopy_en',
            field=models.TextField(null=True, verbose_name='Subheader'),
        ),
        migrations.AddField(
            model_name='initiativesection',
            name='sectionCopy_es',
            field=models.TextField(null=True, verbose_name='Subheader'),
        ),
        migrations.AddField(
            model_name='initiativesection',
            name='sectionCopy_fr',
            field=models.TextField(null=True, verbose_name='Subheader'),
        ),
        migrations.AddField(
            model_name='initiativesection',
            name='sectionCopy_pl',
            field=models.TextField(null=True, verbose_name='Subheader'),
        ),
        migrations.AddField(
            model_name='initiativesection',
            name='sectionCopy_pt',
            field=models.TextField(null=True, verbose_name='Subheader'),
        ),
        migrations.AddField(
            model_name='initiativesection',
            name='sectionHeader_de',
            field=models.CharField(max_length=250, null=True, verbose_name='Header'),
        ),
        migrations.AddField(
            model_name='initiativesection',
            name='sectionHeader_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Header'),
        ),
        migrations.AddField(
            model_name='initiativesection',
            name='sectionHeader_es',
            field=models.CharField(max_length=250, null=True, verbose_name='Header'),
        ),
        migrations.AddField(
            model_name='initiativesection',
            name='sectionHeader_fr',
            field=models.CharField(max_length=250, null=True, verbose_name='Header'),
        ),
        migrations.AddField(
            model_name='initiativesection',
            name='sectionHeader_pl',
            field=models.CharField(max_length=250, null=True, verbose_name='Header'),
        ),
        migrations.AddField(
            model_name='initiativesection',
            name='sectionHeader_pt',
            field=models.CharField(max_length=250, null=True, verbose_name='Header'),
        ),
        migrations.AddField(
            model_name='initiativesection',
            name='sectionImage_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_image', to='wagtailimages.Image', verbose_name='Hero Image'),
        ),
        migrations.AddField(
            model_name='initiativesection',
            name='sectionImage_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_image', to='wagtailimages.Image', verbose_name='Hero Image'),
        ),
        migrations.AddField(
            model_name='initiativesection',
            name='sectionImage_es',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_image', to='wagtailimages.Image', verbose_name='Hero Image'),
        ),
        migrations.AddField(
            model_name='initiativesection',
            name='sectionImage_fr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_image', to='wagtailimages.Image', verbose_name='Hero Image'),
        ),
        migrations.AddField(
            model_name='initiativesection',
            name='sectionImage_pl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_image', to='wagtailimages.Image', verbose_name='Hero Image'),
        ),
        migrations.AddField(
            model_name='initiativesection',
            name='sectionImage_pt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_image', to='wagtailimages.Image', verbose_name='Hero Image'),
        ),
        migrations.AddField(
            model_name='initiativespage',
            name='h3_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='initiativespage',
            name='h3_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='initiativespage',
            name='h3_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='initiativespage',
            name='h3_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='initiativespage',
            name='h3_pl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='initiativespage',
            name='h3_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='initiativespage',
            name='sub_h3_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='initiativespage',
            name='sub_h3_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='initiativespage',
            name='sub_h3_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='initiativespage',
            name='sub_h3_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='initiativespage',
            name='sub_h3_pl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='initiativespage',
            name='sub_h3_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='initiativespage',
            name='subheader_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='initiativespage',
            name='subheader_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='initiativespage',
            name='subheader_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='initiativespage',
            name='subheader_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='initiativespage',
            name='subheader_pl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='initiativespage',
            name='subheader_pt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
