# Generated by Django 2.2.4 on 2019-09-18 23:28

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtailmetadata.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtailpages', '0083_auto_20190918_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialTemplatePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('template', models.CharField(choices=[(None, '-'), ('wagtailpages/one-off-pages/youtube.html', 'Youtube Campaign')], default=None, help_text='The template to be used to render this one-off page', max_length=500)),
                ('textfields', wagtail.core.fields.StreamField([('textblock', wagtail.core.blocks.StructBlock([('key', wagtail.core.blocks.CharBlock(required=True)), ('textblock', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'h2', 'h3', 'h4', 'h5', 'h6', 'ol', 'ul', 'link'], required=True))]))])),
                ('textfields_en', wagtail.core.fields.StreamField([('textblock', wagtail.core.blocks.StructBlock([('key', wagtail.core.blocks.CharBlock(required=True)), ('textblock', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'h2', 'h3', 'h4', 'h5', 'h6', 'ol', 'ul', 'link'], required=True))]))], null=True)),
                ('textfields_de', wagtail.core.fields.StreamField([('textblock', wagtail.core.blocks.StructBlock([('key', wagtail.core.blocks.CharBlock(required=True)), ('textblock', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'h2', 'h3', 'h4', 'h5', 'h6', 'ol', 'ul', 'link'], required=True))]))], null=True)),
                ('textfields_pt', wagtail.core.fields.StreamField([('textblock', wagtail.core.blocks.StructBlock([('key', wagtail.core.blocks.CharBlock(required=True)), ('textblock', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'h2', 'h3', 'h4', 'h5', 'h6', 'ol', 'ul', 'link'], required=True))]))], null=True)),
                ('textfields_es', wagtail.core.fields.StreamField([('textblock', wagtail.core.blocks.StructBlock([('key', wagtail.core.blocks.CharBlock(required=True)), ('textblock', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'h2', 'h3', 'h4', 'h5', 'h6', 'ol', 'ul', 'link'], required=True))]))], null=True)),
                ('textfields_fr', wagtail.core.fields.StreamField([('textblock', wagtail.core.blocks.StructBlock([('key', wagtail.core.blocks.CharBlock(required=True)), ('textblock', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'h2', 'h3', 'h4', 'h5', 'h6', 'ol', 'ul', 'link'], required=True))]))], null=True)),
                ('textfields_pl', wagtail.core.fields.StreamField([('textblock', wagtail.core.blocks.StructBlock([('key', wagtail.core.blocks.CharBlock(required=True)), ('textblock', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'h2', 'h3', 'h4', 'h5', 'h6', 'ol', 'ul', 'link'], required=True))]))], null=True)),
                ('search_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Search image')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtailmetadata.models.MetadataMixin, 'wagtailcore.page', models.Model),
        ),
    ]
