# Generated by Django 2.2.5 on 2019-10-03 00:28

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0086_auto_20191001_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtuberegretspage',
            name='faq',
            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'h2', 'h3', 'h4', 'h5', 'ol', 'ul', 'link', 'hr']))], blank=True),
        ),
    ]
