# Generated by Django 2.2.7 on 2019-11-20 00:19

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0088_auto_20191106_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpagecategory',
            name='intro_de',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpagecategory',
            name='intro_en',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpagecategory',
            name='intro_es',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpagecategory',
            name='intro_fr',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpagecategory',
            name='intro_pl',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpagecategory',
            name='intro_pt',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpagecategory',
            name='name_de',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='blogpagecategory',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='blogpagecategory',
            name='name_es',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='blogpagecategory',
            name='name_fr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='blogpagecategory',
            name='name_pl',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='blogpagecategory',
            name='name_pt',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
