# Generated by Django 3.2.19 on 2023-06-22 17:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailpages", "0090_remove_research_prefixes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rccauthorsindexpage",
            options={"verbose_name": "RCC authors index page", "verbose_name_plural": "RCC authors index pages"},
        ),
        migrations.AlterModelOptions(
            name="rccdetailpage",
            options={"verbose_name": "RCC detail page", "verbose_name_plural": "RCC detail pages"},
        ),
        migrations.AlterModelOptions(
            name="rcclandingpage",
            options={"verbose_name": "RCC landing page", "verbose_name_plural": "RCC landing pages"},
        ),
        migrations.AlterModelOptions(
            name="rcclibrarypage",
            options={"verbose_name": "RCC library page", "verbose_name_plural": "RCC library pages"},
        ),
    ]
