# Generated by Django 3.2.19 on 2023-06-29 02:15

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailpages", "0091_alter_rcc_pages_verbose_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="rcclandingpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "about",
                        wagtail.blocks.StructBlock(
                            [
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                (
                                    "image_alt_text",
                                    wagtail.blocks.CharBlock(
                                        help_text="Image description (for screen readers).", required=True
                                    ),
                                ),
                                ("heading", wagtail.blocks.CharBlock(help_text="Heading for the About Block")),
                                ("content", wagtail.blocks.RichTextBlock(features=["bold", "italic", "link"])),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AddField(
            model_name="researchlandingpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "about",
                        wagtail.blocks.StructBlock(
                            [
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                (
                                    "image_alt_text",
                                    wagtail.blocks.CharBlock(
                                        help_text="Image description (for screen readers).", required=True
                                    ),
                                ),
                                ("heading", wagtail.blocks.CharBlock(help_text="Heading for the About Block")),
                                ("content", wagtail.blocks.RichTextBlock(features=["bold", "italic", "link"])),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
