# Generated by Django 3.2.20 on 2023-07-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailpages", "0093_auto_20230726_2248"),
    ]

    operations = [
        migrations.AlterField(
            model_name="petition",
            name="campaign_id",
            field=models.CharField(
                help_text="Which campaign identifier should this petition be tied to?", max_length=20, null=True
            ),
        ),
    ]
