# Generated by Django 3.2.20 on 2023-07-20 02:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailpages", "0093_make_petition_id_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="donationmodal",
            name="donate_url",
            field=models.CharField(
                blank=True,
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Please enter a valid URL (starting with http:// or https://), or a valid query string starting with ? (Ex: ?form=donate).",
                        regex="^(https?://[\\w.-]+(/\\S*)?)?(\\?[\\w-]+(=[\\w-]*)?(&[\\w-]+(=[\\w-]*)?)*)?$",
                    )
                ],
            ),
        ),
    ]
