# Generated by Django 3.2.20 on 2023-08-03 19:13

from django.db import migrations


def map_old_to_new(apps, schema_editor):
    Petition = apps.get_model("wagtailpages", "Petition")
    for petition in Petition.objects.all():
        if petition.comment_requirements == "none":
            petition.show_comment_field = False
        else:
            petition.show_comment_field = True
        petition.save()


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailpages", "0095_auto_20230803_1903"),
    ]

    operations = [
        migrations.RunPython(map_old_to_new),
    ]
