# Generated by Django 3.2.20 on 2023-08-02 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0096_map_petition_comment_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petition',
            name='comment_requirements',
        ),
    ]
