# Generated by Django 3.2.21 on 2023-10-04 09:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailpages", "0108_consumercreepometerpage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FeatureFlags",
        ),
    ]
