# Generated by Django 3.2.21 on 2023-11-09 19:31

from django.db import migrations, transaction

# Hardcoded default language code to avoid settings change
DEFAULT_LANGUAGE_CODE = "en"


def add_evaluation_to_product_page_latest_revision(apps, schema_editor):
    ProductPage = apps.get_model("wagtailpages", "ProductPage")
    ProductPageEvaluation = apps.get_model("wagtailpages", "ProductPageEvaluation")
    Revision = apps.get_model("wagtailcore", "Revision")

    default_product_pages = ProductPage.objects.select_related("evaluation").filter(
        locale__language_code=DEFAULT_LANGUAGE_CODE
    )

    for product in default_product_pages:
        with transaction.atomic():
            evaluation = product.evaluation

            if not evaluation:
                evaluation = ProductPageEvaluation.objects.create()
                ProductPage.objects.filter(translation_key=product.translation_key).update(evaluation=evaluation)

            revision = product.latest_revision
            if not revision:
                break

            content = revision.content
            content["evaluation"] = evaluation.pk
            Revision.objects.filter(pk=revision.pk).update(content=content)


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailpages", "0112_fix_pni_category_slugs"),
        ("wagtailcore", "0078_referenceindex"),
    ]

    operations = [
        migrations.RunPython(add_evaluation_to_product_page_latest_revision, migrations.RunPython.noop),
    ]
