# Generated by Django 3.2.21 on 2023-11-14 15:18

import uuid

import django.db.models.deletion
import wagtail.blocks
import wagtail.blocks.static_block
import wagtail.documents.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtail.snippets.blocks
import wagtailmedia.blocks
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0078_referenceindex"),
        ("wagtailpages", "0113_alter_blogpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "accordion",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "accordion_items",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "title",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Heading for the Accordion Item"
                                                    ),
                                                ),
                                                (
                                                    "content",
                                                    wagtail.blocks.StreamBlock(
                                                        [
                                                            (
                                                                "rich_text",
                                                                wagtail.blocks.RichTextBlock(
                                                                    blank=True,
                                                                    features=[
                                                                        "bold",
                                                                        "italic",
                                                                        "link",
                                                                        "ul",
                                                                        "ol",
                                                                        "document-link",
                                                                    ],
                                                                ),
                                                            ),
                                                            (
                                                                "datawrapper",
                                                                wagtail.embeds.blocks.EmbedBlock(
                                                                    help_text='Enter the "visualization only" link of the Datawrapper chart. It looks something like this: https://datawrapper.dwcdn.net/KwSKp/1/',
                                                                    icon="image",
                                                                    template="wagtailpages/blocks/datawrapper_block.html",
                                                                ),
                                                            ),
                                                            (
                                                                "image",
                                                                wagtail.blocks.StructBlock(
                                                                    [
                                                                        (
                                                                            "image",
                                                                            wagtail.images.blocks.ImageChooserBlock(),
                                                                        ),
                                                                        (
                                                                            "altText",
                                                                            wagtail.blocks.CharBlock(
                                                                                help_text="Image description (for screen readers).",
                                                                                required=True,
                                                                            ),
                                                                        ),
                                                                    ]
                                                                ),
                                                            ),
                                                            (
                                                                "video",
                                                                wagtail.blocks.StructBlock(
                                                                    [
                                                                        (
                                                                            "url",
                                                                            wagtail.blocks.CharBlock(
                                                                                help_text="For YouTube: go to your YouTube video and click “Share,” then “Embed,” and then copy and paste the provided URL only. For example: https://www.youtube.com/embed/3FIVXBawyQw For Vimeo: follow similar steps to grab the embed URL. For example: https://player.vimeo.com/video/9004979",
                                                                                label="Embed URL",
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "caption",
                                                                            wagtail.blocks.CharBlock(required=False),
                                                                        ),
                                                                        (
                                                                            "captionURL",
                                                                            wagtail.blocks.CharBlock(
                                                                                help_text="Optional URL for caption to link to.",
                                                                                required=False,
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "video_width",
                                                                            wagtail.blocks.ChoiceBlock(
                                                                                choices=[
                                                                                    ("normal", "Normal"),
                                                                                    ("wide", "Wide"),
                                                                                    ("full_width", "Full Width"),
                                                                                ],
                                                                                help_text="Wide videos are col-12, Full-Width videos reach both ends of the screen.",
                                                                            ),
                                                                        ),
                                                                    ]
                                                                ),
                                                            ),
                                                        ]
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "paragraph",
                        wagtail.blocks.RichTextBlock(
                            features=[
                                "bold",
                                "italic",
                                "link",
                                "h2",
                                "h3",
                                "h4",
                                "h5",
                                "ol",
                                "ul",
                                "hr",
                                "document-link",
                            ],
                            template="wagtailpages/blocks/rich_text_block.html",
                        ),
                    ),
                    (
                        "card_grid",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "cards",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                                (
                                                    "alt_text",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Alt text for card's image.", required=False
                                                    ),
                                                ),
                                                ("title", wagtail.blocks.CharBlock(help_text="Heading for the card.")),
                                                ("body", wagtail.blocks.TextBlock(help_text="Body text of the card.")),
                                                (
                                                    "link_url",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Optional URL that this card should link out to. (Note: If left blank, link will not render.) ",
                                                        required=False,
                                                    ),
                                                ),
                                                (
                                                    "link_label",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Optional Label for the URL link above. (Note: If left blank, link will not render.) ",
                                                        required=False,
                                                    ),
                                                ),
                                            ]
                                        ),
                                        help_text="Please use a minimum of 2 cards.",
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "CTA_card",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "style",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[("pop", "Pop"), ("outline", "Outline"), ("filled", "Filled")]
                                    ),
                                ),
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Optional title for the card.", max_length=100, required=False
                                    ),
                                ),
                                (
                                    "body",
                                    wagtail.blocks.RichTextBlock(
                                        features=["bold", "italic", "link", "hr", "h4", "h5", "ul", "ol"],
                                        help_text="Body text of the card.",
                                    ),
                                ),
                                (
                                    "image",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                                (
                                                    "altText",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Image description (for screen readers).",
                                                        required=True,
                                                    ),
                                                ),
                                            ]
                                        ),
                                        default=[],
                                        max_num=1,
                                        min_num=0,
                                    ),
                                ),
                                (
                                    "button",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                ("label", wagtail.blocks.CharBlock()),
                                                ("URL", wagtail.blocks.CharBlock()),
                                                (
                                                    "styling",
                                                    wagtail.blocks.ChoiceBlock(
                                                        choices=[
                                                            ("btn-primary", "Primary button"),
                                                            ("btn-secondary", "Secondary button"),
                                                        ]
                                                    ),
                                                ),
                                            ]
                                        ),
                                        default=[],
                                        max_num=1,
                                        min_num=0,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "CTA_card_with_text",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "alignment",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[("right", "Right"), ("left", "Left")],
                                        help_text="For full-width cards, please use a regular Blog CTA Card block with a separate paragraph.",
                                    ),
                                ),
                                (
                                    "card",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "style",
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[
                                                        ("pop", "Pop"),
                                                        ("outline", "Outline"),
                                                        ("filled", "Filled"),
                                                    ]
                                                ),
                                            ),
                                            (
                                                "title",
                                                wagtail.blocks.CharBlock(
                                                    help_text="Optional title for the card.",
                                                    max_length=100,
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "body",
                                                wagtail.blocks.RichTextBlock(
                                                    features=["bold", "italic", "link", "hr", "h4", "h5", "ul", "ol"],
                                                    help_text="Body text of the card.",
                                                ),
                                            ),
                                            (
                                                "image",
                                                wagtail.blocks.ListBlock(
                                                    wagtail.blocks.StructBlock(
                                                        [
                                                            ("image", wagtail.images.blocks.ImageChooserBlock()),
                                                            (
                                                                "altText",
                                                                wagtail.blocks.CharBlock(
                                                                    help_text="Image description (for screen readers).",
                                                                    required=True,
                                                                ),
                                                            ),
                                                        ]
                                                    ),
                                                    default=[],
                                                    max_num=1,
                                                    min_num=0,
                                                ),
                                            ),
                                            (
                                                "button",
                                                wagtail.blocks.ListBlock(
                                                    wagtail.blocks.StructBlock(
                                                        [
                                                            ("label", wagtail.blocks.CharBlock()),
                                                            ("URL", wagtail.blocks.CharBlock()),
                                                            (
                                                                "styling",
                                                                wagtail.blocks.ChoiceBlock(
                                                                    choices=[
                                                                        ("btn-primary", "Primary button"),
                                                                        ("btn-secondary", "Secondary button"),
                                                                    ]
                                                                ),
                                                            ),
                                                        ]
                                                    ),
                                                    default=[],
                                                    max_num=1,
                                                    min_num=0,
                                                ),
                                            ),
                                        ],
                                        required=True,
                                        template="wagtailpages/blocks/blog_cta_card_block_regular.html",
                                    ),
                                ),
                                (
                                    "paragraph",
                                    wagtail.blocks.RichTextBlock(
                                        features=[
                                            "bold",
                                            "italic",
                                            "link",
                                            "h2",
                                            "h3",
                                            "h4",
                                            "h5",
                                            "ol",
                                            "ul",
                                            "hr",
                                            "document-link",
                                        ],
                                        help_text="Text to be displayed next to the card.",
                                        template="wagtailpages/blocks/rich_text_block.html",
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "image_grid",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "grid_items",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                                (
                                                    "alt_text",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Alt text for this image.", required=False
                                                    ),
                                                ),
                                                (
                                                    "caption",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Please remember to properly attribute any images we use.",
                                                        required=False,
                                                    ),
                                                ),
                                                (
                                                    "url",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Optional URL that this figure should link out to.",
                                                        required=False,
                                                    ),
                                                ),
                                                (
                                                    "square_image",
                                                    wagtail.blocks.BooleanBlock(
                                                        default=True,
                                                        help_text="If left checked, the image will be cropped to be square.",
                                                        required=False,
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "iframe",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "url",
                                    wagtail.blocks.CharBlock(
                                        help_text="Please note that only URLs from allow-listed domains will work."
                                    ),
                                ),
                                (
                                    "height",
                                    wagtail.blocks.IntegerBlock(
                                        help_text="Optional integer pixel value for custom iFrame height",
                                        required=False,
                                    ),
                                ),
                                ("caption", wagtail.blocks.CharBlock(required=False)),
                                (
                                    "captionURL",
                                    wagtail.blocks.CharBlock(
                                        help_text="Optional URL that this caption should link out to.", required=False
                                    ),
                                ),
                                (
                                    "iframe_width",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[("normal", "Normal"), ("wide", "Wide"), ("full_width", "Full Width")],
                                        help_text="Wide iframes are col-12, Full-Width iframes reach both ends of the screen",
                                    ),
                                ),
                                (
                                    "disable_scroll",
                                    wagtail.blocks.BooleanBlock(
                                        default=False,
                                        help_text='Checking this will add "scrolling=no" to the iframe. Use this if your iframe is rendering an unnecessary scroll bar or whitespace below it.',
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "image",
                        wagtail.blocks.StructBlock(
                            [
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                (
                                    "altText",
                                    wagtail.blocks.CharBlock(
                                        help_text="Image description (for screen readers).", required=True
                                    ),
                                ),
                                ("caption", wagtail.blocks.CharBlock(required=False)),
                                (
                                    "captionURL",
                                    wagtail.blocks.CharBlock(
                                        help_text="Optional URL that this caption should link out to.", required=False
                                    ),
                                ),
                                (
                                    "image_width",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[("normal", "Normal"), ("wide", "Wide"), ("full_width", "Full Width")],
                                        help_text="Wide images are col-12, Full-Width Images reach both ends of the screen (16:6 images recommended for full width)",
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "audio",
                        wagtail.blocks.StructBlock(
                            [
                                ("audio", wagtailmedia.blocks.AudioChooserBlock()),
                                ("caption", wagtail.blocks.CharBlock(required=False)),
                            ]
                        ),
                    ),
                    (
                        "image_text",
                        wagtail.blocks.StructBlock(
                            [
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                (
                                    "altText",
                                    wagtail.blocks.CharBlock(
                                        help_text="Image description (for screen readers).", required=True
                                    ),
                                ),
                                (
                                    "text",
                                    wagtail.blocks.RichTextBlock(
                                        features=[
                                            "bold",
                                            "italic",
                                            "link",
                                            "h2",
                                            "h3",
                                            "h4",
                                            "h5",
                                            "ol",
                                            "ul",
                                            "hr",
                                            "document-link",
                                        ]
                                    ),
                                ),
                                (
                                    "url",
                                    wagtail.blocks.CharBlock(
                                        help_text="Optional URL that this image should link out to.", required=False
                                    ),
                                ),
                                (
                                    "top_divider",
                                    wagtail.blocks.BooleanBlock(
                                        help_text="Optional divider above content block.", required=False
                                    ),
                                ),
                                (
                                    "bottom_divider",
                                    wagtail.blocks.BooleanBlock(
                                        help_text="Optional divider below content block.", required=False
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "image_text_mini",
                        wagtail.blocks.StructBlock(
                            [
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                (
                                    "altText",
                                    wagtail.blocks.CharBlock(
                                        help_text="Image description (for screen readers).", required=True
                                    ),
                                ),
                                ("text", wagtail.blocks.RichTextBlock(features=["bold", "italic", "link"])),
                            ]
                        ),
                    ),
                    (
                        "video",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "url",
                                    wagtail.blocks.CharBlock(
                                        help_text="For YouTube: go to your YouTube video and click “Share,” then “Embed,” and then copy and paste the provided URL only. For example: https://www.youtube.com/embed/3FIVXBawyQw For Vimeo: follow similar steps to grab the embed URL. For example: https://player.vimeo.com/video/9004979",
                                        label="Embed URL",
                                    ),
                                ),
                                ("caption", wagtail.blocks.CharBlock(required=False)),
                                (
                                    "captionURL",
                                    wagtail.blocks.CharBlock(
                                        help_text="Optional URL for caption to link to.", required=False
                                    ),
                                ),
                                (
                                    "video_width",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[("normal", "Normal"), ("wide", "Wide"), ("full_width", "Full Width")],
                                        help_text="Wide videos are col-12, Full-Width videos reach both ends of the screen.",
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "linkbutton",
                        wagtail.blocks.StructBlock(
                            [
                                ("label", wagtail.blocks.CharBlock()),
                                ("URL", wagtail.blocks.CharBlock()),
                                (
                                    "styling",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("btn-primary", "Primary button"),
                                            ("btn-secondary", "Secondary button"),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "looping_video",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "video_url",
                                    wagtail.blocks.CharBlock(
                                        help_text='Log into Vimeo using 1Password and upload the desired video. Then select the video and click "Advanced", "Distribution", and "Video File Links". Copy and paste the link here.',
                                        label="Embed URL",
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "pulse_listing",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "search_terms",
                                    wagtail.blocks.CharBlock(
                                        help_text="Test your search at mozillapulse.org/search",
                                        label="Search",
                                        required=False,
                                    ),
                                ),
                                (
                                    "max_number_of_results",
                                    wagtail.blocks.IntegerBlock(
                                        default=6,
                                        help_text="Choose 1-12. If you want visitors to see more, link to a search or tag on Pulse.",
                                        max_value=12,
                                        min_value=0,
                                        required=True,
                                    ),
                                ),
                                (
                                    "only_featured_entries",
                                    wagtail.blocks.BooleanBlock(
                                        default=False,
                                        help_text="Featured items are selected by Pulse moderators.",
                                        label="Display only featured entries",
                                        required=False,
                                    ),
                                ),
                                (
                                    "newest_first",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("True", "Show newer entries first"),
                                            ("False", "Show older entries first"),
                                        ],
                                        label="Sort",
                                    ),
                                ),
                                (
                                    "advanced_filter_header",
                                    wagtail.blocks.static_block.StaticBlock(
                                        admin_text="-------- ADVANCED FILTERS: OPTIONS TO DISPLAY FEWER, MORE TARGETED RESULTS. --------",
                                        label=" ",
                                    ),
                                ),
                                (
                                    "issues",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("all", "All"),
                                            ("Decentralization", "Decentralization"),
                                            ("Digital Inclusion", "Digital Inclusion"),
                                            ("Online Privacy & Security", "Online Privacy & Security"),
                                            ("Open Innovation", "Open Innovation"),
                                            ("Web Literacy", "Web Literacy"),
                                        ]
                                    ),
                                ),
                                (
                                    "help",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("all", "All"),
                                            ("Attend", "Attend"),
                                            ("Create content", "Create content"),
                                            ("Code", "Code"),
                                            ("Design", "Design"),
                                            ("Fundraise", "Fundraise"),
                                            ("Join community", "Join community"),
                                            ("Localize & translate", "Localize & translate"),
                                            ("Mentor", "Mentor"),
                                            ("Plan & organize", "Plan & organize"),
                                            ("Promote", "Promote"),
                                            ("Take action", "Take action"),
                                            ("Test & feedback", "Test & feedback"),
                                            ("Write documentation", "Write documentation"),
                                        ],
                                        label="Type of help needed",
                                    ),
                                ),
                                (
                                    "direct_link",
                                    wagtail.blocks.BooleanBlock(
                                        default=False,
                                        help_text="Checked: user goes to project link. Unchecked: user goes to pulse entry",
                                        label="Direct link",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "single_quote",
                        wagtail.blocks.StructBlock(
                            [
                                ("quote", wagtail.blocks.RichTextBlock(features=["bold"])),
                                ("attribution", wagtail.blocks.CharBlock(required=False)),
                                (
                                    "attribution_info",
                                    wagtail.blocks.RichTextBlock(features=["bold", "link", "large"], required=False),
                                ),
                            ]
                        ),
                    ),
                    (
                        "slider",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(help_text="Heading for the slider.", required=False),
                                ),
                                (
                                    "slides",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "slide",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "title",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Heading of the card.", required=False
                                                            ),
                                                        ),
                                                        (
                                                            "image",
                                                            wagtail.images.blocks.ImageChooserBlock(
                                                                help_text="The image associated with this event."
                                                            ),
                                                        ),
                                                        (
                                                            "caption",
                                                            wagtail.blocks.TextBlock(
                                                                help_text="Caption for slider image", required=False
                                                            ),
                                                        ),
                                                        (
                                                            "body",
                                                            wagtail.blocks.RichTextBlock(
                                                                blank=True,
                                                                features=["bold", "italic", "link", "large"],
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "buttons",
                                                            wagtail.blocks.StreamBlock(
                                                                [
                                                                    (
                                                                        "internal",
                                                                        wagtail.blocks.StructBlock(
                                                                            [
                                                                                (
                                                                                    "label",
                                                                                    wagtail.blocks.CharBlock(
                                                                                        help_text="Label for this link."
                                                                                    ),
                                                                                ),
                                                                                (
                                                                                    "link",
                                                                                    wagtail.blocks.PageChooserBlock(
                                                                                        help_text="Page that this should link out to."
                                                                                    ),
                                                                                ),
                                                                            ]
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "external",
                                                                        wagtail.blocks.StructBlock(
                                                                            [
                                                                                (
                                                                                    "label",
                                                                                    wagtail.blocks.CharBlock(
                                                                                        help_text="Label for this link."
                                                                                    ),
                                                                                ),
                                                                                (
                                                                                    "link",
                                                                                    wagtail.blocks.URLBlock(
                                                                                        help_text="URL that this should link out to."
                                                                                    ),
                                                                                ),
                                                                            ]
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "document",
                                                                        wagtail.blocks.StructBlock(
                                                                            [
                                                                                (
                                                                                    "label",
                                                                                    wagtail.blocks.CharBlock(
                                                                                        help_text="Label for this link."
                                                                                    ),
                                                                                ),
                                                                                (
                                                                                    "document",
                                                                                    wagtail.documents.blocks.DocumentChooserBlock(
                                                                                        help_text="Document that this should link out to."
                                                                                    ),
                                                                                ),
                                                                            ],
                                                                            help_text='An iCal document can be attached here for an "Add to Calendar" button.',
                                                                        ),
                                                                    ),
                                                                ],
                                                                help_text="A list of buttons that will appear at the bottom of the card.",
                                                                max_num=2,
                                                                required=False,
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            )
                                        ],
                                        help_text="A list of slides.",
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "spacer",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "size",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("1", "quarter spacing"),
                                            ("2", "half spacing"),
                                            ("3", "single spacing"),
                                            ("4", "one and a half spacing"),
                                            ("5", "triple spacing"),
                                        ]
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "airtable",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "url",
                                    wagtail.blocks.URLBlock(
                                        help_text="Copied from the Airtable embed code. The word 'embed' will be in the url"
                                    ),
                                ),
                                (
                                    "height",
                                    wagtail.blocks.IntegerBlock(
                                        default=533,
                                        help_text="The pixel height on desktop view, usually copied from the Airtable embed code",
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "datawrapper",
                        wagtail.embeds.blocks.EmbedBlock(
                            help_text='Enter the "visualization only" link of the Datawrapper chart. It looks something like this: https://datawrapper.dwcdn.net/KwSKp/1/',
                            icon="image",
                            template="wagtailpages/blocks/datawrapper_block.html",
                        ),
                    ),
                    (
                        "typeform",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "embed_id",
                                    wagtail.blocks.CharBlock(
                                        help_text="The embed id of your Typeform page (e.g. if the form is on admin.typeform.com/form/e8zScc6t, the id will be: e8zScc6t)",
                                        required=True,
                                    ),
                                ),
                                (
                                    "button_type",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("btn-primary", "Primary button"),
                                            ("btn-secondary", "Secondary button"),
                                        ]
                                    ),
                                ),
                                (
                                    "button_text",
                                    wagtail.blocks.CharBlock(
                                        help_text="This is a text prompt for users to open the typeform content",
                                        required=True,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "newsletter_signup",
                        wagtail.blocks.StructBlock(
                            [("signup", wagtail.snippets.blocks.SnippetChooserBlock("wagtailpages.BlogSignup"))]
                        ),
                    ),
                ],
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="cta",
            name="newsletter",
            field=models.CharField(
                default="mozilla-foundation", help_text="The (pre-existing) newsletter to sign up for", max_length=100
            ),
        ),
        migrations.CreateModel(
            name="BlogSignup",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("translation_key", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "name",
                    models.CharField(
                        default="", help_text="Identify this component for other editors", max_length=100
                    ),
                ),
                (
                    "header",
                    models.CharField(
                        blank=True, help_text="Heading that will display on page for this component", max_length=500
                    ),
                ),
                (
                    "newsletter",
                    models.CharField(
                        default="mozilla-foundation",
                        help_text="The (pre-existing) newsletter to sign up for",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    wagtail.fields.RichTextField(blank=True, help_text="Signup's body (richtext)", max_length=300),
                ),
                (
                    "locale",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="wagtailcore.locale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Signup",
                "verbose_name_plural": "Blog Signups",
                "ordering": ["name"],
                "abstract": False,
                "unique_together": {("translation_key", "locale")},
            },
        ),
    ]
