# Generated by Django 3.2.23 on 2023-12-08 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0078_referenceindex"),
        ("wagtailpages", "0115_setup_related_names_on_blog_featured_pages_and_related_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyersguidepageherosupportingpagerelation",
            name="supporting_page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bg_homepage_supporting_page_relation",
                to="wagtailcore.page",
            ),
        ),
    ]
