# Generated by Django 4.2.9 on 2024-02-01 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailpages", "0122_alter_petition_show_comment_field_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productupdates",
            name="update",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_pages",
                to="wagtailpages.update",
            ),
        ),
    ]
