# Generated by Django 4.2.9 on 2024-02-09 20:24

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailpages", "0123_alter_petition_show_comment_field_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuyersGuideCategoryNav",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
            options={
                "verbose_name": "*PNI categories navbar",
                "verbose_name_plural": "*PNI categories navbar",
            },
        ),
        migrations.AlterModelOptions(
            name="buyersguideproductcategory",
            options={
                "ordering": [models.OrderBy(models.F("parent__name"), nulls_first=True), "name"],
                "verbose_name": "Buyers Guide Product Category",
                "verbose_name_plural": "Buyers Guide Product Categories",
            },
        ),
        migrations.RemoveField(
            model_name="buyersguideproductcategory",
            name="sort_order",
        ),
        migrations.CreateModel(
            name="BuyersGuideCategoryNavRelation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nav_relations",
                        to="wagtailpages.buyersguideproductcategory",
                    ),
                ),
                (
                    "nav",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_relations",
                        to="wagtailpages.buyersguidecategorynav",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category Navigation Relation",
                "verbose_name_plural": "Category Navigation Relations",
                "ordering": ["sort_order"],
                "unique_together": {("nav", "category")},
            },
        ),
    ]
