# Generated by Django 4.2.10 on 2024-02-29 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailpages", "0124_buyersguidecategorynav_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productpage",
            name="privacy_ding",
            field=models.BooleanField(default=False, verbose_name="*Privacy Not Included ding"),
        ),
    ]
