# Generated by Django 4.2.9 on 2024-02-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailpages", "0124_buyersguidecategorynav_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="buyersguideproductcategory",
            options={
                "ordering": [models.OrderBy(models.F("parent__name"), nulls_first=True), "name"],
                "verbose_name": "Buyers Guide Product Category",
                "verbose_name_plural": "Buyers Guide Product Categories",
            },
        ),
        migrations.RemoveField(
            model_name="buyersguideproductcategory",
            name="hidden",
        ),
        migrations.RemoveField(
            model_name="buyersguideproductcategory",
            name="sort_order",
        ),
    ]
