# Generated by Django 4.2.10 on 2024-02-27 12:28
from django.db import migrations
from wagtail.blocks.migrations.migrate_operation import MigrateStreamData

from networkapi.wagtailcustomization.migrationutils.operations import (
    AlterStreamChildBlockDataOperation,
)


def migrate_linkbuttonblock(source_block):
    """Copy old link data to new LinkBlock inside a LinkButtonBlock."""
    return {
        **source_block,
        "value": {
            "label": source_block["value"]["label"],
            "URL": source_block["value"]["URL"],
            "styling": source_block["value"]["styling"],
            "target": {
                "link": {
                    "file": None,
                    "page": None,
                    "email": "",
                    "phone": "",
                    "anchor": "",
                    "link_to": "custom_url",
                    "custom_url": source_block["value"]["URL"],
                    "new_window": False,
                },
                "label": source_block["value"]["label"],
            },
        },
    }


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailpages", "0125_add_linkblock_to_linkbuttonblock"),
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
    ]

    # Technically, we would need to also migrate the data inside the `CTAAsideBlock`, used on
    # `aside_cta` field for the `RCCLandingPage` and `ResearchLandingPage` models. However,
    # both of those in production are empty, so we can skip that for now, since there is a bug
    # with `MigrateStreamData` that makes it crash because the `field_name` is not found
    # in the stream if editors never added it in the first place (it's not empty, it was
    # never added to the revision's content).

    operations = [
        MigrateStreamData(
            app_name="wagtailpages",
            model_name="ArticlePage",
            field_name="body",
            operations_and_block_paths=[
                (AlterStreamChildBlockDataOperation(block="linkbutton", operation=migrate_linkbuttonblock), ""),
            ],
        ),
        MigrateStreamData(
            app_name="wagtailpages",
            model_name="BlogPage",
            field_name="body",
            operations_and_block_paths=[
                (AlterStreamChildBlockDataOperation(block="linkbutton", operation=migrate_linkbuttonblock), ""),
                (
                    AlterStreamChildBlockDataOperation(block="linkbutton", operation=migrate_linkbuttonblock),
                    "block_with_aside.aside",
                ),
            ],
        ),
        MigrateStreamData(
            app_name="wagtailpages",
            model_name="BuyersGuideArticlePage",
            field_name="body",
            operations_and_block_paths=[
                (AlterStreamChildBlockDataOperation(block="linkbutton", operation=migrate_linkbuttonblock), ""),
            ],
        ),
        MigrateStreamData(
            app_name="wagtailpages",
            model_name="BuyersGuideCampaignPage",
            field_name="body",
            operations_and_block_paths=[
                (AlterStreamChildBlockDataOperation(block="linkbutton", operation=migrate_linkbuttonblock), ""),
            ],
        ),
        MigrateStreamData(
            app_name="wagtailpages",
            model_name="ModularPage",
            field_name="body",
            operations_and_block_paths=[
                (AlterStreamChildBlockDataOperation(block="linkbutton", operation=migrate_linkbuttonblock), ""),
                (
                    AlterStreamChildBlockDataOperation(block="linkbutton", operation=migrate_linkbuttonblock),
                    "block_with_aside.aside",
                ),
            ],
        ),
        MigrateStreamData(
            app_name="wagtailpages",
            model_name="PrimaryPage",
            field_name="body",
            operations_and_block_paths=[
                (AlterStreamChildBlockDataOperation(block="linkbutton", operation=migrate_linkbuttonblock), ""),
                (
                    AlterStreamChildBlockDataOperation(block="linkbutton", operation=migrate_linkbuttonblock),
                    "block_with_aside.aside",
                ),
            ],
        ),
    ]
