# Generated by Django 4.2.11 on 2024-03-28 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("wagtailpages", "0132_make_link_to_required_in_link_block"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppInstallPage",
            fields=[
                (
                    "campaignpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailpages.campaignpage",
                    ),
                ),
                ("hero_heading", models.CharField(help_text="Hero story headline", max_length=80)),
                ("hero_subheading", models.CharField(blank=True, help_text="Hero story subheadline", max_length=80)),
                (
                    "hero_video",
                    models.URLField(
                        blank=True,
                        help_text="To find embed link: go to your YouTube video and click “Share,” then “Embed,” and then copy and paste the provided URL only. For example: https://www.youtube.com/embed/3FIVXBawyQw.",
                        null=True,
                    ),
                ),
                (
                    "button1_text",
                    models.CharField(blank=True, help_text="Text for Button 1", max_length=50, null=True),
                ),
                (
                    "button1_download_link",
                    models.URLField(blank=True, help_text="Download link for Button 1", max_length=255, null=True),
                ),
                (
                    "button2_text",
                    models.CharField(blank=True, help_text="Text for Button 2", max_length=50, null=True),
                ),
                (
                    "button2_download_link",
                    models.URLField(blank=True, help_text="Download link for Button 2", max_length=255, null=True),
                ),
                (
                    "button1_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image for Button 1",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "button2_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image for Button 2",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "hero_background",
                    models.ForeignKey(
                        help_text="Background image for the hero section",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailpages.campaignpage",),
        ),
    ]
