# Generated by Django 4.2.10 on 2024-02-27 12:28
from django.db import migrations
from wagtail.blocks.migrations.migrate_operation import MigrateStreamData

from networkapi.utility.migration.operations import AlterStreamChildBlockDataOperation


def migrate_image_block(source_block):
    new_value = {
        "image": source_block["value"]["image"],
        "altText": source_block["value"]["altText"],
        "caption": source_block["value"]["caption"],
        "caption_url": [],
    }
    if "captionURL" in source_block["value"] and source_block["value"]["captionURL"]:
        new_value["caption_url"] = [
            {
                "link_to": "external_url",
                "external_url": source_block["value"]["captionURL"],
                "new_window": True,
            }
        ]
    return {
        **source_block,
        "value": new_value,
    }


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailpages", "0138_alter_blogpage_body_and_more"),
    ]

    operations = [
        MigrateStreamData(
            app_name="wagtailpages",
            model_name="blogpage",
            field_name="body",
            operations_and_block_paths=[
                (AlterStreamChildBlockDataOperation(block="image", operation=migrate_image_block), ""),
            ],
        ),
    ]
