# Generated by Django 4.2.11 on 2024-06-23 22:18

import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.snippets.blocks
import wagtailmedia.blocks
from django.db import migrations
from wagtail.blocks.migrations.migrate_operation import MigrateStreamData

import networkapi.wagtailpages.pagemodels.blog.blog_topic
import networkapi.wagtailpages.validators
from networkapi.utility.migration.operations import AlterStreamChildBlockDataOperation


def migrate_blogindexpage_callout_box_block(source_block):
    new_value = {
        "title": source_block["value"].get("title"),
        "related_topics": source_block["value"].get("related_topics"),
        "show_icon": source_block["value"].get("show_icon"),
        "body": source_block["value"].get("body"),
        "audio": source_block["value"].get("audio"),
        "link_button": [],
    }
    if source_block["value"].get("link_button_text") and source_block["value"].get("link_button_url"):
        new_value["link_button"].append(
            {
                "label": source_block["value"].get("link_button_text"),
                "link_to": "external_url",
                "external_url": source_block["value"].get("link_button_url"),
                "new_window": True,
            }
        )
    return {
        **source_block,
        "value": new_value,
    }


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailpages", "0140_update_iframeblock_with_linkblock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogindexpage",
            name="callout_box",
            field=wagtail.fields.StreamField(
                [
                    (
                        "callout_box",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(help_text="Heading for the callout box.")),
                                (
                                    "related_topics",
                                    wagtail.blocks.ListBlock(
                                        wagtail.snippets.blocks.SnippetChooserBlock(
                                            networkapi.wagtailpages.pagemodels.blog.blog_topic.BlogPageTopic
                                        ),
                                        help_text="Optional topics to display at the top of the callout box.",
                                        max_num=2,
                                    ),
                                ),
                                (
                                    "show_icon",
                                    wagtail.blocks.BooleanBlock(
                                        help_text="Check this if you would like to render the headphone icon.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "body",
                                    wagtail.blocks.RichTextBlock(
                                        features=["bold", "italic", "link"],
                                        help_text="Body text for the callout box.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "audio",
                                    wagtailmedia.blocks.AudioChooserBlock(
                                        help_text="Optional audio player that will appear after the body.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "link_button_text",
                                    wagtail.blocks.CharBlock(
                                        help_text="Label text for the link button at the bottom of the box.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "link_button_url",
                                    wagtail.blocks.CharBlock(
                                        help_text="URL that the button should link out to.", required=False
                                    ),
                                ),
                                (
                                    "link_button",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                ("label", wagtail.blocks.CharBlock()),
                                                (
                                                    "link_to",
                                                    wagtail.blocks.ChoiceBlock(
                                                        choices=[
                                                            ("page", "Page"),
                                                            ("external_url", "External URL"),
                                                            ("relative_url", "Relative URL"),
                                                            ("email", "Email"),
                                                            ("anchor", "Anchor"),
                                                            ("file", "File"),
                                                            ("phone", "Phone"),
                                                        ],
                                                        label="Link to",
                                                    ),
                                                ),
                                                (
                                                    "page",
                                                    wagtail.blocks.PageChooserBlock(label="Page", required=False),
                                                ),
                                                (
                                                    "external_url",
                                                    wagtail.blocks.URLBlock(
                                                        help_text="Enter a full URL including http:// or https://",
                                                        label="External URL",
                                                        max_length=300,
                                                        required=False,
                                                    ),
                                                ),
                                                (
                                                    "relative_url",
                                                    wagtail.blocks.CharBlock(
                                                        help_text='A path relative to this domain. For example, "/foo/bar"',
                                                        label="Relative URL",
                                                        max_length=300,
                                                        required=False,
                                                        validators=[
                                                            networkapi.wagtailpages.validators.RelativeURLValidator()
                                                        ],
                                                    ),
                                                ),
                                                (
                                                    "anchor",
                                                    wagtail.blocks.CharBlock(
                                                        help_text='An id attribute of an element on the current page. For example, "#section-1"',
                                                        label="#",
                                                        max_length=300,
                                                        required=False,
                                                        validators=[
                                                            networkapi.wagtailpages.validators.AnchorLinkValidator()
                                                        ],
                                                    ),
                                                ),
                                                ("email", wagtail.blocks.EmailBlock(required=False)),
                                                (
                                                    "file",
                                                    wagtail.documents.blocks.DocumentChooserBlock(
                                                        label="File", required=False
                                                    ),
                                                ),
                                                (
                                                    "phone",
                                                    wagtail.blocks.CharBlock(
                                                        label="Phone", max_length=30, required=False
                                                    ),
                                                ),
                                                (
                                                    "new_window",
                                                    wagtail.blocks.BooleanBlock(
                                                        label="Open in new window", required=False
                                                    ),
                                                ),
                                            ]
                                        ),
                                        help_text="Optional Link Button for the callout box.",
                                        max_num=1,
                                        min_num=0,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                help_text="Callout box that appears after the featured posts section",
                use_json_field=True,
            ),
        ),
        MigrateStreamData(
            app_name="wagtailpages",
            model_name="blogindexpage",
            field_name="callout_box",
            operations_and_block_paths=[
                (
                    AlterStreamChildBlockDataOperation(
                        block="callout_box", operation=migrate_blogindexpage_callout_box_block
                    ),
                    "",
                ),
            ],
        ),
        migrations.AlterField(
            model_name="blogindexpage",
            name="callout_box",
            field=wagtail.fields.StreamField(
                [
                    (
                        "callout_box",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(help_text="Heading for the callout box.")),
                                (
                                    "related_topics",
                                    wagtail.blocks.ListBlock(
                                        wagtail.snippets.blocks.SnippetChooserBlock(
                                            networkapi.wagtailpages.pagemodels.blog.blog_topic.BlogPageTopic
                                        ),
                                        help_text="Optional topics to display at the top of the callout box.",
                                        max_num=2,
                                    ),
                                ),
                                (
                                    "show_icon",
                                    wagtail.blocks.BooleanBlock(
                                        help_text="Check this if you would like to render the headphone icon.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "body",
                                    wagtail.blocks.RichTextBlock(
                                        features=["bold", "italic", "link"],
                                        help_text="Body text for the callout box.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "audio",
                                    wagtailmedia.blocks.AudioChooserBlock(
                                        help_text="Optional audio player that will appear after the body.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "link_button",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                ("label", wagtail.blocks.CharBlock()),
                                                (
                                                    "link_to",
                                                    wagtail.blocks.ChoiceBlock(
                                                        choices=[
                                                            ("page", "Page"),
                                                            ("external_url", "External URL"),
                                                            ("relative_url", "Relative URL"),
                                                            ("email", "Email"),
                                                            ("anchor", "Anchor"),
                                                            ("file", "File"),
                                                            ("phone", "Phone"),
                                                        ],
                                                        label="Link to",
                                                    ),
                                                ),
                                                (
                                                    "page",
                                                    wagtail.blocks.PageChooserBlock(label="Page", required=False),
                                                ),
                                                (
                                                    "external_url",
                                                    wagtail.blocks.URLBlock(
                                                        help_text="Enter a full URL including http:// or https://",
                                                        label="External URL",
                                                        max_length=300,
                                                        required=False,
                                                    ),
                                                ),
                                                (
                                                    "relative_url",
                                                    wagtail.blocks.CharBlock(
                                                        help_text='A path relative to this domain. For example, "/foo/bar"',
                                                        label="Relative URL",
                                                        max_length=300,
                                                        required=False,
                                                        validators=[
                                                            networkapi.wagtailpages.validators.RelativeURLValidator()
                                                        ],
                                                    ),
                                                ),
                                                (
                                                    "anchor",
                                                    wagtail.blocks.CharBlock(
                                                        help_text='An id attribute of an element on the current page. For example, "#section-1"',
                                                        label="#",
                                                        max_length=300,
                                                        required=False,
                                                        validators=[
                                                            networkapi.wagtailpages.validators.AnchorLinkValidator()
                                                        ],
                                                    ),
                                                ),
                                                ("email", wagtail.blocks.EmailBlock(required=False)),
                                                (
                                                    "file",
                                                    wagtail.documents.blocks.DocumentChooserBlock(
                                                        label="File", required=False
                                                    ),
                                                ),
                                                (
                                                    "phone",
                                                    wagtail.blocks.CharBlock(
                                                        label="Phone", max_length=30, required=False
                                                    ),
                                                ),
                                                (
                                                    "new_window",
                                                    wagtail.blocks.BooleanBlock(
                                                        label="Open in new window", required=False
                                                    ),
                                                ),
                                            ]
                                        ),
                                        help_text="Optional Link Button for the callout box.",
                                        max_num=1,
                                        min_num=0,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                help_text="Callout box that appears after the featured posts section",
                use_json_field=True,
            ),
        ),
    ]
