# Generated by Django 4.2.11 on 2024-07-03 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailpages", "0142_alter_blogindexpage_callout_box"),
    ]

    operations = [
        migrations.DeleteModel(
            name="YoutubeRegretsReporterExtensionPage",
        ),
    ]
