# Generated by Django 4.2.14 on 2024-07-18 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailpages", "0149_buyersguidecalltoaction_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buyersguidecalltoaction",
            name="link_label",
        ),
        migrations.RemoveField(
            model_name="buyersguidecalltoaction",
            name="link_target_page",
        ),
        migrations.RemoveField(
            model_name="buyersguidecalltoaction",
            name="link_target_url",
        ),
    ]
