# Generated by Django 4.2.15 on 2024-09-09 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("wagtailpages", "0160_homepageideasposts_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="ideas_headline",
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="ideas_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ideas_image",
                to="wagtailimages.image",
            ),
        ),
    ]
