# Generated by Django 4.2.15 on 2024-09-11 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("wagtailpages", "0161_alter_homepage_ideas_headline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="hero_bottom_body",
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_bottom_heading",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_bottom_link_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hero_bottom_link",
                to="wagtailcore.page",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_bottom_link_text",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
