# Generated by Django 4.2.15 on 2024-10-09 23:35

from django.db import migrations, models

import networkapi.wagtailpages.fields


def map_yes_no_to_cant_determine(apps, schema_editor):
    GeneralProductPage = apps.get_model("wagtailpages", "GeneralProductPage")

    # Filter all instances where 'ai_can_user_control' is 'Yes' or 'No'
    pages_to_update = GeneralProductPage.objects.filter(ai_can_user_control__in=["Yes", "No"])

    # Iterate over the pages and update them
    for page in pages_to_update:
        page.ai_can_user_control = "CD"
        page.save()


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailpages", "0168_alter_generalproductpage_ai_is_transparent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalproductpage",
            name="ai_can_user_control",
            field=networkapi.wagtailpages.fields.ExtendedChoiceField(
                verbose_name="How much control do users have over the data the AI collects?"
            ),
        ),
        migrations.AlterField(
            model_name="generalproductpage",
            name="ai_can_user_control_helptext",
            field=models.TextField(blank=True, max_length=5000, verbose_name="AI Control Explanation"),
        ),
        migrations.RunPython(map_yes_no_to_cant_determine),
    ]
