# Generated by Django 4.2.27 on 2026-01-28 21:23

import django.db.models.deletion
import modelcluster.contrib.taggit
import wagtail.fields
import wagtailmetadata.models
from django.db import migrations, models

import foundation_cms.legacy_apps.wagtailpages.validators
import foundation_cms.validators


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("images", "0002_foundationcustomimage_original_gif"),
        ("base", "0006_remove_new_from_verbose_names"),
        ("mozilla_festival", "0002_alter_mozfesthomepage_theme"),
    ]

    operations = [
        migrations.CreateModel(
            name="MozfestAboutPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("default", "Default"),
                            ("nothing_personal", "Nothing Personal"),
                            ("mozilla_festival", "Mozilla Festival"),
                        ],
                        help_text="Optional. If unset, theme will be inherited from section root.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("accordion_block", 5),
                            ("custom_media", 11),
                            ("divider", 12),
                            ("featured_card_block", 28),
                            ("fru_element_block", 31),
                            ("iframe_block", 36),
                            ("image", 39),
                            ("impact_numbers", 45),
                            ("link_button_block", 46),
                            ("list_block", 51),
                            ("newsletter_signup", 53),
                            ("newsletter_unsubscribe", 55),
                            ("pillar_card_set", 60),
                            ("podcast_block", 63),
                            ("portrait_card_set_block", 69),
                            ("quote", 72),
                            ("rich_text", 73),
                            ("spacer_block", 75),
                            ("spotlight_card_set_block", 80),
                            ("tabbed_content", 92),
                            ("timely_activations_cards", 98),
                            ("title_block", 101),
                            ("two_column_container_block", 120),
                            ("video_block", 121),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Heading for the Accordion Item", "required": True},
                            ),
                            1: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "bold",
                                        "italic",
                                        "large",
                                        "ol",
                                        "ul",
                                        "hr",
                                        "embed",
                                        "link",
                                        "document-link",
                                        "image",
                                    ]
                                },
                            ),
                            2: (
                                "wagtail.blocks.StreamBlock",
                                [[("rich_text", 1)]],
                                {"required": False, "use_json_field": True},
                            ),
                            3: ("wagtail.blocks.StructBlock", [[("title", 0), ("content", 2)]], {}),
                            4: ("wagtail.blocks.ListBlock", (3,), {"min_num": 1}),
                            5: ("wagtail.blocks.StructBlock", [[("accordion_items", 4)]], {"group": "Text"}),
                            6: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Title/caption for this media", "required": False},
                            ),
                            7: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [("image", "Image"), ("video", "Video")],
                                    "help_text": "Select the type of media to display",
                                },
                            ),
                            8: ("wagtail.images.blocks.ImageBlock", [], {}),
                            9: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": 'Log into Vimeo using 1Password and upload the desired video. Then select the video and click "...", "Video File Links", and select "(mp4, 1920 x 1080)". Copy and paste the link here.',
                                    "max_length": 500,
                                    "required": False,
                                },
                            ),
                            10: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("portrait", "Portrait"),
                                        ("landscape", "Landscape"),
                                        ("square", "Square"),
                                        ("widescreen", "Widescreen 16:9 (12 columns wide)"),
                                    ],
                                    "help_text": "Select the orientation of this media",
                                },
                            ),
                            11: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 6), ("content", 7), ("image", 8), ("video_url", 9), ("orientation", 10)]],
                                {"group": "Media & Embeds"},
                            ),
                            12: ("wagtail.blocks.StructBlock", [[]], {"group": "Layout"}),
                            13: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Heading", "max_length": 50, "required": True},
                            ),
                            14: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic"],
                                    "label": "Description",
                                    "max_length": 500,
                                    "required": True,
                                },
                            ),
                            15: (
                                "wagtail.images.blocks.ImageBlock",
                                [],
                                {"help_text": "Image for the card", "label": "Image"},
                            ),
                            16: ("wagtail.blocks.CharBlock", (), {}),
                            17: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("page", "Page"),
                                        ("external_url", "External URL"),
                                        ("relative_url", "Relative URL"),
                                        ("email", "Email"),
                                        ("anchor", "Anchor"),
                                        ("file", "File"),
                                        ("phone", "Phone"),
                                    ],
                                    "label": "Link to",
                                },
                            ),
                            18: ("wagtail.blocks.PageChooserBlock", (), {"label": "Page", "required": False}),
                            19: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {
                                    "help_text": "Enter a full URL including http:// or https://",
                                    "label": "External URL",
                                    "max_length": 300,
                                    "required": False,
                                },
                            ),
                            20: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": 'A path relative to this domain. For example, "/foo/bar" or "?foo=bar".',
                                    "label": "Relative URL",
                                    "max_length": 300,
                                    "required": False,
                                    "validators": [
                                        foundation_cms.legacy_apps.wagtailpages.validators.RelativeURLValidator()
                                    ],
                                },
                            ),
                            21: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": 'An id attribute of an element on the current page. For example, "#section-1"',
                                    "label": "#",
                                    "max_length": 300,
                                    "required": False,
                                    "validators": [foundation_cms.validators.AnchorLinkValidator()],
                                },
                            ),
                            22: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                            23: (
                                "wagtail.documents.blocks.DocumentChooserBlock",
                                (),
                                {"label": "File", "required": False},
                            ),
                            24: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Phone", "max_length": 30, "required": False},
                            ),
                            25: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {"label": "Open in new window", "required": False},
                            ),
                            26: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {"choices": [("btn-primary", "Primary"), ("btn-secondary", "Secondary")]},
                            ),
                            27: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("label", 16),
                                        ("link_to", 17),
                                        ("page", 18),
                                        ("external_url", 19),
                                        ("relative_url", 20),
                                        ("anchor", 21),
                                        ("email", 22),
                                        ("file", 23),
                                        ("phone", 24),
                                        ("new_window", 25),
                                        ("style", 26),
                                    ]
                                ],
                                {"help_text": "Link button for the card.", "label": "Button", "required": False},
                            ),
                            28: (
                                "wagtail.blocks.StructBlock",
                                [[("heading", 13), ("description", 14), ("image", 15), ("button", 27)]],
                                {"group": "Card Collections"},
                            ),
                            29: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("donation-form", "Donation Form"),
                                        ("donor-map", "Donor Map"),
                                        ("top-locations", "Top Locations"),
                                        ("donation-levels", "Donation Levels"),
                                        ("donate-button", "Donate Button"),
                                    ],
                                    "help_text": "Select the type of Fundraise Up element.",
                                },
                            ),
                            30: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Copy the HTML code generated by the desired Fundraise Up element and paste it here.",
                                    "required": True,
                                },
                            ),
                            31: (
                                "wagtail.blocks.StructBlock",
                                [[("fru_element_type", 29), ("fru_element_embed_code", 30)]],
                                {"group": "Engagement & Buttons"},
                            ),
                            32: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Please note that only URLs from allow-listed domains will work."},
                            ),
                            33: (
                                "wagtail.blocks.IntegerBlock",
                                (),
                                {
                                    "help_text": "Optional integer pixel value for custom iFrame height",
                                    "required": False,
                                },
                            ),
                            34: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {"choices": [("normal", "Normal"), ("full_width", "Full Width")]},
                            ),
                            35: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": 'Checking this will add "scrolling=no" to the iframe. Use this if your iframe is rendering an unnecessary scroll bar or whitespace below it.',
                                    "required": False,
                                },
                            ),
                            36: (
                                "wagtail.blocks.StructBlock",
                                [[("url", 32), ("height", 33), ("iframe_width", 34), ("disable_scroll", 35)]],
                                {"group": "Media & Embeds"},
                            ),
                            37: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Title/caption for this image", "required": False},
                            ),
                            38: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("portrait", "Portrait"),
                                        ("landscape", "Landscape"),
                                        ("square", "Square"),
                                    ],
                                    "help_text": "Select the orientation of this image",
                                },
                            ),
                            39: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 37), ("image", 8), ("orientation", 38)]],
                                {"group": "Media & Embeds"},
                            ),
                            40: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "The full value to animate, including any symbols, commas, decimals, or suffixes (e.g., $5.2M).",
                                    "max_length": 5,
                                    "required": True,
                                },
                            ),
                            41: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Heading of the stat", "required": True},
                            ),
                            42: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Short description of the stat", "required": False},
                            ),
                            43: (
                                "wagtail.blocks.StructBlock",
                                [[("stat_number", 40), ("stat_heading", 41), ("stat_description", 42)]],
                                {},
                            ),
                            44: (
                                "wagtail.blocks.ListBlock",
                                (43,),
                                {
                                    "default": [
                                        {"stat_description": "", "stat_heading": "", "stat_number": ""},
                                        {"stat_description": "", "stat_heading": "", "stat_number": ""},
                                        {"stat_description": "", "stat_heading": "", "stat_number": ""},
                                    ],
                                    "help_text": "Add exactly 3 stats to appear in the Impact Numbers section",
                                    "label": "Impact Stats",
                                    "max_num": 3,
                                    "min_num": 3,
                                },
                            ),
                            45: ("wagtail.blocks.StructBlock", [[("stats", 44)]], {"group": "Data Display"}),
                            46: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("label", 16),
                                        ("link_to", 17),
                                        ("page", 18),
                                        ("external_url", 19),
                                        ("relative_url", 20),
                                        ("anchor", 21),
                                        ("email", 22),
                                        ("file", 23),
                                        ("phone", 24),
                                        ("new_window", 25),
                                        ("style", 26),
                                    ]
                                ],
                                {"group": "Engagement & Buttons"},
                            ),
                            47: ("wagtail.blocks.CharBlock", (), {"help_text": "Heading displayed above the list"}),
                            48: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"help_text": "Description displayed above the list", "required": False},
                            ),
                            49: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("label", 16),
                                        ("link_to", 17),
                                        ("page", 18),
                                        ("external_url", 19),
                                        ("relative_url", 20),
                                        ("anchor", 21),
                                        ("email", 22),
                                        ("file", 23),
                                        ("phone", 24),
                                        ("new_window", 25),
                                    ]
                                ],
                                {},
                            ),
                            50: ("wagtail.blocks.ListBlock", (49,), {"max_num": 4, "min_num": 1}),
                            51: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 47), ("description", 48), ("items", 50)]],
                                {"group": "Data Display"},
                            ),
                            52: (
                                "wagtail.snippets.blocks.SnippetChooserBlock",
                                ("snippets.NewsletterSignup",),
                                {"max_num": 1},
                            ),
                            53: (
                                "wagtail.blocks.StructBlock",
                                [[("newsletter_signup", 52)]],
                                {"group": "Engagement & Buttons"},
                            ),
                            54: (
                                "wagtail.snippets.blocks.SnippetChooserBlock",
                                ("snippets.NewsletterUnsubscribe",),
                                {"max_num": 1},
                            ),
                            55: (
                                "wagtail.blocks.StructBlock",
                                [[("newsletter_unsubscribe", 54)]],
                                {"group": "Engagement & Buttons"},
                            ),
                            56: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Appears as the main heading.", "label": "Headline", "required": False},
                            ),
                            57: (
                                "foundation_cms.blocks.link_block.OptionalLinkBlock",
                                (),
                                {
                                    "help_text": "Optional link for the card.",
                                    "label": "Call to Action Link",
                                    "required": False,
                                },
                            ),
                            58: ("wagtail.blocks.StructBlock", [[("headline", 56), ("cta_link", 57)]], {}),
                            59: (
                                "wagtail.blocks.ListBlock",
                                (58,),
                                {
                                    "default": [
                                        {"cta_link": [], "headline": ""},
                                        {"cta_link": [], "headline": ""},
                                        {"cta_link": [], "headline": ""},
                                    ],
                                    "help_text": "3 cards required.",
                                    "label": "Pillar Cards",
                                    "max_num": 3,
                                    "min_num": 3,
                                },
                            ),
                            60: ("wagtail.blocks.StructBlock", [[("cards", 59)]], {"group": "Card Collections"}),
                            61: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": 'Title of the podcast. <strong>Note:</strong> Does not render on "NothingPersonal" pages.'
                                },
                            ),
                            62: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {
                                    "help_text": 'Optional short description of the podcast. <strong>Note:</strong> Does not render on "NothingPersonal" pages.',
                                    "required": False,
                                },
                            ),
                            63: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 61), ("description", 62), ("simplecast_embed_code", 16)]],
                                {"group": "Media & Embeds"},
                            ),
                            64: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Appears above the headline.", "label": "Label", "required": False},
                            ),
                            65: (
                                "wagtail.images.blocks.ImageBlock",
                                [],
                                {"help_text": "Optional Image for the card", "label": "Image"},
                            ),
                            66: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("label", 16),
                                        ("link_to", 17),
                                        ("page", 18),
                                        ("external_url", 19),
                                        ("relative_url", 20),
                                        ("anchor", 21),
                                        ("email", 22),
                                        ("file", 23),
                                        ("phone", 24),
                                        ("new_window", 25),
                                    ]
                                ],
                                {"help_text": "Link for the card.", "label": "Call to Action Link", "required": True},
                            ),
                            67: (
                                "wagtail.blocks.StructBlock",
                                [[("label", 64), ("headline", 56), ("image", 65), ("cta_link", 66)]],
                                {},
                            ),
                            68: (
                                "wagtail.blocks.ListBlock",
                                (67,),
                                {
                                    "help_text": "Minimum of 3 cards required. More than 3 will turn element into a carousel.",
                                    "label": "Portrait Cards",
                                    "min_num": 3,
                                },
                            ),
                            69: ("wagtail.blocks.StructBlock", [[("cards", 68)]], {"group": "Card Collections"}),
                            70: ("wagtail.blocks.CharBlock", (), {"required": True}),
                            71: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            72: (
                                "wagtail.blocks.StructBlock",
                                [[("quote", 70), ("attribution", 71)]],
                                {"group": "Text"},
                            ),
                            73: (
                                "foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock",
                                (),
                                {"group": "Text"},
                            ),
                            74: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("small", "Small"),
                                        ("medium", "Medium"),
                                        ("large", "Large"),
                                        ("xlarge", "Extra Large"),
                                    ],
                                    "help_text": "Select the size of the spacer",
                                },
                            ),
                            75: ("wagtail.blocks.StructBlock", [[("size", 74)]], {"group": "Layout"}),
                            76: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Name", "max_length": 50, "required": True},
                            ),
                            77: (
                                "wagtail.images.blocks.ImageBlock",
                                [],
                                {"help_text": "Image should follow a 1:1 aspect ratio.", "label": "Image"},
                            ),
                            78: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 70), ("name", 76), ("description", 14), ("image", 77)]],
                                {},
                            ),
                            79: (
                                "wagtail.blocks.ListBlock",
                                (78,),
                                {
                                    "help_text": "3 cards required.",
                                    "label": "Spotlight Cards",
                                    "max_num": 3,
                                    "min_num": 3,
                                },
                            ),
                            80: ("wagtail.blocks.StructBlock", [[("cards", 79)]], {"group": "Card Collections"}),
                            81: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Title shown on the tab button", "required": True},
                            ),
                            82: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Subtitle shown under the title on the tab", "required": False},
                            ),
                            83: ("wagtail.blocks.RichTextBlock", (), {}),
                            84: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                            85: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 37), ("image", 8), ("orientation", 38)]],
                                {"required": False},
                            ),
                            86: ("foundation_cms.blocks.link_block.OptionalLinkBlock", (), {"required": False}),
                            87: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 71), ("subtitle", 71), ("text", 84), ("image", 85), ("link", 86)]],
                                {},
                            ),
                            88: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 16), ("image", 8), ("subtitle", 16), ("link", 86)]],
                                {},
                            ),
                            89: (
                                "wagtail.blocks.StreamBlock",
                                [[("rich_text", 83), ("text_image", 87), ("tab_card_set", 88)]],
                                {
                                    "help_text": "Add one or more content blocks to the tab.",
                                    "min_num": 1,
                                    "required": True,
                                },
                            ),
                            90: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 81), ("subtitle", 82), ("content", 89)]],
                                {},
                            ),
                            91: ("wagtail.blocks.ListBlock", (90,), {"label": "Tabs", "max_num": 8, "min_num": 1}),
                            92: ("wagtail.blocks.StructBlock", [[("tabs", 91)]], {"group": "Card Collections"}),
                            93: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Optional category for the card", "required": False},
                            ),
                            94: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Title for the card", "required": True},
                            ),
                            95: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"help_text": "Optional description text", "required": False},
                            ),
                            96: (
                                "wagtail.blocks.StructBlock",
                                [[("category", 93), ("title", 94), ("text", 95), ("image", 8), ("link", 49)]],
                                {},
                            ),
                            97: (
                                "wagtail.blocks.StreamBlock",
                                [[("card", 96)]],
                                {"help_text": "Add between 1 and 3 cards.", "max_num": 3, "min_num": 1},
                            ),
                            98: ("wagtail.blocks.StructBlock", [[("cards", 97)]], {"group": "Card Collections"}),
                            99: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Title for the block", "required": True},
                            ),
                            100: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [("shape", "Shape"), ("loop-line", "Loop Line")],
                                    "help_text": "Select the style of the title",
                                },
                            ),
                            101: ("wagtail.blocks.StructBlock", [[("title", 99), ("style", 100)]], {"group": "Text"}),
                            102: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("white", "White"),
                                        ("neutral-100", "Grey 100"),
                                        ("neutral-200", "Grey 200"),
                                        ("neutral-300", "Grey 300"),
                                        ("blue-100", "Blue 100"),
                                        ("blue-200", "Blue 200"),
                                        ("blue-300", "Blue 300"),
                                        ("green-100", "Green 100"),
                                        ("green-200", "Green 200"),
                                        ("green-300", "Green 300"),
                                        ("orange-100", "Orange 100"),
                                        ("orange-200", "Orange 200"),
                                        ("orange-300", "Orange 300"),
                                        ("yellow-100", "Yellow 100"),
                                        ("yellow-200", "Yellow 200"),
                                        ("yellow-300", "Yellow 300"),
                                    ]
                                },
                            ),
                            103: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [("top", "Top"), ("middle", "Middle"), ("bottom", "Bottom")],
                                    "help_text": "Vertical alignment of the columns content",
                                },
                            ),
                            104: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 61), ("description", 62), ("simplecast_embed_code", 16)]],
                                {},
                            ),
                            105: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 37), ("image", 8), ("orientation", 38)]],
                                {},
                            ),
                            106: ("wagtail.blocks.StructBlock", [[("newsletter_signup", 52)]], {}),
                            107: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Log into Vimeo, select your desired video, and click 'Copy Link'",
                                    "label": "Vimeo Video URL",
                                    "required": True,
                                },
                            ),
                            108: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Optional Caption Text", "required": False},
                            ),
                            109: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("link_to", 17),
                                        ("page", 18),
                                        ("external_url", 19),
                                        ("relative_url", 20),
                                        ("anchor", 21),
                                        ("email", 22),
                                        ("file", 23),
                                        ("phone", 24),
                                        ("new_window", 25),
                                    ]
                                ],
                                {},
                            ),
                            110: (
                                "wagtail.blocks.ListBlock",
                                (109,),
                                {
                                    "default": [],
                                    "help_text": "Optional URL that this caption should link out to.",
                                    "max_num": 1,
                                    "min_num": 0,
                                },
                            ),
                            111: (
                                "wagtail.blocks.StructBlock",
                                [[("video_url", 107), ("caption", 108), ("caption_url", 110)]],
                                {},
                            ),
                            112: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 47), ("description", 48), ("items", 50)]],
                                {},
                            ),
                            113: ("wagtail.blocks.StructBlock", [[("size", 74)]], {}),
                            114: ("wagtail.blocks.StructBlock", [[("quote", 70), ("attribution", 71)]], {}),
                            115: ("wagtail.blocks.StructBlock", [[("title", 71), ("text", 84)]], {}),
                            116: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("label", 16),
                                        ("link_to", 17),
                                        ("page", 18),
                                        ("external_url", 19),
                                        ("relative_url", 20),
                                        ("anchor", 21),
                                        ("email", 22),
                                        ("file", 23),
                                        ("phone", 24),
                                        ("new_window", 25),
                                        ("style", 26),
                                    ]
                                ],
                                {},
                            ),
                            117: (
                                "wagtail.blocks.StructBlock",
                                [[("fru_element_type", 29), ("fru_element_embed_code", 30)]],
                                {},
                            ),
                            118: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("rich_text", 83),
                                        ("podcast", 104),
                                        ("image", 105),
                                        ("newsletter_signup", 106),
                                        ("video", 111),
                                        ("list", 112),
                                        ("spacer", 113),
                                        ("quote", 114),
                                        ("text_social", 115),
                                        ("link_button", 116),
                                        ("fru_element", 117),
                                    ]
                                ],
                                {"label": "Left Column", "required": False},
                            ),
                            119: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("rich_text", 83),
                                        ("podcast", 104),
                                        ("image", 105),
                                        ("newsletter_signup", 106),
                                        ("video", 111),
                                        ("list", 112),
                                        ("spacer", 113),
                                        ("quote", 114),
                                        ("text_social", 115),
                                        ("link_button", 116),
                                        ("fru_element", 117),
                                    ]
                                ],
                                {"label": "Right Column", "required": False},
                            ),
                            120: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("background_color", 102),
                                        ("vertical_alignment", 103),
                                        ("left_column", 118),
                                        ("right_column", 119),
                                    ]
                                ],
                                {"group": "Layout"},
                            ),
                            121: (
                                "wagtail.blocks.StructBlock",
                                [[("video_url", 107), ("caption", 108), ("caption_url", 110)]],
                                {"group": "Media & Embeds"},
                            ),
                        },
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_pages",
                        to="base.author",
                    ),
                ),
                (
                    "search_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image must be high quality, include our logo mark and have the dimensions 1200 x 628 px. For more design guidelines see here: https://foundation.mozilla.org/en/docs/brand/brand-identity/social-media/#og-images",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.foundationcustomimage",
                        verbose_name="Search image",
                    ),
                ),
                (
                    "topics",
                    modelcluster.contrib.taggit.ClusterTaggableManager(
                        blank=True,
                        help_text="Add one or more existing topics. Start typing to search, then press “Down” arrow on your keyboard to select topic. If topic is unavailable check if Topic exists by going to the left side-nav to Snippet > Page Topics > Check if topic exists. If not, click “Add new page topics”.",
                        through="base.PageTopic",
                        to="base.Topic",
                        verbose_name="Page Topics",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mozfest About Page",
            },
            bases=(wagtailmetadata.models.WagtailImageMetadataMixin, "wagtailcore.page", models.Model),
        ),
    ]
