# Generated by Django 4.2.15 on 2024-09-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donate_banner", "0002_remove_cta_text_and_update_max_lengths"),
    ]

    operations = [
        migrations.AddField(
            model_name="donatebanner",
            name="bgcolor",
            field=models.CharField(
                choices=[("bg-red-60", "Red"), ("bg-blue-60", "Blue"), ("bg-green-60", "Green")],
                default="bg-blue-60",
                help_text="Background color for the banner",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="donatebanner",
            name="textcolor",
            field=models.CharField(
                choices=[("text-white", "White"), ("text-black", "Black")],
                default="text-white",
                help_text="Text color for the banner",
                max_length=20,
            ),
        ),
    ]
