# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-20 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyersguide', '0002_auto_20180910_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='location',
            new_name='location_device',
        ),
        migrations.RemoveField(
            model_name='product',
            name='camera',
        ),
        migrations.RemoveField(
            model_name='product',
            name='microphone',
        ),
        migrations.AddField(
            model_name='product',
            name='camera_app',
            field=models.NullBooleanField(help_text='Does the app have or access a camera?'),
        ),
        migrations.AddField(
            model_name='product',
            name='camera_device',
            field=models.NullBooleanField(help_text='Does this device have or access a camera?'),
        ),
        migrations.AddField(
            model_name='product',
            name='location_app',
            field=models.NullBooleanField(help_text='Does this app access your location?'),
        ),
        migrations.AddField(
            model_name='product',
            name='microphone_app',
            field=models.NullBooleanField(help_text='Does this app have or access a microphone?'),
        ),
        migrations.AddField(
            model_name='product',
            name='microphone_device',
            field=models.NullBooleanField(help_text='Does this Device have or access a microphone?'),
        ),
    ]
