# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-02 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyersguide', '0003_auto_20180927_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='customer_support_easy',
        ),
        migrations.RemoveField(
            model_name='product',
            name='customer_support_easy_helptext',
        ),
        migrations.RemoveField(
            model_name='product',
            name='privacy_policy',
        ),
        migrations.AddField(
            model_name='product',
            name='meets_minimum_security_standards',
            field=models.NullBooleanField(help_text='Does this product meet minimum security standards?'),
        ),
        migrations.AddField(
            model_name='product',
            name='privacy_policy_reading_level',
            field=models.CharField(choices=[('0', "Can't Determine"), ('7', 'Grade 7'), ('8', 'Grade 8'), ('9', 'Grade 9'), ('10', 'Grade 10'), ('11', 'Grade 11'), ('12', 'Grade 12'), ('13', 'Grade 13'), ('14', 'Grade 14'), ('15', 'Grade 15'), ('16', 'Grade 16'), ('17', 'Grade 17'), ('18', 'Grade 18'), ('19', 'Grade 19')], default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='product',
            name='privacy_policy_url',
            field=models.URLField(blank='True'),
        ),
        migrations.AddField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, null=True, related_name='_product_related_products_+', to='buyersguide.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='twitter',
            field=models.CharField(blank='True', help_text='Twitter username', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='updates',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='buyersguide.Update'),
        ),
    ]
