# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-20 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyersguide', '0003_auto_20180920_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uses_encryption_helptext',
            field=models.TextField(blank='True', max_length=5000),
        ),
    ]
