# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-27 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyersguide', '0004_product_related_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(null=True, related_name='rps', to='buyersguide.Product'),
        ),
    ]
