# Generated by Django 2.2.16 on 2020-12-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyersguide', '0006_buyersguideproductcategory_og_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyersguideproductcategory',
            name='name_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyersguideproductcategory',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyersguideproductcategory',
            name='name_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyersguideproductcategory',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyersguideproductcategory',
            name='name_fy_NL',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyersguideproductcategory',
            name='name_nl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyersguideproductcategory',
            name='name_pl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyersguideproductcategory',
            name='name_pt',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
