# Generated by Django 2.2.16 on 2020-10-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyersguide', '0006_auto_20201015_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_date',
            field=models.DateField(blank=True, help_text='The date this product was created', null=True),
        ),
    ]
