# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-25 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyersguide', '0007_auto_20180921_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank='True', max_length=256)),
                ('title', models.CharField(blank='True', max_length=256)),
                ('author', models.CharField(blank='True', max_length=256)),
                ('snippet', models.TextField(blank='True', max_length=5000)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='update',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='buyersguide.Update'),
        ),
    ]
