# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-28 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyersguide', '0007_auto_20180928_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='privacy_policy_reading_level',
            field=models.CharField(choices=[(None, "Can't Determine"), ('0', 'Grade 8-12'), ('1', 'Grade 13+')], default=0, max_length=1),
        ),
    ]
