# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 20:47
from __future__ import unicode_literals

from django.db import migrations
from django.utils.text import slugify


def generate_slugs(apps, schema_editor):
    Product = apps.get_model('buyersguide', 'Product')
    for product in Product.objects.all():
        product.slug = slugify(product.name)
        product.save()


def remove_slug():
    # It's safe for these to just get deleted
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('buyersguide', '0008_product_slug'),
    ]

    operations = [
        migrations.RunPython(generate_slugs, remove_slug)
]
