# Generated by Django 2.2.17 on 2021-01-27 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyersguide', '0008_auto_20210126_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyersguideproductcategory',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='buyersguideproductcategory',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='buyersguideproductcategory',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='buyersguideproductcategory',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='buyersguideproductcategory',
            name='name_fy_NL',
        ),
        migrations.RemoveField(
            model_name='buyersguideproductcategory',
            name='name_nl',
        ),
        migrations.RemoveField(
            model_name='buyersguideproductcategory',
            name='name_pl',
        ),
        migrations.RemoveField(
            model_name='buyersguideproductcategory',
            name='name_pt',
        ),
    ]
