# Generated by Django 2.2.17 on 2021-03-24 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyersguide', '0009_remove_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booleanvote',
            name='product',
        ),
        migrations.RemoveField(
            model_name='booleanvotebreakdown',
            name='product_vote',
        ),
        migrations.RemoveField(
            model_name='generalproduct',
            name='product_ptr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='related_products',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updates',
        ),
        migrations.RemoveField(
            model_name='rangeproductvote',
            name='product',
        ),
        migrations.RemoveField(
            model_name='rangevote',
            name='product',
        ),
        migrations.RemoveField(
            model_name='rangevotebreakdown',
            name='product_vote',
        ),
        migrations.RemoveField(
            model_name='softwareproduct',
            name='product_ptr',
        ),
        migrations.RemoveField(
            model_name='productprivacypolicylink',
            name='product',
        ),
        migrations.DeleteModel(
            name='BooleanProductVote',
        ),
        migrations.DeleteModel(
            name='BooleanVote',
        ),
        migrations.DeleteModel(
            name='BooleanVoteBreakdown',
        ),
        migrations.DeleteModel(
            name='GeneralProduct',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='RangeProductVote',
        ),
        migrations.DeleteModel(
            name='RangeVote',
        ),
        migrations.DeleteModel(
            name='RangeVoteBreakdown',
        ),
        migrations.DeleteModel(
            name='SoftwareProduct',
        ),
    ]
