# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyersguide', '0009_auto_20181018_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(blank=True, default=None, editable=False, help_text='slug used in urls', max_length=256),
        ),
    ]
