# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-27 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyersguide', '0011_auto_20180925_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='updates',
            field=models.ManyToManyField(null=True, related_name='products', to='buyersguide.Update'),
        ),
    ]
