# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyersguide', '0011_auto_20181023_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='need_account',
        ),
        migrations.RemoveField(
            model_name='product',
            name='need_account_helptext',
        ),
    ]
