# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-01 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyersguide', '0015_product_has_moz_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='has_moz_approval',
            field=models.NullBooleanField(help_text='Does this product meet minimum security standards?'),
        ),
    ]
