# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-14 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyersguide', '0016_auto_20181107_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, related_name='rps', to='buyersguide.Product'),
        ),
    ]
