# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-30 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyersguide', '0018_product_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyersguideproductcategory',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the product category. Max. 300 characters.', max_length=300),
        ),
        migrations.AddField(
            model_name='buyersguideproductcategory',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='not_safe_for_work',
            field=models.BooleanField(default=False, help_text='When checked, product thumbnail will appear blurred as well as have a 18+ badge on it'),
        ),
    ]
