# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-29 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyersguide', '0020_buyersguideproductcategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='not_safe_for_work',
            field=models.BooleanField(default=False, help_text='When checked, product thumbnail will appear blurred as well as have a 18+ badge on it'),
        ),
    ]
