# Generated by Django 2.2.4 on 2019-09-16 22:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyersguide', '0021_buyersguideproductcategory_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='review_date',
            field=models.DateField(default=datetime.date(2018, 11, 1), help_text='Review date of this product'),
        ),
    ]
