# Generated by Django 2.2.5 on 2019-10-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyersguide', '0028_uplift_tri_to_quadstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprivacypolicylink',
            name='label',
            field=models.CharField(help_text='Label for this link on the product page', max_length=500),
        ),
    ]
