# Generated by Django 2.2.11 on 2020-04-15 19:33

from django.db import migrations
import networkapi.buyersguide.fields


class Migration(migrations.Migration):

    dependencies = [
        ('buyersguide', '0039_migrate_product_voting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwareproduct',
            name='recording_alert',
            field=networkapi.buyersguide.fields.ExtendedYesNoField(help_text='Alerts when calls are being recorded?', null=True),
        ),
    ]
