# Generated by Django 2.2.11 on 2020-04-16 20:46

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('buyersguide', '0041_auto_20200415_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyersguideproductcategory',
            name='long_description',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='The long description for this product category, if necessary.'),
        ),
    ]
