# Generated by Django 2.2.12 on 2020-04-09 20:09

from django.db import migrations, models
import django.db.models.deletion

def deduplicate(apps, schema_editor):
    BaseRangeProductVote = apps.get_model("buyersguide", "BaseRangeProductVote")
    BaseRangeProductVote.objects.filter(votes=0).delete()

    BaseBooleanProductVote = apps.get_model("buyersguide", "BaseBooleanProductVote")
    BaseBooleanProductVote.objects.filter(votes=0).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('buyersguide', '0042_auto_20200416_1946'),
    ]

    operations = [
        migrations.RunPython(deduplicate, migrations.RunPython.noop),
    ]
