# Generated by Django 2.2.12 on 2020-04-23 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyersguide', '0043_deduplication_pass'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseproduct',
            options={'ordering': ['name']},
        ),
    ]
