# Generated by Django 2.2.12 on 2020-05-07 16:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import networkapi.buyersguide.validators


class Migration(migrations.Migration):

    dependencies = [
        ('buyersguide', '0047_auto_20200506_1918'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BaseBooleanVote',
            new_name='BooleanVote',
        ),
        migrations.RenameModel(
            old_name='BaseProductPrivacyPolicyLink',
            new_name='ProductPrivacyPolicyLink',
        ),
        migrations.RenameModel(
            old_name='BaseRangeVote',
            new_name='RangeVote',
        ),
        migrations.RenameModel(
            old_name='BaseBooleanProductVote',
            new_name='BooleanProductVote',
        ),
        migrations.RenameModel(
            old_name='BaseBooleanVoteBreakdown',
            new_name='BooleanVoteBreakdown',
        ),
        migrations.RenameModel(
            old_name='BaseRangeProductVote',
            new_name='RangeProductVote',
        ),
        migrations.RenameModel(
            old_name='BaseRangeVoteBreakdown',
            new_name='RangeVoteBreakdown',
        ),
    ]
