# Generated by Django 2.2.16 on 2020-09-30 20:19

from django.db import migrations, models
import networkapi.highlights.models


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0001_squashed_0007_nullify_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='image',
            field=models.FileField(help_text='Image representing this highlight', max_length=2048, upload_to=networkapi.highlights.models.get_highlights_image_upload_path),
        ),
    ]
