# Generated by Django 2.2.12 on 2020-05-27 21:04

from django.db import migrations, models
import networkapi.highlights.models


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0001_squashed_0007_nullify_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='image',
            field=models.ImageField(blank=True, help_text='Image representing this highlight', upload_to=networkapi.highlights.models.get_highlights_image_upload_path),
        ),
    ]
