# Generated by Django 2.2.17 on 2021-04-08 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('highlights', '0002_auto_20200930_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='image_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.Image'),
        ),
    ]
