# Generated by Django 2.2.17 on 2021-02-08 21:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0004_auto_20210208_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='locale',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.Locale'),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
