# Generated by Django 2.2.1 on 2019-05-16 22:58

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mozfest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mozfestprimarypage',
            name='intro',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Page intro content'),
        ),
        migrations.AlterField(
            model_name='mozfestprimarypage',
            name='intro_de',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Page intro content', null=True),
        ),
        migrations.AlterField(
            model_name='mozfestprimarypage',
            name='intro_en',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Page intro content', null=True),
        ),
        migrations.AlterField(
            model_name='mozfestprimarypage',
            name='intro_es',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Page intro content', null=True),
        ),
        migrations.AlterField(
            model_name='mozfestprimarypage',
            name='intro_fr',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Page intro content', null=True),
        ),
        migrations.AlterField(
            model_name='mozfestprimarypage',
            name='intro_pl',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Page intro content', null=True),
        ),
        migrations.AlterField(
            model_name='mozfestprimarypage',
            name='intro_pt',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Page intro content', null=True),
        ),
    ]
