# Generated by Django 2.2.1 on 2019-05-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mozfest', '0003_ensure_mozfest_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='mozfestprimarypage',
            name='use_wide_template',
            field=models.BooleanField(default=False, help_text='Make the body content wide, useful for components like directories'),
        ),
    ]
