# Generated by Django 2.2.1 on 2019-05-15 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mozfest', '0003_auto_20190515_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mozfesthomepage',
            old_name='banned_guide_text',
            new_name='banner_guide_text',
        ),
    ]
