# Generated by Django 2.2.1 on 2019-05-16 16:48

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mozfest', '0004_auto_20190515_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='mozfesthomepage',
            name='prefooter_text',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Pre-footer content'),
        ),
    ]
