# Generated by Django 3.1.11 on 2021-10-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mozfest', '0020_auto_20210910_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='mozfestprimarypage',
            name='structured_data',
            field=models.TextField(blank=True, help_text='Structured data JSON for Google search results, see https://schema.org/ for properties', max_length=500, null=True),
        ),
    ]
