# Generated by Django 3.1.11 on 2022-01-26 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mozfest', '0035_auto_20220125_2235'),
        ('mozfest', '0035_mozfestprimarypage_structured_data'),
    ]

    operations = [
    ]
