# Generated by Django 4.2.16 on 2025-03-06 14:51

from django.db import migrations
import networkapi.wagtailpages.pagemodels.blog.blog_topic
import networkapi.wagtailpages.pagemodels.profiles
import networkapi.wagtailpages.validators
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("mozfest", "0068_alter_mozfestprimarypage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mozfestprimarypage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("paragraph", 0),
                    ("card_grid", 19),
                    ("image", 25),
                    ("image_text", 30),
                    ("image_text_mini", 32),
                    ("image_grid", 39),
                    ("video", 42),
                    ("iframe", 47),
                    ("linkbutton", 49),
                    ("spacer", 51),
                    ("single_quote", 54),
                    ("profile_by_id", 56),
                    ("profile_directory", 63),
                    ("recent_blog_entries", 66),
                    ("blog_set", 69),
                    ("datawrapper", 72),
                    ("listing", 81),
                    ("profiles", 85),
                    ("group_listing_block", 92),
                    ("image_feature", 95),
                    ("image_teaser_block", 97),
                    ("text_only_teaser", 103),
                    ("block_with_aside", 109),
                    ("accordion", 116),
                    ("session_slider", 133),
                    ("current_events_slider", 142),
                    ("spaces", 145),
                    ("tito_widget", 150),
                    ("statistics", 155),
                    ("carousel_and_text", 158),
                    ("tickets", 161),
                    ("dark_quote", 54),
                    ("cta", 163),
                    ("newsletter_signup", 165),
                    ("mixed_content", 173),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "link",
                                "h2",
                                "h3",
                                "h4",
                                "h5",
                                "ol",
                                "ul",
                                "hr",
                                "document-link",
                                "large",
                            ],
                            "template": "wagtailpages/blocks/rich_text_block.html",
                        },
                    ),
                    1: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Alt text for card's image.", "required": False},
                    ),
                    3: ("wagtail.blocks.CharBlock", (), {"help_text": "Heading for the card."}),
                    4: ("wagtail.blocks.TextBlock", (), {"help_text": "Body text of the card."}),
                    5: ("wagtail.blocks.CharBlock", (), {}),
                    6: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("external_url", "External URL"),
                                ("relative_url", "Relative URL"),
                                ("email", "Email"),
                                ("anchor", "Anchor"),
                                ("file", "File"),
                                ("phone", "Phone"),
                            ],
                            "label": "Link to",
                        },
                    ),
                    7: ("wagtail.blocks.PageChooserBlock", (), {"label": "Page", "required": False}),
                    8: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Enter a full URL including http:// or https://",
                            "label": "External URL",
                            "max_length": 300,
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'A path relative to this domain. For example, "/foo/bar" or "?foo=bar".',
                            "label": "Relative URL",
                            "max_length": 300,
                            "required": False,
                            "validators": [networkapi.wagtailpages.validators.RelativeURLValidator()],
                        },
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'An id attribute of an element on the current page. For example, "#section-1"',
                            "label": "#",
                            "max_length": 300,
                            "required": False,
                            "validators": [networkapi.wagtailpages.validators.AnchorLinkValidator()],
                        },
                    ),
                    11: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    12: ("wagtail.documents.blocks.DocumentChooserBlock", (), {"label": "File", "required": False}),
                    13: ("wagtail.blocks.CharBlock", (), {"label": "Phone", "max_length": 30, "required": False}),
                    14: ("wagtail.blocks.BooleanBlock", (), {"label": "Open in new window", "required": False}),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 5),
                                ("link_to", 6),
                                ("page", 7),
                                ("external_url", 8),
                                ("relative_url", 9),
                                ("anchor", 10),
                                ("email", 11),
                                ("file", 12),
                                ("phone", 13),
                                ("new_window", 14),
                            ]
                        ],
                        {},
                    ),
                    16: (
                        "wagtail.blocks.ListBlock",
                        (15,),
                        {"help_text": "Optional link that this card should link out to.", "max_num": 1, "min_num": 0},
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 1), ("alt_text", 2), ("title", 3), ("body", 4), ("link", 16)]],
                        {},
                    ),
                    18: ("wagtail.blocks.ListBlock", (17,), {"help_text": "Please use a minimum of 2 cards."}),
                    19: ("wagtail.blocks.StructBlock", [[("cards", 18)]], {}),
                    20: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Image description (for screen readers).", "required": True},
                    ),
                    21: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_to", 6),
                                ("page", 7),
                                ("external_url", 8),
                                ("relative_url", 9),
                                ("anchor", 10),
                                ("email", 11),
                                ("file", 12),
                                ("phone", 13),
                                ("new_window", 14),
                            ]
                        ],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.ListBlock",
                        (22,),
                        {
                            "help_text": "Optional URL that this caption should link out to.",
                            "max_num": 1,
                            "min_num": 0,
                        },
                    ),
                    24: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("normal", "Normal"), ("wide", "Wide"), ("full_width", "Full Width")],
                            "help_text": "Wide images are col-12, Full-Width Images reach both ends of the screen (16:6 images recommended for full width)",
                        },
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 1), ("altText", 20), ("caption", 21), ("caption_url", 23), ("image_width", 24)]],
                        {},
                    ),
                    26: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "link",
                                "h2",
                                "h3",
                                "h4",
                                "h5",
                                "ol",
                                "ul",
                                "hr",
                                "document-link",
                            ]
                        },
                    ),
                    27: (
                        "wagtail.blocks.ListBlock",
                        (22,),
                        {"help_text": "Optional URL that this image should link out to.", "max_num": 1, "min_num": 0},
                    ),
                    28: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"help_text": "Optional divider above content block.", "required": False},
                    ),
                    29: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"help_text": "Optional divider below content block.", "required": False},
                    ),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 1),
                                ("altText", 20),
                                ("text", 26),
                                ("url", 27),
                                ("top_divider", 28),
                                ("bottom_divider", 29),
                            ]
                        ],
                        {},
                    ),
                    31: ("wagtail.blocks.RichTextBlock", (), {"features": ["bold", "italic", "link"]}),
                    32: ("wagtail.blocks.StructBlock", [[("image", 1), ("altText", 20), ("text", 31)]], {}),
                    33: ("wagtail.blocks.CharBlock", (), {"help_text": "Alt text for this image.", "required": False}),
                    34: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Please remember to properly attribute any images we use.", "required": False},
                    ),
                    35: (
                        "wagtail.blocks.ListBlock",
                        (22,),
                        {
                            "help_text": "Optional link that this figure should link out to.",
                            "max_num": 1,
                            "min_num": 0,
                        },
                    ),
                    36: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "If left checked, the image will be cropped to be square.",
                            "required": False,
                        },
                    ),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 1), ("alt_text", 33), ("caption", 34), ("link", 35), ("square_image", 36)]],
                        {},
                    ),
                    38: ("wagtail.blocks.ListBlock", (37,), {}),
                    39: ("wagtail.blocks.StructBlock", [[("grid_items", 38)]], {}),
                    40: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "For YouTube: go to your YouTube video and click “Share,” then “Embed,” and then copy and paste the provided URL only. For example: https://www.youtube.com/embed/3FIVXBawyQw For Vimeo: follow similar steps to grab the embed URL. For example: https://player.vimeo.com/video/9004979",
                            "label": "Embed URL",
                        },
                    ),
                    41: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("normal", "Normal"), ("wide", "Wide"), ("full_width", "Full Width")],
                            "help_text": "Wide videos are col-12, Full-Width videos reach both ends of the screen.",
                        },
                    ),
                    42: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 40), ("caption", 21), ("caption_url", 23), ("video_width", 41)]],
                        {},
                    ),
                    43: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Please note that only URLs from allow-listed domains will work."},
                    ),
                    44: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Optional integer pixel value for custom iFrame height", "required": False},
                    ),
                    45: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("normal", "Normal"), ("wide", "Wide"), ("full_width", "Full Width")],
                            "help_text": "Wide iframes are col-12, Full-Width iframes reach both ends of the screen",
                        },
                    ),
                    46: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": 'Checking this will add "scrolling=no" to the iframe. Use this if your iframe is rendering an unnecessary scroll bar or whitespace below it.',
                            "required": False,
                        },
                    ),
                    47: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("url", 43),
                                ("height", 44),
                                ("caption", 21),
                                ("caption_url", 23),
                                ("iframe_width", 45),
                                ("disable_scroll", 46),
                            ]
                        ],
                        {},
                    ),
                    48: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("btn-primary", "Primary button"), ("btn-secondary", "Secondary button")]},
                    ),
                    49: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 5),
                                ("link_to", 6),
                                ("page", 7),
                                ("external_url", 8),
                                ("relative_url", 9),
                                ("anchor", 10),
                                ("email", 11),
                                ("file", 12),
                                ("phone", 13),
                                ("new_window", 14),
                                ("styling", 48),
                            ]
                        ],
                        {},
                    ),
                    50: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("1", "quarter spacing"),
                                ("2", "half spacing"),
                                ("3", "single spacing"),
                                ("4", "one and a half spacing"),
                                ("5", "triple spacing"),
                            ]
                        },
                    ),
                    51: ("wagtail.blocks.StructBlock", [[("size", 50)]], {}),
                    52: ("wagtail.blocks.RichTextBlock", (), {"features": ["bold"]}),
                    53: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "link", "large"], "required": False},
                    ),
                    54: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 52), ("attribution", 21), ("attribution_info", 53)]],
                        {},
                    ),
                    55: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Show profiles for pulse users with specific profile ids (https://api.mozillapulse.org/api/pulse/v2/profiles/[##]). For multiple profiles, specify a comma separated list (e.g. 85,105,332).",
                            "label": "Profile by ID",
                        },
                    ),
                    56: ("wagtail.blocks.StructBlock", [[("ids", 55)]], {}),
                    57: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 12,
                            "help_text": "Pick up to 48 profiles.",
                            "max_value": 48,
                            "min_value": 1,
                            "required": True,
                        },
                    ),
                    58: (
                        "wagtail.blocks.static_block.StaticBlock",
                        (),
                        {
                            "admin_text": "-------- ADVANCED FILTERS: OPTIONS TO DISPLAY FEWER, MORE TARGETED RESULTS. --------",
                            "label": " ",
                        },
                    ),
                    59: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "", "help_text": "Example: Fellow.", "required": False},
                    ),
                    60: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "", "help_text": "Example: Tech Policy.", "required": False},
                    ),
                    61: ("wagtail.blocks.CharBlock", (), {"default": "", "required": False}),
                    62: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "2019,2018,2017,2016,2015,2014,2013",
                            "help_text": "Example: 2019,2018,2017,2016,2015,2014,2013",
                            "required": True,
                        },
                    ),
                    63: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("max_number_of_results", 57),
                                ("advanced_filter_header", 58),
                                ("profile_type", 59),
                                ("program_type", 60),
                                ("year", 61),
                                ("filter_values", 62),
                            ]
                        ],
                        {},
                    ),
                    64: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Test this filter at foundation.mozilla.org/blog/tags/",
                            "label": "Filter by Tag",
                            "required": False,
                        },
                    ),
                    65: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": networkapi.wagtailpages.pagemodels.blog.blog_topic.BlogPageTopic.get_topics,
                            "help_text": "Test this filter at foundation.mozilla.org/blog/topic/",
                            "label": "Filter by Topic",
                            "required": False,
                        },
                    ),
                    66: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 21),
                                ("tag_filter", 64),
                                ("topic_filter", 65),
                                ("top_divider", 28),
                                ("bottom_divider", 29),
                            ]
                        ],
                        {},
                    ),
                    67: ("wagtail.blocks.PageChooserBlock", (), {"page_type": ["wagtailpages.BlogPage"]}),
                    68: ("wagtail.blocks.ListBlock", (67,), {}),
                    69: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 5), ("top_divider", 28), ("bottom_divider", 29), ("blog_pages", 68)]],
                        {},
                    ),
                    70: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {
                            "help_text": 'Enter the "visualization only" link of the Datawrapper chart. It looks something like this: https://datawrapper.dwcdn.net/KwSKp/1/',
                            "icon": "image",
                            "template": "wagtailpages/blocks/datawrapper_embed_block.html",
                        },
                    ),
                    71: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "If checked, the table will render wider than the other page body content.",
                            "required": False,
                        },
                    ),
                    72: ("wagtail.blocks.StructBlock", [[("datawrapper", 70), ("wide", 71)]], {}),
                    73: ("wagtail.blocks.CharBlock", (), {"help_text": "Heading for the block.", "required": False}),
                    74: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Metadata to highlight on the card.", "required": False},
                    ),
                    75: ("wagtail.blocks.CharBlock", (), {"help_text": "Generic metadata.", "required": False}),
                    76: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold"], "help_text": "Body text of the card.", "required": False},
                    ),
                    77: (
                        "wagtail.blocks.ListBlock",
                        (22,),
                        {"help_text": "Optional link that this card should link out to.", "max_num": 1, "min_num": 0},
                    ),
                    78: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 1),
                                ("alt_text", 2),
                                ("title", 3),
                                ("highlighted_metadata", 74),
                                ("metadata", 75),
                                ("body", 76),
                                ("link", 77),
                            ]
                        ],
                        {},
                    ),
                    79: (
                        "wagtail.blocks.ListBlock",
                        (78,),
                        {"help_text": "Please use a minimum of 2 cards.", "min_num": 2},
                    ),
                    80: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [(2, "2"), (3, "3")],
                            "help_text": "Number of cards per row. Note: this is a max and fewer might be used if is less space is available.",
                            "required": False,
                        },
                    ),
                    81: ("wagtail.blocks.StructBlock", [[("heading", 73), ("cards", 79), ("cards_per_row", 80)]], {}),
                    82: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        (networkapi.wagtailpages.pagemodels.profiles.Profile,),
                        {},
                    ),
                    83: ("wagtail.blocks.StructBlock", [[("profile", 82)]], {}),
                    84: ("wagtail.blocks.ListBlock", (83,), {"min_num": 1}),
                    85: ("wagtail.blocks.StructBlock", [[("profiles", 84)]], {}),
                    86: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Heading for the group of cards.", "required": False},
                    ),
                    87: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional meta data information for the card.", "required": False},
                    ),
                    88: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "link"], "help_text": "Body text of the card."},
                    ),
                    89: (
                        "wagtail.blocks.ListBlock",
                        (22,),
                        {"help_text": "Optional link that this card should link to.", "max_num": 1, "min_num": 0},
                    ),
                    90: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 1), ("alt_text", 2), ("meta_data", 87), ("title", 3), ("body", 88), ("link", 89)]],
                        {},
                    ),
                    91: ("wagtail.blocks.ListBlock", (90,), {}),
                    92: ("wagtail.blocks.StructBlock", [[("title", 86), ("cards", 91)]], {}),
                    93: ("wagtail.blocks.CharBlock", (), {"help_text": "Image description (for screen readers)."}),
                    94: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Page that the title should link out to.", "required": False},
                    ),
                    95: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 1),
                                ("alt_text", 93),
                                ("metadata", 21),
                                ("title", 3),
                                ("title_link", 94),
                                ("body", 21),
                            ]
                        ],
                        {},
                    ),
                    96: (
                        "wagtail.blocks.ListBlock",
                        (49,),
                        {"help_text": "Optional link button", "max_num": 1, "min_num": 0},
                    ),
                    97: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 3),
                                ("text", 52),
                                ("image", 1),
                                ("altText", 20),
                                ("link_button", 96),
                                ("top_divider", 28),
                                ("bottom_divider", 29),
                            ]
                        ],
                        {},
                    ),
                    98: (
                        "wagtail.blocks.ListBlock",
                        (22,),
                        {"help_text": "Optional link that the header should link out to.", "max_num": 1, "min_num": 0},
                    ),
                    99: ("wagtail.blocks.CharBlock", (), {"max_length": 500}),
                    100: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Body text of the card.", "max_length": 200, "required": False},
                    ),
                    101: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 3), ("link", 98), ("meta_data", 99), ("body", 100)]],
                        {},
                    ),
                    102: (
                        "wagtail.blocks.ListBlock",
                        (101,),
                        {"help_text": "Please use a minimum of 3 cards.", "min_num": 3},
                    ),
                    103: ("wagtail.blocks.StructBlock", [[("cards", 102)]], {}),
                    104: (
                        "wagtail.blocks.StreamBlock",
                        [[("listing", 81), ("paragraph", 26)]],
                        {
                            "help_text": "The wider block that appears on the left on desktop",
                            "icon": "doc-full",
                            "max_num": 1,
                        },
                    ),
                    105: ("wagtail.blocks.CharBlock", (), {"help_text": "Heading for the card.", "required": False}),
                    106: ("wagtail.blocks.TextBlock", (), {"help_text": "Body text of the card.", "required": False}),
                    107: ("wagtail.blocks.StructBlock", [[("title", 105), ("body", 106)]], {}),
                    108: (
                        "wagtail.blocks.StreamBlock",
                        [[("aside_content", 107), ("linkbutton", 49), ("spacer", 51)]],
                        {
                            "help_text": "Elements here will appear in the column on the right side of the page on desktop. This can be left blank if you would just like a 2/3 column on the left",
                            "icon": "doc-full",
                            "required": False,
                        },
                    ),
                    109: ("wagtail.blocks.StructBlock", [[("content", 104), ("aside", 108)]], {}),
                    110: ("wagtail.blocks.CharBlock", (), {"help_text": "Heading for the Accordion Item"}),
                    111: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"blank": True, "features": ["bold", "italic", "link", "ul", "ol", "document-link"]},
                    ),
                    112: ("wagtail.blocks.StructBlock", [[("image", 1), ("altText", 20)]], {}),
                    113: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 111), ("datawrapper", 72), ("image", 112), ("video", 42)]],
                        {},
                    ),
                    114: ("wagtail.blocks.StructBlock", [[("title", 110), ("content", 113)]], {}),
                    115: ("wagtail.blocks.ListBlock", (114,), {}),
                    116: ("wagtail.blocks.StructBlock", [[("accordion_items", 115)]], {}),
                    117: ("wagtail.blocks.CharBlock", (), {"help_text": "Heading for the slider."}),
                    118: ("wagtail.blocks.CharBlock", (), {"help_text": "Author of this session.", "required": False}),
                    119: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "The image associated with this session."},
                    ),
                    120: ("wagtail.blocks.RichTextBlock", (), {"help_text": "Body text of this card."}),
                    121: (
                        "wagtailmedia.blocks.VideoChooserBlock",
                        (),
                        {"help_text": "Video that will autoplay when this card is hovered on", "required": False},
                    ),
                    122: ("wagtail.blocks.PageChooserBlock", (), {"help_text": "Page that this should link out to."}),
                    123: ("wagtail.blocks.StructBlock", [[("link", 122)]], {}),
                    124: ("wagtail.blocks.URLBlock", (), {"help_text": "URL that this should link out to."}),
                    125: ("wagtail.blocks.StructBlock", [[("link", 124)]], {}),
                    126: (
                        "wagtail.blocks.StreamBlock",
                        [[("internal", 123), ("external", 125)]],
                        {"help_text": "Page or external URL this card will link out to.", "max_num": 1},
                    ),
                    127: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 3),
                                ("author_subheading", 118),
                                ("image", 119),
                                ("body", 120),
                                ("video", 121),
                                ("link", 126),
                            ]
                        ],
                        {},
                    ),
                    128: (
                        "wagtail.blocks.StreamBlock",
                        [[("session_item", 127)]],
                        {"help_text": "A list of sessions in the slider."},
                    ),
                    129: ("wagtail.blocks.CharBlock", (), {"help_text": "Label for this link."}),
                    130: ("wagtail.blocks.StructBlock", [[("label", 129), ("link", 122)]], {}),
                    131: ("wagtail.blocks.StructBlock", [[("label", 129), ("link", 124)]], {}),
                    132: (
                        "wagtail.blocks.StreamBlock",
                        [[("internal", 130), ("external", 131)]],
                        {"help_text": "Button that appears below the slider.", "max_num": 1, "required": False},
                    ),
                    133: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 117), ("session_items", 128), ("button", 132)]],
                        {},
                    ),
                    134: ("wagtail.blocks.CharBlock", (), {"help_text": "Heading of the card."}),
                    135: (
                        "wagtail.blocks.StreamBlock",
                        [[("internal", 130), ("external", 131)]],
                        {
                            "help_text": "The link that appears below the card heading.",
                            "max_num": 1,
                            "required": False,
                        },
                    ),
                    136: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "The image associated with this event."},
                    ),
                    137: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"help_text": "Document that this should link out to."},
                    ),
                    138: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 129), ("document", 137)]],
                        {"help_text": 'An iCal document can be attached here for an "Add to Calendar" button.'},
                    ),
                    139: (
                        "wagtail.blocks.StreamBlock",
                        [[("internal", 130), ("external", 131), ("document", 138)]],
                        {"help_text": "A list of buttons that will appear at the bottom of the card.", "max_num": 2},
                    ),
                    140: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 134), ("subheading_link", 135), ("image", 136), ("body", 4), ("buttons", 139)]],
                        {},
                    ),
                    141: (
                        "wagtail.blocks.StreamBlock",
                        [[("current_event", 140)]],
                        {"help_text": "A list of current events in the slider."},
                    ),
                    142: ("wagtail.blocks.StructBlock", [[("title", 117), ("current_events", 141)]], {}),
                    143: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 1), ("title", 3), ("body", 4), ("link", 126)]],
                        {},
                    ),
                    144: (
                        "wagtail.blocks.StreamBlock",
                        [[("space_card", 143)]],
                        {"help_text": "A list of Spaces Cards."},
                    ),
                    145: ("wagtail.blocks.StructBlock", [[("title", 5), ("cards", 144)]], {}),
                    146: ("wagtail.blocks.CharBlock", (), {"help_text": "The text to show on the Tito button."}),
                    147: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("events.TitoEvent",),
                        {"help_event": "The Tito event to be displayed"},
                    ),
                    148: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Comma-separated list of ticket/release IDs to limit to, e.g. "3elajg6qcxu,6qiiw4socs4"',
                            "required": False,
                        },
                    ),
                    149: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter a source to track where events come from.",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    150: (
                        "wagtail.blocks.StructBlock",
                        [[("button_label", 146), ("styling", 48), ("event", 147), ("releases", 148), ("source", 149)]],
                        {},
                    ),
                    151: ("wagtail.blocks.CharBlock", (), {"help_text": "The statistic figure, e.g '1000+' or '10%'"}),
                    152: ("wagtail.blocks.CharBlock", (), {"help_text": "Context or description for the statistic"}),
                    153: ("wagtail.blocks.StructBlock", [[("title", 151), ("description", 152)]], {}),
                    154: (
                        "wagtail.blocks.ListBlock",
                        (153,),
                        {"help_text": "Please use a minimum of 2 cards.", "max_num": 4, "min_num": 2},
                    ),
                    155: ("wagtail.blocks.StructBlock", [[("statistics", 154)]], {}),
                    156: (
                        "wagtail.blocks.ListBlock",
                        (15,),
                        {"help_text": "A CTA Link for the carousel", "max_num": 1, "min_num": 0},
                    ),
                    157: ("wagtail.blocks.ListBlock", (112,), {"max_num": 4}),
                    158: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 73), ("text", 31), ("link", 156), ("carousel_images", 157)]],
                        {},
                    ),
                    159: ("wagtail.snippets.blocks.SnippetChooserBlock", ("mozfest.Ticket",), {}),
                    160: ("wagtail.blocks.ListBlock", (159,), {"max_num": 3}),
                    161: ("wagtail.blocks.StructBlock", [[("heading", 73), ("tickets", 160)]], {}),
                    162: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    163: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 5),
                                ("link_to", 6),
                                ("page", 7),
                                ("external_url", 8),
                                ("relative_url", 9),
                                ("anchor", 10),
                                ("email", 11),
                                ("file", 12),
                                ("phone", 13),
                                ("new_window", 14),
                                ("heading", 21),
                                ("text", 21),
                                ("dark_background", 162),
                            ]
                        ],
                        {},
                    ),
                    164: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("mozfest.NewsletterSignupWithBackground",),
                        {},
                    ),
                    165: ("wagtail.blocks.StructBlock", [[("snippet", 164)]], {}),
                    166: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional caption for the video, displayed next to the play button.",
                            "max_length": 25,
                            "required": False,
                        },
                    ),
                    167: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional title for the video.", "max_length": 50, "required": False},
                    ),
                    168: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Text content to display with the video title.", "required": False},
                    ),
                    169: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "The image to show before the video is played."},
                    ),
                    170: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 40), ("caption", 166), ("title", 167), ("text", 168), ("thumbnail", 169)]],
                        {},
                    ),
                    171: ("wagtail.blocks.ListBlock", (78,), {"max_num": 4, "min_num": 1}),
                    172: (
                        "wagtail.blocks.ListBlock",
                        (15,),
                        {
                            "help_text": "Optional link that this mixed content block should link out to.",
                            "max_num": 1,
                            "min_num": 0,
                        },
                    ),
                    173: ("wagtail.blocks.StructBlock", [[("video", 170), ("cards", 171), ("link", 172)]], {}),
                },
            ),
        ),
    ]
