# Generated by Django 4.2.20 on 2025-03-26 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
        ("mozfest", "0069_alter_mozfestprimarypage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mozfestprimarypage",
            name="banner",
            field=models.ForeignKey(
                blank=True,
                help_text="Choose an image that's bigger than 4032px x 1152px with aspect ratio 3.5:1",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mozfest_primary_banner",
                to="images.foundationcustomimage",
                verbose_name="Hero Image",
            ),
        ),
        migrations.AlterField(
            model_name="mozfestprimarypage",
            name="search_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Image must be high quality, include our logo mark and have the dimensions 1200 x 628 px. For more design guidelines see here: https://foundation.mozilla.org/en/docs/brand/brand-identity/social-media/#og-images",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.foundationcustomimage",
                verbose_name="Search image",
            ),
        ),
        migrations.AlterField(
            model_name="newslettersignupwithbackground",
            name="background_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional background image for the rendered signup snippet.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mozfest_newsletter_signup_background",
                to="images.foundationcustomimage",
                verbose_name="Background Image",
            ),
        ),
    ]
