# Generated by Django 4.2.25 on 2026-01-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="foundationcustomimage",
            name="original_gif",
            field=models.FileField(
                blank=True,
                help_text="Original uploaded GIF (stored for reference).",
                null=True,
                upload_to="images/original_gif/",
            ),
        ),
    ]
