# Generated by Django 4.2.20 on 2025-06-13 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foundationcustomrendition",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="renditions",
                to="images.foundationcustomimage",
            ),
        ),
    ]
