# Generated by Django 4.2.20 on 2025-04-03 16:56

from django.db import migrations, models
import django.db.models.deletion
import foundation_cms.base.mixins.theme_mixin
import modelcluster.fields
import wagtail.fields
import wagtailmetadata.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("taggit", "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx"),
        ("base", "__first__"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("body", wagtail.fields.StreamField([], blank=True, block_lookup={})),
                ("hero_headline", models.CharField(blank=True, help_text="Hero story headline", max_length=120)),
                (
                    "hero_intro_heading",
                    models.CharField(
                        blank=True,
                        default="A healthy internet is one in which privacy, openness, and inclusion are the norms.",
                        max_length=100,
                    ),
                ),
                (
                    "hero_intro_body",
                    models.TextField(
                        blank=True,
                        default="Mozilla empowers consumers to demand better online privacy, trustworthy AI, and safe online experiences from Big Tech and governments. We work across borders, disciplines, and technologies to uphold principles like privacy, inclusion and decentralization online.",
                        max_length=300,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_pages",
                        to="base.author",
                    ),
                ),
                (
                    "hero_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "search_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Search image",
                    ),
                ),
                ("tags", modelcluster.fields.ParentalManyToManyField(blank=True, to="taggit.tag")),
            ],
            options={
                "verbose_name": "Home Page (new)",
            },
            bases=(
                wagtailmetadata.models.WagtailImageMetadataMixin,
                foundation_cms.base.mixins.theme_mixin.ThemedPageMixin,
                "wagtailcore.page",
                models.Model,
            ),
        ),
    ]
