# Generated by Django 4.2.20 on 2025-05-19 14:43

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("rich_text", 0)], blank=True, block_lookup={0: ("wagtail.blocks.RichTextBlock", (), {})}
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("rich_text", 0)], blank=True, block_lookup={0: ("wagtail.blocks.RichTextBlock", (), {})}
            ),
        ),
    ]
