# Generated by Django 4.2.20 on 2025-05-20 19:43

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_generalpage_body_alter_homepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("rich_text", 0), ("tabbed_content", 6)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title shown on the tab button", "required": True},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Subtitle shown under the title on the tab", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 0)]],
                        {"help_text": "Only one content block per tab.", "max_num": 1, "min_num": 1, "required": True},
                    ),
                    4: ("wagtail.blocks.StructBlock", [[("title", 1), ("subtitle", 2), ("content", 3)]], {}),
                    5: ("wagtail.blocks.ListBlock", (4,), {"label": "Tabs", "max_num": 8, "min_num": 1}),
                    6: ("wagtail.blocks.StructBlock", [[("tabs", 5)]], {}),
                },
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("rich_text", 0), ("tabbed_content", 6)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title shown on the tab button", "required": True},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Subtitle shown under the title on the tab", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 0)]],
                        {"help_text": "Only one content block per tab.", "max_num": 1, "min_num": 1, "required": True},
                    ),
                    4: ("wagtail.blocks.StructBlock", [[("title", 1), ("subtitle", 2), ("content", 3)]], {}),
                    5: ("wagtail.blocks.ListBlock", (4,), {"label": "Tabs", "max_num": 8, "min_num": 1}),
                    6: ("wagtail.blocks.StructBlock", [[("tabs", 5)]], {}),
                },
            ),
        ),
    ]
