# Generated by Django 4.2.20 on 2025-05-20 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_generalpage_body_alter_homepage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalpage",
            name="theme",
            field=models.CharField(
                blank=True,
                choices=[("default", "Default"), ("magazine", "Magazine")],
                help_text="Optional. If unset, theme will be inherited from section root.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="theme",
            field=models.CharField(
                blank=True,
                choices=[("default", "Default"), ("magazine", "Magazine")],
                help_text="Optional. If unset, theme will be inherited from section root.",
                max_length=50,
                null=True,
            ),
        ),
    ]
