# Generated by Django 4.2.20 on 2025-05-22 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_add_theme_to_core_pages"),
        ("core", "0003_alter_generalpage_body_alter_homepage_body"),
    ]

    operations = []
