# Generated by Django 4.2.20 on 2025-05-23 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_generalpage_sized_images_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="hero_headline",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="hero_image",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="hero_intro_body",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="hero_intro_heading",
        ),
    ]
