# Generated by Django 4.2.20 on 2025-05-30 05:07

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_generalpage_body_alter_homepage_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="hero_headline",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="hero_image",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="hero_intro_body",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="hero_intro_heading",
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_accordion",
            field=wagtail.fields.StreamField(
                [("video_panel", 4), ("image_text_panel", 8)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    1: ("wagtail.blocks.CharBlock", (), {"max_length": 40, "required": False}),
                    2: ("wagtail.images.blocks.ImageBlock", [], {}),
                    3: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Please enter a valid Vimeo URL (e.g. https://vimeo.com/123456789 or https://player.vimeo.com/video/123456789).",
                            "required": True,
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 0), ("heading", 1), ("thumbnail", 2), ("video_url", 3)]],
                        {},
                    ),
                    5: ("wagtail.blocks.CharBlock", (), {"max_length": 40, "required": True}),
                    6: ("wagtail.blocks.URLBlock", (), {"required": True}),
                    7: ("wagtail.blocks.TextBlock", (), {"max_length": 100, "required": False}),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 0),
                                ("heading", 5),
                                ("image", 2),
                                ("cta_text", 0),
                                ("cta_link", 6),
                                ("description", 7),
                            ]
                        ],
                        {},
                    ),
                },
                verbose_name="Hero Accordion",
            ),
        ),
    ]
