# Generated by Django 4.2.20 on 2025-06-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_generalpage_body_alter_homepage_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generalpage",
            name="header",
        ),
        migrations.RemoveField(
            model_name="generalpage",
            name="hero_headline",
        ),
        migrations.AddField(
            model_name="generalpage",
            name="hero_description",
            field=models.CharField(blank=True, help_text="Hero Description", max_length=120),
        ),
        migrations.AddField(
            model_name="generalpage",
            name="hero_title",
            field=models.TextField(blank=True, help_text="Hero Title"),
        ),
        migrations.AddField(
            model_name="generalpage",
            name="hero_variant",
            field=models.CharField(
                choices=[("side-by-side", "Side by Side"), ("top-to-bottom", "Top to Bottom")],
                default="side-by-side",
                help_text="Select the variant of the hero section",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="generalpage",
            name="show_hero",
            field=models.BooleanField(
                default=True,
                help_text="Check to display the hero section on this page.",
                verbose_name="Show Hero Section",
            ),
        ),
        migrations.AddField(
            model_name="generalpage",
            name="topics",
            field=models.TextField(
                blank=True, help_text="Comma-separated list of topics related to this page.", verbose_name="Topics"
            ),
        ),
    ]
