# Generated by Django 4.2.20 on 2025-06-17 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_add_newsletter_signup"),
        ("core", "0017_alter_generalpage_body_alter_homepage_body"),
    ]

    operations = []
