# Generated by Django 4.2.20 on 2025-07-02 17:27

from django.db import migrations
import foundation_cms.legacy_apps.wagtailpages.validators
import foundation_cms.validators
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_alter_generalpage_search_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("rich_text", 0),
                    ("image", 4),
                    ("audio_block", 9),
                    ("tabbed_content", 30),
                    ("two_column_container_block", 41),
                    ("link_button_block", 24),
                    ("portrait_card_set_block", 50),
                    ("spotlight_card_set_block", 57),
                    ("spacer_block", 59),
                    ("impact_numbers", 65),
                    ("newsletter_signup", 33),
                    ("timely_activations_cards", 74),
                    ("quote", 75),
                    ("list_block", 80),
                    ("video_block", 38),
                    ("pillar_card_set", 83),
                    ("featured_card_block", 87),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title/caption for this image", "required": False},
                    ),
                    2: ("wagtail.images.blocks.ImageBlock", [], {}),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("portrait", "Portrait"), ("landscape", "Landscape"), ("square", "Square")],
                            "help_text": "Select the orientation of this image",
                        },
                    ),
                    4: ("wagtail.blocks.StructBlock", [[("title", 1), ("image", 2), ("orientation", 3)]], {}),
                    5: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Optional image to display at the top of the block.", "required": False},
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Image description (for screen readers).", "required": False},
                    ),
                    7: ("wagtail.blocks.CharBlock", (), {}),
                    8: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Short description of the audio", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 5),
                                ("image_alt_text", 6),
                                ("title", 7),
                                ("description", 8),
                                ("simplecast_embed_code", 7),
                            ]
                        ],
                        {},
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title shown on the tab button", "required": True},
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Subtitle shown under the title on the tab", "required": False},
                    ),
                    12: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    13: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("image", 2), ("orientation", 3)]],
                        {"required": False},
                    ),
                    15: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("external_url", "External URL"),
                                ("relative_url", "Relative URL"),
                                ("email", "Email"),
                                ("anchor", "Anchor"),
                                ("file", "File"),
                                ("phone", "Phone"),
                            ],
                            "label": "Link to",
                        },
                    ),
                    16: ("wagtail.blocks.PageChooserBlock", (), {"label": "Page", "required": False}),
                    17: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Enter a full URL including http:// or https://",
                            "label": "External URL",
                            "max_length": 300,
                            "required": False,
                        },
                    ),
                    18: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'A path relative to this domain. For example, "/foo/bar" or "?foo=bar".',
                            "label": "Relative URL",
                            "max_length": 300,
                            "required": False,
                            "validators": [foundation_cms.legacy_apps.wagtailpages.validators.RelativeURLValidator()],
                        },
                    ),
                    19: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'An id attribute of an element on the current page. For example, "#section-1"',
                            "label": "#",
                            "max_length": 300,
                            "required": False,
                            "validators": [foundation_cms.validators.AnchorLinkValidator()],
                        },
                    ),
                    20: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    21: ("wagtail.documents.blocks.DocumentChooserBlock", (), {"label": "File", "required": False}),
                    22: ("wagtail.blocks.CharBlock", (), {"label": "Phone", "max_length": 30, "required": False}),
                    23: ("wagtail.blocks.BooleanBlock", (), {"label": "Open in new window", "required": False}),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 7),
                                ("link_to", 15),
                                ("page", 16),
                                ("external_url", 17),
                                ("relative_url", 18),
                                ("anchor", 19),
                                ("email", 20),
                                ("file", 21),
                                ("phone", 22),
                                ("new_window", 23),
                            ]
                        ],
                        {},
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 12), ("subtitle", 12), ("text", 13), ("image", 14), ("link", 24)]],
                        {},
                    ),
                    26: ("wagtail.blocks.StructBlock", [[("title", 7), ("image", 2), ("subtitle", 7)]], {}),
                    27: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 0), ("text_image", 25), ("tab_card_set", 26)]],
                        {"help_text": "Add one or more content blocks to the tab.", "min_num": 1, "required": True},
                    ),
                    28: ("wagtail.blocks.StructBlock", [[("title", 10), ("subtitle", 11), ("content", 27)]], {}),
                    29: ("wagtail.blocks.ListBlock", (28,), {"label": "Tabs", "max_num": 8, "min_num": 1}),
                    30: ("wagtail.blocks.StructBlock", [[("tabs", 29)]], {}),
                    31: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional title for the block", "required": False},
                    ),
                    32: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("snippets.NewsletterSignup",),
                        {"max_num": 1},
                    ),
                    33: ("wagtail.blocks.StructBlock", [[("newsletter_signup", 32)]], {}),
                    34: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Log into Vimeo, select your desired video, and click 'Copy Link'",
                            "label": "Vimeo Video URL",
                            "required": True,
                        },
                    ),
                    35: ("wagtail.blocks.CharBlock", (), {"help_text": "Optional Caption Text", "required": False}),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_to", 15),
                                ("page", 16),
                                ("external_url", 17),
                                ("relative_url", 18),
                                ("anchor", 19),
                                ("email", 20),
                                ("file", 21),
                                ("phone", 22),
                                ("new_window", 23),
                            ]
                        ],
                        {},
                    ),
                    37: (
                        "wagtail.blocks.ListBlock",
                        (36,),
                        {
                            "default": [],
                            "help_text": "Optional URL that this caption should link out to.",
                            "max_num": 1,
                            "min_num": 0,
                        },
                    ),
                    38: (
                        "wagtail.blocks.StructBlock",
                        [[("video_url", 34), ("caption", 35), ("caption_url", 37)]],
                        {},
                    ),
                    39: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 0), ("audio", 9), ("image", 4), ("newsletter_signup", 33), ("video", 38)]],
                        {"label": "Left Column"},
                    ),
                    40: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 0), ("audio", 9), ("image", 4), ("newsletter_signup", 33), ("video", 38)]],
                        {"label": "Right Column"},
                    ),
                    41: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 31), ("left_column", 39), ("right_column", 40)]],
                        {},
                    ),
                    42: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Main heading for the card set.", "label": "Headline", "required": False},
                    ),
                    43: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Appears above the headline.", "label": "Label", "required": False},
                    ),
                    44: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Appears as the main heading.", "label": "Headline", "required": False},
                    ),
                    45: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Optional Image for the card", "label": "Image", "required": False},
                    ),
                    46: (
                        "foundation_cms.blocks.link_block.OptionalLinkBlock",
                        (),
                        {
                            "help_text": "Optional link for the card.",
                            "label": "Call to Action Link",
                            "required": False,
                        },
                    ),
                    47: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 43), ("headline", 44), ("image", 45), ("cta_link", 46)]],
                        {},
                    ),
                    48: (
                        "wagtail.blocks.ListBlock",
                        (47,),
                        {
                            "help_text": "Minimum of 3 cards required. More than 3 will turn element into a carousel.",
                            "label": "Portrait Cards",
                            "min_num": 3,
                        },
                    ),
                    49: (
                        "foundation_cms.blocks.link_block.OptionalLinkBlock",
                        (),
                        {
                            "help_text": "Optional link below the cards.",
                            "label": "Call to Action Link",
                            "required": False,
                        },
                    ),
                    50: ("wagtail.blocks.StructBlock", [[("headline", 42), ("cards", 48), ("cta_link", 49)]], {}),
                    51: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    52: ("wagtail.blocks.CharBlock", (), {"label": "Name", "max_length": 50, "required": True}),
                    53: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic"], "label": "Description", "max_length": 500, "required": True},
                    ),
                    54: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Image should follow a 1:1 aspect ratio.", "label": "Image"},
                    ),
                    55: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 51), ("name", 52), ("description", 53), ("image", 54)]],
                        {},
                    ),
                    56: (
                        "wagtail.blocks.ListBlock",
                        (55,),
                        {"help_text": "3 cards required.", "label": "Spotlight Cards", "max_num": 3, "min_num": 3},
                    ),
                    57: ("wagtail.blocks.StructBlock", [[("cards", 56)]], {}),
                    58: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("small", "Small"),
                                ("medium", "Medium"),
                                ("large", "Large"),
                                ("xlarge", "Extra Large"),
                            ],
                            "help_text": "Select the size of the spacer",
                        },
                    ),
                    59: ("wagtail.blocks.StructBlock", [[("size", 58)]], {}),
                    60: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The full value to animate, including any symbols, commas, decimals, or suffixes (e.g., $5.2M).",
                            "max_length": 5,
                            "required": True,
                        },
                    ),
                    61: ("wagtail.blocks.CharBlock", (), {"help_text": "Heading of the stat", "required": True}),
                    62: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Short description of the stat", "required": True},
                    ),
                    63: (
                        "wagtail.blocks.StructBlock",
                        [[("stat_number", 60), ("stat_heading", 61), ("stat_description", 62)]],
                        {},
                    ),
                    64: (
                        "wagtail.blocks.ListBlock",
                        (63,),
                        {
                            "default": [
                                {"stat_description": "", "stat_heading": "", "stat_number": ""},
                                {"stat_description": "", "stat_heading": "", "stat_number": ""},
                                {"stat_description": "", "stat_heading": "", "stat_number": ""},
                            ],
                            "help_text": "Add exactly 3 stats to appear in the Impact Numbers section",
                            "label": "Impact Stats",
                            "max_num": 3,
                            "min_num": 3,
                        },
                    ),
                    65: ("wagtail.blocks.StructBlock", [[("stats", 64)]], {}),
                    66: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title for the activations section", "required": False},
                    ),
                    67: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("1", "One Card (Full Width)"), ("2", "Two Cards"), ("3", "Three Cards")],
                            "help_text": "Select how many cards to display in a row",
                        },
                    ),
                    68: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional topic tag for the card", "required": False},
                    ),
                    69: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional category for the card", "required": False},
                    ),
                    70: ("wagtail.blocks.CharBlock", (), {"help_text": "Title for the card", "required": True}),
                    71: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Optional description text", "required": False},
                    ),
                    72: (
                        "wagtail.blocks.StructBlock",
                        [[("topic", 68), ("category", 69), ("title", 70), ("text", 71), ("image", 2), ("link", 24)]],
                        {},
                    ),
                    73: (
                        "wagtail.blocks.StreamBlock",
                        [[("card", 72)]],
                        {
                            "help_text": "Add between 1 and 3 cards. Only the number of cards selected above will be displayed.",
                            "max_num": 3,
                            "min_num": 1,
                        },
                    ),
                    74: ("wagtail.blocks.StructBlock", [[("title", 66), ("card_count", 67), ("cards", 73)]], {}),
                    75: ("wagtail.blocks.StructBlock", [[("quote", 51), ("attribution", 12)]], {}),
                    76: ("wagtail.blocks.CharBlock", (), {"help_text": "Heading displayed above the list"}),
                    77: ("wagtail.blocks.TextBlock", (), {"help_text": "Description displayed above the list"}),
                    78: ("wagtail.blocks.PageChooserBlock", (), {}),
                    79: ("wagtail.blocks.ListBlock", (78,), {"max_num": 4, "min_num": 1}),
                    80: ("wagtail.blocks.StructBlock", [[("title", 76), ("description", 77), ("items", 79)]], {}),
                    81: ("wagtail.blocks.StructBlock", [[("headline", 44), ("image", 45), ("cta_link", 46)]], {}),
                    82: (
                        "wagtail.blocks.ListBlock",
                        (81,),
                        {
                            "default": [
                                {"cta_link": [], "headline": "", "image": None},
                                {"cta_link": [], "headline": "", "image": None},
                                {"cta_link": [], "headline": "", "image": None},
                            ],
                            "help_text": "3 cards required.",
                            "label": "Pillar Cards",
                            "max_num": 3,
                            "min_num": 3,
                        },
                    ),
                    83: ("wagtail.blocks.StructBlock", [[("cards", 82)]], {}),
                    84: ("wagtail.blocks.CharBlock", (), {"label": "Heading", "max_length": 50, "required": True}),
                    85: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Image for the card", "label": "Image", "required": True},
                    ),
                    86: (
                        "foundation_cms.blocks.link_block.OptionalLinkBlock",
                        (),
                        {"help_text": "Button label and link for the card.", "label": "Button", "required": False},
                    ),
                    87: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 84), ("description", 53), ("image", 85), ("button", 86)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("rich_text", 0),
                    ("image", 4),
                    ("audio_block", 9),
                    ("tabbed_content", 30),
                    ("two_column_container_block", 41),
                    ("link_button_block", 24),
                    ("portrait_card_set_block", 50),
                    ("spotlight_card_set_block", 57),
                    ("spacer_block", 59),
                    ("impact_numbers", 65),
                    ("newsletter_signup", 33),
                    ("timely_activations_cards", 74),
                    ("quote", 75),
                    ("list_block", 80),
                    ("video_block", 38),
                    ("pillar_card_set", 83),
                    ("featured_card_block", 87),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title/caption for this image", "required": False},
                    ),
                    2: ("wagtail.images.blocks.ImageBlock", [], {}),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("portrait", "Portrait"), ("landscape", "Landscape"), ("square", "Square")],
                            "help_text": "Select the orientation of this image",
                        },
                    ),
                    4: ("wagtail.blocks.StructBlock", [[("title", 1), ("image", 2), ("orientation", 3)]], {}),
                    5: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Optional image to display at the top of the block.", "required": False},
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Image description (for screen readers).", "required": False},
                    ),
                    7: ("wagtail.blocks.CharBlock", (), {}),
                    8: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Short description of the audio", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 5),
                                ("image_alt_text", 6),
                                ("title", 7),
                                ("description", 8),
                                ("simplecast_embed_code", 7),
                            ]
                        ],
                        {},
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title shown on the tab button", "required": True},
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Subtitle shown under the title on the tab", "required": False},
                    ),
                    12: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    13: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("image", 2), ("orientation", 3)]],
                        {"required": False},
                    ),
                    15: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("external_url", "External URL"),
                                ("relative_url", "Relative URL"),
                                ("email", "Email"),
                                ("anchor", "Anchor"),
                                ("file", "File"),
                                ("phone", "Phone"),
                            ],
                            "label": "Link to",
                        },
                    ),
                    16: ("wagtail.blocks.PageChooserBlock", (), {"label": "Page", "required": False}),
                    17: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Enter a full URL including http:// or https://",
                            "label": "External URL",
                            "max_length": 300,
                            "required": False,
                        },
                    ),
                    18: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'A path relative to this domain. For example, "/foo/bar" or "?foo=bar".',
                            "label": "Relative URL",
                            "max_length": 300,
                            "required": False,
                            "validators": [foundation_cms.legacy_apps.wagtailpages.validators.RelativeURLValidator()],
                        },
                    ),
                    19: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'An id attribute of an element on the current page. For example, "#section-1"',
                            "label": "#",
                            "max_length": 300,
                            "required": False,
                            "validators": [foundation_cms.validators.AnchorLinkValidator()],
                        },
                    ),
                    20: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    21: ("wagtail.documents.blocks.DocumentChooserBlock", (), {"label": "File", "required": False}),
                    22: ("wagtail.blocks.CharBlock", (), {"label": "Phone", "max_length": 30, "required": False}),
                    23: ("wagtail.blocks.BooleanBlock", (), {"label": "Open in new window", "required": False}),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 7),
                                ("link_to", 15),
                                ("page", 16),
                                ("external_url", 17),
                                ("relative_url", 18),
                                ("anchor", 19),
                                ("email", 20),
                                ("file", 21),
                                ("phone", 22),
                                ("new_window", 23),
                            ]
                        ],
                        {},
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 12), ("subtitle", 12), ("text", 13), ("image", 14), ("link", 24)]],
                        {},
                    ),
                    26: ("wagtail.blocks.StructBlock", [[("title", 7), ("image", 2), ("subtitle", 7)]], {}),
                    27: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 0), ("text_image", 25), ("tab_card_set", 26)]],
                        {"help_text": "Add one or more content blocks to the tab.", "min_num": 1, "required": True},
                    ),
                    28: ("wagtail.blocks.StructBlock", [[("title", 10), ("subtitle", 11), ("content", 27)]], {}),
                    29: ("wagtail.blocks.ListBlock", (28,), {"label": "Tabs", "max_num": 8, "min_num": 1}),
                    30: ("wagtail.blocks.StructBlock", [[("tabs", 29)]], {}),
                    31: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional title for the block", "required": False},
                    ),
                    32: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("snippets.NewsletterSignup",),
                        {"max_num": 1},
                    ),
                    33: ("wagtail.blocks.StructBlock", [[("newsletter_signup", 32)]], {}),
                    34: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Log into Vimeo, select your desired video, and click 'Copy Link'",
                            "label": "Vimeo Video URL",
                            "required": True,
                        },
                    ),
                    35: ("wagtail.blocks.CharBlock", (), {"help_text": "Optional Caption Text", "required": False}),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_to", 15),
                                ("page", 16),
                                ("external_url", 17),
                                ("relative_url", 18),
                                ("anchor", 19),
                                ("email", 20),
                                ("file", 21),
                                ("phone", 22),
                                ("new_window", 23),
                            ]
                        ],
                        {},
                    ),
                    37: (
                        "wagtail.blocks.ListBlock",
                        (36,),
                        {
                            "default": [],
                            "help_text": "Optional URL that this caption should link out to.",
                            "max_num": 1,
                            "min_num": 0,
                        },
                    ),
                    38: (
                        "wagtail.blocks.StructBlock",
                        [[("video_url", 34), ("caption", 35), ("caption_url", 37)]],
                        {},
                    ),
                    39: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 0), ("audio", 9), ("image", 4), ("newsletter_signup", 33), ("video", 38)]],
                        {"label": "Left Column"},
                    ),
                    40: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 0), ("audio", 9), ("image", 4), ("newsletter_signup", 33), ("video", 38)]],
                        {"label": "Right Column"},
                    ),
                    41: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 31), ("left_column", 39), ("right_column", 40)]],
                        {},
                    ),
                    42: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Main heading for the card set.", "label": "Headline", "required": False},
                    ),
                    43: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Appears above the headline.", "label": "Label", "required": False},
                    ),
                    44: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Appears as the main heading.", "label": "Headline", "required": False},
                    ),
                    45: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Optional Image for the card", "label": "Image", "required": False},
                    ),
                    46: (
                        "foundation_cms.blocks.link_block.OptionalLinkBlock",
                        (),
                        {
                            "help_text": "Optional link for the card.",
                            "label": "Call to Action Link",
                            "required": False,
                        },
                    ),
                    47: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 43), ("headline", 44), ("image", 45), ("cta_link", 46)]],
                        {},
                    ),
                    48: (
                        "wagtail.blocks.ListBlock",
                        (47,),
                        {
                            "help_text": "Minimum of 3 cards required. More than 3 will turn element into a carousel.",
                            "label": "Portrait Cards",
                            "min_num": 3,
                        },
                    ),
                    49: (
                        "foundation_cms.blocks.link_block.OptionalLinkBlock",
                        (),
                        {
                            "help_text": "Optional link below the cards.",
                            "label": "Call to Action Link",
                            "required": False,
                        },
                    ),
                    50: ("wagtail.blocks.StructBlock", [[("headline", 42), ("cards", 48), ("cta_link", 49)]], {}),
                    51: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    52: ("wagtail.blocks.CharBlock", (), {"label": "Name", "max_length": 50, "required": True}),
                    53: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic"], "label": "Description", "max_length": 500, "required": True},
                    ),
                    54: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Image should follow a 1:1 aspect ratio.", "label": "Image"},
                    ),
                    55: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 51), ("name", 52), ("description", 53), ("image", 54)]],
                        {},
                    ),
                    56: (
                        "wagtail.blocks.ListBlock",
                        (55,),
                        {"help_text": "3 cards required.", "label": "Spotlight Cards", "max_num": 3, "min_num": 3},
                    ),
                    57: ("wagtail.blocks.StructBlock", [[("cards", 56)]], {}),
                    58: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("small", "Small"),
                                ("medium", "Medium"),
                                ("large", "Large"),
                                ("xlarge", "Extra Large"),
                            ],
                            "help_text": "Select the size of the spacer",
                        },
                    ),
                    59: ("wagtail.blocks.StructBlock", [[("size", 58)]], {}),
                    60: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The full value to animate, including any symbols, commas, decimals, or suffixes (e.g., $5.2M).",
                            "max_length": 5,
                            "required": True,
                        },
                    ),
                    61: ("wagtail.blocks.CharBlock", (), {"help_text": "Heading of the stat", "required": True}),
                    62: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Short description of the stat", "required": True},
                    ),
                    63: (
                        "wagtail.blocks.StructBlock",
                        [[("stat_number", 60), ("stat_heading", 61), ("stat_description", 62)]],
                        {},
                    ),
                    64: (
                        "wagtail.blocks.ListBlock",
                        (63,),
                        {
                            "default": [
                                {"stat_description": "", "stat_heading": "", "stat_number": ""},
                                {"stat_description": "", "stat_heading": "", "stat_number": ""},
                                {"stat_description": "", "stat_heading": "", "stat_number": ""},
                            ],
                            "help_text": "Add exactly 3 stats to appear in the Impact Numbers section",
                            "label": "Impact Stats",
                            "max_num": 3,
                            "min_num": 3,
                        },
                    ),
                    65: ("wagtail.blocks.StructBlock", [[("stats", 64)]], {}),
                    66: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title for the activations section", "required": False},
                    ),
                    67: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("1", "One Card (Full Width)"), ("2", "Two Cards"), ("3", "Three Cards")],
                            "help_text": "Select how many cards to display in a row",
                        },
                    ),
                    68: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional topic tag for the card", "required": False},
                    ),
                    69: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional category for the card", "required": False},
                    ),
                    70: ("wagtail.blocks.CharBlock", (), {"help_text": "Title for the card", "required": True}),
                    71: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Optional description text", "required": False},
                    ),
                    72: (
                        "wagtail.blocks.StructBlock",
                        [[("topic", 68), ("category", 69), ("title", 70), ("text", 71), ("image", 2), ("link", 24)]],
                        {},
                    ),
                    73: (
                        "wagtail.blocks.StreamBlock",
                        [[("card", 72)]],
                        {
                            "help_text": "Add between 1 and 3 cards. Only the number of cards selected above will be displayed.",
                            "max_num": 3,
                            "min_num": 1,
                        },
                    ),
                    74: ("wagtail.blocks.StructBlock", [[("title", 66), ("card_count", 67), ("cards", 73)]], {}),
                    75: ("wagtail.blocks.StructBlock", [[("quote", 51), ("attribution", 12)]], {}),
                    76: ("wagtail.blocks.CharBlock", (), {"help_text": "Heading displayed above the list"}),
                    77: ("wagtail.blocks.TextBlock", (), {"help_text": "Description displayed above the list"}),
                    78: ("wagtail.blocks.PageChooserBlock", (), {}),
                    79: ("wagtail.blocks.ListBlock", (78,), {"max_num": 4, "min_num": 1}),
                    80: ("wagtail.blocks.StructBlock", [[("title", 76), ("description", 77), ("items", 79)]], {}),
                    81: ("wagtail.blocks.StructBlock", [[("headline", 44), ("image", 45), ("cta_link", 46)]], {}),
                    82: (
                        "wagtail.blocks.ListBlock",
                        (81,),
                        {
                            "default": [
                                {"cta_link": [], "headline": "", "image": None},
                                {"cta_link": [], "headline": "", "image": None},
                                {"cta_link": [], "headline": "", "image": None},
                            ],
                            "help_text": "3 cards required.",
                            "label": "Pillar Cards",
                            "max_num": 3,
                            "min_num": 3,
                        },
                    ),
                    83: ("wagtail.blocks.StructBlock", [[("cards", 82)]], {}),
                    84: ("wagtail.blocks.CharBlock", (), {"label": "Heading", "max_length": 50, "required": True}),
                    85: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Image for the card", "label": "Image", "required": True},
                    ),
                    86: (
                        "foundation_cms.blocks.link_block.OptionalLinkBlock",
                        (),
                        {"help_text": "Button label and link for the card.", "label": "Button", "required": False},
                    ),
                    87: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 84), ("description", 53), ("image", 85), ("button", 86)]],
                        {},
                    ),
                },
            ),
        ),
    ]
