# Generated by Django 4.2.20 on 2025-07-08 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
        ("core", "0030_alter_generalpage_body_alter_homepage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalpage",
            name="hero_background_color",
            field=models.CharField(
                choices=[("orange-200", "Orange"), ("yellow-200", "Yellow")],
                default="orange-200",
                help_text="Select the color of the hero background",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="generalpage",
            name="hero_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Image for page hero section.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="images.foundationcustomimage",
                verbose_name="Hero Image",
            ),
        ),
    ]
