# Generated by Django 4.2.20 on 2025-08-19 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0002_donatebanner"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("core", "0042_generalpage_hero_image_alt_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="SitewideDonateBannerPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "donate_banner",
                    models.ForeignKey(
                        blank=True,
                        help_text="CTA Banner rendered at the top of the page site-wide. Note: A/B testing of this banner will also be site-wide and across all locales.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="site_donate_banner",
                        to="snippets.donatebanner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Donate Banner Page",
                "verbose_name_plural": "Donate Banner Pages",
            },
            bases=("wagtailcore.page",),
        ),
    ]
