# Generated by Django 4.2.20 on 2025-08-14 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailmedia", "0004_duration_optional_floatfield"),
        ("core", "0042_generalpage_hero_image_alt_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalpage",
            name="hero_media_type",
            field=models.CharField(
                choices=[("image", "Image"), ("video", "Video")],
                default="image",
                help_text="Select the media type for Hero Section.",
                max_length=20,
                verbose_name="Hero Media Type",
            ),
        ),
        migrations.AddField(
            model_name="generalpage",
            name="hero_video",
            field=models.ForeignKey(
                blank=True,
                help_text="Video for page hero section.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailmedia.media",
                verbose_name="Hero Video",
            ),
        ),
    ]
