# Generated by Django 4.2.20 on 2025-08-11 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_migrate_hero_image_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generalpage",
            name="hero_image_legacy",
        ),
    ]
