# Generated by Django 4.2.25 on 2025-11-21 20:39

import wagtail.fields
from django.db import migrations

import foundation_cms.legacy_apps.wagtailpages.validators
import foundation_cms.validators


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0055_alter_generalpage_body_alter_homepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("rich_text", 0),
                    ("image", 4),
                    ("podcast_block", 7),
                    ("tabbed_content", 20),
                    ("two_column_container_block", 56),
                    ("link_button_block", 50),
                    ("portrait_card_set_block", 63),
                    ("spotlight_card_set_block", 69),
                    ("spacer_block", 45),
                    ("iframe_block", 74),
                    ("impact_numbers", 80),
                    ("newsletter_signup", 24),
                    ("newsletter_unsubscribe", 82),
                    ("timely_activations_cards", 88),
                    ("quote", 47),
                    ("list_block", 43),
                    ("video_block", 38),
                    ("pillar_card_set", 92),
                    ("featured_card_block", 96),
                    ("fru_element_block", 53),
                    ("divider", 97),
                    ("title_block", 100),
                    ("custom_media", 105),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"template": "patterns/blocks/themes/default/rich_text_block.html"},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title/caption for this image", "required": False},
                    ),
                    2: ("wagtail.images.blocks.ImageBlock", [], {}),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("portrait", "Portrait"), ("landscape", "Landscape"), ("square", "Square")],
                            "help_text": "Select the orientation of this image",
                        },
                    ),
                    4: ("wagtail.blocks.StructBlock", [[("title", 1), ("image", 2), ("orientation", 3)]], {}),
                    5: ("wagtail.blocks.CharBlock", (), {}),
                    6: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Optional short description of the podcast", "required": False},
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 5), ("description", 6), ("simplecast_embed_code", 5)]],
                        {},
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title shown on the tab button", "required": True},
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Subtitle shown under the title on the tab", "required": False},
                    ),
                    10: ("wagtail.blocks.RichTextBlock", (), {}),
                    11: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    12: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("image", 2), ("orientation", 3)]],
                        {"required": False},
                    ),
                    14: ("foundation_cms.blocks.link_block.OptionalLinkBlock", (), {"required": False}),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 11), ("subtitle", 11), ("text", 12), ("image", 13), ("link", 14)]],
                        {},
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 5), ("image", 2), ("subtitle", 5), ("link", 14)]],
                        {},
                    ),
                    17: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 10), ("text_image", 15), ("tab_card_set", 16)]],
                        {"help_text": "Add one or more content blocks to the tab.", "min_num": 1, "required": True},
                    ),
                    18: ("wagtail.blocks.StructBlock", [[("title", 8), ("subtitle", 9), ("content", 17)]], {}),
                    19: ("wagtail.blocks.ListBlock", (18,), {"label": "Tabs", "max_num": 8, "min_num": 1}),
                    20: ("wagtail.blocks.StructBlock", [[("tabs", 19)]], {}),
                    21: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("white", "White"),
                                ("neutral-100", "Grey 100"),
                                ("neutral-200", "Grey 200"),
                                ("neutral-300", "Grey 300"),
                                ("blue-100", "Blue 100"),
                                ("blue-200", "Blue 200"),
                                ("blue-300", "Blue 300"),
                                ("green-100", "Green 100"),
                                ("green-200", "Green 200"),
                                ("green-300", "Green 300"),
                                ("orange-100", "Orange 100"),
                                ("orange-200", "Orange 200"),
                                ("orange-300", "Orange 300"),
                                ("yellow-100", "Yellow 100"),
                                ("yellow-200", "Yellow 200"),
                                ("yellow-300", "Yellow 300"),
                            ]
                        },
                    ),
                    22: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("top", "Top"), ("middle", "Middle"), ("bottom", "Bottom")],
                            "help_text": "Vertical alignment of the columns content",
                        },
                    ),
                    23: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("snippets.NewsletterSignup",),
                        {"max_num": 1},
                    ),
                    24: ("wagtail.blocks.StructBlock", [[("newsletter_signup", 23)]], {}),
                    25: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Log into Vimeo, select your desired video, and click 'Copy Link'",
                            "label": "Vimeo Video URL",
                            "required": True,
                        },
                    ),
                    26: ("wagtail.blocks.CharBlock", (), {"help_text": "Optional Caption Text", "required": False}),
                    27: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("external_url", "External URL"),
                                ("relative_url", "Relative URL"),
                                ("email", "Email"),
                                ("anchor", "Anchor"),
                                ("file", "File"),
                                ("phone", "Phone"),
                            ],
                            "label": "Link to",
                        },
                    ),
                    28: ("wagtail.blocks.PageChooserBlock", (), {"label": "Page", "required": False}),
                    29: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Enter a full URL including http:// or https://",
                            "label": "External URL",
                            "max_length": 300,
                            "required": False,
                        },
                    ),
                    30: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'A path relative to this domain. For example, "/foo/bar" or "?foo=bar".',
                            "label": "Relative URL",
                            "max_length": 300,
                            "required": False,
                            "validators": [foundation_cms.legacy_apps.wagtailpages.validators.RelativeURLValidator()],
                        },
                    ),
                    31: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'An id attribute of an element on the current page. For example, "#section-1"',
                            "label": "#",
                            "max_length": 300,
                            "required": False,
                            "validators": [foundation_cms.validators.AnchorLinkValidator()],
                        },
                    ),
                    32: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    33: ("wagtail.documents.blocks.DocumentChooserBlock", (), {"label": "File", "required": False}),
                    34: ("wagtail.blocks.CharBlock", (), {"label": "Phone", "max_length": 30, "required": False}),
                    35: ("wagtail.blocks.BooleanBlock", (), {"label": "Open in new window", "required": False}),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_to", 27),
                                ("page", 28),
                                ("external_url", 29),
                                ("relative_url", 30),
                                ("anchor", 31),
                                ("email", 32),
                                ("file", 33),
                                ("phone", 34),
                                ("new_window", 35),
                            ]
                        ],
                        {},
                    ),
                    37: (
                        "wagtail.blocks.ListBlock",
                        (36,),
                        {
                            "default": [],
                            "help_text": "Optional URL that this caption should link out to.",
                            "max_num": 1,
                            "min_num": 0,
                        },
                    ),
                    38: (
                        "wagtail.blocks.StructBlock",
                        [[("video_url", 25), ("caption", 26), ("caption_url", 37)]],
                        {},
                    ),
                    39: ("wagtail.blocks.CharBlock", (), {"help_text": "Heading displayed above the list"}),
                    40: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Description displayed above the list", "required": False},
                    ),
                    41: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 5),
                                ("link_to", 27),
                                ("page", 28),
                                ("external_url", 29),
                                ("relative_url", 30),
                                ("anchor", 31),
                                ("email", 32),
                                ("file", 33),
                                ("phone", 34),
                                ("new_window", 35),
                            ]
                        ],
                        {},
                    ),
                    42: ("wagtail.blocks.ListBlock", (41,), {"max_num": 4, "min_num": 1}),
                    43: ("wagtail.blocks.StructBlock", [[("title", 39), ("description", 40), ("items", 42)]], {}),
                    44: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("small", "Small"),
                                ("medium", "Medium"),
                                ("large", "Large"),
                                ("xlarge", "Extra Large"),
                            ],
                            "help_text": "Select the size of the spacer",
                        },
                    ),
                    45: ("wagtail.blocks.StructBlock", [[("size", 44)]], {}),
                    46: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    47: ("wagtail.blocks.StructBlock", [[("quote", 46), ("attribution", 11)]], {}),
                    48: ("wagtail.blocks.StructBlock", [[("title", 11), ("text", 12)]], {}),
                    49: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("btn-primary", "Primary"), ("btn-secondary", "Secondary")]},
                    ),
                    50: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 5),
                                ("link_to", 27),
                                ("page", 28),
                                ("external_url", 29),
                                ("relative_url", 30),
                                ("anchor", 31),
                                ("email", 32),
                                ("file", 33),
                                ("phone", 34),
                                ("new_window", 35),
                                ("style", 49),
                            ]
                        ],
                        {},
                    ),
                    51: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("donation-form", "Donation Form"),
                                ("donor-map", "Donor Map"),
                                ("top-locations", "Top Locations"),
                                ("donation-levels", "Donation Levels"),
                            ],
                            "help_text": "Select the type of Fundraise Up element.",
                        },
                    ),
                    52: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Copy the HTML code generated by the desired Fundraise Up element and paste it here.",
                            "required": True,
                        },
                    ),
                    53: (
                        "wagtail.blocks.StructBlock",
                        [[("fru_element_type", 51), ("fru_element_embed_code", 52)]],
                        {},
                    ),
                    54: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 10),
                                ("podcast", 7),
                                ("image", 4),
                                ("newsletter_signup", 24),
                                ("video", 38),
                                ("list", 43),
                                ("spacer", 45),
                                ("quote", 47),
                                ("text_social", 48),
                                ("link_button", 50),
                                ("fru_element", 53),
                            ]
                        ],
                        {"label": "Left Column", "required": False},
                    ),
                    55: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 10),
                                ("podcast", 7),
                                ("image", 4),
                                ("newsletter_signup", 24),
                                ("video", 38),
                                ("list", 43),
                                ("spacer", 45),
                                ("quote", 47),
                                ("text_social", 48),
                                ("link_button", 50),
                                ("fru_element", 53),
                            ]
                        ],
                        {"label": "Right Column", "required": False},
                    ),
                    56: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 21),
                                ("vertical_alignment", 22),
                                ("left_column", 54),
                                ("right_column", 55),
                            ]
                        ],
                        {},
                    ),
                    57: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Appears above the headline.", "label": "Label", "required": False},
                    ),
                    58: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Appears as the main heading.", "label": "Headline", "required": False},
                    ),
                    59: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Optional Image for the card", "label": "Image"},
                    ),
                    60: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 5),
                                ("link_to", 27),
                                ("page", 28),
                                ("external_url", 29),
                                ("relative_url", 30),
                                ("anchor", 31),
                                ("email", 32),
                                ("file", 33),
                                ("phone", 34),
                                ("new_window", 35),
                            ]
                        ],
                        {"help_text": "Link for the card.", "label": "Call to Action Link", "required": True},
                    ),
                    61: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 57), ("headline", 58), ("image", 59), ("cta_link", 60)]],
                        {},
                    ),
                    62: (
                        "wagtail.blocks.ListBlock",
                        (61,),
                        {
                            "help_text": "Minimum of 3 cards required. More than 3 will turn element into a carousel.",
                            "label": "Portrait Cards",
                            "min_num": 3,
                        },
                    ),
                    63: ("wagtail.blocks.StructBlock", [[("cards", 62)]], {}),
                    64: ("wagtail.blocks.CharBlock", (), {"label": "Name", "max_length": 50, "required": True}),
                    65: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic"], "label": "Description", "max_length": 500, "required": True},
                    ),
                    66: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Image should follow a 1:1 aspect ratio.", "label": "Image"},
                    ),
                    67: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 46), ("name", 64), ("description", 65), ("image", 66)]],
                        {},
                    ),
                    68: (
                        "wagtail.blocks.ListBlock",
                        (67,),
                        {"help_text": "3 cards required.", "label": "Spotlight Cards", "max_num": 3, "min_num": 3},
                    ),
                    69: ("wagtail.blocks.StructBlock", [[("cards", 68)]], {}),
                    70: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Please note that only URLs from allow-listed domains will work."},
                    ),
                    71: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Optional integer pixel value for custom iFrame height", "required": False},
                    ),
                    72: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("normal", "Normal"), ("full_width", "Full Width")]},
                    ),
                    73: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": 'Checking this will add "scrolling=no" to the iframe. Use this if your iframe is rendering an unnecessary scroll bar or whitespace below it.',
                            "required": False,
                        },
                    ),
                    74: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 70), ("height", 71), ("iframe_width", 72), ("disable_scroll", 73)]],
                        {},
                    ),
                    75: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The full value to animate, including any symbols, commas, decimals, or suffixes (e.g., $5.2M).",
                            "max_length": 5,
                            "required": True,
                        },
                    ),
                    76: ("wagtail.blocks.CharBlock", (), {"help_text": "Heading of the stat", "required": True}),
                    77: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Short description of the stat", "required": False},
                    ),
                    78: (
                        "wagtail.blocks.StructBlock",
                        [[("stat_number", 75), ("stat_heading", 76), ("stat_description", 77)]],
                        {},
                    ),
                    79: (
                        "wagtail.blocks.ListBlock",
                        (78,),
                        {
                            "default": [
                                {"stat_description": "", "stat_heading": "", "stat_number": ""},
                                {"stat_description": "", "stat_heading": "", "stat_number": ""},
                                {"stat_description": "", "stat_heading": "", "stat_number": ""},
                            ],
                            "help_text": "Add exactly 3 stats to appear in the Impact Numbers section",
                            "label": "Impact Stats",
                            "max_num": 3,
                            "min_num": 3,
                        },
                    ),
                    80: ("wagtail.blocks.StructBlock", [[("stats", 79)]], {}),
                    81: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("snippets.NewsletterUnsubscribe",),
                        {"max_num": 1},
                    ),
                    82: ("wagtail.blocks.StructBlock", [[("newsletter_unsubscribe", 81)]], {}),
                    83: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional category for the card", "required": False},
                    ),
                    84: ("wagtail.blocks.CharBlock", (), {"help_text": "Title for the card", "required": True}),
                    85: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Optional description text", "required": False},
                    ),
                    86: (
                        "wagtail.blocks.StructBlock",
                        [[("category", 83), ("title", 84), ("text", 85), ("image", 2), ("link", 41)]],
                        {},
                    ),
                    87: (
                        "wagtail.blocks.StreamBlock",
                        [[("card", 86)]],
                        {"help_text": "Add between 1 and 3 cards.", "max_num": 3, "min_num": 1},
                    ),
                    88: ("wagtail.blocks.StructBlock", [[("cards", 87)]], {}),
                    89: (
                        "foundation_cms.blocks.link_block.OptionalLinkBlock",
                        (),
                        {
                            "help_text": "Optional link for the card.",
                            "label": "Call to Action Link",
                            "required": False,
                        },
                    ),
                    90: ("wagtail.blocks.StructBlock", [[("headline", 58), ("cta_link", 89)]], {}),
                    91: (
                        "wagtail.blocks.ListBlock",
                        (90,),
                        {
                            "default": [
                                {"cta_link": [], "headline": ""},
                                {"cta_link": [], "headline": ""},
                                {"cta_link": [], "headline": ""},
                            ],
                            "help_text": "3 cards required.",
                            "label": "Pillar Cards",
                            "max_num": 3,
                            "min_num": 3,
                        },
                    ),
                    92: ("wagtail.blocks.StructBlock", [[("cards", 91)]], {}),
                    93: ("wagtail.blocks.CharBlock", (), {"label": "Heading", "max_length": 50, "required": True}),
                    94: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Image for the card", "label": "Image"},
                    ),
                    95: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 5),
                                ("link_to", 27),
                                ("page", 28),
                                ("external_url", 29),
                                ("relative_url", 30),
                                ("anchor", 31),
                                ("email", 32),
                                ("file", 33),
                                ("phone", 34),
                                ("new_window", 35),
                                ("style", 49),
                            ]
                        ],
                        {"help_text": "Link button for the card.", "label": "Button", "required": False},
                    ),
                    96: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 93), ("description", 65), ("image", 94), ("button", 95)]],
                        {},
                    ),
                    97: ("wagtail.blocks.StructBlock", [[]], {}),
                    98: ("wagtail.blocks.CharBlock", (), {"help_text": "Title for the block", "required": True}),
                    99: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("shape", "Shape"), ("loop-line", "Loop Line")],
                            "help_text": "Select the style of the title",
                        },
                    ),
                    100: ("wagtail.blocks.StructBlock", [[("title", 98), ("style", 99)]], {}),
                    101: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title/caption for this media", "required": False},
                    ),
                    102: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("image", "Image"), ("video", "Video")],
                            "help_text": "Select the type of media to display",
                        },
                    ),
                    103: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Log into Vimeo using 1Password and upload the desired video. Then select the video and click "...", "Video File Links", and select "(mp4, 1920 x 1080)". Copy and paste the link here.',
                            "max_length": 500,
                            "required": False,
                        },
                    ),
                    104: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("portrait", "Portrait"),
                                ("landscape", "Landscape"),
                                ("square", "Square"),
                                ("widescreen", "Widescreen 16:9 (12 columns wide)"),
                            ],
                            "help_text": "Select the orientation of this media",
                        },
                    ),
                    105: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 101), ("content", 102), ("image", 2), ("video_url", 103), ("orientation", 104)]],
                        {},
                    ),
                },
            ),
        ),
    ]
