# Generated by Django 4.2.27 on 2026-01-18 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("snippets", "0008_remove_donatebanner_background_color_and_more"),
        ("core", "0060_remove_new_from_verbose_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="SitewideFooterNewsletterSignupPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "newsletter_signup",
                    models.ForeignKey(
                        blank=True,
                        help_text="CTA Banner rendered at the top of the page site-wide. Note: A/B testing of this banner will also be site-wide and across all locales.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sitewide_footer_newsletter_signup",
                        to="snippets.newslettersignup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Footer Newsletter Signup Page",
                "verbose_name_plural": "Footer Newsletter Signup Pages",
            },
            bases=("wagtailcore.page",),
        ),
    ]
