# Generated by Django 4.2.27 on 2026-03-03 14:43

import wagtail.fields
from django.db import migrations

import foundation_cms.legacy_apps.wagtailpages.validators
import foundation_cms.validators


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0067_sitewidefooternewslettersignuppage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("accordion_block", 5),
                    ("custom_media", 11),
                    ("divider", 12),
                    ("featured_card_block", 29),
                    ("fru_element_block", 32),
                    ("iframe_block", 37),
                    ("image", 40),
                    ("image_grid", 50),
                    ("impact_numbers", 56),
                    ("link_button_block", 57),
                    ("list_block", 62),
                    ("newsletter_signup", 64),
                    ("newsletter_unsubscribe", 66),
                    ("pillar_card_set", 71),
                    ("podcast_block", 74),
                    ("portrait_card_set_block", 80),
                    ("quote", 83),
                    ("rich_text", 84),
                    ("spacer_block", 86),
                    ("spotlight_card_set_block", 91),
                    ("tabbed_content", 102),
                    ("timely_activations_cards", 108),
                    ("title_block", 111),
                    ("two_column_container_block", 130),
                    ("video_block", 131),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Heading for the Accordion Item", "required": True},
                    ),
                    1: ("foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock", (), {}),
                    2: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 1)]],
                        {"required": False, "use_json_field": True},
                    ),
                    3: ("wagtail.blocks.StructBlock", [[("title", 0), ("content", 2)]], {}),
                    4: ("wagtail.blocks.ListBlock", (3,), {"min_num": 1}),
                    5: ("wagtail.blocks.StructBlock", [[("accordion_items", 4)]], {"group": "Text"}),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title/caption for this media", "required": False},
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("image", "Image"), ("video", "Video")],
                            "help_text": "Select the type of media to display",
                        },
                    ),
                    8: ("wagtail.images.blocks.ImageBlock", [], {}),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Log into Vimeo using 1Password and upload the desired video. Then select the video and click "...", "Video File Links", and select "(mp4, 1920 x 1080)". Copy and paste the link here.',
                            "max_length": 500,
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("portrait", "Portrait"),
                                ("landscape", "Landscape"),
                                ("square", "Square"),
                                ("widescreen", "Widescreen 16:9 (12 columns wide)"),
                            ],
                            "help_text": "Select the orientation of this media",
                        },
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 6), ("content", 7), ("image", 8), ("video_url", 9), ("orientation", 10)]],
                        {"group": "Media & Embeds"},
                    ),
                    12: ("wagtail.blocks.StructBlock", [[]], {"group": "Layout"}),
                    13: ("wagtail.blocks.CharBlock", (), {"label": "Heading", "max_length": 50, "required": True}),
                    14: (
                        "foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock",
                        (),
                        {"features": ["bold", "italic"], "label": "Description", "max_length": 500, "required": True},
                    ),
                    15: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Image for the card", "label": "Image"},
                    ),
                    16: ("wagtail.blocks.CharBlock", (), {}),
                    17: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("external_url", "External URL"),
                                ("relative_url", "Relative URL"),
                                ("email", "Email"),
                                ("anchor", "Anchor"),
                                ("file", "File"),
                                ("phone", "Phone"),
                            ],
                            "label": "Link to",
                        },
                    ),
                    18: ("wagtail.blocks.PageChooserBlock", (), {"label": "Page", "required": False}),
                    19: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Enter a full URL including http:// or https://",
                            "label": "External URL",
                            "max_length": 300,
                            "required": False,
                        },
                    ),
                    20: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'A path relative to this domain. For example, "/foo/bar" or "?foo=bar".',
                            "label": "Relative URL",
                            "max_length": 300,
                            "required": False,
                            "validators": [foundation_cms.legacy_apps.wagtailpages.validators.RelativeURLValidator()],
                        },
                    ),
                    21: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'An id attribute of an element on the current page. For example, "#section-1"',
                            "label": "#",
                            "max_length": 300,
                            "required": False,
                            "validators": [foundation_cms.validators.AnchorLinkValidator()],
                        },
                    ),
                    22: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    23: ("wagtail.documents.blocks.DocumentChooserBlock", (), {"label": "File", "required": False}),
                    24: ("wagtail.blocks.CharBlock", (), {"label": "Phone", "max_length": 30, "required": False}),
                    25: ("wagtail.blocks.BooleanBlock", (), {"label": "Open in new window", "required": False}),
                    26: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("btn-primary", "Primary"), ("btn-secondary", "Secondary")]},
                    ),
                    27: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("link-button-block__left", "Left"), ("link-button-block__center", "Center")]},
                    ),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 16),
                                ("link_to", 17),
                                ("page", 18),
                                ("external_url", 19),
                                ("relative_url", 20),
                                ("anchor", 21),
                                ("email", 22),
                                ("file", 23),
                                ("phone", 24),
                                ("new_window", 25),
                                ("style", 26),
                                ("alignment", 27),
                            ]
                        ],
                        {"help_text": "Link button for the card.", "label": "Button", "required": False},
                    ),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 13), ("description", 14), ("image", 15), ("button", 28)]],
                        {"group": "Card Collections"},
                    ),
                    30: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("donation-form", "Donation Form"),
                                ("donor-map", "Donor Map"),
                                ("top-locations", "Top Locations"),
                                ("donation-levels", "Donation Levels"),
                                ("donate-button", "Donate Button"),
                            ],
                            "help_text": "Select the type of Fundraise Up element.",
                        },
                    ),
                    31: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Copy the HTML code generated by the desired Fundraise Up element and paste it here.",
                            "required": True,
                        },
                    ),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [[("fru_element_type", 30), ("fru_element_embed_code", 31)]],
                        {"group": "Engagement & Buttons"},
                    ),
                    33: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Please note that only URLs from allow-listed domains will work."},
                    ),
                    34: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Optional integer pixel value for custom iFrame height", "required": False},
                    ),
                    35: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("normal", "Normal"), ("full_width", "Full Width")]},
                    ),
                    36: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": 'Checking this will add "scrolling=no" to the iframe. Use this if your iframe is rendering an unnecessary scroll bar or whitespace below it.',
                            "required": False,
                        },
                    ),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 33), ("height", 34), ("iframe_width", 35), ("disable_scroll", 36)]],
                        {"group": "Media & Embeds"},
                    ),
                    38: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title/caption for this image", "required": False},
                    ),
                    39: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("portrait", "Portrait"), ("landscape", "Landscape"), ("square", "Square")],
                            "help_text": "Select the orientation of this image",
                        },
                    ),
                    40: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 38), ("image", 8), ("orientation", 39)]],
                        {"group": "Media & Embeds"},
                    ),
                    41: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional heading for this section", "max_length": 100, "required": False},
                    ),
                    42: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("portrait", "Portrait"), ("landscape", "Landscape"), ("square", "Square")],
                            "help_text": "Orientation for all images in this section",
                            "label": "Image grid section orientation",
                        },
                    ),
                    43: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("4", "4 per row"), ("5", "5 per row"), ("6", "6 per row")],
                            "label": "Items per section row",
                        },
                    ),
                    44: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["h5", "h6", "large", "bold", "italic"],
                            "help_text": "Optional caption for this image",
                            "required": False,
                        },
                    ),
                    45: (
                        "foundation_cms.blocks.link_block.OptionalLinkBlock",
                        (),
                        {"help_text": "Optional link for both image and caption", "required": False},
                    ),
                    46: ("wagtail.blocks.StructBlock", [[("image", 8), ("caption", 44), ("link", 45)]], {}),
                    47: ("wagtail.blocks.ListBlock", (46,), {"min_num": 1}),
                    48: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 41), ("section_orientation", 42), ("items_per_row", 43), ("items", 47)]],
                        {},
                    ),
                    49: ("wagtail.blocks.ListBlock", (48,), {"label": "Image grid sections", "min_num": 1}),
                    50: ("wagtail.blocks.StructBlock", [[("sections", 49)]], {"group": "Card Collections"}),
                    51: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The full value to animate, including any symbols, commas, decimals, or suffixes (e.g., $5.2M).",
                            "max_length": 5,
                            "required": True,
                        },
                    ),
                    52: ("wagtail.blocks.CharBlock", (), {"help_text": "Heading of the stat", "required": True}),
                    53: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Short description of the stat", "required": False},
                    ),
                    54: (
                        "wagtail.blocks.StructBlock",
                        [[("stat_number", 51), ("stat_heading", 52), ("stat_description", 53)]],
                        {},
                    ),
                    55: (
                        "wagtail.blocks.ListBlock",
                        (54,),
                        {
                            "default": [
                                {"stat_description": "", "stat_heading": "", "stat_number": ""},
                                {"stat_description": "", "stat_heading": "", "stat_number": ""},
                                {"stat_description": "", "stat_heading": "", "stat_number": ""},
                            ],
                            "help_text": "Add exactly 3 stats to appear in the Impact Numbers section",
                            "label": "Impact Stats",
                            "max_num": 3,
                            "min_num": 3,
                        },
                    ),
                    56: ("wagtail.blocks.StructBlock", [[("stats", 55)]], {"group": "Data Display"}),
                    57: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 16),
                                ("link_to", 17),
                                ("page", 18),
                                ("external_url", 19),
                                ("relative_url", 20),
                                ("anchor", 21),
                                ("email", 22),
                                ("file", 23),
                                ("phone", 24),
                                ("new_window", 25),
                                ("style", 26),
                                ("alignment", 27),
                            ]
                        ],
                        {"group": "Engagement & Buttons"},
                    ),
                    58: ("wagtail.blocks.CharBlock", (), {"help_text": "Heading displayed above the list"}),
                    59: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Description displayed above the list", "required": False},
                    ),
                    60: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 16),
                                ("link_to", 17),
                                ("page", 18),
                                ("external_url", 19),
                                ("relative_url", 20),
                                ("anchor", 21),
                                ("email", 22),
                                ("file", 23),
                                ("phone", 24),
                                ("new_window", 25),
                            ]
                        ],
                        {},
                    ),
                    61: ("wagtail.blocks.ListBlock", (60,), {"max_num": 4, "min_num": 1}),
                    62: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 58), ("description", 59), ("items", 61)]],
                        {"group": "Data Display"},
                    ),
                    63: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("snippets.NewsletterSignup",),
                        {"max_num": 1},
                    ),
                    64: (
                        "wagtail.blocks.StructBlock",
                        [[("newsletter_signup", 63)]],
                        {"group": "Engagement & Buttons"},
                    ),
                    65: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("snippets.NewsletterUnsubscribe",),
                        {"max_num": 1},
                    ),
                    66: (
                        "wagtail.blocks.StructBlock",
                        [[("newsletter_unsubscribe", 65)]],
                        {"group": "Engagement & Buttons"},
                    ),
                    67: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Appears as the main heading.", "label": "Headline", "required": False},
                    ),
                    68: (
                        "foundation_cms.blocks.link_block.OptionalLinkBlock",
                        (),
                        {
                            "help_text": "Optional link for the card.",
                            "label": "Call to Action Link",
                            "required": False,
                        },
                    ),
                    69: ("wagtail.blocks.StructBlock", [[("headline", 67), ("cta_link", 68)]], {}),
                    70: (
                        "wagtail.blocks.ListBlock",
                        (69,),
                        {
                            "default": [
                                {"cta_link": [], "headline": ""},
                                {"cta_link": [], "headline": ""},
                                {"cta_link": [], "headline": ""},
                            ],
                            "help_text": "3 cards required.",
                            "label": "Pillar Cards",
                            "max_num": 3,
                            "min_num": 3,
                        },
                    ),
                    71: ("wagtail.blocks.StructBlock", [[("cards", 70)]], {"group": "Card Collections"}),
                    72: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Title of the podcast. <strong>Note:</strong> Does not render on "NothingPersonal" pages.'
                        },
                    ),
                    73: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": 'Optional short description of the podcast. <strong>Note:</strong> Does not render on "NothingPersonal" pages.',
                            "required": False,
                        },
                    ),
                    74: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 72), ("description", 73), ("simplecast_embed_code", 16)]],
                        {"group": "Media & Embeds"},
                    ),
                    75: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Appears above the headline.", "label": "Label", "required": False},
                    ),
                    76: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Optional Image for the card", "label": "Image"},
                    ),
                    77: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 16),
                                ("link_to", 17),
                                ("page", 18),
                                ("external_url", 19),
                                ("relative_url", 20),
                                ("anchor", 21),
                                ("email", 22),
                                ("file", 23),
                                ("phone", 24),
                                ("new_window", 25),
                            ]
                        ],
                        {"help_text": "Link for the card.", "label": "Call to Action Link", "required": True},
                    ),
                    78: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 75), ("headline", 67), ("image", 76), ("cta_link", 77)]],
                        {},
                    ),
                    79: (
                        "wagtail.blocks.ListBlock",
                        (78,),
                        {
                            "help_text": "Minimum of 3 cards required. More than 3 will turn element into a carousel.",
                            "label": "Portrait Cards",
                            "min_num": 3,
                        },
                    ),
                    80: ("wagtail.blocks.StructBlock", [[("cards", 79)]], {"group": "Card Collections"}),
                    81: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    82: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    83: ("wagtail.blocks.StructBlock", [[("quote", 81), ("attribution", 82)]], {"group": "Text"}),
                    84: ("foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock", (), {"group": "Text"}),
                    85: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("small", "Small"),
                                ("medium", "Medium"),
                                ("large", "Large"),
                                ("xlarge", "Extra Large"),
                            ],
                            "help_text": "Select the size of the spacer",
                        },
                    ),
                    86: ("wagtail.blocks.StructBlock", [[("size", 85)]], {"group": "Layout"}),
                    87: ("wagtail.blocks.CharBlock", (), {"label": "Name", "max_length": 50, "required": True}),
                    88: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Image should follow a 1:1 aspect ratio.", "label": "Image"},
                    ),
                    89: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 81), ("name", 87), ("description", 14), ("image", 88)]],
                        {},
                    ),
                    90: (
                        "wagtail.blocks.ListBlock",
                        (89,),
                        {"help_text": "3 cards required.", "label": "Spotlight Cards", "max_num": 3, "min_num": 3},
                    ),
                    91: ("wagtail.blocks.StructBlock", [[("cards", 90)]], {"group": "Card Collections"}),
                    92: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title shown on the tab button", "required": True},
                    ),
                    93: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Subtitle shown under the title on the tab", "required": False},
                    ),
                    94: ("foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock", (), {"required": False}),
                    95: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 38), ("image", 8), ("orientation", 39)]],
                        {"required": False},
                    ),
                    96: ("foundation_cms.blocks.link_block.OptionalLinkBlock", (), {"required": False}),
                    97: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 82), ("subtitle", 82), ("text", 94), ("image", 95), ("link", 96)]],
                        {},
                    ),
                    98: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 16), ("image", 8), ("subtitle", 16), ("link", 96)]],
                        {},
                    ),
                    99: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 1), ("text_image", 97), ("tab_card_set", 98)]],
                        {"help_text": "Add one or more content blocks to the tab.", "min_num": 1, "required": True},
                    ),
                    100: ("wagtail.blocks.StructBlock", [[("title", 92), ("subtitle", 93), ("content", 99)]], {}),
                    101: ("wagtail.blocks.ListBlock", (100,), {"label": "Tabs", "max_num": 8, "min_num": 1}),
                    102: ("wagtail.blocks.StructBlock", [[("tabs", 101)]], {"group": "Card Collections"}),
                    103: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional category for the card", "required": False},
                    ),
                    104: ("wagtail.blocks.CharBlock", (), {"help_text": "Title for the card", "required": True}),
                    105: (
                        "foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock",
                        (),
                        {"help_text": "Optional description text", "required": False},
                    ),
                    106: (
                        "wagtail.blocks.StructBlock",
                        [[("category", 103), ("title", 104), ("text", 105), ("image", 8), ("link", 60)]],
                        {},
                    ),
                    107: (
                        "wagtail.blocks.StreamBlock",
                        [[("card", 106)]],
                        {"help_text": "Add between 1 and 3 cards.", "max_num": 3, "min_num": 1},
                    ),
                    108: ("wagtail.blocks.StructBlock", [[("cards", 107)]], {"group": "Card Collections"}),
                    109: ("wagtail.blocks.CharBlock", (), {"help_text": "Title for the block", "required": True}),
                    110: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("shape", "Shape"), ("loop-line", "Loop Line")],
                            "help_text": "Select the style of the title",
                        },
                    ),
                    111: ("wagtail.blocks.StructBlock", [[("title", 109), ("style", 110)]], {"group": "Text"}),
                    112: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("white", "White"),
                                ("neutral-100", "Grey 100"),
                                ("neutral-200", "Grey 200"),
                                ("neutral-300", "Grey 300"),
                                ("blue-100", "Blue 100"),
                                ("blue-200", "Blue 200"),
                                ("blue-300", "Blue 300"),
                                ("green-100", "Green 100"),
                                ("green-200", "Green 200"),
                                ("green-300", "Green 300"),
                                ("orange-100", "Orange 100"),
                                ("orange-200", "Orange 200"),
                                ("orange-300", "Orange 300"),
                                ("yellow-100", "Yellow 100"),
                                ("yellow-200", "Yellow 200"),
                                ("yellow-300", "Yellow 300"),
                            ]
                        },
                    ),
                    113: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("top", "Top"), ("middle", "Middle"), ("bottom", "Bottom")],
                            "help_text": "Vertical alignment of the columns content",
                        },
                    ),
                    114: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 72), ("description", 73), ("simplecast_embed_code", 16)]],
                        {},
                    ),
                    115: ("wagtail.blocks.StructBlock", [[("title", 38), ("image", 8), ("orientation", 39)]], {}),
                    116: ("wagtail.blocks.StructBlock", [[("newsletter_signup", 63)]], {}),
                    117: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Log into Vimeo, select your desired video, and click 'Copy Link'",
                            "label": "Vimeo Video URL",
                            "required": True,
                        },
                    ),
                    118: ("wagtail.blocks.CharBlock", (), {"help_text": "Optional Caption Text", "required": False}),
                    119: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_to", 17),
                                ("page", 18),
                                ("external_url", 19),
                                ("relative_url", 20),
                                ("anchor", 21),
                                ("email", 22),
                                ("file", 23),
                                ("phone", 24),
                                ("new_window", 25),
                            ]
                        ],
                        {},
                    ),
                    120: (
                        "wagtail.blocks.ListBlock",
                        (119,),
                        {
                            "default": [],
                            "help_text": "Optional URL that this caption should link out to.",
                            "max_num": 1,
                            "min_num": 0,
                        },
                    ),
                    121: (
                        "wagtail.blocks.StructBlock",
                        [[("video_url", 117), ("caption", 118), ("caption_url", 120)]],
                        {},
                    ),
                    122: ("wagtail.blocks.StructBlock", [[("title", 58), ("description", 59), ("items", 61)]], {}),
                    123: ("wagtail.blocks.StructBlock", [[("size", 85)]], {}),
                    124: ("wagtail.blocks.StructBlock", [[("quote", 81), ("attribution", 82)]], {}),
                    125: ("wagtail.blocks.StructBlock", [[("title", 82), ("text", 94)]], {}),
                    126: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 16),
                                ("link_to", 17),
                                ("page", 18),
                                ("external_url", 19),
                                ("relative_url", 20),
                                ("anchor", 21),
                                ("email", 22),
                                ("file", 23),
                                ("phone", 24),
                                ("new_window", 25),
                                ("style", 26),
                                ("alignment", 27),
                            ]
                        ],
                        {},
                    ),
                    127: (
                        "wagtail.blocks.StructBlock",
                        [[("fru_element_type", 30), ("fru_element_embed_code", 31)]],
                        {},
                    ),
                    128: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 1),
                                ("podcast", 114),
                                ("image", 115),
                                ("newsletter_signup", 116),
                                ("video", 121),
                                ("list", 122),
                                ("spacer", 123),
                                ("quote", 124),
                                ("text_social", 125),
                                ("link_button", 126),
                                ("fru_element", 127),
                            ]
                        ],
                        {"label": "Left Column", "required": False},
                    ),
                    129: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 1),
                                ("podcast", 114),
                                ("image", 115),
                                ("newsletter_signup", 116),
                                ("video", 121),
                                ("list", 122),
                                ("spacer", 123),
                                ("quote", 124),
                                ("text_social", 125),
                                ("link_button", 126),
                                ("fru_element", 127),
                            ]
                        ],
                        {"label": "Right Column", "required": False},
                    ),
                    130: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 112),
                                ("vertical_alignment", 113),
                                ("left_column", 128),
                                ("right_column", 129),
                            ]
                        ],
                        {"group": "Layout"},
                    ),
                    131: (
                        "wagtail.blocks.StructBlock",
                        [[("video_url", 117), ("caption", 118), ("caption_url", 120)]],
                        {"group": "Media & Embeds"},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("accordion_block", 5),
                    ("divider", 6),
                    ("featured_card_block", 23),
                    ("fru_element_block", 26),
                    ("iframe_block", 31),
                    ("image", 35),
                    ("image_grid", 45),
                    ("impact_numbers", 51),
                    ("link_button_block", 52),
                    ("list_block", 57),
                    ("newsletter_signup", 59),
                    ("newsletter_unsubscribe", 61),
                    ("pillar_card_set", 66),
                    ("podcast_block", 69),
                    ("portrait_card_set_block", 75),
                    ("quote", 78),
                    ("rich_text", 79),
                    ("spacer_block", 81),
                    ("spotlight_card_set_block", 86),
                    ("tabbed_content", 97),
                    ("timely_activations_cards", 103),
                    ("title_block", 106),
                    ("two_column_container_block", 125),
                    ("video_block", 126),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Heading for the Accordion Item", "required": True},
                    ),
                    1: ("foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock", (), {}),
                    2: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 1)]],
                        {"required": False, "use_json_field": True},
                    ),
                    3: ("wagtail.blocks.StructBlock", [[("title", 0), ("content", 2)]], {}),
                    4: ("wagtail.blocks.ListBlock", (3,), {"min_num": 1}),
                    5: ("wagtail.blocks.StructBlock", [[("accordion_items", 4)]], {"group": "Text"}),
                    6: ("wagtail.blocks.StructBlock", [[]], {"group": "Layout"}),
                    7: ("wagtail.blocks.CharBlock", (), {"label": "Heading", "max_length": 50, "required": True}),
                    8: (
                        "foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock",
                        (),
                        {"features": ["bold", "italic"], "label": "Description", "max_length": 500, "required": True},
                    ),
                    9: ("wagtail.images.blocks.ImageBlock", [], {"help_text": "Image for the card", "label": "Image"}),
                    10: ("wagtail.blocks.CharBlock", (), {}),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("external_url", "External URL"),
                                ("relative_url", "Relative URL"),
                                ("email", "Email"),
                                ("anchor", "Anchor"),
                                ("file", "File"),
                                ("phone", "Phone"),
                            ],
                            "label": "Link to",
                        },
                    ),
                    12: ("wagtail.blocks.PageChooserBlock", (), {"label": "Page", "required": False}),
                    13: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Enter a full URL including http:// or https://",
                            "label": "External URL",
                            "max_length": 300,
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'A path relative to this domain. For example, "/foo/bar" or "?foo=bar".',
                            "label": "Relative URL",
                            "max_length": 300,
                            "required": False,
                            "validators": [foundation_cms.legacy_apps.wagtailpages.validators.RelativeURLValidator()],
                        },
                    ),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'An id attribute of an element on the current page. For example, "#section-1"',
                            "label": "#",
                            "max_length": 300,
                            "required": False,
                            "validators": [foundation_cms.validators.AnchorLinkValidator()],
                        },
                    ),
                    16: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    17: ("wagtail.documents.blocks.DocumentChooserBlock", (), {"label": "File", "required": False}),
                    18: ("wagtail.blocks.CharBlock", (), {"label": "Phone", "max_length": 30, "required": False}),
                    19: ("wagtail.blocks.BooleanBlock", (), {"label": "Open in new window", "required": False}),
                    20: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("btn-primary", "Primary"), ("btn-secondary", "Secondary")]},
                    ),
                    21: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("link-button-block__left", "Left"), ("link-button-block__center", "Center")]},
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 10),
                                ("link_to", 11),
                                ("page", 12),
                                ("external_url", 13),
                                ("relative_url", 14),
                                ("anchor", 15),
                                ("email", 16),
                                ("file", 17),
                                ("phone", 18),
                                ("new_window", 19),
                                ("style", 20),
                                ("alignment", 21),
                            ]
                        ],
                        {"help_text": "Link button for the card.", "label": "Button", "required": False},
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 7), ("description", 8), ("image", 9), ("button", 22)]],
                        {"group": "Card Collections"},
                    ),
                    24: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("donation-form", "Donation Form"),
                                ("donor-map", "Donor Map"),
                                ("top-locations", "Top Locations"),
                                ("donation-levels", "Donation Levels"),
                                ("donate-button", "Donate Button"),
                            ],
                            "help_text": "Select the type of Fundraise Up element.",
                        },
                    ),
                    25: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Copy the HTML code generated by the desired Fundraise Up element and paste it here.",
                            "required": True,
                        },
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [[("fru_element_type", 24), ("fru_element_embed_code", 25)]],
                        {"group": "Engagement & Buttons"},
                    ),
                    27: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Please note that only URLs from allow-listed domains will work."},
                    ),
                    28: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Optional integer pixel value for custom iFrame height", "required": False},
                    ),
                    29: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("normal", "Normal"), ("full_width", "Full Width")]},
                    ),
                    30: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": 'Checking this will add "scrolling=no" to the iframe. Use this if your iframe is rendering an unnecessary scroll bar or whitespace below it.',
                            "required": False,
                        },
                    ),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 27), ("height", 28), ("iframe_width", 29), ("disable_scroll", 30)]],
                        {"group": "Media & Embeds"},
                    ),
                    32: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title/caption for this image", "required": False},
                    ),
                    33: ("wagtail.images.blocks.ImageBlock", [], {}),
                    34: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("portrait", "Portrait"), ("landscape", "Landscape"), ("square", "Square")],
                            "help_text": "Select the orientation of this image",
                        },
                    ),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 32), ("image", 33), ("orientation", 34)]],
                        {"group": "Media & Embeds"},
                    ),
                    36: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional heading for this section", "max_length": 100, "required": False},
                    ),
                    37: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("portrait", "Portrait"), ("landscape", "Landscape"), ("square", "Square")],
                            "help_text": "Orientation for all images in this section",
                            "label": "Image grid section orientation",
                        },
                    ),
                    38: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("4", "4 per row"), ("5", "5 per row"), ("6", "6 per row")],
                            "label": "Items per section row",
                        },
                    ),
                    39: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["h5", "h6", "large", "bold", "italic"],
                            "help_text": "Optional caption for this image",
                            "required": False,
                        },
                    ),
                    40: (
                        "foundation_cms.blocks.link_block.OptionalLinkBlock",
                        (),
                        {"help_text": "Optional link for both image and caption", "required": False},
                    ),
                    41: ("wagtail.blocks.StructBlock", [[("image", 33), ("caption", 39), ("link", 40)]], {}),
                    42: ("wagtail.blocks.ListBlock", (41,), {"min_num": 1}),
                    43: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 36), ("section_orientation", 37), ("items_per_row", 38), ("items", 42)]],
                        {},
                    ),
                    44: ("wagtail.blocks.ListBlock", (43,), {"label": "Image grid sections", "min_num": 1}),
                    45: ("wagtail.blocks.StructBlock", [[("sections", 44)]], {"group": "Card Collections"}),
                    46: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The full value to animate, including any symbols, commas, decimals, or suffixes (e.g., $5.2M).",
                            "max_length": 5,
                            "required": True,
                        },
                    ),
                    47: ("wagtail.blocks.CharBlock", (), {"help_text": "Heading of the stat", "required": True}),
                    48: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Short description of the stat", "required": False},
                    ),
                    49: (
                        "wagtail.blocks.StructBlock",
                        [[("stat_number", 46), ("stat_heading", 47), ("stat_description", 48)]],
                        {},
                    ),
                    50: (
                        "wagtail.blocks.ListBlock",
                        (49,),
                        {
                            "default": [
                                {"stat_description": "", "stat_heading": "", "stat_number": ""},
                                {"stat_description": "", "stat_heading": "", "stat_number": ""},
                                {"stat_description": "", "stat_heading": "", "stat_number": ""},
                            ],
                            "help_text": "Add exactly 3 stats to appear in the Impact Numbers section",
                            "label": "Impact Stats",
                            "max_num": 3,
                            "min_num": 3,
                        },
                    ),
                    51: ("wagtail.blocks.StructBlock", [[("stats", 50)]], {"group": "Data Display"}),
                    52: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 10),
                                ("link_to", 11),
                                ("page", 12),
                                ("external_url", 13),
                                ("relative_url", 14),
                                ("anchor", 15),
                                ("email", 16),
                                ("file", 17),
                                ("phone", 18),
                                ("new_window", 19),
                                ("style", 20),
                                ("alignment", 21),
                            ]
                        ],
                        {"group": "Engagement & Buttons"},
                    ),
                    53: ("wagtail.blocks.CharBlock", (), {"help_text": "Heading displayed above the list"}),
                    54: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Description displayed above the list", "required": False},
                    ),
                    55: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 10),
                                ("link_to", 11),
                                ("page", 12),
                                ("external_url", 13),
                                ("relative_url", 14),
                                ("anchor", 15),
                                ("email", 16),
                                ("file", 17),
                                ("phone", 18),
                                ("new_window", 19),
                            ]
                        ],
                        {},
                    ),
                    56: ("wagtail.blocks.ListBlock", (55,), {"max_num": 4, "min_num": 1}),
                    57: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 53), ("description", 54), ("items", 56)]],
                        {"group": "Data Display"},
                    ),
                    58: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("snippets.NewsletterSignup",),
                        {"max_num": 1},
                    ),
                    59: (
                        "wagtail.blocks.StructBlock",
                        [[("newsletter_signup", 58)]],
                        {"group": "Engagement & Buttons"},
                    ),
                    60: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("snippets.NewsletterUnsubscribe",),
                        {"max_num": 1},
                    ),
                    61: (
                        "wagtail.blocks.StructBlock",
                        [[("newsletter_unsubscribe", 60)]],
                        {"group": "Engagement & Buttons"},
                    ),
                    62: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Appears as the main heading.", "label": "Headline", "required": False},
                    ),
                    63: (
                        "foundation_cms.blocks.link_block.OptionalLinkBlock",
                        (),
                        {
                            "help_text": "Optional link for the card.",
                            "label": "Call to Action Link",
                            "required": False,
                        },
                    ),
                    64: ("wagtail.blocks.StructBlock", [[("headline", 62), ("cta_link", 63)]], {}),
                    65: (
                        "wagtail.blocks.ListBlock",
                        (64,),
                        {
                            "default": [
                                {"cta_link": [], "headline": ""},
                                {"cta_link": [], "headline": ""},
                                {"cta_link": [], "headline": ""},
                            ],
                            "help_text": "3 cards required.",
                            "label": "Pillar Cards",
                            "max_num": 3,
                            "min_num": 3,
                        },
                    ),
                    66: ("wagtail.blocks.StructBlock", [[("cards", 65)]], {"group": "Card Collections"}),
                    67: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Title of the podcast. <strong>Note:</strong> Does not render on "NothingPersonal" pages.'
                        },
                    ),
                    68: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": 'Optional short description of the podcast. <strong>Note:</strong> Does not render on "NothingPersonal" pages.',
                            "required": False,
                        },
                    ),
                    69: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 67), ("description", 68), ("simplecast_embed_code", 10)]],
                        {"group": "Media & Embeds"},
                    ),
                    70: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Appears above the headline.", "label": "Label", "required": False},
                    ),
                    71: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Optional Image for the card", "label": "Image"},
                    ),
                    72: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 10),
                                ("link_to", 11),
                                ("page", 12),
                                ("external_url", 13),
                                ("relative_url", 14),
                                ("anchor", 15),
                                ("email", 16),
                                ("file", 17),
                                ("phone", 18),
                                ("new_window", 19),
                            ]
                        ],
                        {"help_text": "Link for the card.", "label": "Call to Action Link", "required": True},
                    ),
                    73: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 70), ("headline", 62), ("image", 71), ("cta_link", 72)]],
                        {},
                    ),
                    74: (
                        "wagtail.blocks.ListBlock",
                        (73,),
                        {
                            "help_text": "Minimum of 3 cards required. More than 3 will turn element into a carousel.",
                            "label": "Portrait Cards",
                            "min_num": 3,
                        },
                    ),
                    75: ("wagtail.blocks.StructBlock", [[("cards", 74)]], {"group": "Card Collections"}),
                    76: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    77: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    78: ("wagtail.blocks.StructBlock", [[("quote", 76), ("attribution", 77)]], {"group": "Text"}),
                    79: ("foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock", (), {"group": "Text"}),
                    80: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("small", "Small"),
                                ("medium", "Medium"),
                                ("large", "Large"),
                                ("xlarge", "Extra Large"),
                            ],
                            "help_text": "Select the size of the spacer",
                        },
                    ),
                    81: ("wagtail.blocks.StructBlock", [[("size", 80)]], {"group": "Layout"}),
                    82: ("wagtail.blocks.CharBlock", (), {"label": "Name", "max_length": 50, "required": True}),
                    83: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Image should follow a 1:1 aspect ratio.", "label": "Image"},
                    ),
                    84: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 76), ("name", 82), ("description", 8), ("image", 83)]],
                        {},
                    ),
                    85: (
                        "wagtail.blocks.ListBlock",
                        (84,),
                        {"help_text": "3 cards required.", "label": "Spotlight Cards", "max_num": 3, "min_num": 3},
                    ),
                    86: ("wagtail.blocks.StructBlock", [[("cards", 85)]], {"group": "Card Collections"}),
                    87: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title shown on the tab button", "required": True},
                    ),
                    88: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Subtitle shown under the title on the tab", "required": False},
                    ),
                    89: ("foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock", (), {"required": False}),
                    90: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 32), ("image", 33), ("orientation", 34)]],
                        {"required": False},
                    ),
                    91: ("foundation_cms.blocks.link_block.OptionalLinkBlock", (), {"required": False}),
                    92: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 77), ("subtitle", 77), ("text", 89), ("image", 90), ("link", 91)]],
                        {},
                    ),
                    93: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 10), ("image", 33), ("subtitle", 10), ("link", 91)]],
                        {},
                    ),
                    94: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 1), ("text_image", 92), ("tab_card_set", 93)]],
                        {"help_text": "Add one or more content blocks to the tab.", "min_num": 1, "required": True},
                    ),
                    95: ("wagtail.blocks.StructBlock", [[("title", 87), ("subtitle", 88), ("content", 94)]], {}),
                    96: ("wagtail.blocks.ListBlock", (95,), {"label": "Tabs", "max_num": 8, "min_num": 1}),
                    97: ("wagtail.blocks.StructBlock", [[("tabs", 96)]], {"group": "Card Collections"}),
                    98: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional category for the card", "required": False},
                    ),
                    99: ("wagtail.blocks.CharBlock", (), {"help_text": "Title for the card", "required": True}),
                    100: (
                        "foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock",
                        (),
                        {"help_text": "Optional description text", "required": False},
                    ),
                    101: (
                        "wagtail.blocks.StructBlock",
                        [[("category", 98), ("title", 99), ("text", 100), ("image", 33), ("link", 55)]],
                        {},
                    ),
                    102: (
                        "wagtail.blocks.StreamBlock",
                        [[("card", 101)]],
                        {"help_text": "Add between 1 and 3 cards.", "max_num": 3, "min_num": 1},
                    ),
                    103: ("wagtail.blocks.StructBlock", [[("cards", 102)]], {"group": "Card Collections"}),
                    104: ("wagtail.blocks.CharBlock", (), {"help_text": "Title for the block", "required": True}),
                    105: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("shape", "Shape"), ("loop-line", "Loop Line")],
                            "help_text": "Select the style of the title",
                        },
                    ),
                    106: ("wagtail.blocks.StructBlock", [[("title", 104), ("style", 105)]], {"group": "Text"}),
                    107: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("white", "White"),
                                ("neutral-100", "Grey 100"),
                                ("neutral-200", "Grey 200"),
                                ("neutral-300", "Grey 300"),
                                ("blue-100", "Blue 100"),
                                ("blue-200", "Blue 200"),
                                ("blue-300", "Blue 300"),
                                ("green-100", "Green 100"),
                                ("green-200", "Green 200"),
                                ("green-300", "Green 300"),
                                ("orange-100", "Orange 100"),
                                ("orange-200", "Orange 200"),
                                ("orange-300", "Orange 300"),
                                ("yellow-100", "Yellow 100"),
                                ("yellow-200", "Yellow 200"),
                                ("yellow-300", "Yellow 300"),
                            ]
                        },
                    ),
                    108: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("top", "Top"), ("middle", "Middle"), ("bottom", "Bottom")],
                            "help_text": "Vertical alignment of the columns content",
                        },
                    ),
                    109: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 67), ("description", 68), ("simplecast_embed_code", 10)]],
                        {},
                    ),
                    110: ("wagtail.blocks.StructBlock", [[("title", 32), ("image", 33), ("orientation", 34)]], {}),
                    111: ("wagtail.blocks.StructBlock", [[("newsletter_signup", 58)]], {}),
                    112: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Log into Vimeo, select your desired video, and click 'Copy Link'",
                            "label": "Vimeo Video URL",
                            "required": True,
                        },
                    ),
                    113: ("wagtail.blocks.CharBlock", (), {"help_text": "Optional Caption Text", "required": False}),
                    114: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_to", 11),
                                ("page", 12),
                                ("external_url", 13),
                                ("relative_url", 14),
                                ("anchor", 15),
                                ("email", 16),
                                ("file", 17),
                                ("phone", 18),
                                ("new_window", 19),
                            ]
                        ],
                        {},
                    ),
                    115: (
                        "wagtail.blocks.ListBlock",
                        (114,),
                        {
                            "default": [],
                            "help_text": "Optional URL that this caption should link out to.",
                            "max_num": 1,
                            "min_num": 0,
                        },
                    ),
                    116: (
                        "wagtail.blocks.StructBlock",
                        [[("video_url", 112), ("caption", 113), ("caption_url", 115)]],
                        {},
                    ),
                    117: ("wagtail.blocks.StructBlock", [[("title", 53), ("description", 54), ("items", 56)]], {}),
                    118: ("wagtail.blocks.StructBlock", [[("size", 80)]], {}),
                    119: ("wagtail.blocks.StructBlock", [[("quote", 76), ("attribution", 77)]], {}),
                    120: ("wagtail.blocks.StructBlock", [[("title", 77), ("text", 89)]], {}),
                    121: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 10),
                                ("link_to", 11),
                                ("page", 12),
                                ("external_url", 13),
                                ("relative_url", 14),
                                ("anchor", 15),
                                ("email", 16),
                                ("file", 17),
                                ("phone", 18),
                                ("new_window", 19),
                                ("style", 20),
                                ("alignment", 21),
                            ]
                        ],
                        {},
                    ),
                    122: (
                        "wagtail.blocks.StructBlock",
                        [[("fru_element_type", 24), ("fru_element_embed_code", 25)]],
                        {},
                    ),
                    123: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 1),
                                ("podcast", 109),
                                ("image", 110),
                                ("newsletter_signup", 111),
                                ("video", 116),
                                ("list", 117),
                                ("spacer", 118),
                                ("quote", 119),
                                ("text_social", 120),
                                ("link_button", 121),
                                ("fru_element", 122),
                            ]
                        ],
                        {"label": "Left Column", "required": False},
                    ),
                    124: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 1),
                                ("podcast", 109),
                                ("image", 110),
                                ("newsletter_signup", 111),
                                ("video", 116),
                                ("list", 117),
                                ("spacer", 118),
                                ("quote", 119),
                                ("text_social", 120),
                                ("link_button", 121),
                                ("fru_element", 122),
                            ]
                        ],
                        {"label": "Right Column", "required": False},
                    ),
                    125: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 107),
                                ("vertical_alignment", 108),
                                ("left_column", 123),
                                ("right_column", 124),
                            ]
                        ],
                        {"group": "Layout"},
                    ),
                    126: (
                        "wagtail.blocks.StructBlock",
                        [[("video_url", 112), ("caption", 113), ("caption_url", 115)]],
                        {"group": "Media & Embeds"},
                    ),
                },
            ),
        ),
    ]
