# Generated by Django 4.2.28 on 2026-03-13 04:40

import modelcluster.contrib.taggit
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_remove_new_from_verbose_names"),
        ("core", "0068_alter_generalpage_body_alter_homepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalpage",
            name="topics",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="Select one or more topics from the dropdown. If a topic is unavailable, please reach out to StratComms for help.",
                through="base.PageTopic",
                to="base.Topic",
                verbose_name="Page Topics",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="topics",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="Select one or more topics from the dropdown. If a topic is unavailable, please reach out to StratComms for help.",
                through="base.PageTopic",
                to="base.Topic",
                verbose_name="Page Topics",
            ),
        ),
    ]
