# Generated by Django 4.2.29 on 2026-03-13 19:27

import wagtail.fields
from django.db import migrations

import foundation_cms.legacy_apps.wagtailpages.validators
import foundation_cms.validators


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0068_alter_generalpage_body_alter_homepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("accordion_block", 5),
                    ("custom_media", 11),
                    ("divider", 12),
                    ("featured_card_block", 29),
                    ("fru_element_block", 32),
                    ("iframe_block", 37),
                    ("image", 40),
                    ("image_grid", 50),
                    ("impact_numbers", 56),
                    ("link_button_block", 57),
                    ("list_block", 62),
                    ("newsletter_signup", 64),
                    ("newsletter_unsubscribe", 66),
                    ("pillar_card_set", 71),
                    ("podcast_block", 74),
                    ("portrait_card_set_block", 80),
                    ("quote", 83),
                    ("rich_text", 84),
                    ("spacer_block", 86),
                    ("speaker_carousel_block", 96),
                    ("spotlight_card_set_block", 101),
                    ("tabbed_content", 112),
                    ("timely_activations_cards", 118),
                    ("title_block", 121),
                    ("two_column_container_block", 140),
                    ("video_block", 141),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Heading for the Accordion Item", "required": True},
                    ),
                    1: ("foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock", (), {}),
                    2: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 1)]],
                        {"required": False, "use_json_field": True},
                    ),
                    3: ("wagtail.blocks.StructBlock", [[("title", 0), ("content", 2)]], {}),
                    4: ("wagtail.blocks.ListBlock", (3,), {"min_num": 1}),
                    5: ("wagtail.blocks.StructBlock", [[("accordion_items", 4)]], {"group": "Text"}),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title/caption for this media", "required": False},
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("image", "Image"), ("video", "Video")],
                            "help_text": "Select the type of media to display",
                        },
                    ),
                    8: ("wagtail.images.blocks.ImageBlock", [], {}),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Log into Vimeo using 1Password and upload the desired video. Then select the video and click "...", "Video File Links", and select "(mp4, 1920 x 1080)". Copy and paste the link here.',
                            "max_length": 500,
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("portrait", "Portrait"),
                                ("landscape", "Landscape"),
                                ("square", "Square"),
                                ("widescreen", "Widescreen 16:9 (12 columns wide)"),
                            ],
                            "help_text": "Select the orientation of this media",
                        },
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 6), ("content", 7), ("image", 8), ("video_url", 9), ("orientation", 10)]],
                        {"group": "Media & Embeds"},
                    ),
                    12: ("wagtail.blocks.StructBlock", [[]], {"group": "Layout"}),
                    13: ("wagtail.blocks.CharBlock", (), {"label": "Heading", "max_length": 50, "required": True}),
                    14: (
                        "foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock",
                        (),
                        {"features": ["bold", "italic"], "label": "Description", "max_length": 500, "required": True},
                    ),
                    15: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Image for the card", "label": "Image"},
                    ),
                    16: ("wagtail.blocks.CharBlock", (), {}),
                    17: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("external_url", "External URL"),
                                ("relative_url", "Relative URL"),
                                ("email", "Email"),
                                ("anchor", "Anchor"),
                                ("file", "File"),
                                ("phone", "Phone"),
                            ],
                            "label": "Link to",
                        },
                    ),
                    18: ("wagtail.blocks.PageChooserBlock", (), {"label": "Page", "required": False}),
                    19: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Enter a full URL including http:// or https://",
                            "label": "External URL",
                            "max_length": 300,
                            "required": False,
                        },
                    ),
                    20: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'A path relative to this domain. For example, "/foo/bar" or "?foo=bar".',
                            "label": "Relative URL",
                            "max_length": 300,
                            "required": False,
                            "validators": [foundation_cms.legacy_apps.wagtailpages.validators.RelativeURLValidator()],
                        },
                    ),
                    21: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'An id attribute of an element on the current page. For example, "#section-1"',
                            "label": "#",
                            "max_length": 300,
                            "required": False,
                            "validators": [foundation_cms.validators.AnchorLinkValidator()],
                        },
                    ),
                    22: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    23: ("wagtail.documents.blocks.DocumentChooserBlock", (), {"label": "File", "required": False}),
                    24: ("wagtail.blocks.CharBlock", (), {"label": "Phone", "max_length": 30, "required": False}),
                    25: ("wagtail.blocks.BooleanBlock", (), {"label": "Open in new window", "required": False}),
                    26: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("btn-primary", "Primary"), ("btn-secondary", "Secondary")]},
                    ),
                    27: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("link-button-block--left", "Left"), ("link-button-block--center", "Center")]},
                    ),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 16),
                                ("link_to", 17),
                                ("page", 18),
                                ("external_url", 19),
                                ("relative_url", 20),
                                ("anchor", 21),
                                ("email", 22),
                                ("file", 23),
                                ("phone", 24),
                                ("new_window", 25),
                                ("style", 26),
                                ("alignment", 27),
                            ]
                        ],
                        {"help_text": "Link button for the card.", "label": "Button", "required": False},
                    ),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 13), ("description", 14), ("image", 15), ("button", 28)]],
                        {"group": "Card Collections"},
                    ),
                    30: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("donation-form", "Donation Form"),
                                ("donor-map", "Donor Map"),
                                ("top-locations", "Top Locations"),
                                ("donation-levels", "Donation Levels"),
                                ("donate-button", "Donate Button"),
                            ],
                            "help_text": "Select the type of Fundraise Up element.",
                        },
                    ),
                    31: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Copy the HTML code generated by the desired Fundraise Up element and paste it here.",
                            "required": True,
                        },
                    ),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [[("fru_element_type", 30), ("fru_element_embed_code", 31)]],
                        {"group": "Engagement & Buttons"},
                    ),
                    33: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Please note that only URLs from allow-listed domains will work."},
                    ),
                    34: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Optional integer pixel value for custom iFrame height", "required": False},
                    ),
                    35: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("normal", "Normal"), ("full_width", "Full Width")]},
                    ),
                    36: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": 'Checking this will add "scrolling=no" to the iframe. Use this if your iframe is rendering an unnecessary scroll bar or whitespace below it.',
                            "required": False,
                        },
                    ),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 33), ("height", 34), ("iframe_width", 35), ("disable_scroll", 36)]],
                        {"group": "Media & Embeds"},
                    ),
                    38: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title/caption for this image", "required": False},
                    ),
                    39: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("portrait", "Portrait"), ("landscape", "Landscape"), ("square", "Square")],
                            "help_text": "Select the orientation of this image",
                        },
                    ),
                    40: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 38), ("image", 8), ("orientation", 39)]],
                        {"group": "Media & Embeds"},
                    ),
                    41: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional heading for this section", "max_length": 100, "required": False},
                    ),
                    42: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("portrait", "Portrait"), ("landscape", "Landscape"), ("square", "Square")],
                            "help_text": "Orientation for all images in this section",
                            "label": "Image grid section orientation",
                        },
                    ),
                    43: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("4", "4 per row"), ("5", "5 per row"), ("6", "6 per row")],
                            "label": "Items per section row",
                        },
                    ),
                    44: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["h5", "h6", "large", "bold", "italic"],
                            "help_text": "Optional caption for this image",
                            "required": False,
                        },
                    ),
                    45: (
                        "foundation_cms.blocks.link_block.OptionalLinkBlock",
                        (),
                        {"help_text": "Optional link for both image and caption", "required": False},
                    ),
                    46: ("wagtail.blocks.StructBlock", [[("image", 8), ("caption", 44), ("link", 45)]], {}),
                    47: ("wagtail.blocks.ListBlock", (46,), {"min_num": 1}),
                    48: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 41), ("section_orientation", 42), ("items_per_row", 43), ("items", 47)]],
                        {},
                    ),
                    49: ("wagtail.blocks.ListBlock", (48,), {"label": "Image grid sections", "min_num": 1}),
                    50: ("wagtail.blocks.StructBlock", [[("sections", 49)]], {"group": "Card Collections"}),
                    51: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The full value to animate, including any symbols, commas, decimals, or suffixes (e.g., $5.2M).",
                            "max_length": 5,
                            "required": True,
                        },
                    ),
                    52: ("wagtail.blocks.CharBlock", (), {"help_text": "Heading of the stat", "required": True}),
                    53: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Short description of the stat", "required": False},
                    ),
                    54: (
                        "wagtail.blocks.StructBlock",
                        [[("stat_number", 51), ("stat_heading", 52), ("stat_description", 53)]],
                        {},
                    ),
                    55: (
                        "wagtail.blocks.ListBlock",
                        (54,),
                        {
                            "default": [
                                {"stat_description": "", "stat_heading": "", "stat_number": ""},
                                {"stat_description": "", "stat_heading": "", "stat_number": ""},
                                {"stat_description": "", "stat_heading": "", "stat_number": ""},
                            ],
                            "help_text": "Add exactly 3 stats to appear in the Impact Numbers section",
                            "label": "Impact Stats",
                            "max_num": 3,
                            "min_num": 3,
                        },
                    ),
                    56: ("wagtail.blocks.StructBlock", [[("stats", 55)]], {"group": "Data Display"}),
                    57: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 16),
                                ("link_to", 17),
                                ("page", 18),
                                ("external_url", 19),
                                ("relative_url", 20),
                                ("anchor", 21),
                                ("email", 22),
                                ("file", 23),
                                ("phone", 24),
                                ("new_window", 25),
                                ("style", 26),
                                ("alignment", 27),
                            ]
                        ],
                        {"group": "Engagement & Buttons"},
                    ),
                    58: ("wagtail.blocks.CharBlock", (), {"help_text": "Heading displayed above the list"}),
                    59: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Description displayed above the list", "required": False},
                    ),
                    60: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 16),
                                ("link_to", 17),
                                ("page", 18),
                                ("external_url", 19),
                                ("relative_url", 20),
                                ("anchor", 21),
                                ("email", 22),
                                ("file", 23),
                                ("phone", 24),
                                ("new_window", 25),
                            ]
                        ],
                        {},
                    ),
                    61: ("wagtail.blocks.ListBlock", (60,), {"max_num": 4, "min_num": 1}),
                    62: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 58), ("description", 59), ("items", 61)]],
                        {"group": "Data Display"},
                    ),
                    63: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("snippets.NewsletterSignup",),
                        {"max_num": 1},
                    ),
                    64: (
                        "wagtail.blocks.StructBlock",
                        [[("newsletter_signup", 63)]],
                        {"group": "Engagement & Buttons"},
                    ),
                    65: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("snippets.NewsletterUnsubscribe",),
                        {"max_num": 1},
                    ),
                    66: (
                        "wagtail.blocks.StructBlock",
                        [[("newsletter_unsubscribe", 65)]],
                        {"group": "Engagement & Buttons"},
                    ),
                    67: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Appears as the main heading.", "label": "Headline", "required": False},
                    ),
                    68: (
                        "foundation_cms.blocks.link_block.OptionalLinkBlock",
                        (),
                        {
                            "help_text": "Optional link for the card.",
                            "label": "Call to Action Link",
                            "required": False,
                        },
                    ),
                    69: ("wagtail.blocks.StructBlock", [[("headline", 67), ("cta_link", 68)]], {}),
                    70: (
                        "wagtail.blocks.ListBlock",
                        (69,),
                        {
                            "default": [
                                {"cta_link": [], "headline": ""},
                                {"cta_link": [], "headline": ""},
                                {"cta_link": [], "headline": ""},
                            ],
                            "help_text": "3 cards required.",
                            "label": "Pillar Cards",
                            "max_num": 3,
                            "min_num": 3,
                        },
                    ),
                    71: ("wagtail.blocks.StructBlock", [[("cards", 70)]], {"group": "Card Collections"}),
                    72: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Title of the podcast. <strong>Note:</strong> Does not render on "NothingPersonal" pages.'
                        },
                    ),
                    73: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": 'Optional short description of the podcast. <strong>Note:</strong> Does not render on "NothingPersonal" pages.',
                            "required": False,
                        },
                    ),
                    74: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 72), ("description", 73), ("simplecast_embed_code", 16)]],
                        {"group": "Media & Embeds"},
                    ),
                    75: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Appears above the headline.", "label": "Label", "required": False},
                    ),
                    76: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Optional Image for the card", "label": "Image"},
                    ),
                    77: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 16),
                                ("link_to", 17),
                                ("page", 18),
                                ("external_url", 19),
                                ("relative_url", 20),
                                ("anchor", 21),
                                ("email", 22),
                                ("file", 23),
                                ("phone", 24),
                                ("new_window", 25),
                            ]
                        ],
                        {"help_text": "Link for the card.", "label": "Call to Action Link", "required": True},
                    ),
                    78: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 75), ("headline", 67), ("image", 76), ("cta_link", 77)]],
                        {},
                    ),
                    79: (
                        "wagtail.blocks.ListBlock",
                        (78,),
                        {
                            "help_text": "Minimum of 3 cards required. More than 3 will turn element into a carousel.",
                            "label": "Portrait Cards",
                            "min_num": 3,
                        },
                    ),
                    80: ("wagtail.blocks.StructBlock", [[("cards", 79)]], {"group": "Card Collections"}),
                    81: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    82: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    83: ("wagtail.blocks.StructBlock", [[("quote", 81), ("attribution", 82)]], {"group": "Text"}),
                    84: ("foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock", (), {"group": "Text"}),
                    85: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("small", "Small"),
                                ("medium", "Medium"),
                                ("large", "Large"),
                                ("xlarge", "Extra Large"),
                            ],
                            "help_text": "Select the size of the spacer",
                        },
                    ),
                    86: ("wagtail.blocks.StructBlock", [[("size", 85)]], {"group": "Layout"}),
                    87: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional title for the container.", "required": False},
                    ),
                    88: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("portrait", "Portrait"), ("landscape", "Landscape")],
                            "help_text": "Select the orientation for the carousel items.",
                            "label": "Item Orientation",
                        },
                    ),
                    89: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Select an image for this item.", "required": True},
                    ),
                    90: (
                        "foundation_cms.blocks.link_block.OptionalLinkBlock",
                        (),
                        {"help_text": "Optional link for this item.", "required": False},
                    ),
                    91: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Speaker's full name.", "max_length": 120, "required": True},
                    ),
                    92: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Speaker's role or job title.", "max_length": 120, "required": False},
                    ),
                    93: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Speaker's organization or company.", "max_length": 120, "required": False},
                    ),
                    94: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 89), ("link", 90), ("name", 91), ("role", 92), ("organization", 93)]],
                        {},
                    ),
                    95: (
                        "wagtail.blocks.StreamBlock",
                        [[("speaker_item", 94)]],
                        {"help_text": "Maximum of 10 speakers per carousel.", "max_num": 10},
                    ),
                    96: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 87), ("orientation", 88), ("items", 95)]],
                        {"group": "Card Collections"},
                    ),
                    97: ("wagtail.blocks.CharBlock", (), {"label": "Name", "max_length": 50, "required": True}),
                    98: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Image should follow a 1:1 aspect ratio.", "label": "Image"},
                    ),
                    99: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 81), ("name", 97), ("description", 14), ("image", 98)]],
                        {},
                    ),
                    100: (
                        "wagtail.blocks.ListBlock",
                        (99,),
                        {"help_text": "3 cards required.", "label": "Spotlight Cards", "max_num": 3, "min_num": 3},
                    ),
                    101: ("wagtail.blocks.StructBlock", [[("cards", 100)]], {"group": "Card Collections"}),
                    102: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title shown on the tab button", "required": True},
                    ),
                    103: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Subtitle shown under the title on the tab", "required": False},
                    ),
                    104: ("foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock", (), {"required": False}),
                    105: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 38), ("image", 8), ("orientation", 39)]],
                        {"required": False},
                    ),
                    106: ("foundation_cms.blocks.link_block.OptionalLinkBlock", (), {"required": False}),
                    107: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 82), ("subtitle", 82), ("text", 104), ("image", 105), ("link", 106)]],
                        {},
                    ),
                    108: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 16), ("image", 8), ("subtitle", 16), ("link", 106)]],
                        {},
                    ),
                    109: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 1), ("text_image", 107), ("tab_card_set", 108)]],
                        {"help_text": "Add one or more content blocks to the tab.", "min_num": 1, "required": True},
                    ),
                    110: ("wagtail.blocks.StructBlock", [[("title", 102), ("subtitle", 103), ("content", 109)]], {}),
                    111: ("wagtail.blocks.ListBlock", (110,), {"label": "Tabs", "max_num": 8, "min_num": 1}),
                    112: ("wagtail.blocks.StructBlock", [[("tabs", 111)]], {"group": "Card Collections"}),
                    113: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional category for the card", "required": False},
                    ),
                    114: ("wagtail.blocks.CharBlock", (), {"help_text": "Title for the card", "required": True}),
                    115: (
                        "foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock",
                        (),
                        {"help_text": "Optional description text", "required": False},
                    ),
                    116: (
                        "wagtail.blocks.StructBlock",
                        [[("category", 113), ("title", 114), ("text", 115), ("image", 8), ("link", 60)]],
                        {},
                    ),
                    117: (
                        "wagtail.blocks.StreamBlock",
                        [[("card", 116)]],
                        {"help_text": "Add between 1 and 3 cards.", "max_num": 3, "min_num": 1},
                    ),
                    118: ("wagtail.blocks.StructBlock", [[("cards", 117)]], {"group": "Card Collections"}),
                    119: ("wagtail.blocks.CharBlock", (), {"help_text": "Title for the block", "required": True}),
                    120: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("shape", "Shape"), ("loop-line", "Loop Line")],
                            "help_text": "Select the style of the title",
                        },
                    ),
                    121: ("wagtail.blocks.StructBlock", [[("title", 119), ("style", 120)]], {"group": "Text"}),
                    122: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("white", "White"),
                                ("neutral-100", "Grey 100"),
                                ("neutral-200", "Grey 200"),
                                ("neutral-300", "Grey 300"),
                                ("blue-100", "Blue 100"),
                                ("blue-200", "Blue 200"),
                                ("blue-300", "Blue 300"),
                                ("green-100", "Green 100"),
                                ("green-200", "Green 200"),
                                ("green-300", "Green 300"),
                                ("orange-100", "Orange 100"),
                                ("orange-200", "Orange 200"),
                                ("orange-300", "Orange 300"),
                                ("yellow-100", "Yellow 100"),
                                ("yellow-200", "Yellow 200"),
                                ("yellow-300", "Yellow 300"),
                            ]
                        },
                    ),
                    123: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("top", "Top"), ("middle", "Middle"), ("bottom", "Bottom")],
                            "help_text": "Vertical alignment of the columns content",
                        },
                    ),
                    124: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 72), ("description", 73), ("simplecast_embed_code", 16)]],
                        {},
                    ),
                    125: ("wagtail.blocks.StructBlock", [[("title", 38), ("image", 8), ("orientation", 39)]], {}),
                    126: ("wagtail.blocks.StructBlock", [[("newsletter_signup", 63)]], {}),
                    127: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Log into Vimeo, select your desired video, and click 'Copy Link'",
                            "label": "Vimeo Video URL",
                            "required": True,
                        },
                    ),
                    128: ("wagtail.blocks.CharBlock", (), {"help_text": "Optional Caption Text", "required": False}),
                    129: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_to", 17),
                                ("page", 18),
                                ("external_url", 19),
                                ("relative_url", 20),
                                ("anchor", 21),
                                ("email", 22),
                                ("file", 23),
                                ("phone", 24),
                                ("new_window", 25),
                            ]
                        ],
                        {},
                    ),
                    130: (
                        "wagtail.blocks.ListBlock",
                        (129,),
                        {
                            "default": [],
                            "help_text": "Optional URL that this caption should link out to.",
                            "max_num": 1,
                            "min_num": 0,
                        },
                    ),
                    131: (
                        "wagtail.blocks.StructBlock",
                        [[("video_url", 127), ("caption", 128), ("caption_url", 130)]],
                        {},
                    ),
                    132: ("wagtail.blocks.StructBlock", [[("title", 58), ("description", 59), ("items", 61)]], {}),
                    133: ("wagtail.blocks.StructBlock", [[("size", 85)]], {}),
                    134: ("wagtail.blocks.StructBlock", [[("quote", 81), ("attribution", 82)]], {}),
                    135: ("wagtail.blocks.StructBlock", [[("title", 82), ("text", 104)]], {}),
                    136: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 16),
                                ("link_to", 17),
                                ("page", 18),
                                ("external_url", 19),
                                ("relative_url", 20),
                                ("anchor", 21),
                                ("email", 22),
                                ("file", 23),
                                ("phone", 24),
                                ("new_window", 25),
                                ("style", 26),
                                ("alignment", 27),
                            ]
                        ],
                        {},
                    ),
                    137: (
                        "wagtail.blocks.StructBlock",
                        [[("fru_element_type", 30), ("fru_element_embed_code", 31)]],
                        {},
                    ),
                    138: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 1),
                                ("podcast", 124),
                                ("image", 125),
                                ("newsletter_signup", 126),
                                ("video", 131),
                                ("list", 132),
                                ("spacer", 133),
                                ("quote", 134),
                                ("text_social", 135),
                                ("link_button", 136),
                                ("fru_element", 137),
                            ]
                        ],
                        {"label": "Left Column", "required": False},
                    ),
                    139: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 1),
                                ("podcast", 124),
                                ("image", 125),
                                ("newsletter_signup", 126),
                                ("video", 131),
                                ("list", 132),
                                ("spacer", 133),
                                ("quote", 134),
                                ("text_social", 135),
                                ("link_button", 136),
                                ("fru_element", 137),
                            ]
                        ],
                        {"label": "Right Column", "required": False},
                    ),
                    140: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 122),
                                ("vertical_alignment", 123),
                                ("left_column", 138),
                                ("right_column", 139),
                            ]
                        ],
                        {"group": "Layout"},
                    ),
                    141: (
                        "wagtail.blocks.StructBlock",
                        [[("video_url", 127), ("caption", 128), ("caption_url", 130)]],
                        {"group": "Media & Embeds"},
                    ),
                },
            ),
        ),
    ]
