# Generated by Django 4.2.29 on 2026-04-08 18:58

import wagtail.fields
from django.db import migrations

import foundation_cms.legacy_apps.wagtailpages.validators
import foundation_cms.validators


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0072_alter_generalpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("accordion_block", 5),
                    ("custom_media", 11),
                    ("divider", 12),
                    ("featured_card_block", 29),
                    ("fru_element_block", 32),
                    ("icon_info_grid", 42),
                    ("iframe_block", 47),
                    ("image", 50),
                    ("image_carousel_block", 60),
                    ("image_grid", 70),
                    ("impact_numbers", 76),
                    ("link_button_block", 77),
                    ("list_block", 82),
                    ("newsletter_signup", 84),
                    ("newsletter_unsubscribe", 86),
                    ("pillar_card_set", 91),
                    ("podcast_block", 94),
                    ("portrait_card_set_block", 100),
                    ("quote", 103),
                    ("rich_text", 104),
                    ("spacer_block", 106),
                    ("spotlight_card_set_block", 111),
                    ("tabbed_content", 122),
                    ("timely_activations_cards", 128),
                    ("title_block", 131),
                    ("two_column_container_block", 150),
                    ("video_block", 151),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Heading for the Accordion Item", "required": True},
                    ),
                    1: ("foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock", (), {}),
                    2: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 1)]],
                        {"required": False, "use_json_field": True},
                    ),
                    3: ("wagtail.blocks.StructBlock", [[("title", 0), ("content", 2)]], {}),
                    4: ("wagtail.blocks.ListBlock", (3,), {"min_num": 1}),
                    5: ("wagtail.blocks.StructBlock", [[("accordion_items", 4)]], {"group": "Text"}),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title/caption for this media", "required": False},
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("image", "Image"), ("video", "Video")],
                            "help_text": "Select the type of media to display",
                        },
                    ),
                    8: ("wagtail.images.blocks.ImageBlock", [], {}),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Log into Vimeo using 1Password and upload the desired video. Then select the video and click "...", "Video File Links", and select "(mp4, 1920 x 1080)". Copy and paste the link here.',
                            "max_length": 500,
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("portrait", "Portrait"),
                                ("landscape", "Landscape"),
                                ("square", "Square"),
                                ("widescreen", "Widescreen 16:9 (12 columns wide)"),
                            ],
                            "help_text": "Select the orientation of this media",
                        },
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 6), ("content", 7), ("image", 8), ("video_url", 9), ("orientation", 10)]],
                        {"group": "Media & Embeds"},
                    ),
                    12: ("wagtail.blocks.StructBlock", [[]], {"group": "Layout"}),
                    13: ("wagtail.blocks.CharBlock", (), {"label": "Heading", "max_length": 50, "required": True}),
                    14: (
                        "foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock",
                        (),
                        {"features": ["bold", "italic"], "label": "Description", "max_length": 500, "required": True},
                    ),
                    15: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Image for the card", "label": "Image"},
                    ),
                    16: ("wagtail.blocks.CharBlock", (), {}),
                    17: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("external_url", "External URL"),
                                ("relative_url", "Relative URL"),
                                ("email", "Email"),
                                ("anchor", "Anchor"),
                                ("file", "File"),
                                ("phone", "Phone"),
                            ],
                            "label": "Link to",
                        },
                    ),
                    18: ("wagtail.blocks.PageChooserBlock", (), {"label": "Page", "required": False}),
                    19: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Enter a full URL including http:// or https://",
                            "label": "External URL",
                            "max_length": 300,
                            "required": False,
                        },
                    ),
                    20: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'A path relative to this domain. For example, "/foo/bar" or "?foo=bar".',
                            "label": "Relative URL",
                            "max_length": 300,
                            "required": False,
                            "validators": [foundation_cms.legacy_apps.wagtailpages.validators.RelativeURLValidator()],
                        },
                    ),
                    21: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'An id attribute of an element on the current page. For example, "#section-1"',
                            "label": "#",
                            "max_length": 300,
                            "required": False,
                            "validators": [foundation_cms.validators.AnchorLinkValidator()],
                        },
                    ),
                    22: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    23: ("wagtail.documents.blocks.DocumentChooserBlock", (), {"label": "File", "required": False}),
                    24: ("wagtail.blocks.CharBlock", (), {"label": "Phone", "max_length": 30, "required": False}),
                    25: ("wagtail.blocks.BooleanBlock", (), {"label": "Open in new window", "required": False}),
                    26: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("btn-primary", "Primary"), ("btn-secondary", "Secondary")]},
                    ),
                    27: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("link-button-block--left", "Left"), ("link-button-block--center", "Center")]},
                    ),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 16),
                                ("link_to", 17),
                                ("page", 18),
                                ("external_url", 19),
                                ("relative_url", 20),
                                ("anchor", 21),
                                ("email", 22),
                                ("file", 23),
                                ("phone", 24),
                                ("new_window", 25),
                                ("style", 26),
                                ("alignment", 27),
                            ]
                        ],
                        {"help_text": "Link button for the card.", "label": "Button", "required": False},
                    ),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 13), ("description", 14), ("image", 15), ("button", 28)]],
                        {"group": "Card Collections"},
                    ),
                    30: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("donation-form", "Donation Form"),
                                ("donor-map", "Donor Map"),
                                ("top-locations", "Top Locations"),
                                ("donation-levels", "Donation Levels"),
                                ("donate-button", "Donate Button"),
                            ],
                            "help_text": "Select the type of Fundraise Up element.",
                        },
                    ),
                    31: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Copy the HTML code generated by the desired Fundraise Up element and paste it here.",
                            "required": True,
                        },
                    ),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [[("fru_element_type", 30), ("fru_element_embed_code", 31)]],
                        {"group": "Engagement & Buttons"},
                    ),
                    33: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Section heading for this grid", "max_length": 100, "required": True},
                    ),
                    34: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("orange", "Orange"), ("black", "Black")],
                            "help_text": "Color applied to all icons in this grid",
                        },
                    ),
                    35: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("1", "1 column"), ("2", "2 columns"), ("3", "3 columns")],
                            "help_text": "Number of columns on desktop (automatically stacks on mobile)",
                            "label": "Number of columns for this grid",
                        },
                    ),
                    36: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("compact", "Compact (icons + titles only)"),
                                ("detailed", "Detailed (icons + titles + descriptions)"),
                            ],
                            "help_text": "Choose content density. Compact hides descriptions, Detailed shows them.",
                            "label": "Layout style",
                        },
                    ),
                    37: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("chat", "Chat icon"),
                                ("eye-open", "Eye Open icon"),
                                ("gear", "Gear icon"),
                                ("globe", "Globe icon"),
                                ("megaphone", "Megaphone icon"),
                                ("star", "Star icon"),
                            ],
                            "help_text": "Select an icon for this item",
                        },
                    ),
                    38: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title for this item", "max_length": 100, "required": True},
                    ),
                    39: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional description (max 126 characters)",
                            "max_length": 126,
                            "required": False,
                        },
                    ),
                    40: ("wagtail.blocks.StructBlock", [[("icon", 37), ("title", 38), ("description", 39)]], {}),
                    41: ("wagtail.blocks.ListBlock", (40,), {"help_text": "Add icon info items", "min_num": 1}),
                    42: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 33), ("icon_color", 34), ("columns", 35), ("layout_style", 36), ("items", 41)]],
                        {"group": "Card Collections"},
                    ),
                    43: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Please note that only URLs from allow-listed domains will work."},
                    ),
                    44: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Optional integer pixel value for custom iFrame height", "required": False},
                    ),
                    45: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("normal", "Normal"), ("full_width", "Full Width")]},
                    ),
                    46: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": 'Checking this will add "scrolling=no" to the iframe. Use this if your iframe is rendering an unnecessary scroll bar or whitespace below it.',
                            "required": False,
                        },
                    ),
                    47: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 43), ("height", 44), ("iframe_width", 45), ("disable_scroll", 46)]],
                        {"group": "Media & Embeds"},
                    ),
                    48: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title/caption for this image", "required": False},
                    ),
                    49: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("portrait", "Portrait"), ("landscape", "Landscape"), ("square", "Square")],
                            "help_text": "Select the orientation of this image",
                        },
                    ),
                    50: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 48), ("image", 8), ("orientation", 49)]],
                        {"group": "Media & Embeds"},
                    ),
                    51: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional title for the carousel container.", "required": False},
                    ),
                    52: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("portrait", "Portrait"), ("landscape", "Landscape")],
                            "help_text": "Select the orientation for carousel items.",
                            "label": "Orientation",
                        },
                    ),
                    53: ("wagtail.images.blocks.ImageBlock", [], {"help_text": "Select an image for this item."}),
                    54: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional header text shown above the image item.",
                            "max_length": 80,
                            "required": False,
                        },
                    ),
                    55: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional title for the image item (e.g. speaker name or event title).",
                            "max_length": 120,
                            "required": False,
                        },
                    ),
                    56: (
                        "foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock",
                        (),
                        {
                            "help_text": "Optional rich text description for the image item.",
                            "label": "Description",
                            "required": False,
                        },
                    ),
                    57: (
                        "foundation_cms.blocks.link_block.OptionalLinkBlock",
                        (),
                        {"help_text": "Optional link for this item.", "label": "Link", "required": False},
                    ),
                    58: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 53), ("header", 54), ("title", 55), ("description", 56), ("link", 57)]],
                        {},
                    ),
                    59: (
                        "wagtail.blocks.StreamBlock",
                        [[("carousel_item", 58)]],
                        {"help_text": "Items to display in the carousel. Maximum of 10 items.", "max_num": 10},
                    ),
                    60: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 51), ("orientation", 52), ("items", 59)]],
                        {"group": "Card Collections"},
                    ),
                    61: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional heading for this section", "max_length": 100, "required": False},
                    ),
                    62: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("portrait", "Portrait (2:3)"),
                                ("landscape", "Landscape (3:2)"),
                                ("square", "Square (1:1)"),
                            ],
                            "help_text": "Orientation for all images in this section",
                            "label": "Image grid section orientation",
                        },
                    ),
                    63: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("4", "4 per row"), ("5", "5 per row"), ("6", "6 per row")],
                            "label": "Items per section row",
                        },
                    ),
                    64: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["h5", "h6", "large", "bold", "italic"],
                            "help_text": "Optional caption for this image",
                            "required": False,
                        },
                    ),
                    65: (
                        "foundation_cms.blocks.link_block.OptionalLinkBlock",
                        (),
                        {"help_text": "Optional link for both image and caption", "required": False},
                    ),
                    66: ("wagtail.blocks.StructBlock", [[("image", 8), ("caption", 64), ("link", 65)]], {}),
                    67: ("wagtail.blocks.ListBlock", (66,), {"min_num": 1}),
                    68: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 61), ("section_orientation", 62), ("items_per_row", 63), ("items", 67)]],
                        {},
                    ),
                    69: ("wagtail.blocks.ListBlock", (68,), {"label": "Image grid sections", "min_num": 1}),
                    70: ("wagtail.blocks.StructBlock", [[("sections", 69)]], {"group": "Card Collections"}),
                    71: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The full value to animate, including any symbols, commas, decimals, or suffixes (e.g., $5.2M).",
                            "max_length": 5,
                            "required": True,
                        },
                    ),
                    72: ("wagtail.blocks.CharBlock", (), {"help_text": "Heading of the stat", "required": True}),
                    73: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Short description of the stat", "required": False},
                    ),
                    74: (
                        "wagtail.blocks.StructBlock",
                        [[("stat_number", 71), ("stat_heading", 72), ("stat_description", 73)]],
                        {},
                    ),
                    75: (
                        "wagtail.blocks.ListBlock",
                        (74,),
                        {
                            "default": [
                                {"stat_description": "", "stat_heading": "", "stat_number": ""},
                                {"stat_description": "", "stat_heading": "", "stat_number": ""},
                                {"stat_description": "", "stat_heading": "", "stat_number": ""},
                            ],
                            "help_text": "Add exactly 3 stats to appear in the Impact Numbers section",
                            "label": "Impact Stats",
                            "max_num": 3,
                            "min_num": 3,
                        },
                    ),
                    76: ("wagtail.blocks.StructBlock", [[("stats", 75)]], {"group": "Data Display"}),
                    77: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 16),
                                ("link_to", 17),
                                ("page", 18),
                                ("external_url", 19),
                                ("relative_url", 20),
                                ("anchor", 21),
                                ("email", 22),
                                ("file", 23),
                                ("phone", 24),
                                ("new_window", 25),
                                ("style", 26),
                                ("alignment", 27),
                            ]
                        ],
                        {"group": "Engagement & Buttons"},
                    ),
                    78: ("wagtail.blocks.CharBlock", (), {"help_text": "Heading displayed above the list"}),
                    79: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Description displayed above the list", "required": False},
                    ),
                    80: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 16),
                                ("link_to", 17),
                                ("page", 18),
                                ("external_url", 19),
                                ("relative_url", 20),
                                ("anchor", 21),
                                ("email", 22),
                                ("file", 23),
                                ("phone", 24),
                                ("new_window", 25),
                            ]
                        ],
                        {},
                    ),
                    81: ("wagtail.blocks.ListBlock", (80,), {"max_num": 4, "min_num": 1}),
                    82: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 78), ("description", 79), ("items", 81)]],
                        {"group": "Data Display"},
                    ),
                    83: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("snippets.NewsletterSignup",),
                        {"max_num": 1},
                    ),
                    84: (
                        "wagtail.blocks.StructBlock",
                        [[("newsletter_signup", 83)]],
                        {"group": "Engagement & Buttons"},
                    ),
                    85: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("snippets.NewsletterUnsubscribe",),
                        {"max_num": 1},
                    ),
                    86: (
                        "wagtail.blocks.StructBlock",
                        [[("newsletter_unsubscribe", 85)]],
                        {"group": "Engagement & Buttons"},
                    ),
                    87: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Appears as the main heading.", "label": "Headline", "required": False},
                    ),
                    88: (
                        "foundation_cms.blocks.link_block.OptionalLinkBlock",
                        (),
                        {
                            "help_text": "Optional link for the card.",
                            "label": "Call to Action Link",
                            "required": False,
                        },
                    ),
                    89: ("wagtail.blocks.StructBlock", [[("headline", 87), ("cta_link", 88)]], {}),
                    90: (
                        "wagtail.blocks.ListBlock",
                        (89,),
                        {
                            "default": [
                                {"cta_link": [], "headline": ""},
                                {"cta_link": [], "headline": ""},
                                {"cta_link": [], "headline": ""},
                            ],
                            "help_text": "3 cards required.",
                            "label": "Pillar Cards",
                            "max_num": 3,
                            "min_num": 3,
                        },
                    ),
                    91: ("wagtail.blocks.StructBlock", [[("cards", 90)]], {"group": "Card Collections"}),
                    92: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Title of the podcast. <strong>Note:</strong> Does not render on "NothingPersonal" pages.'
                        },
                    ),
                    93: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": 'Optional short description of the podcast. <strong>Note:</strong> Does not render on "NothingPersonal" pages.',
                            "required": False,
                        },
                    ),
                    94: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 92), ("description", 93), ("simplecast_embed_code", 16)]],
                        {"group": "Media & Embeds"},
                    ),
                    95: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Appears above the headline.", "label": "Label", "required": False},
                    ),
                    96: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Optional Image for the card", "label": "Image"},
                    ),
                    97: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 16),
                                ("link_to", 17),
                                ("page", 18),
                                ("external_url", 19),
                                ("relative_url", 20),
                                ("anchor", 21),
                                ("email", 22),
                                ("file", 23),
                                ("phone", 24),
                                ("new_window", 25),
                            ]
                        ],
                        {"help_text": "Link for the card.", "label": "Call to Action Link", "required": True},
                    ),
                    98: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 95), ("headline", 87), ("image", 96), ("cta_link", 97)]],
                        {},
                    ),
                    99: (
                        "wagtail.blocks.ListBlock",
                        (98,),
                        {
                            "help_text": "Minimum of 3 cards required. More than 3 will turn element into a carousel.",
                            "label": "Portrait Cards",
                            "min_num": 3,
                        },
                    ),
                    100: ("wagtail.blocks.StructBlock", [[("cards", 99)]], {"group": "Card Collections"}),
                    101: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    102: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    103: ("wagtail.blocks.StructBlock", [[("quote", 101), ("attribution", 102)]], {"group": "Text"}),
                    104: ("foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock", (), {"group": "Text"}),
                    105: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("small", "Small"),
                                ("medium", "Medium"),
                                ("large", "Large"),
                                ("xlarge", "Extra Large"),
                            ],
                            "help_text": "Select the size of the spacer",
                        },
                    ),
                    106: ("wagtail.blocks.StructBlock", [[("size", 105)]], {"group": "Layout"}),
                    107: ("wagtail.blocks.CharBlock", (), {"label": "Name", "max_length": 50, "required": True}),
                    108: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Image should follow a 1:1 aspect ratio.", "label": "Image"},
                    ),
                    109: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 101), ("name", 107), ("description", 14), ("image", 108)]],
                        {},
                    ),
                    110: (
                        "wagtail.blocks.ListBlock",
                        (109,),
                        {"help_text": "3 cards required.", "label": "Spotlight Cards", "max_num": 3, "min_num": 3},
                    ),
                    111: ("wagtail.blocks.StructBlock", [[("cards", 110)]], {"group": "Card Collections"}),
                    112: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title shown on the tab button", "required": True},
                    ),
                    113: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Subtitle shown under the title on the tab", "required": False},
                    ),
                    114: ("foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock", (), {"required": False}),
                    115: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 48), ("image", 8), ("orientation", 49)]],
                        {"required": False},
                    ),
                    116: ("foundation_cms.blocks.link_block.OptionalLinkBlock", (), {"required": False}),
                    117: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 102), ("subtitle", 102), ("text", 114), ("image", 115), ("link", 116)]],
                        {},
                    ),
                    118: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 16), ("image", 8), ("subtitle", 16), ("link", 116)]],
                        {},
                    ),
                    119: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 1), ("text_image", 117), ("tab_card_set", 118)]],
                        {"help_text": "Add one or more content blocks to the tab.", "min_num": 1, "required": True},
                    ),
                    120: ("wagtail.blocks.StructBlock", [[("title", 112), ("subtitle", 113), ("content", 119)]], {}),
                    121: ("wagtail.blocks.ListBlock", (120,), {"label": "Tabs", "max_num": 8, "min_num": 1}),
                    122: ("wagtail.blocks.StructBlock", [[("tabs", 121)]], {"group": "Card Collections"}),
                    123: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional category for the card", "required": False},
                    ),
                    124: ("wagtail.blocks.CharBlock", (), {"help_text": "Title for the card", "required": True}),
                    125: (
                        "foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock",
                        (),
                        {"help_text": "Optional description text", "required": False},
                    ),
                    126: (
                        "wagtail.blocks.StructBlock",
                        [[("category", 123), ("title", 124), ("text", 125), ("image", 8), ("link", 80)]],
                        {},
                    ),
                    127: (
                        "wagtail.blocks.StreamBlock",
                        [[("card", 126)]],
                        {"help_text": "Add between 1 and 3 cards.", "max_num": 3, "min_num": 1},
                    ),
                    128: ("wagtail.blocks.StructBlock", [[("cards", 127)]], {"group": "Card Collections"}),
                    129: ("wagtail.blocks.CharBlock", (), {"help_text": "Title for the block", "required": True}),
                    130: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("shape", "Shape"), ("loop-line", "Loop Line")],
                            "help_text": "Select the style of the title",
                        },
                    ),
                    131: ("wagtail.blocks.StructBlock", [[("title", 129), ("style", 130)]], {"group": "Text"}),
                    132: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("white", "White"),
                                ("neutral-100", "Grey 100"),
                                ("neutral-200", "Grey 200"),
                                ("neutral-300", "Grey 300"),
                                ("blue-100", "Blue 100"),
                                ("blue-200", "Blue 200"),
                                ("blue-300", "Blue 300"),
                                ("green-100", "Green 100"),
                                ("green-200", "Green 200"),
                                ("green-300", "Green 300"),
                                ("orange-100", "Orange 100"),
                                ("orange-200", "Orange 200"),
                                ("orange-300", "Orange 300"),
                                ("yellow-100", "Yellow 100"),
                                ("yellow-200", "Yellow 200"),
                                ("yellow-300", "Yellow 300"),
                            ]
                        },
                    ),
                    133: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("top", "Top"), ("middle", "Middle"), ("bottom", "Bottom")],
                            "help_text": "Vertical alignment of the columns content",
                        },
                    ),
                    134: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 92), ("description", 93), ("simplecast_embed_code", 16)]],
                        {},
                    ),
                    135: ("wagtail.blocks.StructBlock", [[("title", 48), ("image", 8), ("orientation", 49)]], {}),
                    136: ("wagtail.blocks.StructBlock", [[("newsletter_signup", 83)]], {}),
                    137: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Log into Vimeo, select your desired video, and click 'Copy Link'",
                            "label": "Vimeo Video URL",
                            "required": True,
                        },
                    ),
                    138: ("wagtail.blocks.CharBlock", (), {"help_text": "Optional Caption Text", "required": False}),
                    139: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_to", 17),
                                ("page", 18),
                                ("external_url", 19),
                                ("relative_url", 20),
                                ("anchor", 21),
                                ("email", 22),
                                ("file", 23),
                                ("phone", 24),
                                ("new_window", 25),
                            ]
                        ],
                        {},
                    ),
                    140: (
                        "wagtail.blocks.ListBlock",
                        (139,),
                        {
                            "default": [],
                            "help_text": "Optional URL that this caption should link out to.",
                            "max_num": 1,
                            "min_num": 0,
                        },
                    ),
                    141: (
                        "wagtail.blocks.StructBlock",
                        [[("video_url", 137), ("caption", 138), ("caption_url", 140)]],
                        {},
                    ),
                    142: ("wagtail.blocks.StructBlock", [[("title", 78), ("description", 79), ("items", 81)]], {}),
                    143: ("wagtail.blocks.StructBlock", [[("size", 105)]], {}),
                    144: ("wagtail.blocks.StructBlock", [[("quote", 101), ("attribution", 102)]], {}),
                    145: ("wagtail.blocks.StructBlock", [[("title", 102), ("text", 114)]], {}),
                    146: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 16),
                                ("link_to", 17),
                                ("page", 18),
                                ("external_url", 19),
                                ("relative_url", 20),
                                ("anchor", 21),
                                ("email", 22),
                                ("file", 23),
                                ("phone", 24),
                                ("new_window", 25),
                                ("style", 26),
                                ("alignment", 27),
                            ]
                        ],
                        {},
                    ),
                    147: (
                        "wagtail.blocks.StructBlock",
                        [[("fru_element_type", 30), ("fru_element_embed_code", 31)]],
                        {},
                    ),
                    148: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 1),
                                ("podcast", 134),
                                ("image", 135),
                                ("newsletter_signup", 136),
                                ("video", 141),
                                ("list", 142),
                                ("spacer", 143),
                                ("quote", 144),
                                ("text_social", 145),
                                ("link_button", 146),
                                ("fru_element", 147),
                            ]
                        ],
                        {"label": "Left Column", "required": False},
                    ),
                    149: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 1),
                                ("podcast", 134),
                                ("image", 135),
                                ("newsletter_signup", 136),
                                ("video", 141),
                                ("list", 142),
                                ("spacer", 143),
                                ("quote", 144),
                                ("text_social", 145),
                                ("link_button", 146),
                                ("fru_element", 147),
                            ]
                        ],
                        {"label": "Right Column", "required": False},
                    ),
                    150: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 132),
                                ("vertical_alignment", 133),
                                ("left_column", 148),
                                ("right_column", 149),
                            ]
                        ],
                        {"group": "Layout"},
                    ),
                    151: (
                        "wagtail.blocks.StructBlock",
                        [[("video_url", 137), ("caption", 138), ("caption_url", 140)]],
                        {"group": "Media & Embeds"},
                    ),
                },
            ),
        ),
    ]
