# Generated by Django 4.2.29 on 2026-04-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0074_remove_generalpage_button_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generalpage",
            name="hero_image_rounded_corners",
        ),
        migrations.AddField(
            model_name="generalpage",
            name="displayed_hero_content",
            field=models.CharField(
                choices=[("image", "Image"), ("video", "Video")],
                default="image",
                max_length=25,
                verbose_name="Select media type from dropdown",
            ),
        ),
        migrations.AddField(
            model_name="generalpage",
            name="hero_media_rounded_corners",
            field=models.BooleanField(
                default=True,
                help_text="By default, rounded corners are applied (top-right corner for 'Side by Side', both top corners for 'Top to Bottom'). Uncheck to remove rounded corners.",
                verbose_name="Hero Media Rounded Corners",
            ),
        ),
        migrations.AddField(
            model_name="generalpage",
            name="hero_video_url",
            field=models.CharField(
                blank=True,
                help_text="Log into Vimeo using 1Password and upload the desired video. Then select the video and click '...', 'Video File Links', and select '(mp4, 1920 x 1080)'. Copy and paste the link here.",
                max_length=500,
            ),
        ),
    ]
