# Generated by Django 5.2.15 on 2026-07-13 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0085_fix_displayed_hero_content"),
        ("navigation", "0002_horizontallinkblock"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalpage",
            name="horizontal_link_block",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional. Displays navigation links below the hero. If not set, inherits from the nearest ancestor General Page.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="navigation.horizontallinkblock",
                verbose_name="Horizontal Link Block",
            ),
        ),
    ]
