# Generated by Django 5.2.15 on 2026-07-29 21:35

import wagtail.fields
from django.db import migrations

import foundation_cms.legacy_apps.wagtailpages.validators
import foundation_cms.validators


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0086_generalpage_horizontal_link_block"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("accordion_block", 5),
                    ("custom_media", 11),
                    ("divider", 12),
                    ("donor_help_contact_us_form", 15),
                    ("featured_card_block", 32),
                    ("fru_element_block", 35),
                    ("icon_info_grid", 45),
                    ("iframe_block", 50),
                    ("illustrated_newsletter_signup", 52),
                    ("image", 55),
                    ("image_carousel_block", 65),
                    ("image_grid", 75),
                    ("impact_numbers", 81),
                    ("link_button_block", 82),
                    ("list_block", 87),
                    ("newsletter_signup", 89),
                    ("newsletter_unsubscribe", 91),
                    ("pillar_card_set", 96),
                    ("podcast_block", 99),
                    ("portrait_card_set_block", 105),
                    ("quote", 108),
                    ("rich_text", 109),
                    ("spacer_block", 111),
                    ("spotlight_card_set_block", 116),
                    ("tabbed_content", 127),
                    ("three_column_container_block", 149),
                    ("timely_activations_cards", 155),
                    ("title_block", 158),
                    ("two_column_container_block", 162),
                    ("video_block", 163),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Heading for the Accordion Item", "required": True},
                    ),
                    1: ("foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock", (), {}),
                    2: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 1)]],
                        {"required": False, "use_json_field": True},
                    ),
                    3: ("wagtail.blocks.StructBlock", [[("title", 0), ("content", 2)]], {}),
                    4: ("wagtail.blocks.ListBlock", (3,), {"min_num": 1}),
                    5: ("wagtail.blocks.StructBlock", [[("accordion_items", 4)]], {"group": "Text"}),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title/caption for this media", "required": False},
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("image", "Image"), ("video", "Video")],
                            "help_text": "Select the type of media to display",
                        },
                    ),
                    8: ("wagtail.images.blocks.ImageBlock", [], {}),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Log into Vimeo using 1Password and upload the desired video. Then select the video and click "...", "Video File Links", and select "(mp4, 1920 x 1080)". Copy and paste the link here.',
                            "max_length": 500,
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("portrait", "Portrait"),
                                ("landscape", "Landscape"),
                                ("square", "Square"),
                                ("widescreen", "Widescreen 16:9 (12 columns wide)"),
                            ],
                            "help_text": "Select the orientation of this media",
                        },
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 6), ("content", 7), ("image", 8), ("video_url", 9), ("orientation", 10)]],
                        {"group": "Media & Embeds"},
                    ),
                    12: ("wagtail.blocks.StructBlock", [[]], {"group": "Layout"}),
                    13: ("wagtail.blocks.CharBlock", (), {"default": "Contact Us", "required": True}),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Questions about your donation? Get in touch with our team by using the form below.",
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 13), ("subheading", 14), ("image", 8)]],
                        {"group": "Engagement & Buttons"},
                    ),
                    16: ("wagtail.blocks.CharBlock", (), {"label": "Heading", "max_length": 50, "required": True}),
                    17: (
                        "foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock",
                        (),
                        {"features": ["bold", "italic"], "label": "Description", "max_length": 500, "required": True},
                    ),
                    18: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Image for the card", "label": "Image"},
                    ),
                    19: ("wagtail.blocks.CharBlock", (), {}),
                    20: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("external_url", "External URL"),
                                ("relative_url", "Relative URL"),
                                ("email", "Email"),
                                ("anchor", "Anchor"),
                                ("file", "File"),
                                ("phone", "Phone"),
                            ],
                            "label": "Link to",
                        },
                    ),
                    21: ("wagtail.blocks.PageChooserBlock", (), {"label": "Page", "required": False}),
                    22: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Enter a full URL including http:// or https://",
                            "label": "External URL",
                            "max_length": 300,
                            "required": False,
                        },
                    ),
                    23: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'A path relative to this domain. For example, "/foo/bar" or "?foo=bar".',
                            "label": "Relative URL",
                            "max_length": 300,
                            "required": False,
                            "validators": [foundation_cms.legacy_apps.wagtailpages.validators.RelativeURLValidator()],
                        },
                    ),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'An id attribute of an element on the current page. For example, "#section-1"',
                            "label": "#",
                            "max_length": 300,
                            "required": False,
                            "validators": [foundation_cms.validators.AnchorLinkValidator()],
                        },
                    ),
                    25: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    26: ("wagtail.documents.blocks.DocumentChooserBlock", (), {"label": "File", "required": False}),
                    27: ("wagtail.blocks.CharBlock", (), {"label": "Phone", "max_length": 30, "required": False}),
                    28: ("wagtail.blocks.BooleanBlock", (), {"label": "Open in new window", "required": False}),
                    29: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("btn-primary", "Primary"), ("btn-secondary", "Secondary")]},
                    ),
                    30: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("link-button-block--left", "Left"), ("link-button-block--center", "Center")]},
                    ),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 19),
                                ("link_to", 20),
                                ("page", 21),
                                ("external_url", 22),
                                ("relative_url", 23),
                                ("anchor", 24),
                                ("email", 25),
                                ("file", 26),
                                ("phone", 27),
                                ("new_window", 28),
                                ("style", 29),
                                ("alignment", 30),
                            ]
                        ],
                        {"help_text": "Link button for the card.", "label": "Button", "required": False},
                    ),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 16), ("description", 17), ("image", 18), ("button", 31)]],
                        {"group": "Card Collections"},
                    ),
                    33: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("donation-form", "Donation Form"),
                                ("donor-map", "Donor Map"),
                                ("top-locations", "Top Locations"),
                                ("donation-levels", "Donation Levels"),
                                ("donate-button", "Donate Button"),
                            ],
                            "help_text": "Select the type of Fundraise Up element.",
                        },
                    ),
                    34: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Copy the HTML code generated by the desired Fundraise Up element and paste it here.",
                            "required": True,
                        },
                    ),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [[("fru_element_type", 33), ("fru_element_embed_code", 34)]],
                        {"group": "Engagement & Buttons"},
                    ),
                    36: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Section heading for this grid", "max_length": 100, "required": True},
                    ),
                    37: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("orange", "Orange"), ("black", "Black")],
                            "help_text": "Color applied to all icons in this grid",
                        },
                    ),
                    38: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("1", "1 column"), ("2", "2 columns"), ("3", "3 columns")],
                            "help_text": "Number of columns on desktop (automatically stacks on mobile)",
                            "label": "Number of columns for this grid",
                        },
                    ),
                    39: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("compact", "Compact (icons + titles only)"),
                                ("detailed", "Detailed (icons + titles + descriptions)"),
                            ],
                            "help_text": "Choose content density. Compact hides descriptions, Detailed shows them.",
                            "label": "Layout style",
                        },
                    ),
                    40: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("chat", "Chat icon"),
                                ("eye-open", "Eye Open icon"),
                                ("gear", "Gear icon"),
                                ("globe", "Globe icon"),
                                ("megaphone", "Megaphone icon"),
                                ("star", "Star icon"),
                            ],
                            "help_text": "Select an icon for this item",
                        },
                    ),
                    41: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title for this item", "max_length": 100, "required": True},
                    ),
                    42: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional description (max 126 characters)",
                            "max_length": 126,
                            "required": False,
                        },
                    ),
                    43: ("wagtail.blocks.StructBlock", [[("icon", 40), ("title", 41), ("description", 42)]], {}),
                    44: ("wagtail.blocks.ListBlock", (43,), {"help_text": "Add icon info items", "min_num": 1}),
                    45: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 36), ("icon_color", 37), ("columns", 38), ("layout_style", 39), ("items", 44)]],
                        {"group": "Card Collections"},
                    ),
                    46: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Please note that only URLs from allow-listed domains will work."},
                    ),
                    47: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Optional integer pixel value for custom iFrame height", "required": False},
                    ),
                    48: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("normal", "Normal"), ("full_width", "Full Width")]},
                    ),
                    49: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": 'Checking this will add "scrolling=no" to the iframe. Use this if your iframe is rendering an unnecessary scroll bar or whitespace below it.',
                            "required": False,
                        },
                    ),
                    50: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 46), ("height", 47), ("iframe_width", 48), ("disable_scroll", 49)]],
                        {"group": "Media & Embeds"},
                    ),
                    51: ("wagtail.snippets.blocks.SnippetChooserBlock", ("snippets.IllustratedNewsletterSignup",), {}),
                    52: (
                        "wagtail.blocks.StructBlock",
                        [[("newsletter_signup", 51)]],
                        {"group": "Engagement & Buttons"},
                    ),
                    53: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title/caption for this image", "required": False},
                    ),
                    54: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("portrait", "Portrait"), ("landscape", "Landscape"), ("square", "Square")],
                            "help_text": "Select the orientation of this image",
                        },
                    ),
                    55: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 53), ("image", 8), ("orientation", 54)]],
                        {"group": "Media & Embeds"},
                    ),
                    56: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional title for the carousel container.", "required": False},
                    ),
                    57: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("portrait", "Portrait"), ("landscape", "Landscape")],
                            "help_text": "Select the orientation for carousel items.",
                            "label": "Orientation",
                        },
                    ),
                    58: ("wagtail.images.blocks.ImageBlock", [], {"help_text": "Select an image for this item."}),
                    59: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional header text shown above the image item.",
                            "max_length": 80,
                            "required": False,
                        },
                    ),
                    60: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional title for the image item (e.g. speaker name or event title).",
                            "max_length": 120,
                            "required": False,
                        },
                    ),
                    61: (
                        "foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock",
                        (),
                        {
                            "help_text": "Optional rich text description for the image item.",
                            "label": "Description",
                            "required": False,
                        },
                    ),
                    62: (
                        "foundation_cms.blocks.link_block.OptionalLinkBlock",
                        (),
                        {"help_text": "Optional link for this item.", "label": "Link", "required": False},
                    ),
                    63: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 58), ("header", 59), ("title", 60), ("description", 61), ("link", 62)]],
                        {},
                    ),
                    64: (
                        "wagtail.blocks.StreamBlock",
                        [[("carousel_item", 63)]],
                        {"help_text": "Items to display in the carousel. Maximum of 10 items.", "max_num": 10},
                    ),
                    65: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 56), ("orientation", 57), ("items", 64)]],
                        {"group": "Card Collections"},
                    ),
                    66: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional heading for this section", "max_length": 100, "required": False},
                    ),
                    67: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("portrait", "Portrait (2:3)"),
                                ("landscape", "Landscape (3:2)"),
                                ("square", "Square (1:1)"),
                            ],
                            "help_text": "Orientation for all images in this section",
                            "label": "Image grid section orientation",
                        },
                    ),
                    68: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("4", "4 per row"), ("5", "5 per row"), ("6", "6 per row")],
                            "label": "Items per section row",
                        },
                    ),
                    69: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["h5", "h6", "large", "bold", "italic"],
                            "help_text": "Optional caption for this image",
                            "required": False,
                        },
                    ),
                    70: (
                        "foundation_cms.blocks.link_block.OptionalLinkBlock",
                        (),
                        {"help_text": "Optional link for both image and caption", "required": False},
                    ),
                    71: ("wagtail.blocks.StructBlock", [[("image", 8), ("caption", 69), ("link", 70)]], {}),
                    72: ("wagtail.blocks.ListBlock", (71,), {"min_num": 1}),
                    73: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 66), ("section_orientation", 67), ("items_per_row", 68), ("items", 72)]],
                        {},
                    ),
                    74: ("wagtail.blocks.ListBlock", (73,), {"label": "Image grid sections", "min_num": 1}),
                    75: ("wagtail.blocks.StructBlock", [[("sections", 74)]], {"group": "Card Collections"}),
                    76: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The full value to animate, including any symbols, commas, decimals, or suffixes (e.g., $5.2M).",
                            "max_length": 5,
                            "required": True,
                        },
                    ),
                    77: ("wagtail.blocks.CharBlock", (), {"help_text": "Heading of the stat", "required": True}),
                    78: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Short description of the stat", "required": False},
                    ),
                    79: (
                        "wagtail.blocks.StructBlock",
                        [[("stat_number", 76), ("stat_heading", 77), ("stat_description", 78)]],
                        {},
                    ),
                    80: (
                        "wagtail.blocks.ListBlock",
                        (79,),
                        {
                            "default": [
                                {"stat_description": "", "stat_heading": "", "stat_number": ""},
                                {"stat_description": "", "stat_heading": "", "stat_number": ""},
                                {"stat_description": "", "stat_heading": "", "stat_number": ""},
                            ],
                            "help_text": "Add exactly 3 stats to appear in the Impact Numbers section",
                            "label": "Impact Stats",
                            "max_num": 3,
                            "min_num": 3,
                        },
                    ),
                    81: ("wagtail.blocks.StructBlock", [[("stats", 80)]], {"group": "Data Display"}),
                    82: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 19),
                                ("link_to", 20),
                                ("page", 21),
                                ("external_url", 22),
                                ("relative_url", 23),
                                ("anchor", 24),
                                ("email", 25),
                                ("file", 26),
                                ("phone", 27),
                                ("new_window", 28),
                                ("style", 29),
                                ("alignment", 30),
                            ]
                        ],
                        {"group": "Engagement & Buttons"},
                    ),
                    83: ("wagtail.blocks.CharBlock", (), {"help_text": "Heading displayed above the list"}),
                    84: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Description displayed above the list", "required": False},
                    ),
                    85: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 19),
                                ("link_to", 20),
                                ("page", 21),
                                ("external_url", 22),
                                ("relative_url", 23),
                                ("anchor", 24),
                                ("email", 25),
                                ("file", 26),
                                ("phone", 27),
                                ("new_window", 28),
                            ]
                        ],
                        {},
                    ),
                    86: ("wagtail.blocks.ListBlock", (85,), {"max_num": 4, "min_num": 1}),
                    87: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 83), ("description", 84), ("items", 86)]],
                        {"group": "Data Display"},
                    ),
                    88: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("snippets.NewsletterSignup",),
                        {"max_num": 1},
                    ),
                    89: (
                        "wagtail.blocks.StructBlock",
                        [[("newsletter_signup", 88)]],
                        {"group": "Engagement & Buttons"},
                    ),
                    90: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("snippets.NewsletterUnsubscribe",),
                        {"max_num": 1},
                    ),
                    91: (
                        "wagtail.blocks.StructBlock",
                        [[("newsletter_unsubscribe", 90)]],
                        {"group": "Engagement & Buttons"},
                    ),
                    92: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Appears as the main heading.", "label": "Headline", "required": False},
                    ),
                    93: (
                        "foundation_cms.blocks.link_block.OptionalLinkBlock",
                        (),
                        {
                            "help_text": "Optional link for the card.",
                            "label": "Call to Action Link",
                            "required": False,
                        },
                    ),
                    94: ("wagtail.blocks.StructBlock", [[("headline", 92), ("cta_link", 93)]], {}),
                    95: (
                        "wagtail.blocks.ListBlock",
                        (94,),
                        {
                            "default": [
                                {"cta_link": [], "headline": ""},
                                {"cta_link": [], "headline": ""},
                                {"cta_link": [], "headline": ""},
                            ],
                            "help_text": "3 cards required.",
                            "label": "Pillar Cards",
                            "max_num": 3,
                            "min_num": 3,
                        },
                    ),
                    96: ("wagtail.blocks.StructBlock", [[("cards", 95)]], {"group": "Card Collections"}),
                    97: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Title of the podcast. <strong>Note:</strong> Does not render on "NothingPersonal" pages.'
                        },
                    ),
                    98: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": 'Optional short description of the podcast. <strong>Note:</strong> Does not render on "NothingPersonal" pages.',
                            "required": False,
                        },
                    ),
                    99: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 97), ("description", 98), ("simplecast_embed_code", 19)]],
                        {"group": "Media & Embeds"},
                    ),
                    100: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Appears above the headline.", "label": "Label", "required": False},
                    ),
                    101: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Optional Image for the card", "label": "Image"},
                    ),
                    102: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 19),
                                ("link_to", 20),
                                ("page", 21),
                                ("external_url", 22),
                                ("relative_url", 23),
                                ("anchor", 24),
                                ("email", 25),
                                ("file", 26),
                                ("phone", 27),
                                ("new_window", 28),
                            ]
                        ],
                        {"help_text": "Link for the card.", "label": "Call to Action Link", "required": True},
                    ),
                    103: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 100), ("headline", 92), ("image", 101), ("cta_link", 102)]],
                        {},
                    ),
                    104: (
                        "wagtail.blocks.ListBlock",
                        (103,),
                        {
                            "help_text": "Minimum of 3 cards required. More than 3 will turn element into a carousel.",
                            "label": "Portrait Cards",
                            "min_num": 3,
                        },
                    ),
                    105: ("wagtail.blocks.StructBlock", [[("cards", 104)]], {"group": "Card Collections"}),
                    106: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    107: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    108: ("wagtail.blocks.StructBlock", [[("quote", 106), ("attribution", 107)]], {"group": "Text"}),
                    109: ("foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock", (), {"group": "Text"}),
                    110: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("small", "Small"),
                                ("medium", "Medium"),
                                ("large", "Large"),
                                ("xlarge", "Extra Large"),
                            ],
                            "help_text": "Select the size of the spacer",
                        },
                    ),
                    111: ("wagtail.blocks.StructBlock", [[("size", 110)]], {"group": "Layout"}),
                    112: ("wagtail.blocks.CharBlock", (), {"label": "Name", "max_length": 50, "required": True}),
                    113: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Image should follow a 1:1 aspect ratio.", "label": "Image"},
                    ),
                    114: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 106), ("name", 112), ("description", 17), ("image", 113)]],
                        {},
                    ),
                    115: (
                        "wagtail.blocks.ListBlock",
                        (114,),
                        {"help_text": "3 cards required.", "label": "Spotlight Cards", "max_num": 3, "min_num": 3},
                    ),
                    116: ("wagtail.blocks.StructBlock", [[("cards", 115)]], {"group": "Card Collections"}),
                    117: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title shown on the tab button", "required": True},
                    ),
                    118: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Subtitle shown under the title on the tab", "required": False},
                    ),
                    119: ("foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock", (), {"required": False}),
                    120: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 53), ("image", 8), ("orientation", 54)]],
                        {"required": False},
                    ),
                    121: ("foundation_cms.blocks.link_block.OptionalLinkBlock", (), {"required": False}),
                    122: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 107), ("subtitle", 107), ("text", 119), ("image", 120), ("link", 121)]],
                        {},
                    ),
                    123: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 19), ("image", 8), ("subtitle", 19), ("link", 121)]],
                        {},
                    ),
                    124: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 1), ("text_image", 122), ("tab_card_set", 123)]],
                        {"help_text": "Add one or more content blocks to the tab.", "min_num": 1, "required": True},
                    ),
                    125: ("wagtail.blocks.StructBlock", [[("title", 117), ("subtitle", 118), ("content", 124)]], {}),
                    126: ("wagtail.blocks.ListBlock", (125,), {"label": "Tabs", "max_num": 8, "min_num": 1}),
                    127: ("wagtail.blocks.StructBlock", [[("tabs", 126)]], {"group": "Card Collections"}),
                    128: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("white", "White"),
                                ("neutral-100", "Grey 100"),
                                ("neutral-200", "Grey 200"),
                                ("neutral-300", "Grey 300"),
                                ("blue-100", "Blue 100"),
                                ("blue-200", "Blue 200"),
                                ("blue-300", "Blue 300"),
                                ("green-100", "Green 100"),
                                ("green-200", "Green 200"),
                                ("green-300", "Green 300"),
                                ("orange-100", "Orange 100"),
                                ("orange-200", "Orange 200"),
                                ("orange-300", "Orange 300"),
                                ("yellow-100", "Yellow 100"),
                                ("yellow-200", "Yellow 200"),
                                ("yellow-300", "Yellow 300"),
                            ]
                        },
                    ),
                    129: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("top", "Top"), ("middle", "Middle"), ("bottom", "Bottom")],
                            "help_text": "Vertical alignment of the columns content",
                        },
                    ),
                    130: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 97), ("description", 98), ("simplecast_embed_code", 19)]],
                        {},
                    ),
                    131: ("wagtail.blocks.StructBlock", [[("title", 53), ("image", 8), ("orientation", 54)]], {}),
                    132: ("wagtail.blocks.StructBlock", [[("newsletter_signup", 88)]], {}),
                    133: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Log into Vimeo, select your desired video, and click 'Copy Link'",
                            "label": "Vimeo Video URL",
                            "required": True,
                        },
                    ),
                    134: ("wagtail.blocks.CharBlock", (), {"help_text": "Optional Caption Text", "required": False}),
                    135: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_to", 20),
                                ("page", 21),
                                ("external_url", 22),
                                ("relative_url", 23),
                                ("anchor", 24),
                                ("email", 25),
                                ("file", 26),
                                ("phone", 27),
                                ("new_window", 28),
                            ]
                        ],
                        {},
                    ),
                    136: (
                        "wagtail.blocks.ListBlock",
                        (135,),
                        {
                            "default": [],
                            "help_text": "Optional URL that this caption should link out to.",
                            "max_num": 1,
                            "min_num": 0,
                        },
                    ),
                    137: (
                        "wagtail.blocks.StructBlock",
                        [[("video_url", 133), ("caption", 134), ("caption_url", 136)]],
                        {},
                    ),
                    138: ("wagtail.blocks.StructBlock", [[("title", 83), ("description", 84), ("items", 86)]], {}),
                    139: ("wagtail.blocks.StructBlock", [[("size", 110)]], {}),
                    140: ("wagtail.blocks.StructBlock", [[("quote", 106), ("attribution", 107)]], {}),
                    141: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 19),
                                ("link_to", 20),
                                ("page", 21),
                                ("external_url", 22),
                                ("relative_url", 23),
                                ("anchor", 24),
                                ("email", 25),
                                ("file", 26),
                                ("phone", 27),
                                ("new_window", 28),
                                ("style", 29),
                                ("alignment", 30),
                            ]
                        ],
                        {},
                    ),
                    142: (
                        "wagtail.blocks.StructBlock",
                        [[("fru_element_type", 33), ("fru_element_embed_code", 34)]],
                        {},
                    ),
                    143: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Project", "page_type": ["gallery_hub.ProjectPage"], "required": True},
                    ),
                    144: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": True, "label": "Show description", "required": False},
                    ),
                    145: ("wagtail.blocks.StructBlock", [[("project", 143), ("show_description", 144)]], {}),
                    146: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 1),
                                ("podcast", 130),
                                ("image", 131),
                                ("newsletter_signup", 132),
                                ("video", 137),
                                ("list", 138),
                                ("spacer", 139),
                                ("quote", 140),
                                ("link_button", 141),
                                ("fru_element", 142),
                                ("project_block", 145),
                            ]
                        ],
                        {"label": "Left Column", "required": False},
                    ),
                    147: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 1),
                                ("podcast", 130),
                                ("image", 131),
                                ("newsletter_signup", 132),
                                ("video", 137),
                                ("list", 138),
                                ("spacer", 139),
                                ("quote", 140),
                                ("link_button", 141),
                                ("fru_element", 142),
                                ("project_block", 145),
                            ]
                        ],
                        {"label": "Center Column", "required": False},
                    ),
                    148: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 1),
                                ("podcast", 130),
                                ("image", 131),
                                ("newsletter_signup", 132),
                                ("video", 137),
                                ("list", 138),
                                ("spacer", 139),
                                ("quote", 140),
                                ("link_button", 141),
                                ("fru_element", 142),
                                ("project_block", 145),
                            ]
                        ],
                        {"label": "Right Column", "required": False},
                    ),
                    149: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 128),
                                ("vertical_alignment", 129),
                                ("left_column", 146),
                                ("center_column", 147),
                                ("right_column", 148),
                            ]
                        ],
                        {"group": "Layout"},
                    ),
                    150: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional category for the card.", "required": False},
                    ),
                    151: ("wagtail.blocks.CharBlock", (), {"help_text": "Title for the card.", "required": True}),
                    152: (
                        "foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock",
                        (),
                        {"help_text": "Optional description text.", "required": False},
                    ),
                    153: (
                        "wagtail.blocks.StructBlock",
                        [[("category", 150), ("title", 151), ("text", 152), ("image", 8), ("link", 85)]],
                        {},
                    ),
                    154: (
                        "wagtail.blocks.StreamBlock",
                        [[("card", 153)]],
                        {"help_text": "Add between 1 and 3 cards.", "max_num": 3, "min_num": 1},
                    ),
                    155: ("wagtail.blocks.StructBlock", [[("cards", 154)]], {"group": "Card Collections"}),
                    156: ("wagtail.blocks.CharBlock", (), {"help_text": "Title for the block", "required": True}),
                    157: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("shape", "Shape"), ("loop-line", "Loop Line")],
                            "help_text": "Select the style of the title",
                        },
                    ),
                    158: ("wagtail.blocks.StructBlock", [[("title", 156), ("style", 157)]], {"group": "Text"}),
                    159: ("wagtail.blocks.StructBlock", [[("title", 107), ("text", 119)]], {}),
                    160: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 1),
                                ("podcast", 130),
                                ("image", 131),
                                ("newsletter_signup", 132),
                                ("video", 137),
                                ("list", 138),
                                ("spacer", 139),
                                ("quote", 140),
                                ("text_social", 159),
                                ("link_button", 141),
                                ("fru_element", 142),
                                ("project_block", 145),
                            ]
                        ],
                        {"label": "Left Column", "required": False},
                    ),
                    161: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 1),
                                ("podcast", 130),
                                ("image", 131),
                                ("newsletter_signup", 132),
                                ("video", 137),
                                ("list", 138),
                                ("spacer", 139),
                                ("quote", 140),
                                ("text_social", 159),
                                ("link_button", 141),
                                ("fru_element", 142),
                                ("project_block", 145),
                            ]
                        ],
                        {"label": "Right Column", "required": False},
                    ),
                    162: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 128),
                                ("vertical_alignment", 129),
                                ("left_column", 160),
                                ("right_column", 161),
                            ]
                        ],
                        {"group": "Layout"},
                    ),
                    163: (
                        "wagtail.blocks.StructBlock",
                        [[("video_url", 133), ("caption", 134), ("caption_url", 136)]],
                        {"group": "Media & Embeds"},
                    ),
                },
            ),
        ),
    ]
