# Generated by Django 5.2.15 on 2026-09-08 23:00

import wagtail.fields
from django.db import migrations

import foundation_cms.legacy_apps.wagtailpages.validators
import foundation_cms.validators


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0088_generalpage_notice_banner_homepage_notice_banner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("accordion_block", 5),
                    ("custom_media", 11),
                    ("divider", 12),
                    ("donor_help_contact_us_form", 15),
                    ("featured_card_block", 32),
                    ("fru_element_block", 35),
                    ("greenhouse_board", 42),
                    ("icon_info_grid", 52),
                    ("iframe_block", 57),
                    ("illustrated_newsletter_signup", 59),
                    ("image", 62),
                    ("image_carousel_block", 72),
                    ("image_grid", 82),
                    ("impact_numbers", 88),
                    ("link_button_block", 89),
                    ("list_block", 94),
                    ("newsletter_signup", 96),
                    ("newsletter_unsubscribe", 98),
                    ("pillar_card_set", 103),
                    ("podcast_block", 106),
                    ("portrait_card_set_block", 112),
                    ("quote", 115),
                    ("rich_text", 116),
                    ("spacer_block", 118),
                    ("spotlight_card_set_block", 123),
                    ("tabbed_content", 134),
                    ("three_column_container_block", 156),
                    ("timely_activations_cards", 162),
                    ("title_block", 165),
                    ("two_column_container_block", 169),
                    ("video_block", 170),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Heading for the Accordion Item", "required": True},
                    ),
                    1: ("foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock", (), {}),
                    2: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 1)]],
                        {"required": False, "use_json_field": True},
                    ),
                    3: ("wagtail.blocks.StructBlock", [[("title", 0), ("content", 2)]], {}),
                    4: ("wagtail.blocks.ListBlock", (3,), {"min_num": 1}),
                    5: ("wagtail.blocks.StructBlock", [[("accordion_items", 4)]], {"group": "Text"}),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title/caption for this media", "required": False},
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("image", "Image"), ("video", "Video")],
                            "help_text": "Select the type of media to display",
                        },
                    ),
                    8: ("wagtail.images.blocks.ImageBlock", [], {}),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Log into Vimeo using 1Password and upload the desired video. Then select the video and click "...", "Video File Links", and select "(mp4, 1920 x 1080)". Copy and paste the link here.',
                            "max_length": 500,
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("portrait", "Portrait"),
                                ("landscape", "Landscape"),
                                ("square", "Square"),
                                ("widescreen", "Widescreen 16:9 (12 columns wide)"),
                            ],
                            "help_text": "Select the orientation of this media",
                        },
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 6), ("content", 7), ("image", 8), ("video_url", 9), ("orientation", 10)]],
                        {"group": "Media & Embeds"},
                    ),
                    12: ("wagtail.blocks.StructBlock", [[]], {"group": "Layout"}),
                    13: ("wagtail.blocks.CharBlock", (), {"default": "Contact Us", "required": True}),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Questions about your donation? Get in touch with our team by using the form below.",
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 13), ("subheading", 14), ("image", 8)]],
                        {"group": "Engagement & Buttons"},
                    ),
                    16: ("wagtail.blocks.CharBlock", (), {"label": "Heading", "max_length": 50, "required": True}),
                    17: (
                        "foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock",
                        (),
                        {"features": ["bold", "italic"], "label": "Description", "max_length": 500, "required": True},
                    ),
                    18: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Image for the card", "label": "Image"},
                    ),
                    19: ("wagtail.blocks.CharBlock", (), {}),
                    20: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("external_url", "External URL"),
                                ("relative_url", "Relative URL"),
                                ("email", "Email"),
                                ("anchor", "Anchor"),
                                ("file", "File"),
                                ("phone", "Phone"),
                            ],
                            "label": "Link to",
                        },
                    ),
                    21: ("wagtail.blocks.PageChooserBlock", (), {"label": "Page", "required": False}),
                    22: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Enter a full URL including http:// or https://",
                            "label": "External URL",
                            "max_length": 300,
                            "required": False,
                        },
                    ),
                    23: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'A path relative to this domain. For example, "/foo/bar" or "?foo=bar".',
                            "label": "Relative URL",
                            "max_length": 300,
                            "required": False,
                            "validators": [foundation_cms.legacy_apps.wagtailpages.validators.RelativeURLValidator()],
                        },
                    ),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'An id attribute of an element on the current page. For example, "#section-1"',
                            "label": "#",
                            "max_length": 300,
                            "required": False,
                            "validators": [foundation_cms.validators.AnchorLinkValidator()],
                        },
                    ),
                    25: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    26: ("wagtail.documents.blocks.DocumentChooserBlock", (), {"label": "File", "required": False}),
                    27: ("wagtail.blocks.CharBlock", (), {"label": "Phone", "max_length": 30, "required": False}),
                    28: ("wagtail.blocks.BooleanBlock", (), {"label": "Open in new window", "required": False}),
                    29: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("btn-primary", "Primary"), ("btn-secondary", "Secondary")]},
                    ),
                    30: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("link-button-block--left", "Left"), ("link-button-block--center", "Center")]},
                    ),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 19),
                                ("link_to", 20),
                                ("page", 21),
                                ("external_url", 22),
                                ("relative_url", 23),
                                ("anchor", 24),
                                ("email", 25),
                                ("file", 26),
                                ("phone", 27),
                                ("new_window", 28),
                                ("style", 29),
                                ("alignment", 30),
                            ]
                        ],
                        {"help_text": "Link button for the card.", "label": "Button", "required": False},
                    ),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 16), ("description", 17), ("image", 18), ("button", 31)]],
                        {"group": "Card Collections"},
                    ),
                    33: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("donation-form", "Donation Form"),
                                ("donor-map", "Donor Map"),
                                ("top-locations", "Top Locations"),
                                ("donation-levels", "Donation Levels"),
                                ("donate-button", "Donate Button"),
                            ],
                            "help_text": "Select the type of Fundraise Up element.",
                        },
                    ),
                    34: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Copy the HTML code generated by the desired Fundraise Up element and paste it here.",
                            "required": True,
                        },
                    ),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [[("fru_element_type", 33), ("fru_element_embed_code", 34)]],
                        {"group": "Engagement & Buttons"},
                    ),
                    36: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "No open roles right now",
                            "help_text": "Shown when the job board has no open positions.",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    37: (
                        "foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock",
                        (),
                        {
                            "default": "<p>We don't have any openings at the moment. Please check back soon.</p>",
                            "help_text": "Shown under the heading when there are no open positions.",
                            "required": False,
                        },
                    ),
                    38: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Our job board is temporarily unavailable",
                            "help_text": "Shown when the job board cannot be loaded at all.",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    39: (
                        "foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock",
                        (),
                        {
                            "default": "<p>We're having trouble loading our open roles. Please try again shortly.</p>",
                            "help_text": "Shown under the heading when the job board cannot be loaded at all.",
                            "required": False,
                        },
                    ),
                    40: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Not seeing our open roles?",
                            "help_text": "Shown under the job board, followed by the link below.",
                            "max_length": 140,
                            "required": False,
                        },
                    ),
                    41: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "View them on Greenhouse",
                            "help_text": "Label for the link to the Greenhouse-hosted board.",
                            "max_length": 60,
                            "required": False,
                        },
                    ),
                    42: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("empty_heading", 36),
                                ("empty_description", 37),
                                ("unavailable_heading", 38),
                                ("unavailable_description", 39),
                                ("hosted_board_notice", 40),
                                ("hosted_board_link_label", 41),
                            ]
                        ],
                        {"group": "Engagement & Buttons"},
                    ),
                    43: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Section heading for this grid", "max_length": 100, "required": True},
                    ),
                    44: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("orange", "Orange"), ("black", "Black")],
                            "help_text": "Color applied to all icons in this grid",
                        },
                    ),
                    45: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("1", "1 column"), ("2", "2 columns"), ("3", "3 columns")],
                            "help_text": "Number of columns on desktop (automatically stacks on mobile)",
                            "label": "Number of columns for this grid",
                        },
                    ),
                    46: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("compact", "Compact (icons + titles only)"),
                                ("detailed", "Detailed (icons + titles + descriptions)"),
                            ],
                            "help_text": "Choose content density. Compact hides descriptions, Detailed shows them.",
                            "label": "Layout style",
                        },
                    ),
                    47: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("chat", "Chat icon"),
                                ("eye-open", "Eye Open icon"),
                                ("gear", "Gear icon"),
                                ("globe", "Globe icon"),
                                ("megaphone", "Megaphone icon"),
                                ("star", "Star icon"),
                            ],
                            "help_text": "Select an icon for this item",
                        },
                    ),
                    48: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title for this item", "max_length": 100, "required": True},
                    ),
                    49: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional description (max 126 characters)",
                            "max_length": 126,
                            "required": False,
                        },
                    ),
                    50: ("wagtail.blocks.StructBlock", [[("icon", 47), ("title", 48), ("description", 49)]], {}),
                    51: ("wagtail.blocks.ListBlock", (50,), {"help_text": "Add icon info items", "min_num": 1}),
                    52: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 43), ("icon_color", 44), ("columns", 45), ("layout_style", 46), ("items", 51)]],
                        {"group": "Card Collections"},
                    ),
                    53: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Please note that only URLs from allow-listed domains will work."},
                    ),
                    54: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Optional integer pixel value for custom iFrame height", "required": False},
                    ),
                    55: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("normal", "Normal"), ("full_width", "Full Width")]},
                    ),
                    56: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": 'Checking this will add "scrolling=no" to the iframe. Use this if your iframe is rendering an unnecessary scroll bar or whitespace below it.',
                            "required": False,
                        },
                    ),
                    57: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 53), ("height", 54), ("iframe_width", 55), ("disable_scroll", 56)]],
                        {"group": "Media & Embeds"},
                    ),
                    58: ("wagtail.snippets.blocks.SnippetChooserBlock", ("snippets.IllustratedNewsletterSignup",), {}),
                    59: (
                        "wagtail.blocks.StructBlock",
                        [[("newsletter_signup", 58)]],
                        {"group": "Engagement & Buttons"},
                    ),
                    60: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title/caption for this image", "required": False},
                    ),
                    61: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("portrait", "Portrait"), ("landscape", "Landscape"), ("square", "Square")],
                            "help_text": "Select the orientation of this image",
                        },
                    ),
                    62: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 60), ("image", 8), ("orientation", 61)]],
                        {"group": "Media & Embeds"},
                    ),
                    63: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional title for the carousel container.", "required": False},
                    ),
                    64: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("portrait", "Portrait"), ("landscape", "Landscape")],
                            "help_text": "Select the orientation for carousel items.",
                            "label": "Orientation",
                        },
                    ),
                    65: ("wagtail.images.blocks.ImageBlock", [], {"help_text": "Select an image for this item."}),
                    66: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional header text shown above the image item.",
                            "max_length": 80,
                            "required": False,
                        },
                    ),
                    67: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional title for the image item (e.g. speaker name or event title).",
                            "max_length": 120,
                            "required": False,
                        },
                    ),
                    68: (
                        "foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock",
                        (),
                        {
                            "help_text": "Optional rich text description for the image item.",
                            "label": "Description",
                            "required": False,
                        },
                    ),
                    69: (
                        "foundation_cms.blocks.link_block.OptionalLinkBlock",
                        (),
                        {"help_text": "Optional link for this item.", "label": "Link", "required": False},
                    ),
                    70: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 65), ("header", 66), ("title", 67), ("description", 68), ("link", 69)]],
                        {},
                    ),
                    71: (
                        "wagtail.blocks.StreamBlock",
                        [[("carousel_item", 70)]],
                        {"help_text": "Items to display in the carousel. Maximum of 10 items.", "max_num": 10},
                    ),
                    72: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 63), ("orientation", 64), ("items", 71)]],
                        {"group": "Card Collections"},
                    ),
                    73: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional heading for this section", "max_length": 100, "required": False},
                    ),
                    74: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("portrait", "Portrait (2:3)"),
                                ("landscape", "Landscape (3:2)"),
                                ("square", "Square (1:1)"),
                            ],
                            "help_text": "Orientation for all images in this section",
                            "label": "Image grid section orientation",
                        },
                    ),
                    75: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("4", "4 per row"), ("5", "5 per row"), ("6", "6 per row")],
                            "label": "Items per section row",
                        },
                    ),
                    76: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["h5", "h6", "large", "bold", "italic"],
                            "help_text": "Optional caption for this image",
                            "required": False,
                        },
                    ),
                    77: (
                        "foundation_cms.blocks.link_block.OptionalLinkBlock",
                        (),
                        {"help_text": "Optional link for both image and caption", "required": False},
                    ),
                    78: ("wagtail.blocks.StructBlock", [[("image", 8), ("caption", 76), ("link", 77)]], {}),
                    79: ("wagtail.blocks.ListBlock", (78,), {"min_num": 1}),
                    80: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 73), ("section_orientation", 74), ("items_per_row", 75), ("items", 79)]],
                        {},
                    ),
                    81: ("wagtail.blocks.ListBlock", (80,), {"label": "Image grid sections", "min_num": 1}),
                    82: ("wagtail.blocks.StructBlock", [[("sections", 81)]], {"group": "Card Collections"}),
                    83: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The full value to animate, including any symbols, commas, decimals, or suffixes (e.g., $5.2M).",
                            "max_length": 5,
                            "required": True,
                        },
                    ),
                    84: ("wagtail.blocks.CharBlock", (), {"help_text": "Heading of the stat", "required": True}),
                    85: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Short description of the stat", "required": False},
                    ),
                    86: (
                        "wagtail.blocks.StructBlock",
                        [[("stat_number", 83), ("stat_heading", 84), ("stat_description", 85)]],
                        {},
                    ),
                    87: (
                        "wagtail.blocks.ListBlock",
                        (86,),
                        {
                            "default": [
                                {"stat_description": "", "stat_heading": "", "stat_number": ""},
                                {"stat_description": "", "stat_heading": "", "stat_number": ""},
                                {"stat_description": "", "stat_heading": "", "stat_number": ""},
                            ],
                            "help_text": "Add exactly 3 stats to appear in the Impact Numbers section",
                            "label": "Impact Stats",
                            "max_num": 3,
                            "min_num": 3,
                        },
                    ),
                    88: ("wagtail.blocks.StructBlock", [[("stats", 87)]], {"group": "Data Display"}),
                    89: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 19),
                                ("link_to", 20),
                                ("page", 21),
                                ("external_url", 22),
                                ("relative_url", 23),
                                ("anchor", 24),
                                ("email", 25),
                                ("file", 26),
                                ("phone", 27),
                                ("new_window", 28),
                                ("style", 29),
                                ("alignment", 30),
                            ]
                        ],
                        {"group": "Engagement & Buttons"},
                    ),
                    90: ("wagtail.blocks.CharBlock", (), {"help_text": "Heading displayed above the list"}),
                    91: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Description displayed above the list", "required": False},
                    ),
                    92: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 19),
                                ("link_to", 20),
                                ("page", 21),
                                ("external_url", 22),
                                ("relative_url", 23),
                                ("anchor", 24),
                                ("email", 25),
                                ("file", 26),
                                ("phone", 27),
                                ("new_window", 28),
                            ]
                        ],
                        {},
                    ),
                    93: ("wagtail.blocks.ListBlock", (92,), {"max_num": 4, "min_num": 1}),
                    94: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 90), ("description", 91), ("items", 93)]],
                        {"group": "Data Display"},
                    ),
                    95: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("snippets.NewsletterSignup",),
                        {"max_num": 1},
                    ),
                    96: (
                        "wagtail.blocks.StructBlock",
                        [[("newsletter_signup", 95)]],
                        {"group": "Engagement & Buttons"},
                    ),
                    97: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("snippets.NewsletterUnsubscribe",),
                        {"max_num": 1},
                    ),
                    98: (
                        "wagtail.blocks.StructBlock",
                        [[("newsletter_unsubscribe", 97)]],
                        {"group": "Engagement & Buttons"},
                    ),
                    99: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Appears as the main heading.", "label": "Headline", "required": False},
                    ),
                    100: (
                        "foundation_cms.blocks.link_block.OptionalLinkBlock",
                        (),
                        {
                            "help_text": "Optional link for the card.",
                            "label": "Call to Action Link",
                            "required": False,
                        },
                    ),
                    101: ("wagtail.blocks.StructBlock", [[("headline", 99), ("cta_link", 100)]], {}),
                    102: (
                        "wagtail.blocks.ListBlock",
                        (101,),
                        {
                            "default": [
                                {"cta_link": [], "headline": ""},
                                {"cta_link": [], "headline": ""},
                                {"cta_link": [], "headline": ""},
                            ],
                            "help_text": "3 cards required.",
                            "label": "Pillar Cards",
                            "max_num": 3,
                            "min_num": 3,
                        },
                    ),
                    103: ("wagtail.blocks.StructBlock", [[("cards", 102)]], {"group": "Card Collections"}),
                    104: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Title of the podcast. <strong>Note:</strong> Does not render on "NothingPersonal" pages.'
                        },
                    ),
                    105: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": 'Optional short description of the podcast. <strong>Note:</strong> Does not render on "NothingPersonal" pages.',
                            "required": False,
                        },
                    ),
                    106: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 104), ("description", 105), ("simplecast_embed_code", 19)]],
                        {"group": "Media & Embeds"},
                    ),
                    107: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Appears above the headline.", "label": "Label", "required": False},
                    ),
                    108: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Optional Image for the card", "label": "Image"},
                    ),
                    109: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 19),
                                ("link_to", 20),
                                ("page", 21),
                                ("external_url", 22),
                                ("relative_url", 23),
                                ("anchor", 24),
                                ("email", 25),
                                ("file", 26),
                                ("phone", 27),
                                ("new_window", 28),
                            ]
                        ],
                        {"help_text": "Link for the card.", "label": "Call to Action Link", "required": True},
                    ),
                    110: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 107), ("headline", 99), ("image", 108), ("cta_link", 109)]],
                        {},
                    ),
                    111: (
                        "wagtail.blocks.ListBlock",
                        (110,),
                        {
                            "help_text": "Minimum of 3 cards required. More than 3 will turn element into a carousel.",
                            "label": "Portrait Cards",
                            "min_num": 3,
                        },
                    ),
                    112: ("wagtail.blocks.StructBlock", [[("cards", 111)]], {"group": "Card Collections"}),
                    113: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    114: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    115: ("wagtail.blocks.StructBlock", [[("quote", 113), ("attribution", 114)]], {"group": "Text"}),
                    116: ("foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock", (), {"group": "Text"}),
                    117: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("small", "Small"),
                                ("medium", "Medium"),
                                ("large", "Large"),
                                ("xlarge", "Extra Large"),
                            ],
                            "help_text": "Select the size of the spacer",
                        },
                    ),
                    118: ("wagtail.blocks.StructBlock", [[("size", 117)]], {"group": "Layout"}),
                    119: ("wagtail.blocks.CharBlock", (), {"label": "Name", "max_length": 50, "required": True}),
                    120: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Image should follow a 1:1 aspect ratio.", "label": "Image"},
                    ),
                    121: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 113), ("name", 119), ("description", 17), ("image", 120)]],
                        {},
                    ),
                    122: (
                        "wagtail.blocks.ListBlock",
                        (121,),
                        {"help_text": "3 cards required.", "label": "Spotlight Cards", "max_num": 3, "min_num": 3},
                    ),
                    123: ("wagtail.blocks.StructBlock", [[("cards", 122)]], {"group": "Card Collections"}),
                    124: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title shown on the tab button", "required": True},
                    ),
                    125: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Subtitle shown under the title on the tab", "required": False},
                    ),
                    126: ("foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock", (), {"required": False}),
                    127: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 60), ("image", 8), ("orientation", 61)]],
                        {"required": False},
                    ),
                    128: ("foundation_cms.blocks.link_block.OptionalLinkBlock", (), {"required": False}),
                    129: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 114), ("subtitle", 114), ("text", 126), ("image", 127), ("link", 128)]],
                        {},
                    ),
                    130: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 19), ("image", 8), ("subtitle", 19), ("link", 128)]],
                        {},
                    ),
                    131: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 1), ("text_image", 129), ("tab_card_set", 130)]],
                        {"help_text": "Add one or more content blocks to the tab.", "min_num": 1, "required": True},
                    ),
                    132: ("wagtail.blocks.StructBlock", [[("title", 124), ("subtitle", 125), ("content", 131)]], {}),
                    133: ("wagtail.blocks.ListBlock", (132,), {"label": "Tabs", "max_num": 8, "min_num": 1}),
                    134: ("wagtail.blocks.StructBlock", [[("tabs", 133)]], {"group": "Card Collections"}),
                    135: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("white", "White"),
                                ("neutral-100", "Grey 100"),
                                ("neutral-200", "Grey 200"),
                                ("neutral-300", "Grey 300"),
                                ("blue-100", "Blue 100"),
                                ("blue-200", "Blue 200"),
                                ("blue-300", "Blue 300"),
                                ("green-100", "Green 100"),
                                ("green-200", "Green 200"),
                                ("green-300", "Green 300"),
                                ("orange-100", "Orange 100"),
                                ("orange-200", "Orange 200"),
                                ("orange-300", "Orange 300"),
                                ("yellow-100", "Yellow 100"),
                                ("yellow-200", "Yellow 200"),
                                ("yellow-300", "Yellow 300"),
                            ]
                        },
                    ),
                    136: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("top", "Top"), ("middle", "Middle"), ("bottom", "Bottom")],
                            "help_text": "Vertical alignment of the columns content",
                        },
                    ),
                    137: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 104), ("description", 105), ("simplecast_embed_code", 19)]],
                        {},
                    ),
                    138: ("wagtail.blocks.StructBlock", [[("title", 60), ("image", 8), ("orientation", 61)]], {}),
                    139: ("wagtail.blocks.StructBlock", [[("newsletter_signup", 95)]], {}),
                    140: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Log into Vimeo, select your desired video, and click 'Copy Link'",
                            "label": "Vimeo Video URL",
                            "required": True,
                        },
                    ),
                    141: ("wagtail.blocks.CharBlock", (), {"help_text": "Optional Caption Text", "required": False}),
                    142: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_to", 20),
                                ("page", 21),
                                ("external_url", 22),
                                ("relative_url", 23),
                                ("anchor", 24),
                                ("email", 25),
                                ("file", 26),
                                ("phone", 27),
                                ("new_window", 28),
                            ]
                        ],
                        {},
                    ),
                    143: (
                        "wagtail.blocks.ListBlock",
                        (142,),
                        {
                            "default": [],
                            "help_text": "Optional URL that this caption should link out to.",
                            "max_num": 1,
                            "min_num": 0,
                        },
                    ),
                    144: (
                        "wagtail.blocks.StructBlock",
                        [[("video_url", 140), ("caption", 141), ("caption_url", 143)]],
                        {},
                    ),
                    145: ("wagtail.blocks.StructBlock", [[("title", 90), ("description", 91), ("items", 93)]], {}),
                    146: ("wagtail.blocks.StructBlock", [[("size", 117)]], {}),
                    147: ("wagtail.blocks.StructBlock", [[("quote", 113), ("attribution", 114)]], {}),
                    148: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 19),
                                ("link_to", 20),
                                ("page", 21),
                                ("external_url", 22),
                                ("relative_url", 23),
                                ("anchor", 24),
                                ("email", 25),
                                ("file", 26),
                                ("phone", 27),
                                ("new_window", 28),
                                ("style", 29),
                                ("alignment", 30),
                            ]
                        ],
                        {},
                    ),
                    149: (
                        "wagtail.blocks.StructBlock",
                        [[("fru_element_type", 33), ("fru_element_embed_code", 34)]],
                        {},
                    ),
                    150: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Project", "page_type": ["gallery_hub.ProjectPage"], "required": True},
                    ),
                    151: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": True, "label": "Show description", "required": False},
                    ),
                    152: ("wagtail.blocks.StructBlock", [[("project", 150), ("show_description", 151)]], {}),
                    153: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 1),
                                ("podcast", 137),
                                ("image", 138),
                                ("newsletter_signup", 139),
                                ("video", 144),
                                ("list", 145),
                                ("spacer", 146),
                                ("quote", 147),
                                ("link_button", 148),
                                ("fru_element", 149),
                                ("project_block", 152),
                            ]
                        ],
                        {"label": "Left Column", "required": False},
                    ),
                    154: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 1),
                                ("podcast", 137),
                                ("image", 138),
                                ("newsletter_signup", 139),
                                ("video", 144),
                                ("list", 145),
                                ("spacer", 146),
                                ("quote", 147),
                                ("link_button", 148),
                                ("fru_element", 149),
                                ("project_block", 152),
                            ]
                        ],
                        {"label": "Center Column", "required": False},
                    ),
                    155: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 1),
                                ("podcast", 137),
                                ("image", 138),
                                ("newsletter_signup", 139),
                                ("video", 144),
                                ("list", 145),
                                ("spacer", 146),
                                ("quote", 147),
                                ("link_button", 148),
                                ("fru_element", 149),
                                ("project_block", 152),
                            ]
                        ],
                        {"label": "Right Column", "required": False},
                    ),
                    156: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 135),
                                ("vertical_alignment", 136),
                                ("left_column", 153),
                                ("center_column", 154),
                                ("right_column", 155),
                            ]
                        ],
                        {"group": "Layout"},
                    ),
                    157: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional category for the card.", "required": False},
                    ),
                    158: ("wagtail.blocks.CharBlock", (), {"help_text": "Title for the card.", "required": True}),
                    159: (
                        "foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock",
                        (),
                        {"help_text": "Optional description text.", "required": False},
                    ),
                    160: (
                        "wagtail.blocks.StructBlock",
                        [[("category", 157), ("title", 158), ("text", 159), ("image", 8), ("link", 92)]],
                        {},
                    ),
                    161: (
                        "wagtail.blocks.StreamBlock",
                        [[("card", 160)]],
                        {"help_text": "Add between 1 and 3 cards.", "max_num": 3, "min_num": 1},
                    ),
                    162: ("wagtail.blocks.StructBlock", [[("cards", 161)]], {"group": "Card Collections"}),
                    163: ("wagtail.blocks.CharBlock", (), {"help_text": "Title for the block", "required": True}),
                    164: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("shape", "Shape"), ("loop-line", "Loop Line")],
                            "help_text": "Select the style of the title",
                        },
                    ),
                    165: ("wagtail.blocks.StructBlock", [[("title", 163), ("style", 164)]], {"group": "Text"}),
                    166: ("wagtail.blocks.StructBlock", [[("title", 114), ("text", 126)]], {}),
                    167: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 1),
                                ("podcast", 137),
                                ("image", 138),
                                ("newsletter_signup", 139),
                                ("video", 144),
                                ("list", 145),
                                ("spacer", 146),
                                ("quote", 147),
                                ("text_social", 166),
                                ("link_button", 148),
                                ("fru_element", 149),
                                ("project_block", 152),
                            ]
                        ],
                        {"label": "Left Column", "required": False},
                    ),
                    168: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 1),
                                ("podcast", 137),
                                ("image", 138),
                                ("newsletter_signup", 139),
                                ("video", 144),
                                ("list", 145),
                                ("spacer", 146),
                                ("quote", 147),
                                ("text_social", 166),
                                ("link_button", 148),
                                ("fru_element", 149),
                                ("project_block", 152),
                            ]
                        ],
                        {"label": "Right Column", "required": False},
                    ),
                    169: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 135),
                                ("vertical_alignment", 136),
                                ("left_column", 167),
                                ("right_column", 168),
                            ]
                        ],
                        {"group": "Layout"},
                    ),
                    170: (
                        "wagtail.blocks.StructBlock",
                        [[("video_url", 140), ("caption", 141), ("caption_url", 143)]],
                        {"group": "Media & Embeds"},
                    ),
                },
            ),
        ),
    ]
