# Generated by Django 5.2.15 on 2026-09-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0089_alter_generalpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalpage",
            name="hero_background_color",
            field=models.CharField(
                blank=True,
                choices=[("orange-200", "Orange"), ("yellow-200", "Yellow"), ("transparent", "Transparent")],
                default="",
                help_text="Select the color of the hero background, only for 'Top to Bottom' variant.",
                max_length=50,
            ),
        ),
    ]
