# Generated by Django 5.2.17 on 2026-09-24 23:31

import wagtail.fields
from django.db import migrations

import foundation_cms.legacy_apps.wagtailpages.validators
import foundation_cms.validators


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0089_alter_generalpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("section_start", 3),
                    ("accordion_block", 9),
                    ("custom_media", 15),
                    ("divider", 16),
                    ("donor_help_contact_us_form", 19),
                    ("featured_card_block", 36),
                    ("fru_element_block", 39),
                    ("greenhouse_board", 46),
                    ("icon_info_grid", 56),
                    ("iframe_block", 61),
                    ("illustrated_newsletter_signup", 63),
                    ("image", 66),
                    ("image_carousel_block", 76),
                    ("image_grid", 86),
                    ("impact_numbers", 92),
                    ("link_button_block", 93),
                    ("list_block", 98),
                    ("newsletter_signup", 100),
                    ("newsletter_unsubscribe", 102),
                    ("pillar_card_set", 107),
                    ("podcast_block", 110),
                    ("portrait_card_set_block", 116),
                    ("quote", 119),
                    ("rich_text", 120),
                    ("spacer_block", 122),
                    ("spotlight_card_set_block", 127),
                    ("tabbed_content", 138),
                    ("three_column_container_block", 160),
                    ("timely_activations_cards", 166),
                    ("title_block", 169),
                    ("two_column_container_block", 173),
                    ("video_block", 174),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Labels this section in the CMS and its minimap. This is not shown on the page.",
                            "max_length": 100,
                        },
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("default", "White (Default)"), ("ground", "Light grey (Ground)")],
                            "label": "Background color",
                        },
                    ),
                    2: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_messages": {"invalid": "Use lowercase letters, numbers and hyphens only."},
                            "help_text": "Optional ID for linking to this section, e.g. 'get-involved' for #get-involved.",
                            "max_length": 50,
                            "regex": "^[a-z0-9]+(?:-[a-z0-9]+)*$",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("name", 0), ("surface", 1), ("anchor_id", 2)]],
                        {"group": "Sections"},
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Heading for the Accordion Item", "required": True},
                    ),
                    5: ("foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock", (), {}),
                    6: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 5)]],
                        {"required": False, "use_json_field": True},
                    ),
                    7: ("wagtail.blocks.StructBlock", [[("title", 4), ("content", 6)]], {}),
                    8: ("wagtail.blocks.ListBlock", (7,), {"min_num": 1}),
                    9: ("wagtail.blocks.StructBlock", [[("accordion_items", 8)]], {"group": "Text"}),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title/caption for this media", "required": False},
                    ),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("image", "Image"), ("video", "Video")],
                            "help_text": "Select the type of media to display",
                        },
                    ),
                    12: ("wagtail.images.blocks.ImageBlock", [], {}),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Log into Vimeo using 1Password and upload the desired video. Then select the video and click "...", "Video File Links", and select "(mp4, 1920 x 1080)". Copy and paste the link here.',
                            "max_length": 500,
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("portrait", "Portrait"),
                                ("landscape", "Landscape"),
                                ("square", "Square"),
                                ("widescreen", "Widescreen 16:9 (12 columns wide)"),
                            ],
                            "help_text": "Select the orientation of this media",
                        },
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 10), ("content", 11), ("image", 12), ("video_url", 13), ("orientation", 14)]],
                        {"group": "Media & Embeds"},
                    ),
                    16: ("wagtail.blocks.StructBlock", [[]], {"group": "Layout"}),
                    17: ("wagtail.blocks.CharBlock", (), {"default": "Contact Us", "required": True}),
                    18: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Questions about your donation? Get in touch with our team by using the form below.",
                            "required": False,
                        },
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 17), ("subheading", 18), ("image", 12)]],
                        {"group": "Engagement & Buttons"},
                    ),
                    20: ("wagtail.blocks.CharBlock", (), {"label": "Heading", "max_length": 50, "required": True}),
                    21: (
                        "foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock",
                        (),
                        {"features": ["bold", "italic"], "label": "Description", "max_length": 500, "required": True},
                    ),
                    22: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Image for the card", "label": "Image"},
                    ),
                    23: ("wagtail.blocks.CharBlock", (), {}),
                    24: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("external_url", "External URL"),
                                ("relative_url", "Relative URL"),
                                ("email", "Email"),
                                ("anchor", "Anchor"),
                                ("file", "File"),
                                ("phone", "Phone"),
                            ],
                            "label": "Link to",
                        },
                    ),
                    25: ("wagtail.blocks.PageChooserBlock", (), {"label": "Page", "required": False}),
                    26: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Enter a full URL including http:// or https://",
                            "label": "External URL",
                            "max_length": 300,
                            "required": False,
                        },
                    ),
                    27: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'A path relative to this domain. For example, "/foo/bar" or "?foo=bar".',
                            "label": "Relative URL",
                            "max_length": 300,
                            "required": False,
                            "validators": [foundation_cms.legacy_apps.wagtailpages.validators.RelativeURLValidator()],
                        },
                    ),
                    28: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'An id attribute of an element on the current page. For example, "#section-1"',
                            "label": "#",
                            "max_length": 300,
                            "required": False,
                            "validators": [foundation_cms.validators.AnchorLinkValidator()],
                        },
                    ),
                    29: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    30: ("wagtail.documents.blocks.DocumentChooserBlock", (), {"label": "File", "required": False}),
                    31: ("wagtail.blocks.CharBlock", (), {"label": "Phone", "max_length": 30, "required": False}),
                    32: ("wagtail.blocks.BooleanBlock", (), {"label": "Open in new window", "required": False}),
                    33: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("btn-primary", "Primary"), ("btn-secondary", "Secondary")]},
                    ),
                    34: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("link-button-block--left", "Left"), ("link-button-block--center", "Center")]},
                    ),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 23),
                                ("link_to", 24),
                                ("page", 25),
                                ("external_url", 26),
                                ("relative_url", 27),
                                ("anchor", 28),
                                ("email", 29),
                                ("file", 30),
                                ("phone", 31),
                                ("new_window", 32),
                                ("style", 33),
                                ("alignment", 34),
                            ]
                        ],
                        {"help_text": "Link button for the card.", "label": "Button", "required": False},
                    ),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 20), ("description", 21), ("image", 22), ("button", 35)]],
                        {"group": "Card Collections"},
                    ),
                    37: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("donation-form", "Donation Form"),
                                ("donor-map", "Donor Map"),
                                ("top-locations", "Top Locations"),
                                ("donation-levels", "Donation Levels"),
                                ("donate-button", "Donate Button"),
                            ],
                            "help_text": "Select the type of Fundraise Up element.",
                        },
                    ),
                    38: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Copy the HTML code generated by the desired Fundraise Up element and paste it here.",
                            "required": True,
                        },
                    ),
                    39: (
                        "wagtail.blocks.StructBlock",
                        [[("fru_element_type", 37), ("fru_element_embed_code", 38)]],
                        {"group": "Engagement & Buttons"},
                    ),
                    40: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "No open roles right now",
                            "help_text": "Shown when the job board has no open positions.",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    41: (
                        "foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock",
                        (),
                        {
                            "default": "<p>We don't have any openings at the moment. Please check back soon.</p>",
                            "help_text": "Shown under the heading when there are no open positions.",
                            "required": False,
                        },
                    ),
                    42: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Our job board is temporarily unavailable",
                            "help_text": "Shown when the job board cannot be loaded at all.",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    43: (
                        "foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock",
                        (),
                        {
                            "default": "<p>We're having trouble loading our open roles. Please try again shortly.</p>",
                            "help_text": "Shown under the heading when the job board cannot be loaded at all.",
                            "required": False,
                        },
                    ),
                    44: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Not seeing our open roles?",
                            "help_text": "Shown under the job board, followed by the link below.",
                            "max_length": 140,
                            "required": False,
                        },
                    ),
                    45: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "View them on Greenhouse",
                            "help_text": "Label for the link to the Greenhouse-hosted board.",
                            "max_length": 60,
                            "required": False,
                        },
                    ),
                    46: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("empty_heading", 40),
                                ("empty_description", 41),
                                ("unavailable_heading", 42),
                                ("unavailable_description", 43),
                                ("hosted_board_notice", 44),
                                ("hosted_board_link_label", 45),
                            ]
                        ],
                        {"group": "Engagement & Buttons"},
                    ),
                    47: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Section heading for this grid", "max_length": 100, "required": True},
                    ),
                    48: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("orange", "Orange"), ("black", "Black")],
                            "help_text": "Color applied to all icons in this grid",
                        },
                    ),
                    49: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("1", "1 column"), ("2", "2 columns"), ("3", "3 columns")],
                            "help_text": "Number of columns on desktop (automatically stacks on mobile)",
                            "label": "Number of columns for this grid",
                        },
                    ),
                    50: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("compact", "Compact (icons + titles only)"),
                                ("detailed", "Detailed (icons + titles + descriptions)"),
                            ],
                            "help_text": "Choose content density. Compact hides descriptions, Detailed shows them.",
                            "label": "Layout style",
                        },
                    ),
                    51: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("chat", "Chat icon"),
                                ("eye-open", "Eye Open icon"),
                                ("gear", "Gear icon"),
                                ("globe", "Globe icon"),
                                ("megaphone", "Megaphone icon"),
                                ("star", "Star icon"),
                            ],
                            "help_text": "Select an icon for this item",
                        },
                    ),
                    52: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title for this item", "max_length": 100, "required": True},
                    ),
                    53: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional description (max 126 characters)",
                            "max_length": 126,
                            "required": False,
                        },
                    ),
                    54: ("wagtail.blocks.StructBlock", [[("icon", 51), ("title", 52), ("description", 53)]], {}),
                    55: ("wagtail.blocks.ListBlock", (54,), {"help_text": "Add icon info items", "min_num": 1}),
                    56: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 47), ("icon_color", 48), ("columns", 49), ("layout_style", 50), ("items", 55)]],
                        {"group": "Card Collections"},
                    ),
                    57: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Please note that only URLs from allow-listed domains will work."},
                    ),
                    58: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Optional integer pixel value for custom iFrame height", "required": False},
                    ),
                    59: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("normal", "Normal"), ("full_width", "Full Width")]},
                    ),
                    60: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": 'Checking this will add "scrolling=no" to the iframe. Use this if your iframe is rendering an unnecessary scroll bar or whitespace below it.',
                            "required": False,
                        },
                    ),
                    61: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 57), ("height", 58), ("iframe_width", 59), ("disable_scroll", 60)]],
                        {"group": "Media & Embeds"},
                    ),
                    62: ("wagtail.snippets.blocks.SnippetChooserBlock", ("snippets.IllustratedNewsletterSignup",), {}),
                    63: (
                        "wagtail.blocks.StructBlock",
                        [[("newsletter_signup", 62)]],
                        {"group": "Engagement & Buttons"},
                    ),
                    64: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title/caption for this image", "required": False},
                    ),
                    65: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("portrait", "Portrait"), ("landscape", "Landscape"), ("square", "Square")],
                            "help_text": "Select the orientation of this image",
                        },
                    ),
                    66: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 64), ("image", 12), ("orientation", 65)]],
                        {"group": "Media & Embeds"},
                    ),
                    67: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional title for the carousel container.", "required": False},
                    ),
                    68: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("portrait", "Portrait"), ("landscape", "Landscape")],
                            "help_text": "Select the orientation for carousel items.",
                            "label": "Orientation",
                        },
                    ),
                    69: ("wagtail.images.blocks.ImageBlock", [], {"help_text": "Select an image for this item."}),
                    70: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional header text shown above the image item.",
                            "max_length": 80,
                            "required": False,
                        },
                    ),
                    71: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional title for the image item (e.g. speaker name or event title).",
                            "max_length": 120,
                            "required": False,
                        },
                    ),
                    72: (
                        "foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock",
                        (),
                        {
                            "help_text": "Optional rich text description for the image item.",
                            "label": "Description",
                            "required": False,
                        },
                    ),
                    73: (
                        "foundation_cms.blocks.link_block.OptionalLinkBlock",
                        (),
                        {"help_text": "Optional link for this item.", "label": "Link", "required": False},
                    ),
                    74: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 69), ("header", 70), ("title", 71), ("description", 72), ("link", 73)]],
                        {},
                    ),
                    75: (
                        "wagtail.blocks.StreamBlock",
                        [[("carousel_item", 74)]],
                        {"help_text": "Items to display in the carousel. Maximum of 10 items.", "max_num": 10},
                    ),
                    76: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 67), ("orientation", 68), ("items", 75)]],
                        {"group": "Card Collections"},
                    ),
                    77: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional heading for this section", "max_length": 100, "required": False},
                    ),
                    78: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("portrait", "Portrait (2:3)"),
                                ("landscape", "Landscape (3:2)"),
                                ("square", "Square (1:1)"),
                            ],
                            "help_text": "Orientation for all images in this section",
                            "label": "Image grid section orientation",
                        },
                    ),
                    79: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("4", "4 per row"), ("5", "5 per row"), ("6", "6 per row")],
                            "label": "Items per section row",
                        },
                    ),
                    80: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["h5", "h6", "large", "bold", "italic"],
                            "help_text": "Optional caption for this image",
                            "required": False,
                        },
                    ),
                    81: (
                        "foundation_cms.blocks.link_block.OptionalLinkBlock",
                        (),
                        {"help_text": "Optional link for both image and caption", "required": False},
                    ),
                    82: ("wagtail.blocks.StructBlock", [[("image", 12), ("caption", 80), ("link", 81)]], {}),
                    83: ("wagtail.blocks.ListBlock", (82,), {"min_num": 1}),
                    84: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 77), ("section_orientation", 78), ("items_per_row", 79), ("items", 83)]],
                        {},
                    ),
                    85: ("wagtail.blocks.ListBlock", (84,), {"label": "Image grid sections", "min_num": 1}),
                    86: ("wagtail.blocks.StructBlock", [[("sections", 85)]], {"group": "Card Collections"}),
                    87: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The full value to animate, including any symbols, commas, decimals, or suffixes (e.g., $5.2M).",
                            "max_length": 5,
                            "required": True,
                        },
                    ),
                    88: ("wagtail.blocks.CharBlock", (), {"help_text": "Heading of the stat", "required": True}),
                    89: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Short description of the stat", "required": False},
                    ),
                    90: (
                        "wagtail.blocks.StructBlock",
                        [[("stat_number", 87), ("stat_heading", 88), ("stat_description", 89)]],
                        {},
                    ),
                    91: (
                        "wagtail.blocks.ListBlock",
                        (90,),
                        {
                            "default": [
                                {"stat_description": "", "stat_heading": "", "stat_number": ""},
                                {"stat_description": "", "stat_heading": "", "stat_number": ""},
                                {"stat_description": "", "stat_heading": "", "stat_number": ""},
                            ],
                            "help_text": "Add exactly 3 stats to appear in the Impact Numbers section",
                            "label": "Impact Stats",
                            "max_num": 3,
                            "min_num": 3,
                        },
                    ),
                    92: ("wagtail.blocks.StructBlock", [[("stats", 91)]], {"group": "Data Display"}),
                    93: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 23),
                                ("link_to", 24),
                                ("page", 25),
                                ("external_url", 26),
                                ("relative_url", 27),
                                ("anchor", 28),
                                ("email", 29),
                                ("file", 30),
                                ("phone", 31),
                                ("new_window", 32),
                                ("style", 33),
                                ("alignment", 34),
                            ]
                        ],
                        {"group": "Engagement & Buttons"},
                    ),
                    94: ("wagtail.blocks.CharBlock", (), {"help_text": "Heading displayed above the list"}),
                    95: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Description displayed above the list", "required": False},
                    ),
                    96: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 23),
                                ("link_to", 24),
                                ("page", 25),
                                ("external_url", 26),
                                ("relative_url", 27),
                                ("anchor", 28),
                                ("email", 29),
                                ("file", 30),
                                ("phone", 31),
                                ("new_window", 32),
                            ]
                        ],
                        {},
                    ),
                    97: ("wagtail.blocks.ListBlock", (96,), {"max_num": 4, "min_num": 1}),
                    98: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 94), ("description", 95), ("items", 97)]],
                        {"group": "Data Display"},
                    ),
                    99: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("snippets.NewsletterSignup",),
                        {"max_num": 1},
                    ),
                    100: (
                        "wagtail.blocks.StructBlock",
                        [[("newsletter_signup", 99)]],
                        {"group": "Engagement & Buttons"},
                    ),
                    101: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("snippets.NewsletterUnsubscribe",),
                        {"max_num": 1},
                    ),
                    102: (
                        "wagtail.blocks.StructBlock",
                        [[("newsletter_unsubscribe", 101)]],
                        {"group": "Engagement & Buttons"},
                    ),
                    103: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Appears as the main heading.", "label": "Headline", "required": False},
                    ),
                    104: (
                        "foundation_cms.blocks.link_block.OptionalLinkBlock",
                        (),
                        {
                            "help_text": "Optional link for the card.",
                            "label": "Call to Action Link",
                            "required": False,
                        },
                    ),
                    105: ("wagtail.blocks.StructBlock", [[("headline", 103), ("cta_link", 104)]], {}),
                    106: (
                        "wagtail.blocks.ListBlock",
                        (105,),
                        {
                            "default": [
                                {"cta_link": [], "headline": ""},
                                {"cta_link": [], "headline": ""},
                                {"cta_link": [], "headline": ""},
                            ],
                            "help_text": "3 cards required.",
                            "label": "Pillar Cards",
                            "max_num": 3,
                            "min_num": 3,
                        },
                    ),
                    107: ("wagtail.blocks.StructBlock", [[("cards", 106)]], {"group": "Card Collections"}),
                    108: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Title of the podcast. <strong>Note:</strong> Does not render on "NothingPersonal" pages.'
                        },
                    ),
                    109: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": 'Optional short description of the podcast. <strong>Note:</strong> Does not render on "NothingPersonal" pages.',
                            "required": False,
                        },
                    ),
                    110: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 108), ("description", 109), ("simplecast_embed_code", 23)]],
                        {"group": "Media & Embeds"},
                    ),
                    111: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Appears above the headline.", "label": "Label", "required": False},
                    ),
                    112: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Optional Image for the card", "label": "Image"},
                    ),
                    113: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 23),
                                ("link_to", 24),
                                ("page", 25),
                                ("external_url", 26),
                                ("relative_url", 27),
                                ("anchor", 28),
                                ("email", 29),
                                ("file", 30),
                                ("phone", 31),
                                ("new_window", 32),
                            ]
                        ],
                        {"help_text": "Link for the card.", "label": "Call to Action Link", "required": True},
                    ),
                    114: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 111), ("headline", 103), ("image", 112), ("cta_link", 113)]],
                        {},
                    ),
                    115: (
                        "wagtail.blocks.ListBlock",
                        (114,),
                        {
                            "help_text": "Minimum of 3 cards required. More than 3 will turn element into a carousel.",
                            "label": "Portrait Cards",
                            "min_num": 3,
                        },
                    ),
                    116: ("wagtail.blocks.StructBlock", [[("cards", 115)]], {"group": "Card Collections"}),
                    117: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    118: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    119: ("wagtail.blocks.StructBlock", [[("quote", 117), ("attribution", 118)]], {"group": "Text"}),
                    120: ("foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock", (), {"group": "Text"}),
                    121: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("small", "Small"),
                                ("medium", "Medium"),
                                ("large", "Large"),
                                ("xlarge", "Extra Large"),
                            ],
                            "help_text": "Select the size of the spacer",
                        },
                    ),
                    122: ("wagtail.blocks.StructBlock", [[("size", 121)]], {"group": "Layout"}),
                    123: ("wagtail.blocks.CharBlock", (), {"label": "Name", "max_length": 50, "required": True}),
                    124: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Image should follow a 1:1 aspect ratio.", "label": "Image"},
                    ),
                    125: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 117), ("name", 123), ("description", 21), ("image", 124)]],
                        {},
                    ),
                    126: (
                        "wagtail.blocks.ListBlock",
                        (125,),
                        {"help_text": "3 cards required.", "label": "Spotlight Cards", "max_num": 3, "min_num": 3},
                    ),
                    127: ("wagtail.blocks.StructBlock", [[("cards", 126)]], {"group": "Card Collections"}),
                    128: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title shown on the tab button", "required": True},
                    ),
                    129: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Subtitle shown under the title on the tab", "required": False},
                    ),
                    130: ("foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock", (), {"required": False}),
                    131: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 64), ("image", 12), ("orientation", 65)]],
                        {"required": False},
                    ),
                    132: ("foundation_cms.blocks.link_block.OptionalLinkBlock", (), {"required": False}),
                    133: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 118), ("subtitle", 118), ("text", 130), ("image", 131), ("link", 132)]],
                        {},
                    ),
                    134: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 23), ("image", 12), ("subtitle", 23), ("link", 132)]],
                        {},
                    ),
                    135: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 5), ("text_image", 133), ("tab_card_set", 134)]],
                        {"help_text": "Add one or more content blocks to the tab.", "min_num": 1, "required": True},
                    ),
                    136: ("wagtail.blocks.StructBlock", [[("title", 128), ("subtitle", 129), ("content", 135)]], {}),
                    137: ("wagtail.blocks.ListBlock", (136,), {"label": "Tabs", "max_num": 8, "min_num": 1}),
                    138: ("wagtail.blocks.StructBlock", [[("tabs", 137)]], {"group": "Card Collections"}),
                    139: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("white", "White"),
                                ("neutral-100", "Grey 100"),
                                ("neutral-200", "Grey 200"),
                                ("neutral-300", "Grey 300"),
                                ("blue-100", "Blue 100"),
                                ("blue-200", "Blue 200"),
                                ("blue-300", "Blue 300"),
                                ("green-100", "Green 100"),
                                ("green-200", "Green 200"),
                                ("green-300", "Green 300"),
                                ("orange-100", "Orange 100"),
                                ("orange-200", "Orange 200"),
                                ("orange-300", "Orange 300"),
                                ("yellow-100", "Yellow 100"),
                                ("yellow-200", "Yellow 200"),
                                ("yellow-300", "Yellow 300"),
                            ]
                        },
                    ),
                    140: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("top", "Top"), ("middle", "Middle"), ("bottom", "Bottom")],
                            "help_text": "Vertical alignment of the columns content",
                        },
                    ),
                    141: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 108), ("description", 109), ("simplecast_embed_code", 23)]],
                        {},
                    ),
                    142: ("wagtail.blocks.StructBlock", [[("title", 64), ("image", 12), ("orientation", 65)]], {}),
                    143: ("wagtail.blocks.StructBlock", [[("newsletter_signup", 99)]], {}),
                    144: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Log into Vimeo, select your desired video, and click 'Copy Link'",
                            "label": "Vimeo Video URL",
                            "required": True,
                        },
                    ),
                    145: ("wagtail.blocks.CharBlock", (), {"help_text": "Optional Caption Text", "required": False}),
                    146: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_to", 24),
                                ("page", 25),
                                ("external_url", 26),
                                ("relative_url", 27),
                                ("anchor", 28),
                                ("email", 29),
                                ("file", 30),
                                ("phone", 31),
                                ("new_window", 32),
                            ]
                        ],
                        {},
                    ),
                    147: (
                        "wagtail.blocks.ListBlock",
                        (146,),
                        {
                            "default": [],
                            "help_text": "Optional URL that this caption should link out to.",
                            "max_num": 1,
                            "min_num": 0,
                        },
                    ),
                    148: (
                        "wagtail.blocks.StructBlock",
                        [[("video_url", 144), ("caption", 145), ("caption_url", 147)]],
                        {},
                    ),
                    149: ("wagtail.blocks.StructBlock", [[("title", 94), ("description", 95), ("items", 97)]], {}),
                    150: ("wagtail.blocks.StructBlock", [[("size", 121)]], {}),
                    151: ("wagtail.blocks.StructBlock", [[("quote", 117), ("attribution", 118)]], {}),
                    152: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 23),
                                ("link_to", 24),
                                ("page", 25),
                                ("external_url", 26),
                                ("relative_url", 27),
                                ("anchor", 28),
                                ("email", 29),
                                ("file", 30),
                                ("phone", 31),
                                ("new_window", 32),
                                ("style", 33),
                                ("alignment", 34),
                            ]
                        ],
                        {},
                    ),
                    153: (
                        "wagtail.blocks.StructBlock",
                        [[("fru_element_type", 37), ("fru_element_embed_code", 38)]],
                        {},
                    ),
                    154: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Project", "page_type": ["gallery_hub.ProjectPage"], "required": True},
                    ),
                    155: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": True, "label": "Show description", "required": False},
                    ),
                    156: ("wagtail.blocks.StructBlock", [[("project", 154), ("show_description", 155)]], {}),
                    157: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 5),
                                ("podcast", 141),
                                ("image", 142),
                                ("newsletter_signup", 143),
                                ("video", 148),
                                ("list", 149),
                                ("spacer", 150),
                                ("quote", 151),
                                ("link_button", 152),
                                ("fru_element", 153),
                                ("project_block", 156),
                            ]
                        ],
                        {"label": "Left Column", "required": False},
                    ),
                    158: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 5),
                                ("podcast", 141),
                                ("image", 142),
                                ("newsletter_signup", 143),
                                ("video", 148),
                                ("list", 149),
                                ("spacer", 150),
                                ("quote", 151),
                                ("link_button", 152),
                                ("fru_element", 153),
                                ("project_block", 156),
                            ]
                        ],
                        {"label": "Center Column", "required": False},
                    ),
                    159: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 5),
                                ("podcast", 141),
                                ("image", 142),
                                ("newsletter_signup", 143),
                                ("video", 148),
                                ("list", 149),
                                ("spacer", 150),
                                ("quote", 151),
                                ("link_button", 152),
                                ("fru_element", 153),
                                ("project_block", 156),
                            ]
                        ],
                        {"label": "Right Column", "required": False},
                    ),
                    160: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 139),
                                ("vertical_alignment", 140),
                                ("left_column", 157),
                                ("center_column", 158),
                                ("right_column", 159),
                            ]
                        ],
                        {"group": "Layout"},
                    ),
                    161: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional category for the card.", "required": False},
                    ),
                    162: ("wagtail.blocks.CharBlock", (), {"help_text": "Title for the card.", "required": True}),
                    163: (
                        "foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock",
                        (),
                        {"help_text": "Optional description text.", "required": False},
                    ),
                    164: (
                        "wagtail.blocks.StructBlock",
                        [[("category", 161), ("title", 162), ("text", 163), ("image", 12), ("link", 96)]],
                        {},
                    ),
                    165: (
                        "wagtail.blocks.StreamBlock",
                        [[("card", 164)]],
                        {"help_text": "Add between 1 and 3 cards.", "max_num": 3, "min_num": 1},
                    ),
                    166: ("wagtail.blocks.StructBlock", [[("cards", 165)]], {"group": "Card Collections"}),
                    167: ("wagtail.blocks.CharBlock", (), {"help_text": "Title for the block", "required": True}),
                    168: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("shape", "Shape"), ("loop-line", "Loop Line")],
                            "help_text": "Select the style of the title",
                        },
                    ),
                    169: ("wagtail.blocks.StructBlock", [[("title", 167), ("style", 168)]], {"group": "Text"}),
                    170: ("wagtail.blocks.StructBlock", [[("title", 118), ("text", 130)]], {}),
                    171: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 5),
                                ("podcast", 141),
                                ("image", 142),
                                ("newsletter_signup", 143),
                                ("video", 148),
                                ("list", 149),
                                ("spacer", 150),
                                ("quote", 151),
                                ("text_social", 170),
                                ("link_button", 152),
                                ("fru_element", 153),
                                ("project_block", 156),
                            ]
                        ],
                        {"label": "Left Column", "required": False},
                    ),
                    172: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 5),
                                ("podcast", 141),
                                ("image", 142),
                                ("newsletter_signup", 143),
                                ("video", 148),
                                ("list", 149),
                                ("spacer", 150),
                                ("quote", 151),
                                ("text_social", 170),
                                ("link_button", 152),
                                ("fru_element", 153),
                                ("project_block", 156),
                            ]
                        ],
                        {"label": "Right Column", "required": False},
                    ),
                    173: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 139),
                                ("vertical_alignment", 140),
                                ("left_column", 171),
                                ("right_column", 172),
                            ]
                        ],
                        {"group": "Layout"},
                    ),
                    174: (
                        "wagtail.blocks.StructBlock",
                        [[("video_url", 144), ("caption", 145), ("caption_url", 147)]],
                        {"group": "Media & Embeds"},
                    ),
                },
            ),
        ),
    ]
