# Generated by Django 5.2.15 on 2026-10-08 18:29

import wagtail.fields
from django.db import migrations

import foundation_cms.legacy_apps.wagtailpages.validators
import foundation_cms.validators


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0090_alter_generalpage_hero_background_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("accordion_block", 5),
                    ("custom_media", 11),
                    ("divider", 12),
                    ("donor_help_contact_us_form", 15),
                    ("featured_card_block", 32),
                    ("flywheel_banner", 35),
                    ("fru_element_block", 38),
                    ("greenhouse_board", 45),
                    ("icon_info_grid", 55),
                    ("iframe_block", 60),
                    ("illustrated_newsletter_signup", 62),
                    ("image", 65),
                    ("image_carousel_block", 75),
                    ("image_grid", 85),
                    ("impact_numbers", 91),
                    ("link_button_block", 92),
                    ("list_block", 97),
                    ("newsletter_signup", 99),
                    ("newsletter_unsubscribe", 101),
                    ("pillar_card_set", 106),
                    ("podcast_block", 109),
                    ("portrait_card_set_block", 115),
                    ("quote", 118),
                    ("rich_text", 119),
                    ("spacer_block", 121),
                    ("spotlight_card_set_block", 126),
                    ("tabbed_content", 137),
                    ("three_column_container_block", 159),
                    ("timely_activations_cards", 165),
                    ("title_block", 168),
                    ("two_column_container_block", 172),
                    ("video_block", 173),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Heading for the Accordion Item", "required": True},
                    ),
                    1: ("foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock", (), {}),
                    2: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 1)]],
                        {"required": False, "use_json_field": True},
                    ),
                    3: ("wagtail.blocks.StructBlock", [[("title", 0), ("content", 2)]], {}),
                    4: ("wagtail.blocks.ListBlock", (3,), {"min_num": 1}),
                    5: ("wagtail.blocks.StructBlock", [[("accordion_items", 4)]], {"group": "Text"}),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title/caption for this media", "required": False},
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("image", "Image"), ("video", "Video")],
                            "help_text": "Select the type of media to display",
                        },
                    ),
                    8: ("wagtail.images.blocks.ImageBlock", [], {}),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Log into Vimeo using 1Password and upload the desired video. Then select the video and click "...", "Video File Links", and select "(mp4, 1920 x 1080)". Copy and paste the link here.',
                            "max_length": 500,
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("portrait", "Portrait"),
                                ("landscape", "Landscape"),
                                ("square", "Square"),
                                ("widescreen", "Widescreen 16:9 (12 columns wide)"),
                            ],
                            "help_text": "Select the orientation of this media",
                        },
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 6), ("content", 7), ("image", 8), ("video_url", 9), ("orientation", 10)]],
                        {"group": "Media & Embeds"},
                    ),
                    12: ("wagtail.blocks.StructBlock", [[]], {"group": "Layout"}),
                    13: ("wagtail.blocks.CharBlock", (), {"default": "Contact Us", "required": True}),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Questions about your donation? Get in touch with our team by using the form below.",
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 13), ("subheading", 14), ("image", 8)]],
                        {"group": "Engagement & Buttons"},
                    ),
                    16: ("wagtail.blocks.CharBlock", (), {"label": "Heading", "max_length": 50, "required": True}),
                    17: (
                        "foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock",
                        (),
                        {"features": ["bold", "italic"], "label": "Description", "max_length": 500, "required": True},
                    ),
                    18: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Image for the card", "label": "Image"},
                    ),
                    19: ("wagtail.blocks.CharBlock", (), {}),
                    20: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("external_url", "External URL"),
                                ("relative_url", "Relative URL"),
                                ("email", "Email"),
                                ("anchor", "Anchor"),
                                ("file", "File"),
                                ("phone", "Phone"),
                            ],
                            "label": "Link to",
                        },
                    ),
                    21: ("wagtail.blocks.PageChooserBlock", (), {"label": "Page", "required": False}),
                    22: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Enter a full URL including http:// or https://",
                            "label": "External URL",
                            "max_length": 300,
                            "required": False,
                        },
                    ),
                    23: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'A path relative to this domain. For example, "/foo/bar" or "?foo=bar".',
                            "label": "Relative URL",
                            "max_length": 300,
                            "required": False,
                            "validators": [foundation_cms.legacy_apps.wagtailpages.validators.RelativeURLValidator()],
                        },
                    ),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'An id attribute of an element on the current page. For example, "#section-1"',
                            "label": "#",
                            "max_length": 300,
                            "required": False,
                            "validators": [foundation_cms.validators.AnchorLinkValidator()],
                        },
                    ),
                    25: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    26: ("wagtail.documents.blocks.DocumentChooserBlock", (), {"label": "File", "required": False}),
                    27: ("wagtail.blocks.CharBlock", (), {"label": "Phone", "max_length": 30, "required": False}),
                    28: ("wagtail.blocks.BooleanBlock", (), {"label": "Open in new window", "required": False}),
                    29: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("btn-primary", "Primary"), ("btn-secondary", "Secondary")]},
                    ),
                    30: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("link-button-block--left", "Left"), ("link-button-block--center", "Center")]},
                    ),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 19),
                                ("link_to", 20),
                                ("page", 21),
                                ("external_url", 22),
                                ("relative_url", 23),
                                ("anchor", 24),
                                ("email", 25),
                                ("file", 26),
                                ("phone", 27),
                                ("new_window", 28),
                                ("style", 29),
                                ("alignment", 30),
                            ]
                        ],
                        {"help_text": "Link button for the card.", "label": "Button", "required": False},
                    ),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 16), ("description", 17), ("image", 18), ("button", 31)]],
                        {"group": "Card Collections"},
                    ),
                    33: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("imagine", "Imagine"), ("co-create", "Co-create"), ("mobilize", "Mobilize")],
                            "help_text": "Select the mission that determines the banner artwork and colors.",
                        },
                    ),
                    34: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Imagine",
                            "help_text": "Defaults to the mission name, but can be customized and translated.",
                            "max_length": 50,
                        },
                    ),
                    35: ("wagtail.blocks.StructBlock", [[("mission", 33), ("heading", 34)]], {"group": "Banners"}),
                    36: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("donation-form", "Donation Form"),
                                ("donor-map", "Donor Map"),
                                ("top-locations", "Top Locations"),
                                ("donation-levels", "Donation Levels"),
                                ("donate-button", "Donate Button"),
                            ],
                            "help_text": "Select the type of Fundraise Up element.",
                        },
                    ),
                    37: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Copy the HTML code generated by the desired Fundraise Up element and paste it here.",
                            "required": True,
                        },
                    ),
                    38: (
                        "wagtail.blocks.StructBlock",
                        [[("fru_element_type", 36), ("fru_element_embed_code", 37)]],
                        {"group": "Engagement & Buttons"},
                    ),
                    39: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "No open roles right now",
                            "help_text": "Shown when the job board has no open positions.",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    40: (
                        "foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock",
                        (),
                        {
                            "default": "<p>We don't have any openings at the moment. Please check back soon.</p>",
                            "help_text": "Shown under the heading when there are no open positions.",
                            "required": False,
                        },
                    ),
                    41: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Our job board is temporarily unavailable",
                            "help_text": "Shown when the job board cannot be loaded at all.",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    42: (
                        "foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock",
                        (),
                        {
                            "default": "<p>We're having trouble loading our open roles. Please try again shortly.</p>",
                            "help_text": "Shown under the heading when the job board cannot be loaded at all.",
                            "required": False,
                        },
                    ),
                    43: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Not seeing our open roles?",
                            "help_text": "Shown under the job board, followed by the link below.",
                            "max_length": 140,
                            "required": False,
                        },
                    ),
                    44: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "View them on Greenhouse",
                            "help_text": "Label for the link to the Greenhouse-hosted board.",
                            "max_length": 60,
                            "required": False,
                        },
                    ),
                    45: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("empty_heading", 39),
                                ("empty_description", 40),
                                ("unavailable_heading", 41),
                                ("unavailable_description", 42),
                                ("hosted_board_notice", 43),
                                ("hosted_board_link_label", 44),
                            ]
                        ],
                        {"group": "Engagement & Buttons"},
                    ),
                    46: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Section heading for this grid", "max_length": 100, "required": True},
                    ),
                    47: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("orange", "Orange"), ("black", "Black")],
                            "help_text": "Color applied to all icons in this grid",
                        },
                    ),
                    48: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("1", "1 column"), ("2", "2 columns"), ("3", "3 columns")],
                            "help_text": "Number of columns on desktop (automatically stacks on mobile)",
                            "label": "Number of columns for this grid",
                        },
                    ),
                    49: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("compact", "Compact (icons + titles only)"),
                                ("detailed", "Detailed (icons + titles + descriptions)"),
                            ],
                            "help_text": "Choose content density. Compact hides descriptions, Detailed shows them.",
                            "label": "Layout style",
                        },
                    ),
                    50: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("chat", "Chat icon"),
                                ("eye-open", "Eye Open icon"),
                                ("gear", "Gear icon"),
                                ("globe", "Globe icon"),
                                ("megaphone", "Megaphone icon"),
                                ("star", "Star icon"),
                            ],
                            "help_text": "Select an icon for this item",
                        },
                    ),
                    51: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title for this item", "max_length": 100, "required": True},
                    ),
                    52: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional description (max 126 characters)",
                            "max_length": 126,
                            "required": False,
                        },
                    ),
                    53: ("wagtail.blocks.StructBlock", [[("icon", 50), ("title", 51), ("description", 52)]], {}),
                    54: ("wagtail.blocks.ListBlock", (53,), {"help_text": "Add icon info items", "min_num": 1}),
                    55: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 46), ("icon_color", 47), ("columns", 48), ("layout_style", 49), ("items", 54)]],
                        {"group": "Card Collections"},
                    ),
                    56: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Please note that only URLs from allow-listed domains will work."},
                    ),
                    57: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Optional integer pixel value for custom iFrame height", "required": False},
                    ),
                    58: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("normal", "Normal"), ("full_width", "Full Width")]},
                    ),
                    59: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": 'Checking this will add "scrolling=no" to the iframe. Use this if your iframe is rendering an unnecessary scroll bar or whitespace below it.',
                            "required": False,
                        },
                    ),
                    60: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 56), ("height", 57), ("iframe_width", 58), ("disable_scroll", 59)]],
                        {"group": "Media & Embeds"},
                    ),
                    61: ("wagtail.snippets.blocks.SnippetChooserBlock", ("snippets.IllustratedNewsletterSignup",), {}),
                    62: (
                        "wagtail.blocks.StructBlock",
                        [[("newsletter_signup", 61)]],
                        {"group": "Engagement & Buttons"},
                    ),
                    63: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title/caption for this image", "required": False},
                    ),
                    64: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("portrait", "Portrait"), ("landscape", "Landscape"), ("square", "Square")],
                            "help_text": "Select the orientation of this image",
                        },
                    ),
                    65: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 63), ("image", 8), ("orientation", 64)]],
                        {"group": "Media & Embeds"},
                    ),
                    66: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional title for the carousel container.", "required": False},
                    ),
                    67: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("portrait", "Portrait"), ("landscape", "Landscape")],
                            "help_text": "Select the orientation for carousel items.",
                            "label": "Orientation",
                        },
                    ),
                    68: ("wagtail.images.blocks.ImageBlock", [], {"help_text": "Select an image for this item."}),
                    69: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional header text shown above the image item.",
                            "max_length": 80,
                            "required": False,
                        },
                    ),
                    70: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional title for the image item (e.g. speaker name or event title).",
                            "max_length": 120,
                            "required": False,
                        },
                    ),
                    71: (
                        "foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock",
                        (),
                        {
                            "help_text": "Optional rich text description for the image item.",
                            "label": "Description",
                            "required": False,
                        },
                    ),
                    72: (
                        "foundation_cms.blocks.link_block.OptionalLinkBlock",
                        (),
                        {"help_text": "Optional link for this item.", "label": "Link", "required": False},
                    ),
                    73: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 68), ("header", 69), ("title", 70), ("description", 71), ("link", 72)]],
                        {},
                    ),
                    74: (
                        "wagtail.blocks.StreamBlock",
                        [[("carousel_item", 73)]],
                        {"help_text": "Items to display in the carousel. Maximum of 10 items.", "max_num": 10},
                    ),
                    75: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 66), ("orientation", 67), ("items", 74)]],
                        {"group": "Card Collections"},
                    ),
                    76: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional heading for this section", "max_length": 100, "required": False},
                    ),
                    77: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("portrait", "Portrait (2:3)"),
                                ("landscape", "Landscape (3:2)"),
                                ("square", "Square (1:1)"),
                            ],
                            "help_text": "Orientation for all images in this section",
                            "label": "Image grid section orientation",
                        },
                    ),
                    78: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("4", "4 per row"), ("5", "5 per row"), ("6", "6 per row")],
                            "label": "Items per section row",
                        },
                    ),
                    79: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["h5", "h6", "large", "bold", "italic"],
                            "help_text": "Optional caption for this image",
                            "required": False,
                        },
                    ),
                    80: (
                        "foundation_cms.blocks.link_block.OptionalLinkBlock",
                        (),
                        {"help_text": "Optional link for both image and caption", "required": False},
                    ),
                    81: ("wagtail.blocks.StructBlock", [[("image", 8), ("caption", 79), ("link", 80)]], {}),
                    82: ("wagtail.blocks.ListBlock", (81,), {"min_num": 1}),
                    83: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 76), ("section_orientation", 77), ("items_per_row", 78), ("items", 82)]],
                        {},
                    ),
                    84: ("wagtail.blocks.ListBlock", (83,), {"label": "Image grid sections", "min_num": 1}),
                    85: ("wagtail.blocks.StructBlock", [[("sections", 84)]], {"group": "Card Collections"}),
                    86: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The full value to animate, including any symbols, commas, decimals, or suffixes (e.g., $5.2M).",
                            "max_length": 5,
                            "required": True,
                        },
                    ),
                    87: ("wagtail.blocks.CharBlock", (), {"help_text": "Heading of the stat", "required": True}),
                    88: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Short description of the stat", "required": False},
                    ),
                    89: (
                        "wagtail.blocks.StructBlock",
                        [[("stat_number", 86), ("stat_heading", 87), ("stat_description", 88)]],
                        {},
                    ),
                    90: (
                        "wagtail.blocks.ListBlock",
                        (89,),
                        {
                            "default": [
                                {"stat_description": "", "stat_heading": "", "stat_number": ""},
                                {"stat_description": "", "stat_heading": "", "stat_number": ""},
                                {"stat_description": "", "stat_heading": "", "stat_number": ""},
                            ],
                            "help_text": "Add exactly 3 stats to appear in the Impact Numbers section",
                            "label": "Impact Stats",
                            "max_num": 3,
                            "min_num": 3,
                        },
                    ),
                    91: ("wagtail.blocks.StructBlock", [[("stats", 90)]], {"group": "Data Display"}),
                    92: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 19),
                                ("link_to", 20),
                                ("page", 21),
                                ("external_url", 22),
                                ("relative_url", 23),
                                ("anchor", 24),
                                ("email", 25),
                                ("file", 26),
                                ("phone", 27),
                                ("new_window", 28),
                                ("style", 29),
                                ("alignment", 30),
                            ]
                        ],
                        {"group": "Engagement & Buttons"},
                    ),
                    93: ("wagtail.blocks.CharBlock", (), {"help_text": "Heading displayed above the list"}),
                    94: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Description displayed above the list", "required": False},
                    ),
                    95: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 19),
                                ("link_to", 20),
                                ("page", 21),
                                ("external_url", 22),
                                ("relative_url", 23),
                                ("anchor", 24),
                                ("email", 25),
                                ("file", 26),
                                ("phone", 27),
                                ("new_window", 28),
                            ]
                        ],
                        {},
                    ),
                    96: ("wagtail.blocks.ListBlock", (95,), {"max_num": 4, "min_num": 1}),
                    97: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 93), ("description", 94), ("items", 96)]],
                        {"group": "Data Display"},
                    ),
                    98: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("snippets.NewsletterSignup",),
                        {"max_num": 1},
                    ),
                    99: (
                        "wagtail.blocks.StructBlock",
                        [[("newsletter_signup", 98)]],
                        {"group": "Engagement & Buttons"},
                    ),
                    100: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("snippets.NewsletterUnsubscribe",),
                        {"max_num": 1},
                    ),
                    101: (
                        "wagtail.blocks.StructBlock",
                        [[("newsletter_unsubscribe", 100)]],
                        {"group": "Engagement & Buttons"},
                    ),
                    102: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Appears as the main heading.", "label": "Headline", "required": False},
                    ),
                    103: (
                        "foundation_cms.blocks.link_block.OptionalLinkBlock",
                        (),
                        {
                            "help_text": "Optional link for the card.",
                            "label": "Call to Action Link",
                            "required": False,
                        },
                    ),
                    104: ("wagtail.blocks.StructBlock", [[("headline", 102), ("cta_link", 103)]], {}),
                    105: (
                        "wagtail.blocks.ListBlock",
                        (104,),
                        {
                            "default": [
                                {"cta_link": [], "headline": ""},
                                {"cta_link": [], "headline": ""},
                                {"cta_link": [], "headline": ""},
                            ],
                            "help_text": "3 cards required.",
                            "label": "Pillar Cards",
                            "max_num": 3,
                            "min_num": 3,
                        },
                    ),
                    106: ("wagtail.blocks.StructBlock", [[("cards", 105)]], {"group": "Card Collections"}),
                    107: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Title of the podcast. <strong>Note:</strong> Does not render on "NothingPersonal" pages.'
                        },
                    ),
                    108: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": 'Optional short description of the podcast. <strong>Note:</strong> Does not render on "NothingPersonal" pages.',
                            "required": False,
                        },
                    ),
                    109: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 107), ("description", 108), ("simplecast_embed_code", 19)]],
                        {"group": "Media & Embeds"},
                    ),
                    110: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Appears above the headline.", "label": "Label", "required": False},
                    ),
                    111: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Optional Image for the card", "label": "Image"},
                    ),
                    112: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 19),
                                ("link_to", 20),
                                ("page", 21),
                                ("external_url", 22),
                                ("relative_url", 23),
                                ("anchor", 24),
                                ("email", 25),
                                ("file", 26),
                                ("phone", 27),
                                ("new_window", 28),
                            ]
                        ],
                        {"help_text": "Link for the card.", "label": "Call to Action Link", "required": True},
                    ),
                    113: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 110), ("headline", 102), ("image", 111), ("cta_link", 112)]],
                        {},
                    ),
                    114: (
                        "wagtail.blocks.ListBlock",
                        (113,),
                        {
                            "help_text": "Minimum of 3 cards required. More than 3 will turn element into a carousel.",
                            "label": "Portrait Cards",
                            "min_num": 3,
                        },
                    ),
                    115: ("wagtail.blocks.StructBlock", [[("cards", 114)]], {"group": "Card Collections"}),
                    116: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    117: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    118: ("wagtail.blocks.StructBlock", [[("quote", 116), ("attribution", 117)]], {"group": "Text"}),
                    119: ("foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock", (), {"group": "Text"}),
                    120: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("small", "Small"),
                                ("medium", "Medium"),
                                ("large", "Large"),
                                ("xlarge", "Extra Large"),
                            ],
                            "help_text": "Select the size of the spacer",
                        },
                    ),
                    121: ("wagtail.blocks.StructBlock", [[("size", 120)]], {"group": "Layout"}),
                    122: ("wagtail.blocks.CharBlock", (), {"label": "Name", "max_length": 50, "required": True}),
                    123: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Image should follow a 1:1 aspect ratio.", "label": "Image"},
                    ),
                    124: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 116), ("name", 122), ("description", 17), ("image", 123)]],
                        {},
                    ),
                    125: (
                        "wagtail.blocks.ListBlock",
                        (124,),
                        {"help_text": "3 cards required.", "label": "Spotlight Cards", "max_num": 3, "min_num": 3},
                    ),
                    126: ("wagtail.blocks.StructBlock", [[("cards", 125)]], {"group": "Card Collections"}),
                    127: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title shown on the tab button", "required": True},
                    ),
                    128: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Subtitle shown under the title on the tab", "required": False},
                    ),
                    129: ("foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock", (), {"required": False}),
                    130: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 63), ("image", 8), ("orientation", 64)]],
                        {"required": False},
                    ),
                    131: ("foundation_cms.blocks.link_block.OptionalLinkBlock", (), {"required": False}),
                    132: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 117), ("subtitle", 117), ("text", 129), ("image", 130), ("link", 131)]],
                        {},
                    ),
                    133: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 19), ("image", 8), ("subtitle", 19), ("link", 131)]],
                        {},
                    ),
                    134: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 1), ("text_image", 132), ("tab_card_set", 133)]],
                        {"help_text": "Add one or more content blocks to the tab.", "min_num": 1, "required": True},
                    ),
                    135: ("wagtail.blocks.StructBlock", [[("title", 127), ("subtitle", 128), ("content", 134)]], {}),
                    136: ("wagtail.blocks.ListBlock", (135,), {"label": "Tabs", "max_num": 8, "min_num": 1}),
                    137: ("wagtail.blocks.StructBlock", [[("tabs", 136)]], {"group": "Card Collections"}),
                    138: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("white", "White"),
                                ("neutral-100", "Grey 100"),
                                ("neutral-200", "Grey 200"),
                                ("neutral-300", "Grey 300"),
                                ("blue-100", "Blue 100"),
                                ("blue-200", "Blue 200"),
                                ("blue-300", "Blue 300"),
                                ("green-100", "Green 100"),
                                ("green-200", "Green 200"),
                                ("green-300", "Green 300"),
                                ("orange-100", "Orange 100"),
                                ("orange-200", "Orange 200"),
                                ("orange-300", "Orange 300"),
                                ("yellow-100", "Yellow 100"),
                                ("yellow-200", "Yellow 200"),
                                ("yellow-300", "Yellow 300"),
                            ]
                        },
                    ),
                    139: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("top", "Top"), ("middle", "Middle"), ("bottom", "Bottom")],
                            "help_text": "Vertical alignment of the columns content",
                        },
                    ),
                    140: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 107), ("description", 108), ("simplecast_embed_code", 19)]],
                        {},
                    ),
                    141: ("wagtail.blocks.StructBlock", [[("title", 63), ("image", 8), ("orientation", 64)]], {}),
                    142: ("wagtail.blocks.StructBlock", [[("newsletter_signup", 98)]], {}),
                    143: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Log into Vimeo, select your desired video, and click 'Copy Link'",
                            "label": "Vimeo Video URL",
                            "required": True,
                        },
                    ),
                    144: ("wagtail.blocks.CharBlock", (), {"help_text": "Optional Caption Text", "required": False}),
                    145: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_to", 20),
                                ("page", 21),
                                ("external_url", 22),
                                ("relative_url", 23),
                                ("anchor", 24),
                                ("email", 25),
                                ("file", 26),
                                ("phone", 27),
                                ("new_window", 28),
                            ]
                        ],
                        {},
                    ),
                    146: (
                        "wagtail.blocks.ListBlock",
                        (145,),
                        {
                            "default": [],
                            "help_text": "Optional URL that this caption should link out to.",
                            "max_num": 1,
                            "min_num": 0,
                        },
                    ),
                    147: (
                        "wagtail.blocks.StructBlock",
                        [[("video_url", 143), ("caption", 144), ("caption_url", 146)]],
                        {},
                    ),
                    148: ("wagtail.blocks.StructBlock", [[("title", 93), ("description", 94), ("items", 96)]], {}),
                    149: ("wagtail.blocks.StructBlock", [[("size", 120)]], {}),
                    150: ("wagtail.blocks.StructBlock", [[("quote", 116), ("attribution", 117)]], {}),
                    151: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 19),
                                ("link_to", 20),
                                ("page", 21),
                                ("external_url", 22),
                                ("relative_url", 23),
                                ("anchor", 24),
                                ("email", 25),
                                ("file", 26),
                                ("phone", 27),
                                ("new_window", 28),
                                ("style", 29),
                                ("alignment", 30),
                            ]
                        ],
                        {},
                    ),
                    152: (
                        "wagtail.blocks.StructBlock",
                        [[("fru_element_type", 36), ("fru_element_embed_code", 37)]],
                        {},
                    ),
                    153: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Project", "page_type": ["gallery_hub.ProjectPage"], "required": True},
                    ),
                    154: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": True, "label": "Show description", "required": False},
                    ),
                    155: ("wagtail.blocks.StructBlock", [[("project", 153), ("show_description", 154)]], {}),
                    156: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 1),
                                ("podcast", 140),
                                ("image", 141),
                                ("newsletter_signup", 142),
                                ("video", 147),
                                ("list", 148),
                                ("spacer", 149),
                                ("quote", 150),
                                ("link_button", 151),
                                ("fru_element", 152),
                                ("project_block", 155),
                            ]
                        ],
                        {"label": "Left Column", "required": False},
                    ),
                    157: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 1),
                                ("podcast", 140),
                                ("image", 141),
                                ("newsletter_signup", 142),
                                ("video", 147),
                                ("list", 148),
                                ("spacer", 149),
                                ("quote", 150),
                                ("link_button", 151),
                                ("fru_element", 152),
                                ("project_block", 155),
                            ]
                        ],
                        {"label": "Center Column", "required": False},
                    ),
                    158: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 1),
                                ("podcast", 140),
                                ("image", 141),
                                ("newsletter_signup", 142),
                                ("video", 147),
                                ("list", 148),
                                ("spacer", 149),
                                ("quote", 150),
                                ("link_button", 151),
                                ("fru_element", 152),
                                ("project_block", 155),
                            ]
                        ],
                        {"label": "Right Column", "required": False},
                    ),
                    159: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 138),
                                ("vertical_alignment", 139),
                                ("left_column", 156),
                                ("center_column", 157),
                                ("right_column", 158),
                            ]
                        ],
                        {"group": "Layout"},
                    ),
                    160: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional category for the card.", "required": False},
                    ),
                    161: ("wagtail.blocks.CharBlock", (), {"help_text": "Title for the card.", "required": True}),
                    162: (
                        "foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock",
                        (),
                        {"help_text": "Optional description text.", "required": False},
                    ),
                    163: (
                        "wagtail.blocks.StructBlock",
                        [[("category", 160), ("title", 161), ("text", 162), ("image", 8), ("link", 95)]],
                        {},
                    ),
                    164: (
                        "wagtail.blocks.StreamBlock",
                        [[("card", 163)]],
                        {"help_text": "Add between 1 and 3 cards.", "max_num": 3, "min_num": 1},
                    ),
                    165: ("wagtail.blocks.StructBlock", [[("cards", 164)]], {"group": "Card Collections"}),
                    166: ("wagtail.blocks.CharBlock", (), {"help_text": "Title for the block", "required": True}),
                    167: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("shape", "Shape"), ("loop-line", "Loop Line")],
                            "help_text": "Select the style of the title",
                        },
                    ),
                    168: ("wagtail.blocks.StructBlock", [[("title", 166), ("style", 167)]], {"group": "Text"}),
                    169: ("wagtail.blocks.StructBlock", [[("title", 117), ("text", 129)]], {}),
                    170: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 1),
                                ("podcast", 140),
                                ("image", 141),
                                ("newsletter_signup", 142),
                                ("video", 147),
                                ("list", 148),
                                ("spacer", 149),
                                ("quote", 150),
                                ("text_social", 169),
                                ("link_button", 151),
                                ("fru_element", 152),
                                ("project_block", 155),
                            ]
                        ],
                        {"label": "Left Column", "required": False},
                    ),
                    171: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 1),
                                ("podcast", 140),
                                ("image", 141),
                                ("newsletter_signup", 142),
                                ("video", 147),
                                ("list", 148),
                                ("spacer", 149),
                                ("quote", 150),
                                ("text_social", 169),
                                ("link_button", 151),
                                ("fru_element", 152),
                                ("project_block", 155),
                            ]
                        ],
                        {"label": "Right Column", "required": False},
                    ),
                    172: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 138),
                                ("vertical_alignment", 139),
                                ("left_column", 170),
                                ("right_column", 171),
                            ]
                        ],
                        {"group": "Layout"},
                    ),
                    173: (
                        "wagtail.blocks.StructBlock",
                        [[("video_url", 143), ("caption", 144), ("caption_url", 146)]],
                        {"group": "Media & Embeds"},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("accordion_block", 5),
                    ("divider", 6),
                    ("featured_card_block", 23),
                    ("flywheel_banner", 26),
                    ("fru_element_block", 29),
                    ("icon_info_grid", 39),
                    ("iframe_block", 44),
                    ("image", 48),
                    ("image_grid", 58),
                    ("impact_numbers", 64),
                    ("link_button_block", 65),
                    ("list_block", 70),
                    ("newsletter_signup", 72),
                    ("newsletter_unsubscribe", 74),
                    ("pillar_card_set", 79),
                    ("podcast_block", 82),
                    ("portrait_card_set_block", 88),
                    ("quote", 91),
                    ("rich_text", 92),
                    ("spacer_block", 94),
                    ("spotlight_card_set_block", 99),
                    ("tabbed_content", 110),
                    ("three_column_container_block", 132),
                    ("timely_activations_cards", 138),
                    ("title_block", 141),
                    ("two_column_container_block", 145),
                    ("video_block", 146),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Heading for the Accordion Item", "required": True},
                    ),
                    1: ("foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock", (), {}),
                    2: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 1)]],
                        {"required": False, "use_json_field": True},
                    ),
                    3: ("wagtail.blocks.StructBlock", [[("title", 0), ("content", 2)]], {}),
                    4: ("wagtail.blocks.ListBlock", (3,), {"min_num": 1}),
                    5: ("wagtail.blocks.StructBlock", [[("accordion_items", 4)]], {"group": "Text"}),
                    6: ("wagtail.blocks.StructBlock", [[]], {"group": "Layout"}),
                    7: ("wagtail.blocks.CharBlock", (), {"label": "Heading", "max_length": 50, "required": True}),
                    8: (
                        "foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock",
                        (),
                        {"features": ["bold", "italic"], "label": "Description", "max_length": 500, "required": True},
                    ),
                    9: ("wagtail.images.blocks.ImageBlock", [], {"help_text": "Image for the card", "label": "Image"}),
                    10: ("wagtail.blocks.CharBlock", (), {}),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("external_url", "External URL"),
                                ("relative_url", "Relative URL"),
                                ("email", "Email"),
                                ("anchor", "Anchor"),
                                ("file", "File"),
                                ("phone", "Phone"),
                            ],
                            "label": "Link to",
                        },
                    ),
                    12: ("wagtail.blocks.PageChooserBlock", (), {"label": "Page", "required": False}),
                    13: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Enter a full URL including http:// or https://",
                            "label": "External URL",
                            "max_length": 300,
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'A path relative to this domain. For example, "/foo/bar" or "?foo=bar".',
                            "label": "Relative URL",
                            "max_length": 300,
                            "required": False,
                            "validators": [foundation_cms.legacy_apps.wagtailpages.validators.RelativeURLValidator()],
                        },
                    ),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'An id attribute of an element on the current page. For example, "#section-1"',
                            "label": "#",
                            "max_length": 300,
                            "required": False,
                            "validators": [foundation_cms.validators.AnchorLinkValidator()],
                        },
                    ),
                    16: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    17: ("wagtail.documents.blocks.DocumentChooserBlock", (), {"label": "File", "required": False}),
                    18: ("wagtail.blocks.CharBlock", (), {"label": "Phone", "max_length": 30, "required": False}),
                    19: ("wagtail.blocks.BooleanBlock", (), {"label": "Open in new window", "required": False}),
                    20: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("btn-primary", "Primary"), ("btn-secondary", "Secondary")]},
                    ),
                    21: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("link-button-block--left", "Left"), ("link-button-block--center", "Center")]},
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 10),
                                ("link_to", 11),
                                ("page", 12),
                                ("external_url", 13),
                                ("relative_url", 14),
                                ("anchor", 15),
                                ("email", 16),
                                ("file", 17),
                                ("phone", 18),
                                ("new_window", 19),
                                ("style", 20),
                                ("alignment", 21),
                            ]
                        ],
                        {"help_text": "Link button for the card.", "label": "Button", "required": False},
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 7), ("description", 8), ("image", 9), ("button", 22)]],
                        {"group": "Card Collections"},
                    ),
                    24: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("imagine", "Imagine"), ("co-create", "Co-create"), ("mobilize", "Mobilize")],
                            "help_text": "Select the mission that determines the banner artwork and colors.",
                        },
                    ),
                    25: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Imagine",
                            "help_text": "Defaults to the mission name, but can be customized and translated.",
                            "max_length": 50,
                        },
                    ),
                    26: ("wagtail.blocks.StructBlock", [[("mission", 24), ("heading", 25)]], {"group": "Banners"}),
                    27: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("donation-form", "Donation Form"),
                                ("donor-map", "Donor Map"),
                                ("top-locations", "Top Locations"),
                                ("donation-levels", "Donation Levels"),
                                ("donate-button", "Donate Button"),
                            ],
                            "help_text": "Select the type of Fundraise Up element.",
                        },
                    ),
                    28: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Copy the HTML code generated by the desired Fundraise Up element and paste it here.",
                            "required": True,
                        },
                    ),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [[("fru_element_type", 27), ("fru_element_embed_code", 28)]],
                        {"group": "Engagement & Buttons"},
                    ),
                    30: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Section heading for this grid", "max_length": 100, "required": True},
                    ),
                    31: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("orange", "Orange"), ("black", "Black")],
                            "help_text": "Color applied to all icons in this grid",
                        },
                    ),
                    32: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("1", "1 column"), ("2", "2 columns"), ("3", "3 columns")],
                            "help_text": "Number of columns on desktop (automatically stacks on mobile)",
                            "label": "Number of columns for this grid",
                        },
                    ),
                    33: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("compact", "Compact (icons + titles only)"),
                                ("detailed", "Detailed (icons + titles + descriptions)"),
                            ],
                            "help_text": "Choose content density. Compact hides descriptions, Detailed shows them.",
                            "label": "Layout style",
                        },
                    ),
                    34: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("chat", "Chat icon"),
                                ("eye-open", "Eye Open icon"),
                                ("gear", "Gear icon"),
                                ("globe", "Globe icon"),
                                ("megaphone", "Megaphone icon"),
                                ("star", "Star icon"),
                            ],
                            "help_text": "Select an icon for this item",
                        },
                    ),
                    35: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title for this item", "max_length": 100, "required": True},
                    ),
                    36: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional description (max 126 characters)",
                            "max_length": 126,
                            "required": False,
                        },
                    ),
                    37: ("wagtail.blocks.StructBlock", [[("icon", 34), ("title", 35), ("description", 36)]], {}),
                    38: ("wagtail.blocks.ListBlock", (37,), {"help_text": "Add icon info items", "min_num": 1}),
                    39: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 30), ("icon_color", 31), ("columns", 32), ("layout_style", 33), ("items", 38)]],
                        {"group": "Card Collections"},
                    ),
                    40: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Please note that only URLs from allow-listed domains will work."},
                    ),
                    41: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Optional integer pixel value for custom iFrame height", "required": False},
                    ),
                    42: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("normal", "Normal"), ("full_width", "Full Width")]},
                    ),
                    43: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": 'Checking this will add "scrolling=no" to the iframe. Use this if your iframe is rendering an unnecessary scroll bar or whitespace below it.',
                            "required": False,
                        },
                    ),
                    44: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 40), ("height", 41), ("iframe_width", 42), ("disable_scroll", 43)]],
                        {"group": "Media & Embeds"},
                    ),
                    45: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title/caption for this image", "required": False},
                    ),
                    46: ("wagtail.images.blocks.ImageBlock", [], {}),
                    47: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("portrait", "Portrait"), ("landscape", "Landscape"), ("square", "Square")],
                            "help_text": "Select the orientation of this image",
                        },
                    ),
                    48: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 45), ("image", 46), ("orientation", 47)]],
                        {"group": "Media & Embeds"},
                    ),
                    49: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional heading for this section", "max_length": 100, "required": False},
                    ),
                    50: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("portrait", "Portrait (2:3)"),
                                ("landscape", "Landscape (3:2)"),
                                ("square", "Square (1:1)"),
                            ],
                            "help_text": "Orientation for all images in this section",
                            "label": "Image grid section orientation",
                        },
                    ),
                    51: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("4", "4 per row"), ("5", "5 per row"), ("6", "6 per row")],
                            "label": "Items per section row",
                        },
                    ),
                    52: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["h5", "h6", "large", "bold", "italic"],
                            "help_text": "Optional caption for this image",
                            "required": False,
                        },
                    ),
                    53: (
                        "foundation_cms.blocks.link_block.OptionalLinkBlock",
                        (),
                        {"help_text": "Optional link for both image and caption", "required": False},
                    ),
                    54: ("wagtail.blocks.StructBlock", [[("image", 46), ("caption", 52), ("link", 53)]], {}),
                    55: ("wagtail.blocks.ListBlock", (54,), {"min_num": 1}),
                    56: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 49), ("section_orientation", 50), ("items_per_row", 51), ("items", 55)]],
                        {},
                    ),
                    57: ("wagtail.blocks.ListBlock", (56,), {"label": "Image grid sections", "min_num": 1}),
                    58: ("wagtail.blocks.StructBlock", [[("sections", 57)]], {"group": "Card Collections"}),
                    59: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The full value to animate, including any symbols, commas, decimals, or suffixes (e.g., $5.2M).",
                            "max_length": 5,
                            "required": True,
                        },
                    ),
                    60: ("wagtail.blocks.CharBlock", (), {"help_text": "Heading of the stat", "required": True}),
                    61: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Short description of the stat", "required": False},
                    ),
                    62: (
                        "wagtail.blocks.StructBlock",
                        [[("stat_number", 59), ("stat_heading", 60), ("stat_description", 61)]],
                        {},
                    ),
                    63: (
                        "wagtail.blocks.ListBlock",
                        (62,),
                        {
                            "default": [
                                {"stat_description": "", "stat_heading": "", "stat_number": ""},
                                {"stat_description": "", "stat_heading": "", "stat_number": ""},
                                {"stat_description": "", "stat_heading": "", "stat_number": ""},
                            ],
                            "help_text": "Add exactly 3 stats to appear in the Impact Numbers section",
                            "label": "Impact Stats",
                            "max_num": 3,
                            "min_num": 3,
                        },
                    ),
                    64: ("wagtail.blocks.StructBlock", [[("stats", 63)]], {"group": "Data Display"}),
                    65: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 10),
                                ("link_to", 11),
                                ("page", 12),
                                ("external_url", 13),
                                ("relative_url", 14),
                                ("anchor", 15),
                                ("email", 16),
                                ("file", 17),
                                ("phone", 18),
                                ("new_window", 19),
                                ("style", 20),
                                ("alignment", 21),
                            ]
                        ],
                        {"group": "Engagement & Buttons"},
                    ),
                    66: ("wagtail.blocks.CharBlock", (), {"help_text": "Heading displayed above the list"}),
                    67: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Description displayed above the list", "required": False},
                    ),
                    68: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 10),
                                ("link_to", 11),
                                ("page", 12),
                                ("external_url", 13),
                                ("relative_url", 14),
                                ("anchor", 15),
                                ("email", 16),
                                ("file", 17),
                                ("phone", 18),
                                ("new_window", 19),
                            ]
                        ],
                        {},
                    ),
                    69: ("wagtail.blocks.ListBlock", (68,), {"max_num": 4, "min_num": 1}),
                    70: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 66), ("description", 67), ("items", 69)]],
                        {"group": "Data Display"},
                    ),
                    71: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("snippets.NewsletterSignup",),
                        {"max_num": 1},
                    ),
                    72: (
                        "wagtail.blocks.StructBlock",
                        [[("newsletter_signup", 71)]],
                        {"group": "Engagement & Buttons"},
                    ),
                    73: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("snippets.NewsletterUnsubscribe",),
                        {"max_num": 1},
                    ),
                    74: (
                        "wagtail.blocks.StructBlock",
                        [[("newsletter_unsubscribe", 73)]],
                        {"group": "Engagement & Buttons"},
                    ),
                    75: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Appears as the main heading.", "label": "Headline", "required": False},
                    ),
                    76: (
                        "foundation_cms.blocks.link_block.OptionalLinkBlock",
                        (),
                        {
                            "help_text": "Optional link for the card.",
                            "label": "Call to Action Link",
                            "required": False,
                        },
                    ),
                    77: ("wagtail.blocks.StructBlock", [[("headline", 75), ("cta_link", 76)]], {}),
                    78: (
                        "wagtail.blocks.ListBlock",
                        (77,),
                        {
                            "default": [
                                {"cta_link": [], "headline": ""},
                                {"cta_link": [], "headline": ""},
                                {"cta_link": [], "headline": ""},
                            ],
                            "help_text": "3 cards required.",
                            "label": "Pillar Cards",
                            "max_num": 3,
                            "min_num": 3,
                        },
                    ),
                    79: ("wagtail.blocks.StructBlock", [[("cards", 78)]], {"group": "Card Collections"}),
                    80: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Title of the podcast. <strong>Note:</strong> Does not render on "NothingPersonal" pages.'
                        },
                    ),
                    81: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": 'Optional short description of the podcast. <strong>Note:</strong> Does not render on "NothingPersonal" pages.',
                            "required": False,
                        },
                    ),
                    82: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 80), ("description", 81), ("simplecast_embed_code", 10)]],
                        {"group": "Media & Embeds"},
                    ),
                    83: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Appears above the headline.", "label": "Label", "required": False},
                    ),
                    84: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Optional Image for the card", "label": "Image"},
                    ),
                    85: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 10),
                                ("link_to", 11),
                                ("page", 12),
                                ("external_url", 13),
                                ("relative_url", 14),
                                ("anchor", 15),
                                ("email", 16),
                                ("file", 17),
                                ("phone", 18),
                                ("new_window", 19),
                            ]
                        ],
                        {"help_text": "Link for the card.", "label": "Call to Action Link", "required": True},
                    ),
                    86: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 83), ("headline", 75), ("image", 84), ("cta_link", 85)]],
                        {},
                    ),
                    87: (
                        "wagtail.blocks.ListBlock",
                        (86,),
                        {
                            "help_text": "Minimum of 3 cards required. More than 3 will turn element into a carousel.",
                            "label": "Portrait Cards",
                            "min_num": 3,
                        },
                    ),
                    88: ("wagtail.blocks.StructBlock", [[("cards", 87)]], {"group": "Card Collections"}),
                    89: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    90: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    91: ("wagtail.blocks.StructBlock", [[("quote", 89), ("attribution", 90)]], {"group": "Text"}),
                    92: ("foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock", (), {"group": "Text"}),
                    93: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("small", "Small"),
                                ("medium", "Medium"),
                                ("large", "Large"),
                                ("xlarge", "Extra Large"),
                            ],
                            "help_text": "Select the size of the spacer",
                        },
                    ),
                    94: ("wagtail.blocks.StructBlock", [[("size", 93)]], {"group": "Layout"}),
                    95: ("wagtail.blocks.CharBlock", (), {"label": "Name", "max_length": 50, "required": True}),
                    96: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Image should follow a 1:1 aspect ratio.", "label": "Image"},
                    ),
                    97: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 89), ("name", 95), ("description", 8), ("image", 96)]],
                        {},
                    ),
                    98: (
                        "wagtail.blocks.ListBlock",
                        (97,),
                        {"help_text": "3 cards required.", "label": "Spotlight Cards", "max_num": 3, "min_num": 3},
                    ),
                    99: ("wagtail.blocks.StructBlock", [[("cards", 98)]], {"group": "Card Collections"}),
                    100: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title shown on the tab button", "required": True},
                    ),
                    101: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Subtitle shown under the title on the tab", "required": False},
                    ),
                    102: ("foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock", (), {"required": False}),
                    103: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 45), ("image", 46), ("orientation", 47)]],
                        {"required": False},
                    ),
                    104: ("foundation_cms.blocks.link_block.OptionalLinkBlock", (), {"required": False}),
                    105: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 90), ("subtitle", 90), ("text", 102), ("image", 103), ("link", 104)]],
                        {},
                    ),
                    106: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 10), ("image", 46), ("subtitle", 10), ("link", 104)]],
                        {},
                    ),
                    107: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 1), ("text_image", 105), ("tab_card_set", 106)]],
                        {"help_text": "Add one or more content blocks to the tab.", "min_num": 1, "required": True},
                    ),
                    108: ("wagtail.blocks.StructBlock", [[("title", 100), ("subtitle", 101), ("content", 107)]], {}),
                    109: ("wagtail.blocks.ListBlock", (108,), {"label": "Tabs", "max_num": 8, "min_num": 1}),
                    110: ("wagtail.blocks.StructBlock", [[("tabs", 109)]], {"group": "Card Collections"}),
                    111: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("white", "White"),
                                ("neutral-100", "Grey 100"),
                                ("neutral-200", "Grey 200"),
                                ("neutral-300", "Grey 300"),
                                ("blue-100", "Blue 100"),
                                ("blue-200", "Blue 200"),
                                ("blue-300", "Blue 300"),
                                ("green-100", "Green 100"),
                                ("green-200", "Green 200"),
                                ("green-300", "Green 300"),
                                ("orange-100", "Orange 100"),
                                ("orange-200", "Orange 200"),
                                ("orange-300", "Orange 300"),
                                ("yellow-100", "Yellow 100"),
                                ("yellow-200", "Yellow 200"),
                                ("yellow-300", "Yellow 300"),
                            ]
                        },
                    ),
                    112: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("top", "Top"), ("middle", "Middle"), ("bottom", "Bottom")],
                            "help_text": "Vertical alignment of the columns content",
                        },
                    ),
                    113: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 80), ("description", 81), ("simplecast_embed_code", 10)]],
                        {},
                    ),
                    114: ("wagtail.blocks.StructBlock", [[("title", 45), ("image", 46), ("orientation", 47)]], {}),
                    115: ("wagtail.blocks.StructBlock", [[("newsletter_signup", 71)]], {}),
                    116: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Log into Vimeo, select your desired video, and click 'Copy Link'",
                            "label": "Vimeo Video URL",
                            "required": True,
                        },
                    ),
                    117: ("wagtail.blocks.CharBlock", (), {"help_text": "Optional Caption Text", "required": False}),
                    118: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_to", 11),
                                ("page", 12),
                                ("external_url", 13),
                                ("relative_url", 14),
                                ("anchor", 15),
                                ("email", 16),
                                ("file", 17),
                                ("phone", 18),
                                ("new_window", 19),
                            ]
                        ],
                        {},
                    ),
                    119: (
                        "wagtail.blocks.ListBlock",
                        (118,),
                        {
                            "default": [],
                            "help_text": "Optional URL that this caption should link out to.",
                            "max_num": 1,
                            "min_num": 0,
                        },
                    ),
                    120: (
                        "wagtail.blocks.StructBlock",
                        [[("video_url", 116), ("caption", 117), ("caption_url", 119)]],
                        {},
                    ),
                    121: ("wagtail.blocks.StructBlock", [[("title", 66), ("description", 67), ("items", 69)]], {}),
                    122: ("wagtail.blocks.StructBlock", [[("size", 93)]], {}),
                    123: ("wagtail.blocks.StructBlock", [[("quote", 89), ("attribution", 90)]], {}),
                    124: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 10),
                                ("link_to", 11),
                                ("page", 12),
                                ("external_url", 13),
                                ("relative_url", 14),
                                ("anchor", 15),
                                ("email", 16),
                                ("file", 17),
                                ("phone", 18),
                                ("new_window", 19),
                                ("style", 20),
                                ("alignment", 21),
                            ]
                        ],
                        {},
                    ),
                    125: (
                        "wagtail.blocks.StructBlock",
                        [[("fru_element_type", 27), ("fru_element_embed_code", 28)]],
                        {},
                    ),
                    126: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Project", "page_type": ["gallery_hub.ProjectPage"], "required": True},
                    ),
                    127: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": True, "label": "Show description", "required": False},
                    ),
                    128: ("wagtail.blocks.StructBlock", [[("project", 126), ("show_description", 127)]], {}),
                    129: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 1),
                                ("podcast", 113),
                                ("image", 114),
                                ("newsletter_signup", 115),
                                ("video", 120),
                                ("list", 121),
                                ("spacer", 122),
                                ("quote", 123),
                                ("link_button", 124),
                                ("fru_element", 125),
                                ("project_block", 128),
                            ]
                        ],
                        {"label": "Left Column", "required": False},
                    ),
                    130: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 1),
                                ("podcast", 113),
                                ("image", 114),
                                ("newsletter_signup", 115),
                                ("video", 120),
                                ("list", 121),
                                ("spacer", 122),
                                ("quote", 123),
                                ("link_button", 124),
                                ("fru_element", 125),
                                ("project_block", 128),
                            ]
                        ],
                        {"label": "Center Column", "required": False},
                    ),
                    131: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 1),
                                ("podcast", 113),
                                ("image", 114),
                                ("newsletter_signup", 115),
                                ("video", 120),
                                ("list", 121),
                                ("spacer", 122),
                                ("quote", 123),
                                ("link_button", 124),
                                ("fru_element", 125),
                                ("project_block", 128),
                            ]
                        ],
                        {"label": "Right Column", "required": False},
                    ),
                    132: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 111),
                                ("vertical_alignment", 112),
                                ("left_column", 129),
                                ("center_column", 130),
                                ("right_column", 131),
                            ]
                        ],
                        {"group": "Layout"},
                    ),
                    133: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional category for the card.", "required": False},
                    ),
                    134: ("wagtail.blocks.CharBlock", (), {"help_text": "Title for the card.", "required": True}),
                    135: (
                        "foundation_cms.blocks.custom_rich_text_block.CustomRichTextBlock",
                        (),
                        {"help_text": "Optional description text.", "required": False},
                    ),
                    136: (
                        "wagtail.blocks.StructBlock",
                        [[("category", 133), ("title", 134), ("text", 135), ("image", 46), ("link", 68)]],
                        {},
                    ),
                    137: (
                        "wagtail.blocks.StreamBlock",
                        [[("card", 136)]],
                        {"help_text": "Add between 1 and 3 cards.", "max_num": 3, "min_num": 1},
                    ),
                    138: ("wagtail.blocks.StructBlock", [[("cards", 137)]], {"group": "Card Collections"}),
                    139: ("wagtail.blocks.CharBlock", (), {"help_text": "Title for the block", "required": True}),
                    140: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("shape", "Shape"), ("loop-line", "Loop Line")],
                            "help_text": "Select the style of the title",
                        },
                    ),
                    141: ("wagtail.blocks.StructBlock", [[("title", 139), ("style", 140)]], {"group": "Text"}),
                    142: ("wagtail.blocks.StructBlock", [[("title", 90), ("text", 102)]], {}),
                    143: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 1),
                                ("podcast", 113),
                                ("image", 114),
                                ("newsletter_signup", 115),
                                ("video", 120),
                                ("list", 121),
                                ("spacer", 122),
                                ("quote", 123),
                                ("text_social", 142),
                                ("link_button", 124),
                                ("fru_element", 125),
                                ("project_block", 128),
                            ]
                        ],
                        {"label": "Left Column", "required": False},
                    ),
                    144: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 1),
                                ("podcast", 113),
                                ("image", 114),
                                ("newsletter_signup", 115),
                                ("video", 120),
                                ("list", 121),
                                ("spacer", 122),
                                ("quote", 123),
                                ("text_social", 142),
                                ("link_button", 124),
                                ("fru_element", 125),
                                ("project_block", 128),
                            ]
                        ],
                        {"label": "Right Column", "required": False},
                    ),
                    145: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 111),
                                ("vertical_alignment", 112),
                                ("left_column", 143),
                                ("right_column", 144),
                            ]
                        ],
                        {"group": "Layout"},
                    ),
                    146: (
                        "wagtail.blocks.StructBlock",
                        [[("video_url", 116), ("caption", 117), ("caption_url", 119)]],
                        {"group": "Media & Embeds"},
                    ),
                },
            ),
        ),
    ]
