# Generated by Django 3.2.16 on 2022-10-27 17:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mozfest", "0013_adds_group_listing_block"),
        ("mozfest", "0013_adds_image_teaser_block"),
    ]

    operations = []
