# Generated by Django 3.2.23 on 2023-12-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mozfest", "0038_adds_signup_with_background_block"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mozfesthomepage",
            name="banner_link_url",
            field=models.CharField(
                blank=True, help_text="Link presented to the user as a CTA in the banner.", max_length=2048
            ),
        ),
        migrations.AlterField(
            model_name="mozfestlandingpage",
            name="banner_link_url",
            field=models.CharField(
                blank=True, help_text="Link presented to the user as a CTA in the banner.", max_length=2048
            ),
        ),
    ]
