# Generated by Django 4.2.9 on 2024-01-23 17:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mozfest", "0044_configure_cards_per_row_on_listing_block"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newslettersignupwithbackground",
            options={"ordering": ["name"], "verbose_name": "Mozfest Newsletter Signup"},
        ),
    ]
