# Generated by Django 4.2.27 on 2026-01-14 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mozfest", "0072_remove_mozfesthomepage_banner_link_text_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mozfesthomepage",
            options={"verbose_name": "MozFest Homepage (Legacy)", "verbose_name_plural": "MozFest Homepages (Legacy)"},
        ),
        migrations.AlterModelOptions(
            name="mozfestlandingpage",
            options={
                "verbose_name": "MozFest Landing Page (Legacy)",
                "verbose_name_plural": "MozFest Landing Pages (Legacy)",
            },
        ),
        migrations.AlterModelOptions(
            name="mozfestprimarypage",
            options={
                "verbose_name": "MozFest Primary Page (Legacy)",
                "verbose_name_plural": "MozFest Primary Pages (Legacy)",
            },
        ),
        migrations.AlterModelOptions(
            name="newslettersignupwithbackground",
            options={
                "ordering": ["name"],
                "verbose_name": "MozFest Newsletter Signup (Legacy)",
                "verbose_name_plural": "MozFest Newsletter Signups (Legacy)",
            },
        ),
        migrations.AlterModelOptions(
            name="ticket",
            options={
                "ordering": ["name"],
                "verbose_name": "Ticket (Legacy)",
                "verbose_name_plural": "Tickets (Legacy)",
            },
        ),
    ]
