# Generated by Django 5.2.13 on 2026-05-19 00:22

import wagtail.fields
from django.db import migrations

import foundation_cms.legacy_apps.wagtailpages.pagemodels.blog.blog_topic
import foundation_cms.legacy_apps.wagtailpages.pagemodels.profiles
import foundation_cms.legacy_apps.wagtailpages.validators


class Migration(migrations.Migration):

    dependencies = [
        ("mozfest", "0073_add_legacy_to_verbose_names"),
        ("wagtailpages", "0175_strip_pulse_blocks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mozfestprimarypage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("paragraph", 0),
                    ("card_grid", 19),
                    ("image", 25),
                    ("image_text", 30),
                    ("image_text_mini", 32),
                    ("image_grid", 39),
                    ("video", 42),
                    ("iframe", 47),
                    ("linkbutton", 49),
                    ("spacer", 51),
                    ("single_quote", 54),
                    ("recent_blog_entries", 57),
                    ("blog_set", 60),
                    ("datawrapper", 63),
                    ("listing", 72),
                    ("profiles", 76),
                    ("group_listing_block", 83),
                    ("image_feature", 86),
                    ("image_teaser_block", 88),
                    ("text_only_teaser", 94),
                    ("block_with_aside", 100),
                    ("accordion", 107),
                    ("session_slider", 124),
                    ("current_events_slider", 133),
                    ("spaces", 136),
                    ("tito_widget", 141),
                    ("statistics", 146),
                    ("carousel_and_text", 149),
                    ("tickets", 152),
                    ("dark_quote", 54),
                    ("cta", 154),
                    ("newsletter_signup", 156),
                    ("mixed_content", 164),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "link",
                                "h2",
                                "h3",
                                "h4",
                                "h5",
                                "ol",
                                "ul",
                                "hr",
                                "document-link",
                                "large",
                            ],
                            "template": "wagtailpages/blocks/rich_text_block.html",
                        },
                    ),
                    1: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Alt text for card's image.", "required": False},
                    ),
                    3: ("wagtail.blocks.CharBlock", (), {"help_text": "Heading for the card."}),
                    4: ("wagtail.blocks.TextBlock", (), {"help_text": "Body text of the card."}),
                    5: ("wagtail.blocks.CharBlock", (), {}),
                    6: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("external_url", "External URL"),
                                ("relative_url", "Relative URL"),
                                ("email", "Email"),
                                ("anchor", "Anchor"),
                                ("file", "File"),
                                ("phone", "Phone"),
                            ],
                            "label": "Link to",
                        },
                    ),
                    7: ("wagtail.blocks.PageChooserBlock", (), {"label": "Page", "required": False}),
                    8: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Enter a full URL including http:// or https://",
                            "label": "External URL",
                            "max_length": 300,
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'A path relative to this domain. For example, "/foo/bar" or "?foo=bar".',
                            "label": "Relative URL",
                            "max_length": 300,
                            "required": False,
                            "validators": [foundation_cms.legacy_apps.wagtailpages.validators.RelativeURLValidator()],
                        },
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'An id attribute of an element on the current page. For example, "#section-1"',
                            "label": "#",
                            "max_length": 300,
                            "required": False,
                            "validators": [foundation_cms.legacy_apps.wagtailpages.validators.AnchorLinkValidator()],
                        },
                    ),
                    11: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    12: ("wagtail.documents.blocks.DocumentChooserBlock", (), {"label": "File", "required": False}),
                    13: ("wagtail.blocks.CharBlock", (), {"label": "Phone", "max_length": 30, "required": False}),
                    14: ("wagtail.blocks.BooleanBlock", (), {"label": "Open in new window", "required": False}),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 5),
                                ("link_to", 6),
                                ("page", 7),
                                ("external_url", 8),
                                ("relative_url", 9),
                                ("anchor", 10),
                                ("email", 11),
                                ("file", 12),
                                ("phone", 13),
                                ("new_window", 14),
                            ]
                        ],
                        {},
                    ),
                    16: (
                        "wagtail.blocks.ListBlock",
                        (15,),
                        {"help_text": "Optional link that this card should link out to.", "max_num": 1, "min_num": 0},
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 1), ("alt_text", 2), ("title", 3), ("body", 4), ("link", 16)]],
                        {},
                    ),
                    18: ("wagtail.blocks.ListBlock", (17,), {"help_text": "Please use a minimum of 2 cards."}),
                    19: ("wagtail.blocks.StructBlock", [[("cards", 18)]], {}),
                    20: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Image description (for screen readers).", "required": True},
                    ),
                    21: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_to", 6),
                                ("page", 7),
                                ("external_url", 8),
                                ("relative_url", 9),
                                ("anchor", 10),
                                ("email", 11),
                                ("file", 12),
                                ("phone", 13),
                                ("new_window", 14),
                            ]
                        ],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.ListBlock",
                        (22,),
                        {
                            "help_text": "Optional URL that this caption should link out to.",
                            "max_num": 1,
                            "min_num": 0,
                        },
                    ),
                    24: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("normal", "Normal"), ("wide", "Wide"), ("full_width", "Full Width")],
                            "help_text": "Wide images are col-12, Full-Width Images reach both ends of the screen (16:6 images recommended for full width)",
                        },
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 1), ("altText", 20), ("caption", 21), ("caption_url", 23), ("image_width", 24)]],
                        {},
                    ),
                    26: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "link",
                                "h2",
                                "h3",
                                "h4",
                                "h5",
                                "ol",
                                "ul",
                                "hr",
                                "document-link",
                            ]
                        },
                    ),
                    27: (
                        "wagtail.blocks.ListBlock",
                        (22,),
                        {"help_text": "Optional URL that this image should link out to.", "max_num": 1, "min_num": 0},
                    ),
                    28: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"help_text": "Optional divider above content block.", "required": False},
                    ),
                    29: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"help_text": "Optional divider below content block.", "required": False},
                    ),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 1),
                                ("altText", 20),
                                ("text", 26),
                                ("url", 27),
                                ("top_divider", 28),
                                ("bottom_divider", 29),
                            ]
                        ],
                        {},
                    ),
                    31: ("wagtail.blocks.RichTextBlock", (), {"features": ["bold", "italic", "link"]}),
                    32: ("wagtail.blocks.StructBlock", [[("image", 1), ("altText", 20), ("text", 31)]], {}),
                    33: ("wagtail.blocks.CharBlock", (), {"help_text": "Alt text for this image.", "required": False}),
                    34: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Please remember to properly attribute any images we use.", "required": False},
                    ),
                    35: (
                        "wagtail.blocks.ListBlock",
                        (22,),
                        {
                            "help_text": "Optional link that this figure should link out to.",
                            "max_num": 1,
                            "min_num": 0,
                        },
                    ),
                    36: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "If left checked, the image will be cropped to be square.",
                            "required": False,
                        },
                    ),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 1), ("alt_text", 33), ("caption", 34), ("link", 35), ("square_image", 36)]],
                        {},
                    ),
                    38: ("wagtail.blocks.ListBlock", (37,), {}),
                    39: ("wagtail.blocks.StructBlock", [[("grid_items", 38)]], {}),
                    40: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "For YouTube: go to your YouTube video and click “Share,” then “Embed,” and then copy and paste the provided URL only. For example: https://www.youtube.com/embed/3FIVXBawyQw For Vimeo: follow similar steps to grab the embed URL. For example: https://player.vimeo.com/video/9004979",
                            "label": "Embed URL",
                        },
                    ),
                    41: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("normal", "Normal"), ("wide", "Wide"), ("full_width", "Full Width")],
                            "help_text": "Wide videos are col-12, Full-Width videos reach both ends of the screen.",
                        },
                    ),
                    42: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 40), ("caption", 21), ("caption_url", 23), ("video_width", 41)]],
                        {},
                    ),
                    43: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Please note that only URLs from allow-listed domains will work."},
                    ),
                    44: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Optional integer pixel value for custom iFrame height", "required": False},
                    ),
                    45: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("normal", "Normal"), ("wide", "Wide"), ("full_width", "Full Width")],
                            "help_text": "Wide iframes are col-12, Full-Width iframes reach both ends of the screen",
                        },
                    ),
                    46: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": 'Checking this will add "scrolling=no" to the iframe. Use this if your iframe is rendering an unnecessary scroll bar or whitespace below it.',
                            "required": False,
                        },
                    ),
                    47: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("url", 43),
                                ("height", 44),
                                ("caption", 21),
                                ("caption_url", 23),
                                ("iframe_width", 45),
                                ("disable_scroll", 46),
                            ]
                        ],
                        {},
                    ),
                    48: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("btn-primary", "Primary button"), ("btn-secondary", "Secondary button")]},
                    ),
                    49: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 5),
                                ("link_to", 6),
                                ("page", 7),
                                ("external_url", 8),
                                ("relative_url", 9),
                                ("anchor", 10),
                                ("email", 11),
                                ("file", 12),
                                ("phone", 13),
                                ("new_window", 14),
                                ("styling", 48),
                            ]
                        ],
                        {},
                    ),
                    50: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("1", "quarter spacing"),
                                ("2", "half spacing"),
                                ("3", "single spacing"),
                                ("4", "one and a half spacing"),
                                ("5", "triple spacing"),
                            ]
                        },
                    ),
                    51: ("wagtail.blocks.StructBlock", [[("size", 50)]], {}),
                    52: ("wagtail.blocks.RichTextBlock", (), {"features": ["bold"]}),
                    53: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "link", "large"], "required": False},
                    ),
                    54: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 52), ("attribution", 21), ("attribution_info", 53)]],
                        {},
                    ),
                    55: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Test this filter at foundation.mozilla.org/blog/tags/",
                            "label": "Filter by Tag",
                            "required": False,
                        },
                    ),
                    56: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": foundation_cms.legacy_apps.wagtailpages.pagemodels.blog.blog_topic.BlogPageTopic.get_topics,
                            "help_text": "Test this filter at foundation.mozilla.org/blog/topic/",
                            "label": "Filter by Topic",
                            "required": False,
                        },
                    ),
                    57: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 21),
                                ("tag_filter", 55),
                                ("topic_filter", 56),
                                ("top_divider", 28),
                                ("bottom_divider", 29),
                            ]
                        ],
                        {},
                    ),
                    58: ("wagtail.blocks.PageChooserBlock", (), {"page_type": ["wagtailpages.BlogPage"]}),
                    59: ("wagtail.blocks.ListBlock", (58,), {}),
                    60: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 5), ("top_divider", 28), ("bottom_divider", 29), ("blog_pages", 59)]],
                        {},
                    ),
                    61: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {
                            "help_text": 'Enter the "visualization only" link of the Datawrapper chart. It looks something like this: https://datawrapper.dwcdn.net/KwSKp/1/',
                            "icon": "image",
                            "template": "wagtailpages/blocks/datawrapper_embed_block.html",
                        },
                    ),
                    62: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "If checked, the table will render wider than the other page body content.",
                            "required": False,
                        },
                    ),
                    63: ("wagtail.blocks.StructBlock", [[("datawrapper", 61), ("wide", 62)]], {}),
                    64: ("wagtail.blocks.CharBlock", (), {"help_text": "Heading for the block.", "required": False}),
                    65: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Metadata to highlight on the card.", "required": False},
                    ),
                    66: ("wagtail.blocks.CharBlock", (), {"help_text": "Generic metadata.", "required": False}),
                    67: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold"], "help_text": "Body text of the card.", "required": False},
                    ),
                    68: (
                        "wagtail.blocks.ListBlock",
                        (22,),
                        {"help_text": "Optional link that this card should link out to.", "max_num": 1, "min_num": 0},
                    ),
                    69: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 1),
                                ("alt_text", 2),
                                ("title", 3),
                                ("highlighted_metadata", 65),
                                ("metadata", 66),
                                ("body", 67),
                                ("link", 68),
                            ]
                        ],
                        {},
                    ),
                    70: (
                        "wagtail.blocks.ListBlock",
                        (69,),
                        {"help_text": "Please use a minimum of 2 cards.", "min_num": 2},
                    ),
                    71: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [(2, "2"), (3, "3")],
                            "help_text": "Number of cards per row. Note: this is a max and fewer might be used if is less space is available.",
                            "required": False,
                        },
                    ),
                    72: ("wagtail.blocks.StructBlock", [[("heading", 64), ("cards", 70), ("cards_per_row", 71)]], {}),
                    73: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        (foundation_cms.legacy_apps.wagtailpages.pagemodels.profiles.Profile,),
                        {},
                    ),
                    74: ("wagtail.blocks.StructBlock", [[("profile", 73)]], {}),
                    75: ("wagtail.blocks.ListBlock", (74,), {"min_num": 1}),
                    76: ("wagtail.blocks.StructBlock", [[("profiles", 75)]], {}),
                    77: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Heading for the group of cards.", "required": False},
                    ),
                    78: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional meta data information for the card.", "required": False},
                    ),
                    79: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "link"], "help_text": "Body text of the card."},
                    ),
                    80: (
                        "wagtail.blocks.ListBlock",
                        (22,),
                        {"help_text": "Optional link that this card should link to.", "max_num": 1, "min_num": 0},
                    ),
                    81: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 1), ("alt_text", 2), ("meta_data", 78), ("title", 3), ("body", 79), ("link", 80)]],
                        {},
                    ),
                    82: ("wagtail.blocks.ListBlock", (81,), {}),
                    83: ("wagtail.blocks.StructBlock", [[("title", 77), ("cards", 82)]], {}),
                    84: ("wagtail.blocks.CharBlock", (), {"help_text": "Image description (for screen readers)."}),
                    85: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Page that the title should link out to.", "required": False},
                    ),
                    86: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 1),
                                ("alt_text", 84),
                                ("metadata", 21),
                                ("title", 3),
                                ("title_link", 85),
                                ("body", 21),
                            ]
                        ],
                        {},
                    ),
                    87: (
                        "wagtail.blocks.ListBlock",
                        (49,),
                        {"help_text": "Optional link button", "max_num": 1, "min_num": 0},
                    ),
                    88: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 3),
                                ("text", 52),
                                ("image", 1),
                                ("altText", 20),
                                ("link_button", 87),
                                ("top_divider", 28),
                                ("bottom_divider", 29),
                            ]
                        ],
                        {},
                    ),
                    89: (
                        "wagtail.blocks.ListBlock",
                        (22,),
                        {"help_text": "Optional link that the header should link out to.", "max_num": 1, "min_num": 0},
                    ),
                    90: ("wagtail.blocks.CharBlock", (), {"max_length": 500}),
                    91: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Body text of the card.", "max_length": 200, "required": False},
                    ),
                    92: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 3), ("link", 89), ("meta_data", 90), ("body", 91)]],
                        {},
                    ),
                    93: (
                        "wagtail.blocks.ListBlock",
                        (92,),
                        {"help_text": "Please use a minimum of 3 cards.", "min_num": 3},
                    ),
                    94: ("wagtail.blocks.StructBlock", [[("cards", 93)]], {}),
                    95: (
                        "wagtail.blocks.StreamBlock",
                        [[("listing", 72), ("paragraph", 26)]],
                        {
                            "help_text": "The wider block that appears on the left on desktop",
                            "icon": "doc-full",
                            "max_num": 1,
                        },
                    ),
                    96: ("wagtail.blocks.CharBlock", (), {"help_text": "Heading for the card.", "required": False}),
                    97: ("wagtail.blocks.TextBlock", (), {"help_text": "Body text of the card.", "required": False}),
                    98: ("wagtail.blocks.StructBlock", [[("title", 96), ("body", 97)]], {}),
                    99: (
                        "wagtail.blocks.StreamBlock",
                        [[("aside_content", 98), ("linkbutton", 49), ("spacer", 51)]],
                        {
                            "help_text": "Elements here will appear in the column on the right side of the page on desktop. This can be left blank if you would just like a 2/3 column on the left",
                            "icon": "doc-full",
                            "required": False,
                        },
                    ),
                    100: ("wagtail.blocks.StructBlock", [[("content", 95), ("aside", 99)]], {}),
                    101: ("wagtail.blocks.CharBlock", (), {"help_text": "Heading for the Accordion Item"}),
                    102: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"blank": True, "features": ["bold", "italic", "link", "ul", "ol", "document-link"]},
                    ),
                    103: ("wagtail.blocks.StructBlock", [[("image", 1), ("altText", 20)]], {}),
                    104: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 102), ("datawrapper", 63), ("image", 103), ("video", 42)]],
                        {},
                    ),
                    105: ("wagtail.blocks.StructBlock", [[("title", 101), ("content", 104)]], {}),
                    106: ("wagtail.blocks.ListBlock", (105,), {}),
                    107: ("wagtail.blocks.StructBlock", [[("accordion_items", 106)]], {}),
                    108: ("wagtail.blocks.CharBlock", (), {"help_text": "Heading for the slider."}),
                    109: ("wagtail.blocks.CharBlock", (), {"help_text": "Author of this session.", "required": False}),
                    110: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "The image associated with this session."},
                    ),
                    111: ("wagtail.blocks.RichTextBlock", (), {"help_text": "Body text of this card."}),
                    112: (
                        "wagtailmedia.blocks.VideoChooserBlock",
                        (),
                        {"help_text": "Video that will autoplay when this card is hovered on", "required": False},
                    ),
                    113: ("wagtail.blocks.PageChooserBlock", (), {"help_text": "Page that this should link out to."}),
                    114: ("wagtail.blocks.StructBlock", [[("link", 113)]], {}),
                    115: ("wagtail.blocks.URLBlock", (), {"help_text": "URL that this should link out to."}),
                    116: ("wagtail.blocks.StructBlock", [[("link", 115)]], {}),
                    117: (
                        "wagtail.blocks.StreamBlock",
                        [[("internal", 114), ("external", 116)]],
                        {"help_text": "Page or external URL this card will link out to.", "max_num": 1},
                    ),
                    118: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 3),
                                ("author_subheading", 109),
                                ("image", 110),
                                ("body", 111),
                                ("video", 112),
                                ("link", 117),
                            ]
                        ],
                        {},
                    ),
                    119: (
                        "wagtail.blocks.StreamBlock",
                        [[("session_item", 118)]],
                        {"help_text": "A list of sessions in the slider."},
                    ),
                    120: ("wagtail.blocks.CharBlock", (), {"help_text": "Label for this link."}),
                    121: ("wagtail.blocks.StructBlock", [[("label", 120), ("link", 113)]], {}),
                    122: ("wagtail.blocks.StructBlock", [[("label", 120), ("link", 115)]], {}),
                    123: (
                        "wagtail.blocks.StreamBlock",
                        [[("internal", 121), ("external", 122)]],
                        {"help_text": "Button that appears below the slider.", "max_num": 1, "required": False},
                    ),
                    124: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 108), ("session_items", 119), ("button", 123)]],
                        {},
                    ),
                    125: ("wagtail.blocks.CharBlock", (), {"help_text": "Heading of the card."}),
                    126: (
                        "wagtail.blocks.StreamBlock",
                        [[("internal", 121), ("external", 122)]],
                        {
                            "help_text": "The link that appears below the card heading.",
                            "max_num": 1,
                            "required": False,
                        },
                    ),
                    127: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "The image associated with this event."},
                    ),
                    128: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"help_text": "Document that this should link out to."},
                    ),
                    129: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 120), ("document", 128)]],
                        {"help_text": 'An iCal document can be attached here for an "Add to Calendar" button.'},
                    ),
                    130: (
                        "wagtail.blocks.StreamBlock",
                        [[("internal", 121), ("external", 122), ("document", 129)]],
                        {"help_text": "A list of buttons that will appear at the bottom of the card.", "max_num": 2},
                    ),
                    131: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 125), ("subheading_link", 126), ("image", 127), ("body", 4), ("buttons", 130)]],
                        {},
                    ),
                    132: (
                        "wagtail.blocks.StreamBlock",
                        [[("current_event", 131)]],
                        {"help_text": "A list of current events in the slider."},
                    ),
                    133: ("wagtail.blocks.StructBlock", [[("title", 108), ("current_events", 132)]], {}),
                    134: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 1), ("title", 3), ("body", 4), ("link", 117)]],
                        {},
                    ),
                    135: (
                        "wagtail.blocks.StreamBlock",
                        [[("space_card", 134)]],
                        {"help_text": "A list of Spaces Cards."},
                    ),
                    136: ("wagtail.blocks.StructBlock", [[("title", 5), ("cards", 135)]], {}),
                    137: ("wagtail.blocks.CharBlock", (), {"help_text": "The text to show on the Tito button."}),
                    138: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("events.TitoEvent",),
                        {"help_event": "The Tito event to be displayed"},
                    ),
                    139: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Comma-separated list of ticket/release IDs to limit to, e.g. "3elajg6qcxu,6qiiw4socs4"',
                            "required": False,
                        },
                    ),
                    140: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter a source to track where events come from.",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    141: (
                        "wagtail.blocks.StructBlock",
                        [[("button_label", 137), ("styling", 48), ("event", 138), ("releases", 139), ("source", 140)]],
                        {},
                    ),
                    142: ("wagtail.blocks.CharBlock", (), {"help_text": "The statistic figure, e.g '1000+' or '10%'"}),
                    143: ("wagtail.blocks.CharBlock", (), {"help_text": "Context or description for the statistic"}),
                    144: ("wagtail.blocks.StructBlock", [[("title", 142), ("description", 143)]], {}),
                    145: (
                        "wagtail.blocks.ListBlock",
                        (144,),
                        {"help_text": "Please use a minimum of 2 cards.", "max_num": 4, "min_num": 2},
                    ),
                    146: ("wagtail.blocks.StructBlock", [[("statistics", 145)]], {}),
                    147: (
                        "wagtail.blocks.ListBlock",
                        (15,),
                        {"help_text": "A CTA Link for the carousel", "max_num": 1, "min_num": 0},
                    ),
                    148: ("wagtail.blocks.ListBlock", (103,), {"max_num": 4}),
                    149: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 64), ("text", 31), ("link", 147), ("carousel_images", 148)]],
                        {},
                    ),
                    150: ("wagtail.snippets.blocks.SnippetChooserBlock", ("mozfest.Ticket",), {}),
                    151: ("wagtail.blocks.ListBlock", (150,), {"max_num": 3}),
                    152: ("wagtail.blocks.StructBlock", [[("heading", 64), ("source", 140), ("tickets", 151)]], {}),
                    153: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    154: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 5),
                                ("link_to", 6),
                                ("page", 7),
                                ("external_url", 8),
                                ("relative_url", 9),
                                ("anchor", 10),
                                ("email", 11),
                                ("file", 12),
                                ("phone", 13),
                                ("new_window", 14),
                                ("heading", 21),
                                ("text", 21),
                                ("dark_background", 153),
                            ]
                        ],
                        {},
                    ),
                    155: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("mozfest.NewsletterSignupWithBackground",),
                        {},
                    ),
                    156: ("wagtail.blocks.StructBlock", [[("snippet", 155)]], {}),
                    157: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional caption for the video, displayed next to the play button.",
                            "max_length": 25,
                            "required": False,
                        },
                    ),
                    158: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional title for the video.", "max_length": 50, "required": False},
                    ),
                    159: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Text content to display with the video title.", "required": False},
                    ),
                    160: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "The image to show before the video is played."},
                    ),
                    161: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 40), ("caption", 157), ("title", 158), ("text", 159), ("thumbnail", 160)]],
                        {},
                    ),
                    162: ("wagtail.blocks.ListBlock", (69,), {"max_num": 4, "min_num": 1}),
                    163: (
                        "wagtail.blocks.ListBlock",
                        (15,),
                        {
                            "help_text": "Optional link that this mixed content block should link out to.",
                            "max_num": 1,
                            "min_num": 0,
                        },
                    ),
                    164: ("wagtail.blocks.StructBlock", [[("video", 161), ("cards", 162), ("link", 163)]], {}),
                },
            ),
        ),
    ]
