# Generated by Django 4.2.20 on 2025-04-15 00:34

from django.db import migrations, models
import django.db.models.deletion
import foundation_cms.base.mixins.theme_mixin
import modelcluster.fields
import wagtail.fields
import wagtailmetadata.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailimages", "0027_image_description"),
        ("base", "0001_initial"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("taggit", "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleProductReview",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("rich_text", 0)], blank=True, block_lookup={0: ("wagtail.blocks.RichTextBlock", (), {})}
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_pages",
                        to="base.author",
                    ),
                ),
                (
                    "search_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Search image",
                    ),
                ),
                ("tags", modelcluster.fields.ParentalManyToManyField(blank=True, to="taggit.tag")),
            ],
            options={
                "verbose_name": "Article Product Review",
            },
            bases=(
                wagtailmetadata.models.WagtailImageMetadataMixin,
                foundation_cms.base.mixins.theme_mixin.ThemedPageMixin,
                "wagtailcore.page",
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="ArticleEditorialFeature",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("rich_text", 0)], blank=True, block_lookup={0: ("wagtail.blocks.RichTextBlock", (), {})}
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_pages",
                        to="base.author",
                    ),
                ),
                (
                    "search_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Search image",
                    ),
                ),
                ("tags", modelcluster.fields.ParentalManyToManyField(blank=True, to="taggit.tag")),
            ],
            options={
                "verbose_name": "Article Editorial Feature",
            },
            bases=(
                wagtailmetadata.models.WagtailImageMetadataMixin,
                foundation_cms.base.mixins.theme_mixin.ThemedPageMixin,
                "wagtailcore.page",
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="ArticleCollectionPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("rich_text", 0)], blank=True, block_lookup={0: ("wagtail.blocks.RichTextBlock", (), {})}
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_pages",
                        to="base.author",
                    ),
                ),
                (
                    "search_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Search image",
                    ),
                ),
                ("tags", modelcluster.fields.ParentalManyToManyField(blank=True, to="taggit.tag")),
            ],
            options={
                "verbose_name": "Article Collection Page",
            },
            bases=(
                wagtailmetadata.models.WagtailImageMetadataMixin,
                foundation_cms.base.mixins.theme_mixin.ThemedPageMixin,
                "wagtailcore.page",
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="ArticleAdviceColumn",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("rich_text", 0)], blank=True, block_lookup={0: ("wagtail.blocks.RichTextBlock", (), {})}
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_pages",
                        to="base.author",
                    ),
                ),
                (
                    "search_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Search image",
                    ),
                ),
                ("tags", modelcluster.fields.ParentalManyToManyField(blank=True, to="taggit.tag")),
            ],
            options={
                "verbose_name": "Article Advice Column",
            },
            bases=(
                wagtailmetadata.models.WagtailImageMetadataMixin,
                foundation_cms.base.mixins.theme_mixin.ThemedPageMixin,
                "wagtailcore.page",
                models.Model,
            ),
        ),
    ]
