# Generated by Django 4.2.20 on 2025-04-21 21:27

from django.db import migrations
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_pagetag_taggedpage"),
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articleadvicecolumn",
            name="tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="base.TaggedPage",
                to="base.PageTag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="articlecollectionpage",
            name="tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="base.TaggedPage",
                to="base.PageTag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="articleeditorialfeature",
            name="tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="base.TaggedPage",
                to="base.PageTag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="articleproductreview",
            name="tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="base.TaggedPage",
                to="base.PageTag",
                verbose_name="Tags",
            ),
        ),
    ]
