# Generated by Django 4.2.20 on 2025-05-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="articleadvicecolumn",
            name="lede_text",
            field=models.TextField(blank=True, help_text="Optional introductory lede text (plain text only)."),
        ),
        migrations.AddField(
            model_name="articlecollectionpage",
            name="lede_text",
            field=models.TextField(blank=True, help_text="Optional introductory lede text (plain text only)."),
        ),
        migrations.AddField(
            model_name="articleeditorialfeature",
            name="lede_text",
            field=models.TextField(blank=True, help_text="Optional introductory lede text (plain text only)."),
        ),
        migrations.AddField(
            model_name="articleproductreview",
            name="lede_text",
            field=models.TextField(blank=True, help_text="Optional introductory lede text (plain text only)."),
        ),
    ]
