# Generated by Django 4.2.20 on 2025-05-21 00:12

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_add_theme_field_to_article_pages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articleadvicecolumn",
            name="body",
            field=wagtail.fields.StreamField(
                [("audio", 4), ("rich_text", 5)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Optional image to display at the top of the block.", "required": False},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Image description (for screen readers).", "required": False},
                    ),
                    2: ("wagtail.blocks.CharBlock", (), {}),
                    3: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Short description of the audio", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 0),
                                ("image_alt_text", 1),
                                ("title", 2),
                                ("description", 3),
                                ("simplecast_embed_code", 2),
                            ]
                        ],
                        {},
                    ),
                    5: ("wagtail.blocks.RichTextBlock", (), {}),
                },
            ),
        ),
        migrations.AlterField(
            model_name="articlecollectionpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("audio", 4), ("rich_text", 5)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Optional image to display at the top of the block.", "required": False},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Image description (for screen readers).", "required": False},
                    ),
                    2: ("wagtail.blocks.CharBlock", (), {}),
                    3: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Short description of the audio", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 0),
                                ("image_alt_text", 1),
                                ("title", 2),
                                ("description", 3),
                                ("simplecast_embed_code", 2),
                            ]
                        ],
                        {},
                    ),
                    5: ("wagtail.blocks.RichTextBlock", (), {}),
                },
            ),
        ),
        migrations.AlterField(
            model_name="articleeditorialfeature",
            name="body",
            field=wagtail.fields.StreamField(
                [("audio", 4), ("rich_text", 5)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Optional image to display at the top of the block.", "required": False},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Image description (for screen readers).", "required": False},
                    ),
                    2: ("wagtail.blocks.CharBlock", (), {}),
                    3: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Short description of the audio", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 0),
                                ("image_alt_text", 1),
                                ("title", 2),
                                ("description", 3),
                                ("simplecast_embed_code", 2),
                            ]
                        ],
                        {},
                    ),
                    5: ("wagtail.blocks.RichTextBlock", (), {}),
                },
            ),
        ),
        migrations.AlterField(
            model_name="articleproductreview",
            name="body",
            field=wagtail.fields.StreamField(
                [("audio", 4), ("rich_text", 5)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Optional image to display at the top of the block.", "required": False},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Image description (for screen readers).", "required": False},
                    ),
                    2: ("wagtail.blocks.CharBlock", (), {}),
                    3: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Short description of the audio", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 0),
                                ("image_alt_text", 1),
                                ("title", 2),
                                ("description", 3),
                                ("simplecast_embed_code", 2),
                            ]
                        ],
                        {},
                    ),
                    5: ("wagtail.blocks.RichTextBlock", (), {}),
                },
            ),
        ),
    ]
