# Generated by Django 4.2.20 on 2025-05-29 17:49

from django.db import migrations
import foundation_cms.legacy_apps.wagtailpages.validators
import foundation_cms.validators
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0009_alter_articleadvicecolumn_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articleadvicecolumn",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("rich_text", 0),
                    ("image", 4),
                    ("audio_block", 9),
                    ("tabbed_content", 15),
                    ("two_column_container_block", 19),
                    ("link_button_block", 29),
                    ("portrait_card_set_block", 37),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title/caption for this image", "required": True},
                    ),
                    2: ("wagtail.images.blocks.ImageBlock", [], {}),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("portrait", "Portrait"), ("landscape", "Landscape")],
                            "help_text": "Select the orientation of this image",
                        },
                    ),
                    4: ("wagtail.blocks.StructBlock", [[("title", 1), ("image", 2), ("orientation", 3)]], {}),
                    5: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Optional image to display at the top of the block.", "required": False},
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Image description (for screen readers).", "required": False},
                    ),
                    7: ("wagtail.blocks.CharBlock", (), {}),
                    8: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Short description of the audio", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 5),
                                ("image_alt_text", 6),
                                ("title", 7),
                                ("description", 8),
                                ("simplecast_embed_code", 7),
                            ]
                        ],
                        {},
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title shown on the tab button", "required": True},
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Subtitle shown under the title on the tab", "required": False},
                    ),
                    12: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 0)]],
                        {"help_text": "Only one content block per tab.", "max_num": 1, "min_num": 1, "required": True},
                    ),
                    13: ("wagtail.blocks.StructBlock", [[("title", 10), ("subtitle", 11), ("content", 12)]], {}),
                    14: ("wagtail.blocks.ListBlock", (13,), {"label": "Tabs", "max_num": 8, "min_num": 1}),
                    15: ("wagtail.blocks.StructBlock", [[("tabs", 14)]], {}),
                    16: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional title for the block", "required": False},
                    ),
                    17: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 0), ("audio", 9), ("image", 4)]],
                        {"label": "Left Column"},
                    ),
                    18: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 0), ("audio", 9), ("image", 4)]],
                        {"label": "Right Column"},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 16), ("left_column", 17), ("right_column", 18)]],
                        {},
                    ),
                    20: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("external_url", "External URL"),
                                ("relative_url", "Relative URL"),
                                ("email", "Email"),
                                ("anchor", "Anchor"),
                                ("file", "File"),
                                ("phone", "Phone"),
                            ],
                            "label": "Link to",
                        },
                    ),
                    21: ("wagtail.blocks.PageChooserBlock", (), {"label": "Page", "required": False}),
                    22: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Enter a full URL including http:// or https://",
                            "label": "External URL",
                            "max_length": 300,
                            "required": False,
                        },
                    ),
                    23: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'A path relative to this domain. For example, "/foo/bar" or "?foo=bar".',
                            "label": "Relative URL",
                            "max_length": 300,
                            "required": False,
                            "validators": [foundation_cms.legacy_apps.wagtailpages.validators.RelativeURLValidator()],
                        },
                    ),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'An id attribute of an element on the current page. For example, "#section-1"',
                            "label": "#",
                            "max_length": 300,
                            "required": False,
                            "validators": [foundation_cms.validators.AnchorLinkValidator()],
                        },
                    ),
                    25: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    26: ("wagtail.documents.blocks.DocumentChooserBlock", (), {"label": "File", "required": False}),
                    27: ("wagtail.blocks.CharBlock", (), {"label": "Phone", "max_length": 30, "required": False}),
                    28: ("wagtail.blocks.BooleanBlock", (), {"label": "Open in new window", "required": False}),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 7),
                                ("link_to", 20),
                                ("page", 21),
                                ("external_url", 22),
                                ("relative_url", 23),
                                ("anchor", 24),
                                ("email", 25),
                                ("file", 26),
                                ("phone", 27),
                                ("new_window", 28),
                            ]
                        ],
                        {},
                    ),
                    30: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Main heading for the card set.", "label": "Headline", "required": False},
                    ),
                    31: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Appears above the headline (max 36 characters).",
                            "label": "Label",
                            "max_length": 36,
                            "required": False,
                        },
                    ),
                    32: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Appears as the main heading (max 36 characters).",
                            "label": "Headline",
                            "max_length": 36,
                            "required": False,
                        },
                    ),
                    33: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Image should follow a 2:3 aspect ratio.", "label": "Image", "required": False},
                    ),
                    34: ("wagtail.blocks.StructBlock", [[("label", 31), ("headline", 32), ("image", 33)]], {}),
                    35: (
                        "wagtail.blocks.ListBlock",
                        (34,),
                        {
                            "help_text": "Exactly 3 cards required.",
                            "label": "Portrait Cards",
                            "max_num": 3,
                            "min_num": 3,
                        },
                    ),
                    36: (
                        "foundation_cms.blocks.link_block.OptionalLinkBlock",
                        (),
                        {
                            "help_text": "Optional link below the cards.",
                            "label": "Call to Action Link",
                            "required": False,
                        },
                    ),
                    37: ("wagtail.blocks.StructBlock", [[("headline", 30), ("cards", 35), ("cta_link", 36)]], {}),
                },
            ),
        ),
        migrations.AlterField(
            model_name="articlecollectionpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("rich_text", 0),
                    ("image", 4),
                    ("audio_block", 9),
                    ("tabbed_content", 15),
                    ("two_column_container_block", 19),
                    ("link_button_block", 29),
                    ("portrait_card_set_block", 37),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title/caption for this image", "required": True},
                    ),
                    2: ("wagtail.images.blocks.ImageBlock", [], {}),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("portrait", "Portrait"), ("landscape", "Landscape")],
                            "help_text": "Select the orientation of this image",
                        },
                    ),
                    4: ("wagtail.blocks.StructBlock", [[("title", 1), ("image", 2), ("orientation", 3)]], {}),
                    5: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Optional image to display at the top of the block.", "required": False},
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Image description (for screen readers).", "required": False},
                    ),
                    7: ("wagtail.blocks.CharBlock", (), {}),
                    8: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Short description of the audio", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 5),
                                ("image_alt_text", 6),
                                ("title", 7),
                                ("description", 8),
                                ("simplecast_embed_code", 7),
                            ]
                        ],
                        {},
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title shown on the tab button", "required": True},
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Subtitle shown under the title on the tab", "required": False},
                    ),
                    12: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 0)]],
                        {"help_text": "Only one content block per tab.", "max_num": 1, "min_num": 1, "required": True},
                    ),
                    13: ("wagtail.blocks.StructBlock", [[("title", 10), ("subtitle", 11), ("content", 12)]], {}),
                    14: ("wagtail.blocks.ListBlock", (13,), {"label": "Tabs", "max_num": 8, "min_num": 1}),
                    15: ("wagtail.blocks.StructBlock", [[("tabs", 14)]], {}),
                    16: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional title for the block", "required": False},
                    ),
                    17: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 0), ("audio", 9), ("image", 4)]],
                        {"label": "Left Column"},
                    ),
                    18: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 0), ("audio", 9), ("image", 4)]],
                        {"label": "Right Column"},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 16), ("left_column", 17), ("right_column", 18)]],
                        {},
                    ),
                    20: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("external_url", "External URL"),
                                ("relative_url", "Relative URL"),
                                ("email", "Email"),
                                ("anchor", "Anchor"),
                                ("file", "File"),
                                ("phone", "Phone"),
                            ],
                            "label": "Link to",
                        },
                    ),
                    21: ("wagtail.blocks.PageChooserBlock", (), {"label": "Page", "required": False}),
                    22: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Enter a full URL including http:// or https://",
                            "label": "External URL",
                            "max_length": 300,
                            "required": False,
                        },
                    ),
                    23: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'A path relative to this domain. For example, "/foo/bar" or "?foo=bar".',
                            "label": "Relative URL",
                            "max_length": 300,
                            "required": False,
                            "validators": [foundation_cms.legacy_apps.wagtailpages.validators.RelativeURLValidator()],
                        },
                    ),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'An id attribute of an element on the current page. For example, "#section-1"',
                            "label": "#",
                            "max_length": 300,
                            "required": False,
                            "validators": [foundation_cms.validators.AnchorLinkValidator()],
                        },
                    ),
                    25: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    26: ("wagtail.documents.blocks.DocumentChooserBlock", (), {"label": "File", "required": False}),
                    27: ("wagtail.blocks.CharBlock", (), {"label": "Phone", "max_length": 30, "required": False}),
                    28: ("wagtail.blocks.BooleanBlock", (), {"label": "Open in new window", "required": False}),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 7),
                                ("link_to", 20),
                                ("page", 21),
                                ("external_url", 22),
                                ("relative_url", 23),
                                ("anchor", 24),
                                ("email", 25),
                                ("file", 26),
                                ("phone", 27),
                                ("new_window", 28),
                            ]
                        ],
                        {},
                    ),
                    30: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Main heading for the card set.", "label": "Headline", "required": False},
                    ),
                    31: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Appears above the headline (max 36 characters).",
                            "label": "Label",
                            "max_length": 36,
                            "required": False,
                        },
                    ),
                    32: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Appears as the main heading (max 36 characters).",
                            "label": "Headline",
                            "max_length": 36,
                            "required": False,
                        },
                    ),
                    33: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Image should follow a 2:3 aspect ratio.", "label": "Image", "required": False},
                    ),
                    34: ("wagtail.blocks.StructBlock", [[("label", 31), ("headline", 32), ("image", 33)]], {}),
                    35: (
                        "wagtail.blocks.ListBlock",
                        (34,),
                        {
                            "help_text": "Exactly 3 cards required.",
                            "label": "Portrait Cards",
                            "max_num": 3,
                            "min_num": 3,
                        },
                    ),
                    36: (
                        "foundation_cms.blocks.link_block.OptionalLinkBlock",
                        (),
                        {
                            "help_text": "Optional link below the cards.",
                            "label": "Call to Action Link",
                            "required": False,
                        },
                    ),
                    37: ("wagtail.blocks.StructBlock", [[("headline", 30), ("cards", 35), ("cta_link", 36)]], {}),
                },
            ),
        ),
        migrations.AlterField(
            model_name="articleeditorialfeature",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("rich_text", 0),
                    ("image", 4),
                    ("audio_block", 9),
                    ("tabbed_content", 15),
                    ("two_column_container_block", 19),
                    ("link_button_block", 29),
                    ("portrait_card_set_block", 37),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title/caption for this image", "required": True},
                    ),
                    2: ("wagtail.images.blocks.ImageBlock", [], {}),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("portrait", "Portrait"), ("landscape", "Landscape")],
                            "help_text": "Select the orientation of this image",
                        },
                    ),
                    4: ("wagtail.blocks.StructBlock", [[("title", 1), ("image", 2), ("orientation", 3)]], {}),
                    5: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Optional image to display at the top of the block.", "required": False},
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Image description (for screen readers).", "required": False},
                    ),
                    7: ("wagtail.blocks.CharBlock", (), {}),
                    8: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Short description of the audio", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 5),
                                ("image_alt_text", 6),
                                ("title", 7),
                                ("description", 8),
                                ("simplecast_embed_code", 7),
                            ]
                        ],
                        {},
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title shown on the tab button", "required": True},
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Subtitle shown under the title on the tab", "required": False},
                    ),
                    12: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 0)]],
                        {"help_text": "Only one content block per tab.", "max_num": 1, "min_num": 1, "required": True},
                    ),
                    13: ("wagtail.blocks.StructBlock", [[("title", 10), ("subtitle", 11), ("content", 12)]], {}),
                    14: ("wagtail.blocks.ListBlock", (13,), {"label": "Tabs", "max_num": 8, "min_num": 1}),
                    15: ("wagtail.blocks.StructBlock", [[("tabs", 14)]], {}),
                    16: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional title for the block", "required": False},
                    ),
                    17: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 0), ("audio", 9), ("image", 4)]],
                        {"label": "Left Column"},
                    ),
                    18: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 0), ("audio", 9), ("image", 4)]],
                        {"label": "Right Column"},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 16), ("left_column", 17), ("right_column", 18)]],
                        {},
                    ),
                    20: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("external_url", "External URL"),
                                ("relative_url", "Relative URL"),
                                ("email", "Email"),
                                ("anchor", "Anchor"),
                                ("file", "File"),
                                ("phone", "Phone"),
                            ],
                            "label": "Link to",
                        },
                    ),
                    21: ("wagtail.blocks.PageChooserBlock", (), {"label": "Page", "required": False}),
                    22: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Enter a full URL including http:// or https://",
                            "label": "External URL",
                            "max_length": 300,
                            "required": False,
                        },
                    ),
                    23: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'A path relative to this domain. For example, "/foo/bar" or "?foo=bar".',
                            "label": "Relative URL",
                            "max_length": 300,
                            "required": False,
                            "validators": [foundation_cms.legacy_apps.wagtailpages.validators.RelativeURLValidator()],
                        },
                    ),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'An id attribute of an element on the current page. For example, "#section-1"',
                            "label": "#",
                            "max_length": 300,
                            "required": False,
                            "validators": [foundation_cms.validators.AnchorLinkValidator()],
                        },
                    ),
                    25: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    26: ("wagtail.documents.blocks.DocumentChooserBlock", (), {"label": "File", "required": False}),
                    27: ("wagtail.blocks.CharBlock", (), {"label": "Phone", "max_length": 30, "required": False}),
                    28: ("wagtail.blocks.BooleanBlock", (), {"label": "Open in new window", "required": False}),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 7),
                                ("link_to", 20),
                                ("page", 21),
                                ("external_url", 22),
                                ("relative_url", 23),
                                ("anchor", 24),
                                ("email", 25),
                                ("file", 26),
                                ("phone", 27),
                                ("new_window", 28),
                            ]
                        ],
                        {},
                    ),
                    30: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Main heading for the card set.", "label": "Headline", "required": False},
                    ),
                    31: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Appears above the headline (max 36 characters).",
                            "label": "Label",
                            "max_length": 36,
                            "required": False,
                        },
                    ),
                    32: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Appears as the main heading (max 36 characters).",
                            "label": "Headline",
                            "max_length": 36,
                            "required": False,
                        },
                    ),
                    33: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Image should follow a 2:3 aspect ratio.", "label": "Image", "required": False},
                    ),
                    34: ("wagtail.blocks.StructBlock", [[("label", 31), ("headline", 32), ("image", 33)]], {}),
                    35: (
                        "wagtail.blocks.ListBlock",
                        (34,),
                        {
                            "help_text": "Exactly 3 cards required.",
                            "label": "Portrait Cards",
                            "max_num": 3,
                            "min_num": 3,
                        },
                    ),
                    36: (
                        "foundation_cms.blocks.link_block.OptionalLinkBlock",
                        (),
                        {
                            "help_text": "Optional link below the cards.",
                            "label": "Call to Action Link",
                            "required": False,
                        },
                    ),
                    37: ("wagtail.blocks.StructBlock", [[("headline", 30), ("cards", 35), ("cta_link", 36)]], {}),
                },
            ),
        ),
        migrations.AlterField(
            model_name="articleproductreview",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("rich_text", 0),
                    ("image", 4),
                    ("audio_block", 9),
                    ("tabbed_content", 15),
                    ("two_column_container_block", 19),
                    ("link_button_block", 29),
                    ("portrait_card_set_block", 37),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title/caption for this image", "required": True},
                    ),
                    2: ("wagtail.images.blocks.ImageBlock", [], {}),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("portrait", "Portrait"), ("landscape", "Landscape")],
                            "help_text": "Select the orientation of this image",
                        },
                    ),
                    4: ("wagtail.blocks.StructBlock", [[("title", 1), ("image", 2), ("orientation", 3)]], {}),
                    5: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Optional image to display at the top of the block.", "required": False},
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Image description (for screen readers).", "required": False},
                    ),
                    7: ("wagtail.blocks.CharBlock", (), {}),
                    8: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Short description of the audio", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 5),
                                ("image_alt_text", 6),
                                ("title", 7),
                                ("description", 8),
                                ("simplecast_embed_code", 7),
                            ]
                        ],
                        {},
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title shown on the tab button", "required": True},
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Subtitle shown under the title on the tab", "required": False},
                    ),
                    12: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 0)]],
                        {"help_text": "Only one content block per tab.", "max_num": 1, "min_num": 1, "required": True},
                    ),
                    13: ("wagtail.blocks.StructBlock", [[("title", 10), ("subtitle", 11), ("content", 12)]], {}),
                    14: ("wagtail.blocks.ListBlock", (13,), {"label": "Tabs", "max_num": 8, "min_num": 1}),
                    15: ("wagtail.blocks.StructBlock", [[("tabs", 14)]], {}),
                    16: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional title for the block", "required": False},
                    ),
                    17: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 0), ("audio", 9), ("image", 4)]],
                        {"label": "Left Column"},
                    ),
                    18: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 0), ("audio", 9), ("image", 4)]],
                        {"label": "Right Column"},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 16), ("left_column", 17), ("right_column", 18)]],
                        {},
                    ),
                    20: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("external_url", "External URL"),
                                ("relative_url", "Relative URL"),
                                ("email", "Email"),
                                ("anchor", "Anchor"),
                                ("file", "File"),
                                ("phone", "Phone"),
                            ],
                            "label": "Link to",
                        },
                    ),
                    21: ("wagtail.blocks.PageChooserBlock", (), {"label": "Page", "required": False}),
                    22: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Enter a full URL including http:// or https://",
                            "label": "External URL",
                            "max_length": 300,
                            "required": False,
                        },
                    ),
                    23: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'A path relative to this domain. For example, "/foo/bar" or "?foo=bar".',
                            "label": "Relative URL",
                            "max_length": 300,
                            "required": False,
                            "validators": [foundation_cms.legacy_apps.wagtailpages.validators.RelativeURLValidator()],
                        },
                    ),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'An id attribute of an element on the current page. For example, "#section-1"',
                            "label": "#",
                            "max_length": 300,
                            "required": False,
                            "validators": [foundation_cms.validators.AnchorLinkValidator()],
                        },
                    ),
                    25: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    26: ("wagtail.documents.blocks.DocumentChooserBlock", (), {"label": "File", "required": False}),
                    27: ("wagtail.blocks.CharBlock", (), {"label": "Phone", "max_length": 30, "required": False}),
                    28: ("wagtail.blocks.BooleanBlock", (), {"label": "Open in new window", "required": False}),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 7),
                                ("link_to", 20),
                                ("page", 21),
                                ("external_url", 22),
                                ("relative_url", 23),
                                ("anchor", 24),
                                ("email", 25),
                                ("file", 26),
                                ("phone", 27),
                                ("new_window", 28),
                            ]
                        ],
                        {},
                    ),
                    30: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Main heading for the card set.", "label": "Headline", "required": False},
                    ),
                    31: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Appears above the headline (max 36 characters).",
                            "label": "Label",
                            "max_length": 36,
                            "required": False,
                        },
                    ),
                    32: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Appears as the main heading (max 36 characters).",
                            "label": "Headline",
                            "max_length": 36,
                            "required": False,
                        },
                    ),
                    33: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Image should follow a 2:3 aspect ratio.", "label": "Image", "required": False},
                    ),
                    34: ("wagtail.blocks.StructBlock", [[("label", 31), ("headline", 32), ("image", 33)]], {}),
                    35: (
                        "wagtail.blocks.ListBlock",
                        (34,),
                        {
                            "help_text": "Exactly 3 cards required.",
                            "label": "Portrait Cards",
                            "max_num": 3,
                            "min_num": 3,
                        },
                    ),
                    36: (
                        "foundation_cms.blocks.link_block.OptionalLinkBlock",
                        (),
                        {
                            "help_text": "Optional link below the cards.",
                            "label": "Call to Action Link",
                            "required": False,
                        },
                    ),
                    37: ("wagtail.blocks.StructBlock", [[("headline", 30), ("cards", 35), ("cta_link", 36)]], {}),
                },
            ),
        ),
    ]
