# Generated by Django 4.2.20 on 2025-06-04 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0011_add_impact_numbers_block"),
        ("articles", "0011_alter_articleadvicecolumn_body_and_more"),
    ]

    operations = []
