# Generated by Django 4.2.20 on 2025-06-27 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
        ("articles", "0020_alter_articleadvicecolumn_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articleadvicecolumn",
            name="search_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.foundationcustomimage",
                verbose_name="Search image",
            ),
        ),
        migrations.AlterField(
            model_name="articlecollectionpage",
            name="search_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.foundationcustomimage",
                verbose_name="Search image",
            ),
        ),
        migrations.AlterField(
            model_name="articleeditorialfeature",
            name="search_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.foundationcustomimage",
                verbose_name="Search image",
            ),
        ),
        migrations.AlterField(
            model_name="articleproductreview",
            name="search_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.foundationcustomimage",
                verbose_name="Search image",
            ),
        ),
    ]
