# Generated by Django 4.2.27 on 2026-01-14 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_order_snippets_alphabetically"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="titoevent",
            options={
                "ordering": ["title"],
                "verbose_name": "Tito Event (Legacy)",
                "verbose_name_plural": "Tito Events (Legacy)",
            },
        ),
    ]
