# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-13 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_auto_20170313_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='links',
            field=models.ManyToManyField(blank=True, related_name='people', to='people.Link'),
        ),
    ]
