# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-14 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import networkapi.people.models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0015_auto_20170314_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.FileField(max_length=2048, upload_to=networkapi.people.models.get_people_image_upload_path),
        ),
        migrations.AlterField(
            model_name='person',
            name='partnership_logo',
            field=models.FileField(blank=True, max_length=2048, null=True, upload_to=networkapi.people.models.get_people_partnership_logo_upload_path),
        ),
    ]
