# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-31 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0023_auto_20170504_2327'),
    ]

    operations = [
        # originally added a homepage dependency that the next migration removed again
    ]
